easybuild/easyconfigs/h/HPL/HPL-2.1-intel-2015a.eb, easybuild/easyconfigs/i/intel/intel-2015a.eb
Proposal for the `intel/2015a` "common toolchain".
Identical to the recently contributed `intel/2014.11` toolchain, consisting of:
* GCC version 4.9.2 (latest to date)
* icc/ifort release 2015.1.133, a.k.a. version 15.0.1.133 (Oct 31st 2014, latest to date)
* impi version 5.0.2.044 (Nov 17th 2014, latest to date)
* imkl version 11.2.1.133 (Oct 31st 2014, latest to date)
Latest available versions of all components were selected keeping in mind that they are required for several important features, including (full) C++11 support, OpenMP v4, MPI3.
This tips the scale in favour of most recent releases rather than being conservative and going for the last update of the previous major release.
Results from testing this toolchain by rebuilding existing `ictce`/`intel` easyconfigs with …
=> add easyconfig for intel/2015a + HPL for testing

easybuild/easyconfigs/g/GCC/GCC-4.6.3-CLooG-PPL.eb, easybuild/easyconfigs/g/GCC/GCC-4.6.3.eb, easybuild/easyconfigs/g/GCC/GCC-4.6.4.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.0-CLooG-PPL.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.0.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.1-CLooG-PPL.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.1.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.2.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.3-CLooG-PPL.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.3.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.4-CLooG-PPL.eb, easybuild/easyconfigs/g/GCC/GCC-4.7.4.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.1-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.1.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.3-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.3.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2.eb
**NOTE: Requires https://github.com/hpcugent/easybuild-easyblocks/pull/535 to be functionally equivalent**, though this PR doesn't break anything but only suppresses the LTO sanity check if the aforementioned easyblocks PR is not applied.
Once https://github.com/hpcugent/easybuild-easyblocks/pull/535 is in place, link-time optimization support for GCC is entirely controlled via the custom `withlto` easyconfig parameter. Thus, listing `lto` in the language list is no longer necessary (it doesn't hurt but is silently ignored).
@wpoely86: If https://github.com/hpcugent/easybuild-easyblocks/pull/535 and this PR gets in, https://github.com/hpcugent/easybuild-easyconfigs/pull/1279 should also be adjusted accordingly.
=> GCC LTO cleanup

easybuild/easyconfigs/s/STREAM/STREAM-5.10-intel-2015a.eb
compilation of STREAM requires specifying the input size, so I've included a couple of reasonable ones in this easyconfigs
it will run the smallest one as a test case
@wpoely86, @stdweird: please review
=> {perf}[intel/2015a] STREAM (REVIEW)

test/easyconfigs/easyconfigs.py
Enhanced unit tests to cover the situation where the (new) generic easyblock used for PyQt4 had a bug in it that went unnoticed, cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/1349.
depends on https://github.com/hpcugent/easybuild-framework/pull/1155 and https://github.com/hpcugent/easybuild-easyblocks/pull/547 to avoid triggering deprecated behaviour
=> add unit test to check that all extra_options keys are defined in EasyConfig instance

easybuild/easyconfigs/l/Lmod/Lmod-5.9-GCC-4.8.2.eb, easybuild/easyconfigs/l/Lmod/Lmod-5.9-GCC-4.8.4.eb, easybuild/easyconfigs/l/Lmod/README.rst, easybuild/easyconfigs/l/Lmod/sourceme, easybuild/easyconfigs/l/Lua/Lua-5.1.4-8-GCC-4.8.4.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-GCC-4.8.4.eb
Lmod/5.9 is cache-fast, bug-free (!), and simply rocks.
=> {tools} [GCC/4.8.x] Lmod/5.9 (REVIEW)

easybuild/easyconfigs/g/GCC/GCC-4.8.3-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.4-CLooG-multilib.eb
CLooG 0.18.0 is specified as a dependency in the `INSTALL/prerequisites.html` file of GCC 4.8.[1-4]. Thus, don't try to use a newer version.
=> Consistently use CLooG 0.18.0 for GCC 4.8 series

easybuild/easyconfigs/p/Pmw/Pmw-1.3.3-goolf-1.4.10-Python-2.7.5.eb
Pmw library is required for fully funcional PyMOL
=> {vis}[goolf-1.4.10-Python-2.7.5] Pmw 1.3.3 (REVIEW)

easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-intel-2015a.eb, easybuild/easyconfigs/t/TINKER/TINKER-7.1.2-intel-2015a.eb
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/578
=> {chem}[intel/2015a] TINKER 7.1.2 (REVIEW)

easybuild/easyconfigs/p/Python/Python-2.7.9-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-goolf-1.5.14.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-intel-2015a.eb
Lockfile installs pbr from pip, so we do not have any control on the version of pbr (as it installed always the newest version) Plus python installation fails on nodes without (or with restricted) internet access) 
I do not know what versions of Lockfile affected, I have only modified the latest Python versions.
=> Python package "lockfile" needs package "pbr"

easybuild/easyconfigs/h/Hadoop/Hadoop-2.4.0-seagate-722af1-native.eb, easybuild/easyconfigs/h/Hadoop/Hadoop-2.5.0-cdh5.3.1-native.eb, easybuild/easyconfigs/h/Hadoop/Hadoop-TeraSort-on-local-filesystem.patch
The patch it to make TeraSort work with native file systems (MAPREDUCE-5528).
=> Add Hadoop-2.5.0-cdh5.3.1 and patch them.

easybuild/easyconfigs/p/Platanus/Platanus-1.2.1-linux-x86_64.eb
no sources available (yet), see remark at http://platanus.bio.titech.ac.jp/platanus-assembler/:
```
Latest version of platanus is 1.2.1. Only precompiled binary for 64bit-linux system version is available now. We’ll provide source code of Platanus a.s.a.p.
```
=> add easyconfig for Platanus (binary)

easybuild/easyconfigs/w/WRF/WRF-3.6.1-CrayGNU-5.1.29-dmpar.eb
I'm still not quite sure why the build simply hangs when using a `tcsh` provided via EB.
=> list tcsh as build dep in WRF built with CrayGNU, rather than providing it as a build dep

easybuild/easyconfigs/c/cutadapt/cutadapt-1.4.1-goolf-1.4.10-Python-2.7.5.eb
updated to latest release
updated download url. Now code is on github and no longer in googlecode.
=> cutadapt-1.4.1-goolf-1.4.10-Python-2.7.5.eb

easybuild/easyconfigs/p/Python/Python-3.4.1-intel-2014b.eb, easybuild/easyconfigs/p/Python/Python-3.4.1-intel-2015a.eb, easybuild/easyconfigs/p/Python/Python-3.4.3-intel-2015a.eb, easybuild/easyconfigs/p/Python/deap-1.0.1_setup-open-README-utf8.patch, easybuild/easyconfigs/p/Python/deap-1.0.2_setup-open-README-utf8.patch, easybuild/easyconfigs/p/Python/paycheck-1.0.2_setup-open-README-utf8.patch
without the patch, installing paycheck with Py3 fails if `$LC_ALL` isn't set to `en_US.utf8`
=> add patch for installing paycheck as Py3 extension

easybuild/easyconfigs/r/R-bundles/R-bundles-20150520-intel-2015a-R-3.1.3-devtools.eb
devtools is a useful package for letting users install packages from, e.g. github. This was made as a bundle based on @boegel's suggestion.
edit: we should sync this with #1387, this should depend on the bundle contributed there
=> {lang}[intel/2015a] R-bundle devtools (Rv3.1.3) (REVIEW)

easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2015.05.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015.05.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-foss-2015.05.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1-foss-2015.05.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.4-foss-2015.05.eb
OpenFOAM built with foss 2015.05 needed for Centos6 on Haswell
=> OpenFOAM foss 2015.05 flavour: needed for Centos6 on Haswell

easybuild/easyconfigs/a/ABINIT/ABINIT-7.10.4-intel-2015a.eb
=> {chem}[intel/2015a] ABINIT 7.10.4 (REVIEW)

easybuild/easyconfigs/c/CUDA/CUDA-6.5.14.eb
needs https://github.com/hpcugent/easybuild-easyblocks/pull/476
=> CUDA 6.5.14

easybuild/easyconfigs/a/ABINIT/ABINIT-7.4.3-goolf-1.4.10.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-7.4.3-x86_64_linux_gnu4.5.eb, easybuild/easyconfigs/e/ETSF_IO/ETSF_IO-1.0.4-goolf-1.4.10.eb
Adding ABINIT v.7.4.3 built with dummy toolchain and also parallel version of ABINIT 7.4.3
ETSF_IO is a dependency for the parallel version of ABINIT.
=> Adding ABINIT v.7.4.3 with dummy and goolf (parallel version) toolchains

easybuild/easyconfigs/a/ABINIT/ABINIT-7.4.3-goolf-1.4.10-ETSF_IO-1.0.4.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-7.4.3-goolf-1.4.10.eb, easybuild/easyconfigs/e/ETSF_IO/ETSF_IO-1.0.4-goolf-1.4.10.eb
Contributing ABINIT build in parallel with OpenMPI. To also enable checkpointing ABINIT should be build with ETSF_IO and netCDF
=> Contributing parallel version of ABINIT built with ETSF_IO

easybuild/easyconfigs/c/CUDA/CUDA-6.0.37.eb
added %(version_major)s_%(version_minor)s to source_urls so it works with future major releases
reviewing the install_dir I see these folders which contains a few libraries and binaries:
```
libnvvp  nvvm  open64
```
but those are not included in LD_LIBRARY_PATH, LIBRARY_PATH and PATH in the generated modulefile. There is also a new folder "pkgconfig" which was not present in cuda-5.x releases.  
Maybe we should improve the cuda easyblock to add this in the modulefile? 
maybe @ajdecon can give some advice about this?
=> Cuda 6.0.37

easybuild/easyconfigs/c/Cube/Cube-4.3-foss-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.42.1-foss-2015a.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.4-foss-2015a.eb, easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2015a.eb, easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.2-foss-2015a.eb, easybuild/easyconfigs/o/OTF2/OTF2-1.5.1-foss-2015a.eb, easybuild/easyconfigs/p/PAPI/PAPI-5.4.0-foss-2015a.eb, easybuild/easyconfigs/p/PDT/PDT-3.20-foss-2015a.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.6-foss-2015a.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.2-foss-2015a.eb, easybuild/easyconfigs/s/Score-P/Score-P-1.4-foss-2015a.eb
* Scalasca
* Cube
* Qt
* GLib
* gettext
* libffi
* OTF2
* OPARI2
* PDT
* Score-P
* PAPI
=> {perf}[foss/2015a] Scalasca + deps (REVIEW)

easybuild/easyconfigs/g/git/git-2.2.2-GCC-4.9.2.eb, easybuild/easyconfigs/g/git/git-2.4.1-GCC-4.9.2.eb
Some of git, especially the submodules code, is written in Perl.
I had some problems with the base version of perl included in centos6, so it makes some sense to use the version of perl available in EB.
=> [gcc-4.9.2] fixed git to include EB perl and path (REVIEW)

easybuild/easyconfigs/p/Python/Python-2.5.6-goalf-1.1.0-no-OFED-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6-gompi-1.4.12-no-OFED-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6-goolf-1.4.10-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6-ictce-4.0.6-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6-ictce-4.1.13-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6-ictce-5.2.0-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6-ictce-5.3.0-bare.eb, easybuild/easyconfigs/p/Python/Python-2.5.6_svnversion-cmd.patch
include patch for Python 2.5.6 to fix issue with newer versions of `svnversion` command that spits out '`Unversioned directory`' rather than '`exported`'
this is an alternative to include subversion as a build dep in the Python 2.5.6 easyconfigs, which is rather a crazy endeavour (see #758)
=> patch out svnversion command in Python 2.5.6

test/easyconfigs/easyconfigs.py
cfr. https://github.com/hpcugent/easybuild-framework/pull/1299
=> fix easyconfigs unit tests after making ModulesTool a non-singleton class

easybuild/easyconfigs/c/Cube/Cube-3.4.3-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/c/Cube/Cube-4.2-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/c/Cube/Cube-4.2.3-goolf-1.5.14.eb, easybuild/easyconfigs/c/Cube/Cube-4.3-foss-2015a.eb, easybuild/easyconfigs/c/Cube/Cube-4.3-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/c/Cube/Cube-4.3.2-foss-2015a.eb
* Add easyconfig for latest Cube release which no longer includes the Java reader (now distributed as a separate package) and therefore doesn't require the `configopts` trickery anymore
* Added checksums
* Fixed sanity checks for Cube 4.x (lib vs. lib64)
* Cosmetics
=> {perf}[*] Cube update (REVIEW)

easybuild/easyconfigs/h/Hadoop/Hadoop-2.5.0-cdh5.3.1-native.eb, easybuild/easyconfigs/s/snappy/snappy-1.1.2-GCC-4.9.2.eb, easybuild/easyconfigs/s/snappy/snappy-1.1.2-intel-2015a.eb
This depends on a forthcoming easyblock update to support 'extra_native_libs'
configuration setting in the Hadoop EasyBlock.
edit (by @boegel): requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/632~~
=> Add snappy support and refer Hadoop to the snappy library.

easybuild/easyconfigs/p/Python/Python-3.4.3-intel-2015a.eb
cfr. https://github.com/hpcugent/easybuild-framework/issues/1313#event-347367190
It's unclear to me why this is even there, especially since this is the only Python 3.x easyconfig that has this.
@JensTimmerman: the original easyconfig is yours (see #1598), any idea why this is there?
It's not unlikely this also fixes https://github.com/hpcugent/easybuild-easyblocks/issues/609.
=> remove exts_filter definition from Python 3.4.3 easyconfig, as it can cause problems

easybuild/easyconfigs/g/GCC/GCC-system.eb
This is an accompanying easyconfig for https://github.com/hpcugent/easybuild-easyblocks/pull/633.  It can be used to create a 'GCC/system' module wrapping a system-provided GCC compiler.
=> Minimal example easyconfig for SystemCompiler easyblock

easybuild/easyconfigs/c/CMake/CMake-3.2.3-foss-2015a.eb, easybuild/easyconfigs/c/CMake/CMake-3.2.3-intel-2015a.eb
wraps around #1751 and #1753 by @ocaisa, fixes some minor style issues
=> enable SSL support in most recent CMake easyconfigs

easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.3-iccifort-2011.13.367.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-ClangGCC-1.1.3.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-GCC-4.6.4.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-GCC-4.7.2-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.4-GCC-4.7.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.7.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.7.3-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.1-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.2-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-GCC-4.8.3.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-iccifort-2013_sp1.2.144.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-iccifort-2013_sp1.4.211-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.6.5-iccifort-2013_sp1.4.211.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.7.3-GCC-4.8.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.7.3-gcccuda-2.6.10.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.1-GCC-4.8.3.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-iccifort-2013_sp1.4.211-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-iccifort-2013_sp1.4.211.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.1.133-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.2.164-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.5-GNU-4.9.2-2.25.eb, easybuild/easyconfigs/o/OpenMPI/openmpi-mca-params.conf-pre-1.8.6.patch
The OpenMPI patch included in #1785 is incomplete, and causes segfaults.
See discussion in #1797 and https://github.com/open-mpi/ompi/issues/638.
It's possible that the patch can be enhanced to make it work, but that will be for an EasyBuild version later than v2.2.0
cc @ULHPC, @sylmarien, @besserox
=> revert #1785, patch for OpenMPI is incomplete and causes segfaults

easybuild/easyconfigs/h/h5py/h5py-2.5.0-intel-2015a-Python-2.7.9.eb
this seems to have changed from 2.2 to 2.5
```
== 2015-08-05 10:21:15,214 main.run DEBUG cmd " python setup.py build  --mpi --hdf5=$EBROOTHDF5 " exited with exitcode 1 and output:
zip_safe flag not set; analyzing archive contents...
Installed /dev/shm/h5py/2.5.0/intel-2015a-Python-2.7.9-gpfs/h5py-2.5.0/.eggs/pkgconfig-1.1.0-py2.7.egg
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: option --mpi not recognized
```
=> {data} [intel-2015a] fixes for mpi enabled h5py (review)

easybuild/easyconfigs/f/FastTree/FastTree-2.1.7-goolf-1.4.10.eb, easybuild/easyconfigs/f/FastTree/FastTree-2.1.7-ictce-5.5.0.eb, easybuild/easyconfigs/f/fastqz/fastqz-1.5-GCC-4.8.2.eb, test/easyconfigs/easyconfigs.py
This is required once https://github.com/hpcugent/easybuild-framework/pull/1345 is merged to make the dump aspect of the easyconfig unit tests pass, unless more easyconfigs are tweaked to use templates like `%(name)s` and/or `%(namelower)s`.
For easyconfigs using the `CmdCp` easyblock, it's a bit more tricky since there additional templates (`%(source)s` and `%(target)s`) are supported by the `CmdCp` easyblock itself, which get in the way when trying to resolve templates (since they're not defined (yet) after just parsing the easyconfig).
That's not too big of an issue, it just means that the unit tests are a bit strict w.r.t. template values for these easyconfigs, and may require that templates like `%(name)s` is used (where applicable) in strings where `%(source)s` and/or `%(target)s` …
=> put dummy template values in place to make comparison with dumped easyconfig more robust

easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/g/GNU/GNU-4.9.3-2.25.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCC-4.9.3-binutils-2.25.eb
this will serve as a base for `foss/2015b` and `intel/2015b`, see #1695 and #1696
=> {toolchain} GNU 4.9.3-2.25 (REVIEW)

test/easyconfigs/easyconfigs.py
required because of https://github.com/hpcugent/easybuild-framework/pull/1356
=> stop using 'unresolved_deps' in easyconfigs unit tests

easybuild/easyconfigs/m/MuTect/MuTect-1.1.4-Java-1.7.0_80.eb
Allow installation of MuTect with the current release of Java 1.7.
=> New version of MuTect to use Java 1.7.0_80

easybuild/easyconfigs/p/Python/Python-2.7.10-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.10-intel-2015a.eb
I'm not very happy with including GMP as a dep to Python itself, since it's only required for the `pycrypto` extension being installed, but it seems like the path of least resistance...
cc @wpoely86 (see https://github.com/hpcugent/easybuild-easyconfigs/pull/1854#issuecomment-131034861)
=> add GMP as missing dep in Python 2.7.10 easyconfigs (required for pycrypto extension)

test/easyconfigs/easyconfigs.py
Conflict detection is currently broken, see for example #1862 and #1780.
This is caused by the change made in #1853, apparently the value for `spec['dependencies']` doesn't include everything after all...
Related: https://github.com/hpcugent/easybuild-framework/pull/1359
note: this requires https://github.com/hpcugent/easybuild-framework/pull/1360
=> fix conflict detection in unit tests

test/easyconfigs/easyconfigs.py
required because of https://github.com/hpcugent/easybuild-framework/pull/1361
=> fix determining whether dependency is an external module

easybuild/easyconfigs/p/Python/Python-2.7.10-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.10-intel-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-intel-2015a.eb
This undoes the changes in #1820, which convolutes the Python easyconfigs too much.
Instead, we should look into installing IPython as a bundle, like we do for GC3Pie.
@ehiggs: thoughts?
=> Rollback extending list of Python extensions to resolve IPython deps

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-goolf-1.7.20-R-3.2.0.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-intel-2015a-R-3.2.1.eb
This updates the golf and intel Bioconductor bundles to the latest release of IRanges. (I mistakenly named the branch ivectors - please ignore that).
Fixing this manually on my test instance worked.
=> Update IRanges to 2.2.7 for Bioconductor bundle

easybuild/easyconfigs/p/PSI/PSI-4.0b5-intel-2015a-mt-maxam7-Python-2.7.10.eb, easybuild/easyconfigs/p/PSI/PSI-4.0b5-intel-2015a-mt-maxam8-Python-2.7.10.eb
=> {chem}[intel/2015a] PSI 4.0b5 w/ higher max. angular momentum + Python 2.7.10, Boost 1.59.0 (REVIEW)

easybuild/easyconfigs/s/SIP/SIP-4.16.4-goolf-1.5.14-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-intel-2015a-Python-2.7.9.eb
Without this, SIP installs into the Python installation directory:
```
$ cd $EASYBUILD_PREFIX/software/Python/2.7.9-intel-2015a 
$ find . -name '*sip*'
./include/python2.7/sip.h
./bin/sip
./lib/python2.7/site-packages/sipdistutils.py
./lib/python2.7/site-packages/sip.so
./lib/python2.7/site-packages/sipconfig.py
```
`>_<`
This went undetected because the default sanity check were not being checked for stuff that is installed with easyblocks that derive from `ExtensionEasyBlock` (for example, `PythonPackage` and freidns) until recently, see https://github.com/hpcugent/easybuild-framework/pull/1366...
=> fix installation prefix for SIP

easybuild/easyconfigs/s/SIP/SIP-4.16.4-goolf-1.5.14-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-intel-2015a-Python-2.7.9.eb
without this, building `PyQt` fails because `sip.h` is not available via `$CPATH`
=> fix include path for SIP

easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-goolf-1.4.10-Python-3.2.3.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-ictce-4.0.6-Python-2.7.3.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-ictce-4.1.13-Python-2.7.3.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-1.3-ictce-5.5.0-Python-2.7.5.eb
required because of enabling fallback to default `bin`/`lib` sanity check paths due to https://github.com/hpcugent/easybuild-framework/pull/1366
=> add custom sanity check paths in mpi4py easyconfigs

easybuild/easyconfigs/x/XML-Dumper/XML-Dumper-0.81-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-goolf-1.4.10-Perl-5.16.3.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/x/XML-Twig/XML-Twig-3.48-goolf-1.4.10-Perl-5.16.3.eb, easybuild/easyconfigs/x/XML-Twig/XML-Twig-3.48-intel-2014b-Perl-5.20.0.eb
=> add custom sanity check paths in Perl XML easyconfigs

easybuild/easyconfigs/y/YAML-Syck/YAML-Syck-1.27-goolf-1.4.10-Perl-5.16.3.eb, easybuild/easyconfigs/y/YAML-Syck/YAML-Syck-1.27-ictce-4.1.13-Perl-5.16.3.eb, easybuild/easyconfigs/y/YAML-Syck/YAML-Syck-1.27-ictce-5.3.0-Perl-5.16.3.eb
required because of enabling fallback to default `bin`/`lib` sanity check paths due to hpcugent/easybuild-framework#1366
=> add custom sanity check paths in YAML-Syck easyconfigs

easybuild/easyconfigs/v/vsc-mympirun-scoop/vsc-mympirun-scoop-3.3.0-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/v/vsc-processcontrol/vsc-processcontrol-1.0.eb
=> add custom sanity check paths in vsc-processcontrol and vsc-mympirun-scoop easyconfigs

easybuild/easyconfigs/g/GraphViz/GraphViz-2.18-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/g/GraphViz2/GraphViz2-2.33-intel-2014b-Perl-5.20.0.eb
=> add custom sanity check paths in GraphViz Perl easyconfigs

easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.13-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.13-ictce-4.1.13-Python-2.7.3.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.13-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.14-ictce-4.1.13-Python-2.7.5.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.14-ictce-5.3.0-Python-2.7.5.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.14-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.16.1-intel-2015a-Python-2.7.9.eb
=> add custom sanity check paths in scikit-learn easyconfigs

easybuild/easyconfigs/n/ncdf/ncdf-1.6.6-ictce-5.3.0-R-2.15.3.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.10-ictce-5.3.0-R-2.15.3.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.10-ictce-5.3.0-R-3.0.2-bare.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.10-ictce-5.3.0-R-3.0.2.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.13-intel-2014b-R-3.1.1.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.6.1-ictce-5.3.0-R-3.0.2-bare.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.6.1-ictce-5.3.0-R-3.0.2.eb
=> add custom sanity check paths in ncdf + ncdf4 R easyconfigs

easybuild/easyconfigs/a/AnalyzeFMRI/AnalyzeFMRI-1.1-15-ictce-4.0.10-R-2.15.2.eb, easybuild/easyconfigs/a/AnalyzeFMRI/AnalyzeFMRI-1.1-15-ictce-5.3.0-R-2.15.2.eb, easybuild/easyconfigs/e/evmix/evmix-2.1-intel-2014b-R-3.1.1.eb, easybuild/easyconfigs/e/evmix/evmix-2.3-intel-2014b-R-3.1.1.eb, easybuild/easyconfigs/f/fmri/fmri-1.4-8-ictce-4.0.10-R-2.15.2.eb, easybuild/easyconfigs/f/fmri/fmri-1.4-8-ictce-5.3.0-R-2.15.2.eb, easybuild/easyconfigs/f/fmri/fmri-1.5-0-ictce-5.3.0-R-2.15.3.eb, easybuild/easyconfigs/g/gsl/gsl-1.9-10-intel-2014b-R-3.1.1.eb, easybuild/easyconfigs/r/rjags/rjags-3-13-intel-2014b-R-3.1.1.eb, easybuild/easyconfigs/r/runjags/runjags-1.2.1-0-intel-2014b-R-3.1.1.eb
=> add custom sanity check paths in various easyconfigs for R libraries

easybuild/easyconfigs/d/DBD-Pg/DBD-Pg-3.4.1-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/d/DBD-SQLite/DBD-SQLite-1.42-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/d/DBD-mysql/DBD-mysql-4.028-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/d/DB_File/DB_File-1.831-ictce-5.5.0-Perl-5.18.2.eb, easybuild/easyconfigs/d/DB_File/DB_File-1.831-ictce-5.5.0-Perl-5.20.0.eb, easybuild/easyconfigs/g/GSSAPI/GSSAPI-0.28-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/n/NetLibIDN/Net-LibIDN-0.12-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/p/Parallel-ForkManager/Parallel-ForkManager-1.06-goolf-1.4.10-Perl-5.16.3.eb, easybuild/easyconfigs/s/SOBAcl/SOBAcl-r18-intel-2014b-Perl-5.20.0.eb
=> add custom sanity check paths in various easyconfigs for Perl modules

easybuild/easyconfigs/f/FastTree/FastTree-2.1.7-goolf-1.4.10.eb, easybuild/easyconfigs/f/FastTree/FastTree-2.1.7-ictce-5.5.0.eb, easybuild/easyconfigs/f/fastqz/fastqz-1.5-GCC-4.8.2.eb
`%(source)s` template key needs to be escaped since 'regular' templating of `%(name)s` kicks in first
=> fix typo in FastTree and fastqz easyconfigs

easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.4.3-intel-2015a-ParMETIS-4.0.3.eb
enabling `static` toolchain option breaks the build with:
```
icc -static ... -o kludemo ...
ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/usr/lib/../lib64/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and rel      ink with -pie 
make[2]: *** [kludemo] Error 1
```
this didn't occur before because `$CFLAGS` wasn't passed down as it should before (this was fixed in https://github.com/hpcugent/easybuild-easyblocks/pull/666)
other/older SuiteSparse versions seem unaffected, no changes needed there
cc @ocaisa
=> don't enable 'static' toolchain option in SuiteSparse 4.4.3 easyconfig

easybuild/easyconfigs/s/sympy/sympy-0.7.6-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/s/sympy/sympy-0.7.6-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/sympy/sympy-0.7.6_fix-numpy-include.patch
For some reason unclear to me, making sympy pass the test suite on top of Python 2.7.10 on CentOS 7 requires the patch included, while it's not required on SL6...
=> {math}[intel/2015a] sympy 0.7.6 w/ Python 2.7.10 (REVIEW)

setup.py
see also https://bitbucket.org/pypa/setuptools/pull-requests/118/remove-warning-on-normalization
=> fix dev version to follow PEP-440, which setuptools basically jams down our throat

easybuild/easyconfigs/a/Autotools/Autotools-20150215-GCC-4.9.2.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCC-4.9.2.eb, easybuild/easyconfigs/o/OCaml/OCaml-4.01.0-goolf-1.4.10.eb, easybuild/easyconfigs/o/OCaml/OCaml-4.02.3-foss-2015a.eb
fleshed out from #1056 
requires https://github.com/hpcugent/easybuild-easyblocks/pull/467
=> {lang}[foss/2015a] OCaml 4.02.3 + extensions (REVIEW)

easybuild/easyconfigs/e/Eigen/Eigen-3.2.5.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.6.eb
recent Eigen3 releases 3.2.5 and 3.2.6
Side question: why are there any compiler/toolchain specific versions of Eigen3? Eigen3 is header-only and only the test suite requires a compiler (which isn't used in the Eigen easyblock).
=> {math}[dummy] Eigen3: 3.2.5 & 3.2.6

easybuild/easyconfigs/c/CGAL/CGAL-4.0-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.0-ictce-4.0.6-Python-2.7.3.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.0-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.6-foss-2015a-Python-2.7.10.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.6-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.6-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.6-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.6.3-intel-2015b-Python-2.7.10.eb
fleshed out from #2013, fixes wrong source URL for CGAL 4.6.3 that was used in #2028 (I noticed too late)
cc @hajgato
=> add checksums for CGAL sources + fix source URL for CGAL 4.6.3

easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.2.1-goolf-1.7.20.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.6-goolf-1.7.20.eb
This is an update to Cufflinks to support the goolf-1.7.20 toolchain. It builds successfully on CentOS 7.
It bumps the tool chain version, Boost, Eigen and zlib. The SAMtools version remains the same.
Moved pull request to target develop branch
=> Cufflinks 2.2.1 samtools 0.1.19 goolf 1.7.20

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.2.1-intel-2015b.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.2.1_yambo-fixes.patch
requires https://github.com/hpcugent/easybuild-easyblocks/pull/714
Because the QE source URLs are sort of broken (don't yield a 404 on missing sources), the source files for QE need to be downloaded manually for now.
This shouldn't block this PR though. I made very sure that the right sources are being used by including checksums for all of them.
=> {chem}[intel/2015b] QuantumESPRESSO 5.2.1 (REVIEW)

easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-3.0.0-cli.eb
matters little since it's commented out, but we were bitten by this in our local install after just commenting out these lines...
=> don't use 'beta' in commented out line in hanythingondemand easyconfigs

easybuild/easyconfigs/t/Tk/Tk-8.6.4-GNU-4.9.3-2.25-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-foss-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-foss-2015b-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-goolf-1.4.10-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-goolf-1.7.20-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-ictce-7.3.5-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2015b-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4_different-prefix-with-tcl.patch
fix for
```
window = Tk.Tk()
File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.10-intel-2015b/lib/python2.7/lib-tk/Tkinter.py", line 1814, in __init__
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Tcl/8.6.4-intel-2015b/lib/tcl8.6/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Tcl/8.6.4-intel-2015b/lib/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/2.7.10-intel-2015b/lib/tk8.6 /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/Python/lib …
```
=> add patch for Tk 8.6.4 to fix problem with tk.tcl not being found

easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-goolf-1.4.10.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-ictce-4.0.6.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-ictce-5.3.0.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-intel-2015a.eb
went undetected because of bug in sanity check implementation, fixed by https://github.com/hpcugent/easybuild-framework/pull/1436
=> fix libunistring sanity check: include/unistring is a directory

easybuild/easyconfigs/s/Stampy/Stampy-1.0.28-intel-2015b-Python-2.7.10.eb
=> also copy 'ext', set $PATH and $PYTHONPATH correctly for Stampy

easybuild/easyconfigs/a/ALADIN/ALADIN-36t1_op2bf1-intel-2015b.eb, easybuild/easyconfigs/a/ALADIN/ALADIN_ictce-clim_import-export.patch, easybuild/easyconfigs/g/grib_api/grib_api-1.14.4-intel-2015b.eb, easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-intel-2015b.eb
requires ~~#2203~~
requires https://github.com/hpcugent/easybuild-easyblocks/pull/764
patch files was updated because recent versions of `patch` commands flag relative paths like `../arp/climate/updcpl.F90` potentially harmful, and refuse to apply the patch file
=> {geo}[intel/2015b] ALADIN 36t1_op2bf1 (REVIEW)

easybuild/easyconfigs/a/ALADIN/ALADIN-36t1_op2bf1-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/a/ALADIN/ALADIN-36t1_op2bf1-goolf-1.4.10.eb, easybuild/easyconfigs/a/ALADIN/ALADIN-36t1_op2bf1-ictce-4.1.13.eb, easybuild/easyconfigs/a/ALADIN/ALADIN-36t1_op2bf1-ictce-5.3.0.eb
changes made to patch file, that were done because newer versions of the `patch` command are not fond of relative paths in patch files, require that the list of sources in ALADIN easyconfigs are reordered 
This is required because the first source file determines the subdir in which the patch is applied.
=> reorder sources in ALADIN easyconfigs because of changed patch file

easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.3.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.3-2.25.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-4.9.3.eb, easybuild/easyconfigs/g/GCCcore/mpfr-3.1.2-allpatches-20141204.patch, easybuild/easyconfigs/m/M4/M4-1.4.17-GCCcore-4.9.3.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCCcore-4.9.3.eb
requires ~~https://github.com/hpcugent/easybuild-framework/pull/1451~~ and https://github.com/hpcugent/easybuild-easyblocks/pull/773
This sort of replaces #2108, and deals with a coupe of problems there, in particular:
* avoids building GCC twice to construct the `foss` toolchain; the `GCC` is just a bundle of `GCCcore` and `binutils`
* drop `binutils` from versionsuffix of `GCCcore` (since it's only a build dep there)
* drop `-binutils-2.25` as versionsuffix for `binutils-2.25`; it looks stupid, and which binutils was used to build binutils with is most likely irrelevant
As opposed to #2108, these additional easyconfigs do not affect existing toolchain, in particular the `2015b` ones, which are close to 'end of life', and thus should not be fiddled with.
The intention is to use the …
=> {bundle}[dummy] GCC-4.9.3-2.25: bundle of GCCcore 4.9.3 and binutils 2.25

easybuild/easyconfigs/h/HPL/HPL-2.1-intel-2015.08.eb, easybuild/easyconfigs/i/icc/icc-2015.5.223-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iccifort/iccifort-2015.5.223-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2015.5.223-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iimpi/iimpi-7.5.5-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.1.150-iimpi-7.5.5-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/impi/impi-5.1.2.150-iccifort-2015.5.223-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/intel/intel-2015.08.eb
latest version of the 2015 Intel compilers + latest Intel MPI and MKL
requires ~~#2108~~ #2214
=> {*}[intel/2015.08] HPL 2.1 (REVIEW)

easybuild/easyconfigs/b/Boost/Boost-1.54.0-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/d/DIRAC/DIRAC-14.1-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/d/DIRAC/DIRAC-14.1_fix-linking-issues.patch
requires https://github.com/hpcugent/easybuild-easyblocks/pull/778
=> {chem}[intel/2015b] DIRAC 14.1 (REVIEW)

easybuild/easyconfigs/b/binutils/binutils-2.25.eb
By adding the system library path using the `rpath` option, the
resulting binaries should be 'harden' to work in an environment with a
other libstdc++ etc. The rpath will make sure it always finds the
correct library.
Fix for #2188
=> Harden dummy:dummy binutils

easybuild/easyconfigs/i/InterProScan/InterProScan-5.16-55.0-intel-2015b.eb
InterProScan 5.16 needs Python 2.7
purposely not adjusting versionsuffix, since it needs both Perl and Python and it would become too messy in this case...
=> add Python as dependency for InterProScan

easybuild/easyconfigs/g/GEOS/GEOS-3.3.5-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.3.5-goolf-1.4.10.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.3.5-ictce-4.0.6.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.3.5-ictce-5.3.0.eb, easybuild/easyconfigs/n/netcdf4-python/netcdf4-python-1.0.7-ictce-5.5.0-Python-2.7.6.eb
=> Various fixes: add sanity check to GEOS and change homepage netcdf4-python

easybuild/easyconfigs/p/Python/Python-3.2.3-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/p/Python/Python-3.2.3-goolf-1.4.10.eb, easybuild/easyconfigs/p/Python/Python-3.2.3-ictce-4.0.6.eb, easybuild/easyconfigs/p/Python/Python-3.2.3-ictce-5.3.0.eb, easybuild/easyconfigs/p/Python/Python-3.4.1-intel-2014b.eb, easybuild/easyconfigs/p/Python/Python-3.4.1-intel-2015a.eb, easybuild/easyconfigs/p/Python/Python-3.4.3-intel-2015a.eb, easybuild/easyconfigs/p/Python/Python-3.5.0-intel-2015b.eb
cfr. https://docs.python.org/3/library/argparse.html
=> argparse is part of the Python standard library as of 3.2

easybuild/easyconfigs/h/hub/hub-2.2.2-linux-amd64.eb
Easyconfig for installing hub 2.2.2.
=> {tools}[dummy/dummy] hub 2.2.2 (REVIEW)

easybuild/easyconfigs/i/Instant/Instant-1.6.0-intel-2015b-Python-2.7.11.eb
These enhancements are required for runtime use of Instant(/DOLFIN)
=> add CMake as runtime dep for Instant, define $CC and $CXX in Instant module file

easybuild/easyconfigs/c/CrayCCE/CrayCCE-2015.06-XC.eb, easybuild/easyconfigs/c/CrayCCE/CrayCCE-2015.11-XC.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/c/CrayIntel/CrayIntel-2015.06-XC.eb, easybuild/easyconfigs/c/CrayIntel/CrayIntel-2015.11-XC.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayCCE-2015.06-XC.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayCCE-2015.11-XC.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayIntel-2015.06-XC.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayIntel-2015.11-XC.eb
This PR adds eb files for the new CrayGNU, CrayIntel and CrayCCE toolchains (with dep. pinning). For validation, it adds also easyconfig files for HPL.
Requires: EB 2.5.0 and [hpcugent/easybuild-easyblocks/pull/766](https://github.com/hpcugent/easybuild-easyblocks/pull/766)
=> added new Cray* toolchain versions with dependency pinning

easybuild/easyconfigs/b/BEDTools/BEDTools-2.25.0-foss-2015a.eb
Simple port of 2.25.0 BEDTools to the FOSS 2015a toolchain.
=> Add BEDTools 2.25.0 for FOSS 2015a

easybuild/easyconfigs/p/PGI/PGI-15.10-GCC-4.9.3-2.25.eb
Note: this depends on framework PR1342
https://github.com/hpcugent/easybuild-framework/pull/1342
which has not been merged yet.
=> Add easyconfig for PGI 15.10 using GCCcore 4.9.3.

easybuild/easyconfigs/n/ncdf4/ncdf4-1.15-intel-2015a-R-3.2.1.eb
I tried to also do it for intel-2015b w/ netCDF-4.3.3.1 but it has conflicting
dependencies that won't work with R-3.2.1-intel-2015b (cURL 7.43 vs 7.45).
=> Add ncdf4 for intel-2015a for a user.

easybuild/easyconfigs/p/PRINSEQ/PRINSEQ-0.20.4-goolf-1.4.10-Perl-5.16.3.eb
This application is the typical bioinformatics perl script which depends on many extra perl libraries. How I was managing this kind of installation before was adding the perl libraries dependencies to my main Perl easyconfig. This was leading to a really huge list of libraries / extensions in my main perl easyconfig. Inspired by the bundle easyblock I tried this weird easyconfig which uses the tarball easyblock with extra perl extensions to try to keep the perl script and it's dependencies more self-contained. 
I am curious to listen @boegel complains :P   Do you have any suggestion about a better approach?
I think this can be useful for people deploying bioinfo stuff where this kind of perl applications are quite common CC: @fgeorgatos @pforai @cfenoy @rjeschmi @georg-rath
=> {bio} [goolf-1.4.10] PRINSEQ-0.20.4-goolf-1.4.10-Perl-5.16.3.eb (REVIEW) 

easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.1-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.2-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.3-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.4-intel-2015a-Python-2.7.9.eb
`vsc.fancylogger` is deprecated (and will soon cease to exist), so only mention `vsc.utils.fancylogger`
=> fix comment in HOD easyconfigs

easybuild/easyconfigs/v/VarScan/VarScan-2.4.1-Java-1.7.0_80.eb, easybuild/easyconfigs/v/VarScan/VarScan-2.4.1-foss-2015b.eb
I'm submitting this separately because the upstream location has changed and I think there was some boilerplate text in the 2.3.9 version (e.g.references to junit and homepage), cfr. #1808
=> {bio}[dummy-dummy] VarScan 2.4.1

easybuild/easyconfigs/g/GTK+/GTK+-2.24.28-intel-2015a.eb, easybuild/easyconfigs/g/GTK+/GTK+-2.24.28-intel-2015b.eb, easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.31.4-intel-2015a.eb, easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.31.4-intel-2015b.eb, easybuild/easyconfigs/g/Gtkmm/Gtkmm-2.24.4-intel-2015a.eb, easybuild/easyconfigs/g/Gtkmm/Gtkmm-2.24.4-intel-2015b.eb, easybuild/easyconfigs/g/gtkglext/gtkglext-1.2.0-intel-2015b.eb, easybuild/easyconfigs/p/PyCairo/PyCairo-1.10.0-intel-2015b-Python-2.7.10.eb
fleshed out from #2443
@ocaisa: I prefer making changes like this in a separate PR (it makes #2443 needlessly complicated, and deserves it's own entry in the release notes)
=> Update naming of GTK+, PyCairo and Gdk-Pixbuf

easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.2.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GNU-4.9.3-2.25.eb
There's an easyblock available for flex, so we should use it (in *all* flex easyconfigs).
=> use available flex easyblock

easybuild/easyconfigs/c/CUDA/CUDA-7.5.18-iccifort-2015.3.187-GNU-4.9.3-2.25.eb
This PR include an easyconfig for CUDA+iccifort. It creates a wrapper for nvcc using the Intel compiler. It requires the changes made in ~~hpcugent/easybuild-easyblocks/pull/758~~
=> Updated CUDA easyconfig

easybuild/easyconfigs/b/BFAST/BFAST-0.7.0a-goolf-1.7.20.eb
This updates to using a newer GCC 4.8.4 via goolf-1.7.20 in order to avoid a build
failure for GCC 4.7.2 in goolf-1.4.10.  The build failes  due to a texinfo parsing
bug in GCC documentation files.
This problem appears on systems like CentOS 7 due to stricter parsing in newer
versions of texinfo (5+) supplied by the system environment.
See the bug report for GCC 4.7.2 and patch description
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52903
Address issue #2507
=> Update BFAST to use goolf-1.7.20

easybuild/easyconfigs/p/Perl/Perl-5.20.3-foss-2015b.eb
Full version of Perl, as needed by vcftools-0.1.14
=> Port Perl-5.20.3 to foss/2015b, for vcftools

easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.1r-foss-2015b.eb
Required by a new EB I'm working on.
I needed to increase the download timeout when testing locally, possibly because I have IPv6 and that download was particularly slow.
=> Update OpenSSL to 1.0.1r

easybuild/easyconfigs/t/texinfo/texinfo-4.13a-GCC-4.8.4.eb, easybuild/easyconfigs/t/texinfo/texinfo-4.13a.eb
Create a texinfo 4.13 easyconfig based on the newer 5.2 easyconfig
to support builing older GCC (<=4.7.2) on newer systems. The 4.x releases
of texinfo tolerated a document parsing error in earlier versions of GCC.
In particular, loading the resulting module allows building GCC 4.7.2
on CentOS7.  This GCC is the foundation of the goolf-1.4.10 toolchain
used by many bioinformatics packages in the current EasyBuild (2.6).
The easyconfig's GCC requirement was set to 4.8.4 as a convinience to match
the version of GCC likely already built by the goolf-1.7.20 toolchain.
=> Create texinfo 4.13a easyconfig

easybuild/easyconfigs/x/xtrans/xtrans-1.2.6-foss-2014b.eb, easybuild/easyconfigs/x/xtrans/xtrans-1.3.4-intel-2014b.eb, easybuild/easyconfigs/x/xtrans/xtrans-1.3.4-intel-2015a.eb, easybuild/easyconfigs/x/xtrans/xtrans-1.3.5-goolf-1.5.14.eb, easybuild/easyconfigs/x/xtrans/xtrans-1.3.5-intel-2015a.eb, easybuild/easyconfigs/x/xtrans/xtrans-1.3.5-intel-2015b.eb
list of files in `sanity_check_paths` was incorrectly expanded in #2504 
reported by @hajgato
=> fix sanity check for xtrans

easybuild/easyconfigs/l/libxml2/libxml2-2.9.3-goolf-1.7.20.eb
I had to modify the default libxml2 easyconfig to include this in the configopts
```
--with-zlib=$EBROOTZLIB
```
before adding ``` --with-zlib=$EBROOTZLIB``` the libxml2 build procedure was using the system zlib (I have zlib-devel rpm installed) and then I was getting weird errors like this one compiling another application which uses libxml2 module. I loaded libxml2 module which loads zlib-1.2.8 as dependency but libxml2.so looks for system zlib
```
/scicore/soft/apps/libxml2/2.9.3-goolf-1.7.20/lib/libxml2.so: undefined reference to `gzopen64@ZLIB_1.2.3.3'
```
I think this fix should be added in every libxml2 easyconfig to avoid issues in systems where zlib-devel is installed
=> {lib} [goolf-1.7.20]  libxml2-2.9.3 (REVIEW)

easybuild/easyconfigs/c/CrayCCE/CrayCCE-2015.06-XC.eb, easybuild/easyconfigs/c/CrayCCE/CrayCCE-2015.11-XC.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/c/CrayIntel/CrayIntel-2015.06-XC.eb, easybuild/easyconfigs/c/CrayIntel/CrayIntel-2015.11-XC.eb
This removes fftw (as discussed before) and also craype from the toolchain. I'm creating this PR to update with the latest results and to keep track of the discussion.
The craype removal was advised by Cray (they claim that craype is backwards compatible) as a fix for the bugs we were having when swapping (non-default) PrgEnv dependencies. 
Ideally we want to pin versions for all the dependencies, but first I'd like to have a working TC and hopefully this version will work on more systems. For the moment this version works on Daint, Dora, Santis and Brisi (we still need to test on Swan and Sisu). 
Here I've also removed the version from the PrgEnv and the other change required is to unload + load the PrgEnv instead of swapping. PR#?? 
This replaces …
=> removed PrgEnv version, craype and fftw from the new Cray* XC toolchain (REVIEW)

.gitignore
Installing software using gc3pie generated `eb-*.log` files; let git ignore these files.
=> Ignore log files created by easybuild via gc3pie

easybuild/easyconfigs/l/LLVM/LLVM-3.6.2-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.6.2-intel-2015a.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.6.2-intel-2015b.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.7.0-intel-2015a.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.7.0-intel-2015b.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.7.1-foss-2016a.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.7.1-intel-2015b.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.7.1-intel-2016a.eb
llvm has `Python` builddependency, `ncurses` was used from there. Since `Python` was only a builddependency, `ncurses` needed as dependency.
=> LLVM llvm-config needs ncurses

easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2016a-libX11-1.6.3.eb
=> {lang}[intel-2016a] Python 2.7.11 with libX11 1.6.3 (REVIEW)

easybuild/easyconfigs/g/GLib/GLib-2.47.5-intel-2016a.eb
as far as I can tell, GLib doesn't require the Python bindings to libxml2
it does require `xmllint` provided by `libxml2` however, both at build time (e.g. for testing), and at runtime (cfr. https://developer.gnome.org/gio/stable/glib-compile-resources.html)
cc @hajgato, @ocaisa
=> GLib doesn't require libxml2 with Python bindings

easybuild/easyconfigs/i/imkl/imkl-10.2.6.038-32bit.eb, easybuild/easyconfigs/i/imkl/imkl-10.2.6.038_fix-install-double-dash.patch
issue introduced by renaming toolchain version to `''`, cfr. #2612)
=> add patch file to imkl 10.2.6.038 32-bit easyconfig to fix installer not being able to deal with -- in build path

easybuild/easyconfigs/p/Perl/Perl-5.20.3-foss-2015b.eb, easybuild/easyconfigs/p/Perl/Perl-5.20.3-foss-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.20.3-intel-2015b.eb, easybuild/easyconfigs/p/Perl/Perl-5.20.3-intel-2016a.eb
a patch was already available to make `XML::Bare` build with `icc`, but it wasn't used everywhere...
=> enable XML::Bare in all Perl easyconfigs

easybuild/easyconfigs/g/GLib/GLib-2.40.0-goolf-1.7.20.eb, easybuild/easyconfigs/g/GLib/GLib-2.41.2-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.41.2-intel-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.0-GCC-4.9.2.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.0-foss-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.0-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-goolf-1.7.20.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.46.0-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/g/GLib/GLib-2.46.0-intel-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.47.1-intel-2015b.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.7-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.5.1-intel-2015b-Mesa-11.0.8.eb
builds on top of #2638 by @nathanhaigh, fixes conflict on libxml2 version in DOLFIN dependency tree
=> add missing libxml2 dependencies in GLib easyconfigs

easybuild/easyconfigs/g/GLib/GLib-2.40.0-goolf-1.7.20.eb, easybuild/easyconfigs/g/GLib/GLib-2.41.2-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.41.2-intel-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.0-GCC-4.9.2.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.0-foss-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.0-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-goolf-1.7.20.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.46.0-intel-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.47.1-intel-2015b.eb
This is in relation to fixing #2636.
Not sure which version to use, especially for the older ones, but stuck with `2.9.2` for simplicity.
=> Added missing libxml2 dependency

easybuild/easyconfigs/b/BamUtil/BamUtil-1.0.13-foss-2015b.eb, easybuild/easyconfigs/b/BamUtil/BamUtil-libStatGen-1.0.13-foss-2015b.eb
I've added the versionsuffix because this build uses the bundled libStatGen library, rather than supplying that from a separate EB.
=> {bio}[foss-2015b] BamUtil-1.0.13

easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.1-foss-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.1-intel-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.2-foss-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.2-foss-2015b.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.2-goolf-1.7.20.eb
The old `apache.belnet.be` location wasn't working. 
There's also been a new release, which means it will work better to use the "archive" location, which should include all releases.
I changed this for all the existing easyconfigs and for the new `foss-2015b` version.
=> Fix Xerces-C++ download location

easybuild/easyconfigs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39.eb
Related to the issue [#2384](https://github.com/hpcugent/easybuild-easyconfigs/issues/2384)
On a clean system trying to install GCC-4.9.3-2.25.eb drives to an error due to missing M4 on the machine. This has been solved adding M4 as builddependency in some of the easyconfigs related to the GCC-4.9.3-2.25 installation and we were thus able to successfully install such toolchain.
=> {compiler}[GCC-4.9.3-2.25] fix: added M4 as builddependency

easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.2.3.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.3.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.0.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.1.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.2.eb
including the custom filter which is the same as the default breaks installation on a system where `python` is Python 3.x
related to https://github.com/hpcugent/easybuild-easyblocks/pull/861
=> remove custom exts_filter in GC3Pie easyconfigs, since PythonPackage will use right filter by default

easybuild/easyconfigs/c/CP2K/CP2K-3.0-CrayGNU-2015.11-XC-cuda-7.0.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2015.11-XC.eb
- CUDA enabled CP2K requires easyblock https://github.com/hpcugent/easybuild-easyblocks/pull/850
- The CPU version should work with stock cp2k.py
by @lucamar
=> {chem} CP2K 3.0 CrayGNU-2015.11-XC 

easybuild/easyconfigs/p/Python/Python-3.5.0-intel-2015b.eb, easybuild/easyconfigs/p/Python/Python-3.5.1-foss-2016a.eb, easybuild/easyconfigs/p/Python/Python-3.5.1-intel-2016a.eb
This syncs up the dependencies with the Python 2.7.11 easyconfigs.
=> add missing dependencines in Python 3.5.x easyconfigs

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.2-intel-2016a-R-3.2.3.eb
can't use `%(version)s` since it gets templated with the *extension* version on download...
=> fix source URLs for Bioconductor 3.2

easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.7-GCC-4.6.3-hwloc-chkpt.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.7-GCC-4.6.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.8.1-GCC-4.7.2.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-ClangGCC-1.1.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-ClangGCC-1.2.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-GCC-4.7.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-iccifort-2011.13.367.eb
MVAPICH2 easyblock uses some deprecated configure options:
- `--enable-mpe` disappeared starting version >= 1.9
- `--enable-hwloc` disappeared starting version >= 2.0
PR https://github.com/hpcugent/easybuild-easyblocks/pull/853 removes these deprecated options from the easyblock. 
This current PR set these options directly in the easyconfig files when there are used.
This PR have to be merged first before PR https://github.com/hpcugent/easybuild-easyblocks/pull/853.
=> Add checksum and remove option with default value in some MVAPICH2 easyconfigs

easybuild/easyconfigs/i/IPython/IPython-3.2.1-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/i/IPython/IPython-3.2.3-foss-2015a-Python-2.7.11.eb, easybuild/easyconfigs/i/IPython/IPython-3.2.3-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-foss-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/n/numba/numba-0.22.1-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/s/Sphinx/Sphinx-1.3.3-intel-2015b-Python-2.7.11.eb
similar fix to #2683, but lower impact since a Python dependency is actually included for these
=> remove custom exts_filter in various easyconfigs for (bundles of) Python packages

easybuild/easyconfigs/a/astropy/astropy-1.0.6-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/c/CosmoloPy/CosmoloPy-0.1.104-goolf-1.4.10-Python-2.7.3.eb
this basically reverts 06e9ae546aa45bcdec0db8857ed5e251dfbd9e2a from #2725 where the astropy and CosmoloPy easyconfigs were removed incorrectly, causing the merged PRs #2723 and #2724 to be undone
cc @tloizou
=> Revert "Updated PR, deleted unwanted files" to reinstate astropy and CosmoloPy easyconfigs

easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-intel-2015b-mt-kmer_100.eb, easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-intel-2015b-mt-kmer_31.eb
In #2495, existing easyconfigs were renamed because `Perl`/`BioPerl` was added as a dependency.
But since our policy is not to remove existing easyconfigs from the repository (unless there's a good reason for it), the existing `Velvet` easyconfigs shouldn't have been removed/renamed, but new ones should've been added.
This PR fixes that by readding the original Velvet easyconfigs.
=> reinstate Velvet easyconfigs that were removed in #2495

easybuild/easyconfigs/p/p4vasp/p4vasp-0.3.29-intel-2016a-Python-2.7.11.eb
As requested by @boegel in PR #2807
=> Use `env` wherever `preinstallopts` is used to set env. vars

easybuild/easyconfigs/f/FFLAS-FFPACK/FFLAS-FFPACK-2.2.0-foss-2016a.eb, easybuild/easyconfigs/g/Givaro/Givaro-4.0.1-foss-2016a.eb, easybuild/easyconfigs/l/LinBox/LinBox-1.4.0-foss-2016a.eb
This PR adds `.eb` recipes for building [LinBox][1] 1.4.0 and its
(minimal) dependencies [FFLAS-FFPACK][2] and [Givaro][3].
The `.eb` files build successfully with toolchains `foss-2016a` and
`foss-2015a`, and probably with any other toolchain that can
successfully build GMP and supports C++11.
[1]: http://linalg.org/
[2]: http://github.com/linbox-team/fflas-ffpack/
[3]: http://github.com/linbox-team/givaro/
=> {math,lib}[foss/2016a] LinBox 1.4.0, FFLAS-FFPACK 2.2.0, Givaro 4.0.1 (REVIEW)

easybuild/easyconfigs/t/TopHat/TopHat-2.1.1-foss-2015b.eb
Update to latest maintenance release.
Disable obsolete patch for older versions of SeqAn. That should probably be removed for the Intel toolchain too, but I don't have that compiler installed anywhere to test.
=> {bio} [foss-2015b] TopHat2-2.1.1

easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/FDS/FDS-6.3.0-intel-2015b.eb, easybuild/easyconfigs/m/Mesa/Mesa-10.4.5-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/m/Mesa/Mesa-10.5.5-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.0.2-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.0.8-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-gimkl-2.11.5.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-intel-2016a.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-ictce-4.0.6-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-ictce-4.1.13-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/m/Minimac3/Minimac3-1.0.10-foss-2015a.eb, easybuild/easyconfigs/m/Minimac3/Minimac3-1.0.10-intel-2015a.eb, easybuild/easyconfigs/m/motif/motif-2.2.4-goolf-1.4.10.eb, easybuild/easyconfigs/m/motif/motif-2.2.4-ictce-4.1.13.eb, easybuild/easyconfigs/m/multitail/multitail-6.2.1-intel-2015a.eb
As requested by @boegel in PR #2807
=> Use `env` wherever `prebuildopts is used to set environmental variables.

easybuild/easyconfigs/s/SoX/SoX-14.4.2-foss-2015a.eb
libsox is used to manipulate audio files and required for installing Torch (I'm working on an easyconfig)
And yes, it's for HPC, thanks Deep Learning...
edit: depends on ~~#2823~~, ~~#2824~~
=> add easyconfig for SoX

easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.42.0-intel-2014b.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.44.0-intel-2015a.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.47.1-intel-2015b.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.47.1-intel-2016a.eb
Check:
https://packages.debian.org/source/sid/gobject-introspection
and
https://packages.debian.org/sid/gobject-introspection
=> Builddependencies fixed for GObject-introspection

easybuild/easyconfigs/p/Python/Python-3.5.1-foss-2016a.eb, easybuild/easyconfigs/p/Python/Python-3.5.1-intel-2016a.eb
Issue encountered in https://github.com/hpcugent/easybuild-easyconfigs/pull/2885
cfr. http://www.devsumo.com/technotes/2013/04/building-python-3-3-with-lzma-on-linux-and-os-x/
=> add XZ as dependency in Python 3.5.1 easyconfigs, required for lzma

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/g/GMP/GMP-6.1.0-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.9.2-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.4-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2016.02-GCC-4.9-no-X11.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-intel-2016.02-GCC-4.9.eb
Generated with "eb Python-2.7.11-intel-2016a.eb --try-toolchain=intel,2016.02-GCC-4.9 -r". It's great that this rebuilds all the dependencies with the new toolchain.
So, assuming I'm already running this in my easyconfig clone repo, from a new branch created from develop, and this runs successfully (as it did), and since something like this can in principle generate many eb files, is there already a way to automatically copy the generated files from ebfiles_repo, put them in the correct place, clean up the build metadata and git add them? :) 
Or maybe since this works from the command line without any additional changes to the files, there is no point in adding them to the repository?
=> Python-2.7.11 (and dependencies) with intel-2016.02-GCC-4.9 toolchain

easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-4.9.2.eb
Requires ~~#2911~~ and ~~#2913~~
=> New EasyConfig for Bison 3.0.4 with the GCCcore 4.9.2 toolchain

easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.2.eb
Requires ~~#2911~~ and ~~#2913~~
=> New EasyConfig for flex 2.5.39 with the GCCcore 4.9.2 toolchain

easybuild/easyconfigs/a/ASE/ASE-3.10.0-intel-2016.02-GCC-4.9-Python-2.7.11.eb
Adapted from ASE-3.9.1.4567-intel-2016a-Python-2.7.11.eb (besides toolchain and version, source url and source name are now different)
Should this explicitly depend on Python-2.7.11 with the same toolchain or is that handled automatically?
edit: requires ~~#2895~~
=> ASE-3.10.0 with intel-2016.02-GCC-4.9 toolchain

easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-4.9.2.eb
Requires ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2911~~ and https://github.com/hpcugent/easybuild-easyconfigs/pull/2916.
=> New EasyConfig for numactl 2.0.11 with the GCCcore toolchain

easybuild/easyconfigs/p/pymatgen/pymatgen-3.5.0-intel-2016.02-GCC-4.9-Python-2.7.11.eb, easybuild/easyconfigs/s/spglib/spglib-1.9.2-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/s/spglib/spglib-1.9.2_remove_duplicate.patch
don't know why pymatgen-3.5.0.tar.gz cannot be found in PYPI_SOURCE url, 3.4.0 can...
=> {chem}[intel/2016.02-GCC-4.9] pymatgen 3.5.10 and spglib 1.9.2

easybuild/easyconfigs/i/IPython/IPython-3.2.3-foss-2015a-Python-2.7.11.eb, easybuild/easyconfigs/i/IPython/IPython-3.2.3-intel-2015b-Python-2.7.10.eb
=> add dependency extensions for MarkupSafe and jsonscheme in IPython 3.2.3 easyconfigs + use %(pyver)s and %(pyshortver)s

easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-foss-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-intel-2016a-Python-3.5.1.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1_fix-Tcl-Tk-libdir.patch
This fixes a segmentation fault that occurs when using `matplotlib` on a system where Tcl/Tk are also available on the OS; this also fixes #2659
Without the patch:
```
$ ldd $EBROOTMATPLOTLIB/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backends/_tkagg.so | egrep 'tcl|tk'
libtcl8.5.so => /usr/lib64/libtcl8.5.so (0x00002b78b64f1000)
libtk8.5.so => /usr/lib64/libtk8.5.so (0x00002b78b681a000)
$ python -c "import matplotlib.pyplot as plt; plt.plot(range(0,100000)); plt.show()"
Segmentation fault
$ echo $?
139
```
With the patch:
```
$ ldd $EBROOTMATPLOTLIB/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-linux-x86_64.egg/matplotlib/backends/_tkagg.so | egrep 'tcl|tk'
libtcl8.6.so => /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/softwar …
```
=> add patch for matplotlib 1.5.1 to fix Tcl/Tk library paths being used

easybuild/easyconfigs/w/worker/worker-1.5.1-intel-2015a.eb, easybuild/easyconfigs/w/worker/worker-1.6.4-intel-2016a.eb
I'm making the assumption that the default module naming scheme and default location of modules relative to install directory is used here, but since the other commands may need to be changed too according to site settings, that is OK-ish.
@cc gjbex
=> add sed command to worker easyconfig files to fix module_path in conf/worker.conf

easybuild/easyconfigs/e/Eigen/Eigen-2.0.17-goolf-1.4.10.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.1-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.1-goolf-1.4.10.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.1-ictce-4.0.6.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.1-ictce-5.3.0.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.4-goalf-1.5.12-no-OFED.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.4-goolf-1.4.10.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.4-ictce-4.1.13.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.4-ictce-5.3.0.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.1.4-ictce-5.5.0.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.0-ictce-5.5.0.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.2-goolf-1.5.14.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.2-ictce-7.1.2.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.2-intel-2014b.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.3-foss-2015a.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.3-intel-2015a.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.5.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.6-goolf-1.7.20.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.6.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-foss-2016a.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-intel-2015b.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-intel-2016a.eb
=> drop toolchainopts from Eigen easyconfigs, since it is headers-only

easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.3-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/p/pompi/pompi-2016.03.eb
I hope to be able to uncomment the sanity_check_commands. For some strange reason, when they are run, `mpicc` does not find `pgcc` in the PATH; however after loading the module the `mpicc` command works just fine.
=> PGI: add OpenMPI and pompi toolchain easyconfigs.

easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016.04.eb, easybuild/easyconfigs/f/foss/foss-2016.04.eb, easybuild/easyconfigs/g/gompi/gompi-2016.04.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-foss-2016.04.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.3.0-2.26-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.04-OpenBLAS-0.2.18-LAPACK-3.6.0.eb
requires ~~#2524~~
note: this is the first version of the `foss` toolchain that uses GCC 5.x (5.3, to be exact)
=> {toolchain}[dummy] foss/2016.04

easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.2g-GCCcore-4.9.3.eb
Add latest version of OpenSSL built with lowest appropriate compiler toolchain that can be used as dependency with `--minimal-toolchains`.
=> OpenSSL-1.0.2g-GCCcore-4.9.3

easybuild/easyconfigs/l/libevent/libevent-2.0.22-GCCcore-4.9.3.eb, easybuild/easyconfigs/t/tmux/tmux-2.2-GCCcore-4.9.3.eb
`tmux-2.2` and it's required dependency `libevent/2.0.22` built for `GCCcore/4.9.3`.
=> tmux-2.2-GCCcore-4.9.3

easybuild/easyconfigs/o/OpenCV/OpenCV-2.4.12-intel-2016a.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-2.4.9-intel-2014.06.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-2.4.9-intel-2014b.eb
without this, `cv2.so` gets installed in the installation prefix of the Python that is listed as a dependency...
another nice example of why specifying `sanity_check_paths` is useful :)
=> correct install location of OpenCV Python bindings

easybuild/easyconfigs/a/Automake/Automake-1.15-ictce-5.3.0.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-ictce-5.3.0.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-ictce-5.3.0.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.1-foss-2015a.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.1-goolf-1.4.10.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.1-ictce-5.3.0.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2015a.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-goolf-1.4.10.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-ictce-5.3.0.eb
run into this while testing https://github.com/hpcugent/easybuild-easyconfigs/pull/2892
workaround with `LIBS` is easier than patching the broken `Makefile`, cfr. https://bugs.gentoo.org/show_bug.cgi?id=444050
=> include XZ as dependency for libunwind

easybuild/easyconfigs/b/bzip2/bzip2-1.0.6.eb
mainly done to avoid the `import os`...
this requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/910~~ (with https://github.com/pescobar/easybuild-easyblocks/pull/5 included)
=> clean up dummy bzip2 easyconfig, define buildopts rather than defining $CC and $CFLAGS via os.environ

easybuild/easyconfigs/m/mpmath/mpmath-0.19-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/s/sympy/sympy-1.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/s/sympy/sympy-1.0_tests-unicode.patch
Update sympy to 1.0 and add patch to fix Unicode-related test failure.
sympy now has an external dependency on mpmath, so I've included that too.
=> {math} [foss-2016a] sympy-1.0-foss-2016a-Python-2.7.11

setup.py, test/__init__.py, test/easyconfigs/easyconfigs.py, test/easyconfigs/suite.py
```
find . -name '*.py' | xargs sed -i '' 's@https://vscentrum.be/nl/en@https://www.vscentrum.be@g'
```
=> fix broken link to VSC website in license headers

easybuild/easyconfigs/s/snappy/snappy-1.1.3-GCC-4.9.3-2.25.eb
fixing to a commit for 1.1.2 but naming it 1.1.3 is kinda wrong...
=> fix source for snappy 1.1.3, drop autogen

easybuild/easyconfigs/i/IPython/IPython-4.2.0-intel-2016a-Python-2.7.11.eb
pathlib is required by pickleshare so it has to be installed before
=> IPython-4.2 fix so it can be installed offline

easybuild/easyconfigs/a/ABINIT/ABINIT-7.10.5-intel-2016.02-GCC-4.9-libxc.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-7.10.5-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-7.10.5-intel-2016.02-GCC-4.9_libxc.eb
Initially generated with "eb ABINIT-7.10.4-intel-2015a.eb --try-software-version=7.10.5
--try-toolchain=intel,2016.02-GCC-4.9", then ensured intel mpi and fft support
=> Abinit-7.10.5 with intel-2016.02-GCC-4.9 toolchain

easybuild/easyconfigs/m/mayavi/mayavi-4.4.4-intel-2016a-Python-2.7.11.eb
this slipped in with #3106, and leads to an error because the source file can not be found (or downloaded, since no source URLs are provided)
the actual source tarball for `mayavi` is downloaded via the extensions
=> drop 'sources' line from mayavi easyconfigs, since it's a bundle

easybuild/easyconfigs/b/Boost/Boost-1.60.0-foss-2015a.eb, easybuild/easyconfigs/b/Boost/Boost-1.60.0-foss-2015b.eb, easybuild/easyconfigs/b/Boost/Boost-1.60.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/b/Boost/Boost-1.60.0-foss-2016a.eb, easybuild/easyconfigs/b/Boost/Boost-1.60.0-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/b/Boost/Boost-1.60.0-intel-2016a.eb, easybuild/easyconfigs/b/Boost/Boost-1.60.0_fix-auto-pointer-reg.patch
cfr. https://github.com/boostorg/python/issues/56, patch grabbed from https://github.com/boostorg/python/pull/59
This fixes a problem that occurs with Yade:
```
File "HPC_Yade_Oedometer_Funk.py", line 319, in <module>
OedometerMasterFunk(packing = 'Random',frictionAngle_Soil=frictionAngle_Soil,limit = limit)                         # SINGLE NODE
File "HPC_Yade_Oedometer_Funk.py", line 81, in OedometerMasterFunk
TopSpheres=pack.regularOrtho(pack.inAlignedBox(B_Corner,T_Corner),radius=TopRadius,gap=TopRadius*0.0,color=(1,1,0),material=FricMat6)
File "/apps/gent/SL6/sandybridge/software/Yade/1.20.0-intel-2016a-Python-2.7.11/lib64/yade-1.20.0/py/yade/pack.py", line 264, in regularOrtho
if predicate(xyz,radius): ret+=[utils.sphere(xyz,radius=radius,**kw)] …
```
=> add patch for Boost 1.60.0 to fix bug resulting in TypeError

easybuild/easyconfigs/r/RAxML/RAxML-8.2.4-foss-2016a-hybrid-avx2.eb
Based on the existing easyconfig for the intel 2015b toolchain.
=> RAxML 8.2.4-hybrid-avx2 for foss 2016a

easybuild/easyconfigs/i/ImageMagick/ImageMagick-6.9.4-8-intel-2016a.eb, easybuild/easyconfigs/i/i-cisTarget/i-cisTarget-20160602-intel-2016a-Python-2.7.11.eb
fix for:
```
python -c "import wand.image"
File "<string>", line 1, in <module>
File "build/bdist.linux-x86_64/egg/wand/image.py", line 20, in <module>
File "build/bdist.linux-x86_64/egg/wand/api.py", line 1394, in <module>
ImportError: MagickWand shared library not found or incompatible
Original exception was raised in:
File "build/bdist.linux-x86_64/egg/wand/api.py", line 289, in <module>
ctypes.c_void_p]
File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
func = self.__getitem__(name)
File "/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/lib/pytho …
```
=> fix ImageMagick version used as dep for i-cisTarget, Wand requires ImageMagic 6.x

easybuild/easyconfigs/e/EasyBuild/EasyBuild-2.8.1.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/957 to actually be picked up
=> also include vsc-install in list of sources, to support offline installation

easybuild/easyconfigs/a/Amber/Amber-14-intel-2016a-AmberTools-15-patchlevel-13-13.eb, easybuild/easyconfigs/a/Amber/Amber-14_fix-hardcoding.patch, easybuild/easyconfigs/a/Amber/AmberTools-15_fix-mdgx-print-bug.patch
heavily based on @thiell's PR #2794
requires https://github.com/hpcugent/easybuild-easyblocks/pull/958
=> {chem}[intel/2016a] Amber 14 w/ AmberTools 15 (REVIEW)

easybuild/easyconfigs/l/Lua/Lua-5.1.4-8.eb
`dummy` toolchain version cause dependency not to be loaded at build time
=> Dependency not loaded for Lua built with dummy

easybuild/easyconfigs/l/Lmod/Lmod-6.4.2.eb
`dummy` toolchain version causes dependency not to be loaded at build time
=> Dependency not loaded for Lmod built with dummy

easybuild/easyconfigs/l/likwid/likwid-4.1.0-GCCcore-4.9.3.eb
This is not needed, and makes the unit tests fail because the `toolchain_inherited` value for the parsed deps changes from `False` to `True` in the test for the dumped easyconfig
=> don't hard specify toolchain for binutils build dep in likwid easyconfig, since it matches parent toolchain

easybuild/easyconfigs/t/TVB/TVB-1.4.1-intel-2016a-Python-2.7.11.eb
without having `$SVN_REVISION` defined, these (alarming looking but actually harmless) warnings are being printed:
```
$ python -c "from tvb.simulator.lab import *"
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```
cfr. https://groups.google.com/forum/#!topic/tvb-users/ON9kZOeLOX8
=> define $SVN_REVISION to supress 'Not a git repository' messages in TVB easyconfig

.travis.yml
pydot 1.2.x that was released over the weekend is no longer compatible with Python 2.6
=> stick to pydot 1.1.0 for Python 2.6 in Travis config

easybuild/easyconfigs/j/JAGS/JAGS-4.2.0-foss-2016a.eb
Based on the existing easyconfig for intel/2016a.
I did replace the hardcoded library names for BLAS and LAPACK by $LIBBLAS and $LIBLAPACK: this also means that OpenBLAS is now used for both BLAS and LAPACK functionality for this version, instead of linking to a separate LAPACK library as was done in an older easyconfig for the goolf toolchain.
=> {math}[foss/2016a] JAGS 4.2.0

easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016a-Python-3.5.1.eb
pkgconfig built with foss/2016a for Python 3.5.1.
=> pkgconfig built with foss/2016a for Python 3.5.1

easybuild/easyconfigs/h/h5py/h5py-2.5.0-foss-2016a-Python-2.7.11-HDF5-1.8.16.eb, easybuild/easyconfigs/h/h5py/h5py-2.5.0-foss-2016a-Python-3.5.1-HDF5-1.8.16.eb, easybuild/easyconfigs/h/h5py/h5py-2.5.0-foss-2016a-Python-3.5.1-HDF5-1.8.16.patch
h5py 2.5.0 built using the foss-2016a toolchain. Both for python 2.7.11 and 3.5.1. The latter requires a patch in order for it to built correctly.
=> h5py 2.5.0 built using the foss-2016a toolchain

easybuild/easyconfigs/n/numpy/numpy-1.11.0-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/n/numpy/numpy-1.11.0-sse42.patch
The change from distutils to setuptools in numpy 1.11.0 seems to cause problems. In the install step the package is seems to be installed in a path under /tmp, and the installation fails since the setup checks if that path is in $PYTHONPATH
=> Numpy 1.11.0

easybuild/easyconfigs/j/JUnit/JUnit-4.12-Java-1.8.0_77.eb
Version of Junit using Java 1.8.0_77.
One of the things I am now running into, is that Java is a moving target. Is it possible to create dependencies on Java 1.7 or 1.8 excluding the subversion? That would make it easy to upgrade Java without having to update configs and reinstall a lot of software.
=> Version of Junit using Java 1.8.0_77

easybuild/easyconfigs/a/ADMIXTURE/ADMIXTURE-1.3.0.eb
It contains a precompiled 32-bit and 64-bit binary, so I guess a versionsuffix (linux? linux-x86?) is not really useful?
=> {bio}[foss/2016a] ADMIXTURE

easybuild/easyconfigs/c/cuDNN/cuDNN-5.0-CUDA-7.5.18.eb
We need to specify the CUDA version now as there is a dependency on CUDA (eg. there will be a different cuDNN 5.0 for CUDA 8.0). I still have a 7.5 hardcoded here in the archive name, any idea welcomed to improve it.
=> add easyconfig for cuDNN 5.0 (GA) for CUDA 7.5

easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-foss-2016a-Python-3.5.1.eb
Matplotlib for Python 3.5.1 using the foss 2016a toolchain.
=> Matplotlib for Python 3.5.1 using the foss 2016a toolchain.

easybuild/easyconfigs/c/configparser/configparser-3.5.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/e/entrypoints/entrypoints-0.2.2-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/e/entrypoints/entrypoints-0.2.2-foss-2016a-Python-3.5.1.eb, easybuild/easyconfigs/i/IPython/IPython-5.0.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/i/IPython/IPython-5.0.0-foss-2016a-Python-3.5.1.eb, easybuild/easyconfigs/i/IPython/ipython-5.0.0_fix-test-paths-symlink.patch, easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.3.0-foss-2016a-Python-2.7.11-zmq4.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.3.0-foss-2016a-Python-3.5.1-zmq4.eb, easybuild/easyconfigs/p/path.py/path.py-8.2.1-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/path.py/path.py-8.2.1-foss-2016a-Python-3.5.1.eb, easybuild/easyconfigs/p/prompt-toolkit/prompt-toolkit-1.0.3-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/prompt-toolkit/prompt-toolkit-1.0.3-foss-2016a-Python-3.5.1.eb, easybuild/easyconfigs/t/testpath/testpath-0.3-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/t/testpath/testpath-0.3-foss-2016a-Python-3.5.1.eb, easybuild/easyconfigs/w/wcwidth/wcwidth-0.1.7-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/w/wcwidth/wcwidth-0.1.7-foss-2016a-Python-3.5.1.eb
Hi all,
here are two versions of the new IPython 5.0.0 for Python 2.7 and 3.5.
I followed the same approach as others used in previous IPython versions, that is to create a bundle out of all the python package dependencies. However I did not succeed to bundle the whl-based python packages (entrypoints, prompt-toolkit, ...). Does anybody know how to do this?
I would be happy for comments from any easybuild guru on whether everything is handled correctly.
Best,
Tomas
=> Add IPython 5.0.0 and missing dependencies.

easybuild/easyconfigs/h/HDF/HDF-4.2.11-foss-2015a.eb
Added hdf4 libraries to foss 2014a.  HDF4 is needed to read NASA EOS  data files from Terra and Aqua (Aura uses h5).
=> Hdf4 foss 2015a

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.1.2-ictce-7.3.5.eb
wrapper PR for #1644 by @sylmarien, adds checksums for sources and removed `plumed` from `buildopts` due to build issue:
```
touch uncompress-plumed                                                                                                                                                                                                                                                                                                  if test -d ../PLUMED; then \                                                                                                                                                                                                                                                                                                     
(cd ../PLUMED ; export plumedir="`pwd`" …
```
=> {chem}[ictce/7.3.5] QuantumESPRESSO 5.1.2

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.1.2-ictce-7.3.5.eb
Hi, here is the latest QuantumESPRESSO built with the latest ictce toolchain.
We have it built on our side on Debian, please tell us if there are things to change.
=> {chem} [ictce-7.3.5] QuantumESPRESSO 5.1.2 (REVIEW)

easybuild/easyconfigs/b/BayPass/BayPass-2.1-foss-2015a.eb
An easyconfig file for BayPass 2.1 using the foss 2015a toolchain.
=> {bio}[foss/2015a] BayPass 2.1

easybuild/easyconfigs/a/AutoDock/AutoDock-4.2.5.1-GCC-5.2.0.eb
An easyconfig for AutoDock 4.2.5.1 with toolchain GCC 5.2.0.
Note that AutoGrid will be provided as a separate easyconfig, due to there not currently being an easyblock for the AutoDock suite.
=> {tools}[GCC/5.2.0] AutoDock 4.2.5.1

easybuild/easyconfigs/b/Boost/Boost-1.52.0-foss-2015a.eb
An easyconfig for Boost 1.52.0 built with the toolchain foss 2015a.
I know there are many versions of Boost already, but I noticed this one was missing.
=> Boost 1.52.0 with foss 2015a

easybuild/easyconfigs/c/CDO/CDO-1.7.1-foss-2015a.eb, easybuild/easyconfigs/y/YAXT/YAXT-0.4.4-foss-2015a.eb
Two easyconfigs, one for CDO 1.7.1 and one for one of its dependencies, YAXT 0.4.4 (netCDF 4.3.2 and HDF5 1.8.13 are already present in the repo). These are built with the toolchain foss 2015a.
=> {data}[foss/2015a] CDO 1.7.1

easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.17.1-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.17.1-foss-2016a-Python-3.5.1.eb
scikit-learn compiled with the foss 2016a toolchain. Both for Python 2.7.11 and 3.5.1.
=> foss 2016a versions of scikit-learn for both Python 2.7.11 and 3.5.1

easybuild/easyconfigs/g/gdc-client/gdc-client-1.0.1-intel-2016b-Python-2.7.12.eb
`source_urls` and `sources` for `gdc-client` are already specified via `exts_list`, also defining them top-level doesn't make sense
=> clean up sources spec for gdc-client bundle easyconfig

easybuild/easyconfigs/f/FDS/FDS-6.3.0-intel-2015b.eb, easybuild/easyconfigs/f/FDS/FDS-r17534-intel-2015a.eb, easybuild/easyconfigs/f/FDS/FDS-r18915-goolf-1.4.10.eb, easybuild/easyconfigs/f/FDS/FDS-r18915-ictce-5.5.0.eb, easybuild/easyconfigs/f/FDS/FDS-r18915-intel-2015a.eb, easybuild/easyconfigs/f/FDS/FDS-r22681-intel-2015a.eb
fix for #3459
TODO: add sanity check command that verifies that `fds` has MPI support?
```
$ fds<enter><enter>
Fire Dynamics Simulator
Current Date     : August 26, 2016  19:43:10
Version          : FDS 6.3.0
Revision         : unknown
Revision Date    : unknown
Compilation Date : unknown
MPI Enabled; Number of MPI Processes:     1
OpenMP Disabled
Consult FDS Users Guide Chapter, Running FDS, for further instructions.
Hit Enter to Escape...
$ echo '' | fds 2>&1 | grep 'MPI Enabled'
MPI Enabled; Number of MPI Processes:     1
$ echo $?
0
```
=> specify correct MPI target in FDS easyconfigs

easybuild/easyconfigs/c/Circos/Circos-0.69-2-ictce-5.5.0-Perl-5.18.2.eb
Circos 0.69-2 built with the toolchain ictce 5.5.0.
=> {bio}[ictce/5.5.0] Circos 0.69-2

easybuild/easyconfigs/f/FFTW/FFTW-3.3.5-gompi-2016.07.eb
A version bump for FFTW to 3.3.5 (otherwise it's the same as FFTW 3.3.4 with gompi 2016b).
=> {numlib}[gompi/2016.07] FFTW 3.3.5

easybuild/easyconfigs/g/gperftools/gperftools-2.5-foss-2016a.eb, easybuild/easyconfigs/m/MIRA/MIRA-4.0.2-foss-2016a-Python-2.7.11.eb
Version of MIRA using the foss 2016a toolchain including an updated version of the dependency gperftools.
=> Mira 402 foss 2016a

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-foss-2016.04.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2016.04.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-foss-2016.04.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016.04.eb, easybuild/easyconfigs/g/GMP/GMP-6.1.1-foss-2016.04.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016.04.eb, easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2016.04.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2016.04.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-foss-2016.04.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.4-foss-2016.04.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-foss-2016.04.eb, easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.2h-foss-2016.04.eb, easybuild/easyconfigs/p/Python/Python-3.5.2-foss-2016.04.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.13.0-foss-2016.04.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-foss-2016.04.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.5-foss-2016.04.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2016.04.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-foss-2016.04.eb
An easyconfig for Python 3.5.2 as well as its (many) dependencies. The reason for foss 2016.04 is because this Python is needed for Blender 2.66a (#3518) and I used a foss toolchain that is similar to 2016.04 in order to build Blender.
=> {lang}[foss/2016.04] Python 3.5.2

easybuild/easyconfigs/f/FFTW/FFTW-3.3.5-gompi-2016.09.eb, easybuild/easyconfigs/f/foss/foss-2016.09.eb, easybuild/easyconfigs/g/gompi/gompi-2016.09.eb, easybuild/easyconfigs/h/HPL/HPL-2.2-foss-2016.09.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompi-2016.09-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.09-OpenBLAS-0.2.19-LAPACK-3.6.1.eb
An experimental toolchain for foss. This toolchain uses:
- GCC 6.2.0-2.27 (already in the repo)
- Open MPI 2.0.1 (which forms gompi 2016.09 with GCC)
- OpenBLAS 0.2.19
- FFTW 3.3.5 
- ScaLAPACK 2.0.2
There is also an easyconfig for HPL 2.2 with this toolchain, as a test.
Hopefully, this combination works out okay as it has not been thoroughly tested (I'm hoping many people using it can find problems faster).
=> {toolchain} foss 2016.09

easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.4.2-foss-2016a-NASM-2.12.01.eb
This is a foss 2016a version of the existing intel 2016a one. It is required for later pull requests, e.g. Gdk-Pixbuf, which will keep foss 2016a better in line with existing intel 2016a versions.
=> libjpeg-turbo foss 2016a with nasm dependency

easybuild/easyconfigs/a/ATK/ATK-2.20.0-foss-2016a.eb
Version of ATK built using the foss 2016a toolchain. This one is similar to the intel 2016a version.
=> Version of ATK built using the foss 2016a toolchain.

easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.35.1-foss-2016a.eb
Adaptation of Gdk-Pixbuf for the intel 2016a toolchain for foss 2016a.
=> Gdk-Pixbuf using the foss 2016a toolchain.

easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.2.7-foss-2016a.eb
Version of Harfbuzz using the foss 2016a toolchain. The config is based on the intel 2016a one.
=> Version of Harfbuzz using the foss 2016a toolchain

easybuild/easyconfigs/f/FFmpeg/FFmpeg-0.10.16-intel-2016a.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-2.8.6-intel-2016a.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-2.8.7-foss-2016a.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-2.8.7-intel-2016a.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.0.2-foss-2016a.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.0.2-intel-2016a.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.1.3-intel-2016b.eb
bzip2 and libxcb are pulled in by FFmpeg if available. Since both have easyconfigs, and are pulled in by other software as well, I suggest to include these dependencies.
Also replaced 'so' with SHLIB_EXT for the intel easyconfigs.
=> Added bzip2 and libxcb dependencies to FFmpeg 3.x easyconfigs

easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.17.1-intel-2016b-Python-2.7.12.eb
(follow-up for #3554)
@wpoely86 although there's an easyconfig available for matplotlib 1.5.2, it's better to stick to 1.5.1 for now since it's commonly used as a dependency
=> stick to matplotlib 1.5.1 in scikit-learn, for compatibility with other Python modules

easybuild/easyconfigs/p/Python/Python-3.5.2-foss-2016.04.eb, easybuild/easyconfigs/p/Python/Python-3.5.2-foss-2016b.eb, easybuild/easyconfigs/p/Python/Python-3.5.2-intel-2016b.eb
Fix the compilation of Python
Had various issues with README file, and realised the patches were not included in 3.5.2, but were for 3.5.1
=> fix python 3.5.2 compilation with all toolchains

easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-6.0.1-foss-2016a.eb, easybuild/easyconfigs/e/EIGENSOFT/EIGENSOFT-6.1.1-foss-2016a.eb
I took the existing easyconfig EIGENSOFT-6.1.1-goolf-1.7.20.eb, but converted it from Tarball to MakeCp: the source tarball contains both source files and precompiled executables, this easyconfig rebuilds the executables.
=> {bio}[foss/2016a] EIGENSOFT 6.0.1 and 6.1.1

easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.0.2-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.0.2-foss-2016a-Python-3.5.1.eb, easybuild/easyconfigs/p/protobuf/protobuf-3.0.2-foss-2016a.eb
Google protobuf 3.0.2 including the Python library. Since protobuf includes libraries that can be used by other programs using a dummy toolchain (as done for older protobuf versions) does not seem to be the right approach.
For now I've choosen the foss 2016a toolchain. Since protobuf itself is a low level compiler and library using a GCC toolchain could also be an option for the main protobuf. Please let me know if this approach is better.
=> Protobuf 3.0.2

easybuild/easyconfigs/t/tabix/tabix-0.2.6-foss-2016a.eb, easybuild/easyconfigs/t/tabix/tabix-0.2.6-goolf-1.4.10.eb, easybuild/easyconfigs/t/tabix/tabix-0.2.6-intel-2014b.eb
not specifying `CC` results in using hardcoded `gcc`, and we shouldn't be overriding `CFLAGS` without taking `$CFLAGS` into account
=> fix buildopts in tabix easyconfigs

easybuild/easyconfigs/h/HPCG/HPCG-2.1-goolf-1.4.10.eb, easybuild/easyconfigs/h/HPCG/HPCG-2.1-ictce-5.5.0.eb
make sure tests for HPCG are still run after changes made to HPCG easyblock in https://github.com/hpcugent/easybuild-easyblocks/pull/993
=> enable running of tests for HPCG

easybuild/easyconfigs/q/Qhull/Qhull-2015.2-foss-2016a.eb
Qhull 2015.2 compiled using the foss 2016a toolchain. The config is based on the intel version.
=> Qhull 2015.2 compiled using the foss 2016a toolchain.

easybuild/easyconfigs/i/i-cisTarget/i-cisTarget-20160602-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/s/STAMP/STAMP-1.2-intel-2016a.eb, easybuild/easyconfigs/s/STAMP/STAMP-1.3-intel-2016a.eb
STAMP *must* be version 1.3 to ensure that a bugfix relevant to i-cisTarget is included, cfr. https://github.com/seqcode/stamp/commit/9cdb2327991d53030bebeab1a42c7bb4ad89bf10
=> correct STAMP dependency in i-cisTarget, must be 1.3

easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-4.9.4.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-5.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-5.4.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-6.1.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-6.2.0.eb
This seems to be a leftover from some debugging, as the non-GCCcore versions already build in parallel.
=> {lang}[GCCcore/*] flex can be built in parallel

easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2016b.eb
This is a weird easyconfig, ignore it please.
It builds worker with system gcc and perl yet depends on the toolchain
as a build dep.
=> {tools}[dummy] worker 1.6.7 with intel/2016b as MPI module

test/easyconfigs/easyconfigs.py
(see also https://github.com/hpcugent/easybuild-framework/pull/1954)
This is required to make the tests pass for easyconfigs that are located in the `0` subdir, e.g. for `3to2` (cfr. #3655).
=> use 'letter_dir_for' function rather than just grabbing 1st letter of software name in easyconfigs tests

easybuild/easyconfigs/f/flex/flex-2.6.0-GCC-4.9.2.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-4.9.4.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-5.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-5.4.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-6.1.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-GCCcore-6.2.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-foss-2015a.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-foss-2016a.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-foss-2016b.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-gimkl-2.11.5.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-intel-2015b.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-intel-2016a.eb, easybuild/easyconfigs/f/flex/flex-2.6.0-intel-2016b.eb, easybuild/easyconfigs/f/flex/flex-2.6.0.eb
As discussed on the mailing list a couple of weeks ago, `Bison` is not really necessary for using `flex` and can thus be specified as a build dependency.  This PR implements this change for flex 2.6.0, and also adds a checksum for the source tarball.  If this change is considered OK, I can prepare corresponding PRs for older versions of flex available in the repo.
**Note:** This change may potentially break packages that only (build-)depend on `flex` rather than depending on both `flex` and `Bison`.  However, how many packages are affected is hard to predict.
edit: ref to thread on ML: https://lists.ugent.be/wws/arc/easybuild/2016-08/msg00017.html
=> {lang}[*] flex: Make Bison a build dependency

easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-iccifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iompi-2016.09-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iomkl/iomkl-2016.09-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iompi/iompi-2016.09-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-iccifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-iccifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-iccifort-2016.3.210-GCC-4.9.3-2.25.eb
Updated versions of iomkl and iompi toolchains to include iccifort 2016.3.210 and GCC 4.9.3 (intended for building apps with CUDA support).
=> Adding new toolchains for iomkl and iompi version 2016.09-GCC-4.9.3-2.25

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-4.0-cleanup.patch
@wpoely86 just to ensure that this patch can be reused with other (non-Intel MPI) toolchains
=> use $CC,$CXX rather than $I_MPI_CC,$I_MPI_CXX in patch for OpenFOAM 4.0

easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.5.1-intel-2016b.eb, easybuild/easyconfigs/p/Pillow/Pillow-3.4.2-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/Pillow/Pillow-3.4.2-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-intel-2016b-Python-3.5.2.eb
fix for scikit-image easyconfigs added in #3720
=> include Pillow as a proper dep for scikit-image rather than as extension, since it has deps itself

easybuild/easyconfigs/c/CUDA/CUDA-8.0.44-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.5-gompic-2016.10.0.eb, easybuild/easyconfigs/g/gcccuda/gcccuda-2016.10.0.eb, easybuild/easyconfigs/g/gompic/gompic-2016.10.0.eb, easybuild/easyconfigs/g/goolfc/goolfc-2016.10.0.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-gcccuda-2016.10.0.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-gcccuda-2016.10.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompic-2016.10.0-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2016.10.0-OpenBLAS-0.2.19-LAPACK-3.6.1.eb
Create a goolfc toolchain using CUDA 8.0.44 and the latest versions of the dependencies.
CUDA 8.0.44
GCC 5.4.0-2.26 (Cuda still doesn't support any newer GCC compiler)
FFTW 3.3.5
OpenBLAS 0.2.19/Lapack 3.6.1
OpenMPI 2.0.1
Scalapack 2.0.2
=> Create a goolfc toolchain using CUDA 8.0.44

easybuild/easyconfigs/i/InterProScan/InterProScan-5.21-60.0-intel-2015b.eb
latest InterProScan. Including required fix for centos6 systems
=> {bio} [intel-2015b] InterProScan-5.21-60.0 . Includes fix for centos6

easybuild/easyconfigs/s/SPAdes/SPAdes-3.9.0-foss-2016a.eb
Based on the existing version for foss 2016b, created using --try-toolchain. Since everyone can install them like that and the only difference now is 2016b->2016a, should I even create PRs for such easyconfigs?
=> SPAdes 3.9.0 with foss 2016a

easybuild/easyconfigs/f/flex/flex-2.5.39-CrayGNU-2015.06.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-CrayGNU-2015.11.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.2.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.2.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2014b.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2015.05.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2015a.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2015b.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2016a.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-gimkl-2.11.5.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-ictce-7.1.2.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2014b.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2015a.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2015b.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2016a.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-para-2014.12.eb, easybuild/easyconfigs/f/flex/flex-2.5.39.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-foss-2015.05.eb
Consistently use `pic=True` toolchain option and `M4` as a dependency in flex 2.5.39 easyconfigs.  Also add a checksum for the tarball.
**Note 1**: The 2.5.39 tarball built for me on a machine w/o `Bison` being available, thus it was not added as a build dependency (cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/3656).
**Note 2**: Running `eb -D flex-2.5.39-GNU-4.9.3-2.25.eb` for me results in `ERROR: Maximum loop cnt 10000 reached, so quitting`.  So something seems to be fishy in this configuration...
=> {lang}[*] flex 2.5.39: Consistency changes

easybuild/easyconfigs/g/GCC/GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/g/GCC/GCC-5.1.0.eb, easybuild/easyconfigs/g/GCC/GCC-5.2.0.eb, easybuild/easyconfigs/g/GCC/GCC-5.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-4.9.2.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-4.9.3.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-4.9.4.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-5.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.1.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.2.0.eb
Building in parallel works fine for recent versions of GCC, there should be no reason to limit it.
=> remove maxparallel in GCCcore and GCC 5.x easyconfigs

easybuild/easyconfigs/g/GCC/GCC-4.9.0-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.3.eb
Building in parallel works fine for recent versions of GCC, there should be no reason to limit it.
=> remove maxparallel in GCC 4.9.x easyconfigs

easybuild/easyconfigs/g/GCC/GCC-4.8.1-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.1.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.3-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.3.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.4-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.4-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.4.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.5.eb
Building in parallel works fine for recent versions of GCC, there should be no reason to limit it.
=> remove maxparallel in GCC 4.8.x easyconfigs

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-gompi-2016.07-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompi-2016.09-LAPACK-3.6.1.eb
The OpenBLAS Makefile only handles large.tgz and timing.tgz and ignores
lapack-x.y.z.tgz. We need to manually unpack the lapack-x.y.z specified
in the easyconfig.
Doing it this way makes it possible to add patches on top of the
unpacked lapack version, which is neccesary to deal with various
compiler problems.
This solves easyconfig issue #1050.
=> Make OpenBLAS use the LAPACK version specified in the easyconfig.

easybuild/easyconfigs/g/GROMACS/GROMACS-2016-foss-2016b-hybrid.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2016-foss-2016b-mt.eb
Boost is only a build dep of Gromacs.
Gromacs now contains tinyxml and thus do not depend on libxml2 any
longer.
=> Add easyconfigs for GROMACS 2016.

easybuild/easyconfigs/h/HPL/HPL-2.2-iomkl-2016.09-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iompi-2016.09-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iomkl/iomkl-2016.09-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iompi/iompi-2016.09-GCC-5.4.0-2.26.eb
These files are based upon the {iomkl,iompi,imkl}-2016.09-GCC-4.9.3-2.25.eb files.
GCC compiler updated to GCC-5.4.0-2.26 because we already have this from the foss2016b toolchain.
OpenMPI 1.10.3 is used because we also have this in the foss2016b toolchain.
The iomkl toolchain MUST be built in a certain order:
1. The OpenMPI requires the Intel compilers.
2. The iompi requires the correct OpenMPI.
3. The iomkl requires imkl.
Commands used and tested:
eb icc-2016.3.210-GCC-5.4.0-2.26.eb iccifort-2016.3.210-GCC-5.4.0-2.26.eb ifort-2016.3.210-GCC-5.4.0-2.26.eb -r
eb OpenMPI-1.10.3-Slurm-iccifort-2016.3.210-GCC-5.4.0-2.26.eb -r	# For Slurm support
eb iompi-2016.09-GCC-5.4.0-2.26.eb imkl-11.3.3.210-iompi-2016.09-GCC-5.4.0-2.26.eb -r
eb iomkl-2016.09-GCC-5.4.0-2.26.eb -r
When the modules are …
=> iomkl toolchain with GCC-5.4.0-2.26 and OpenMPI 1.10.3

easybuild/easyconfigs/i/ifort/ifort-2016.0.109-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.0.109.eb, easybuild/easyconfigs/i/ifort/ifort-2016.1.150-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.2.181-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.2.181-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.0.098-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort_2016_no_mpi_mic_dependency.patch, easybuild/easyconfigs/i/ifort/ifort_2017_no_mpi_mic_dependency.patch
This dependency causes Intel mpirun/mpiexec to be added to $PATH
when the ifort module is loaded, which is not always desirable,
for instance when OpenMPI is already loaded.
Fixes hpcugent/easybuild-easyblocks#1032.
=> Eliminate dependency on mpi-mic-rt in ifort.

easybuild/easyconfigs/i/ifort/ifort-2016.0.109-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.0.109.eb, easybuild/easyconfigs/i/ifort/ifort-2016.1.150-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.2.181-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.2.181-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.0.098-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.1.132-GCC-5.4.0-2.26.eb
Some of the ifort .eb files had gotten an incorrect description,
claiming to be C/C++ instead of Fortran.
=> Fix incorrect descriptions for ifort.

easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-foss-2015b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-goolf-1.4.10.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-ictce-5.3.0.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-ictce-5.5.0.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-intel-2015a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-intel-2015b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.28-GCC-4.8.2.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.28-GCC-4.9.2.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.28-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.28-ictce-5.5.0.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.28-intel-2015a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29-foss-2016a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29-gimkl-2.11.5.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29-intel-2015a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29-intel-2015b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29-intel-2016a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-GCCcore-4.9.3.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-foss-2016a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-foss-2016b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-intel-2016a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-intel-2016b.eb
Apparently this got moved (the old URL auto-directs to the new).
=> fix source_urls in pkg-config easyconfigs

easybuild/easyconfigs/c/CMake/CMake-3.6.2-GCCcore-5.4.0.eb, easybuild/easyconfigs/c/CMake/CMake-3.7.1-GCCcore-5.4.0.eb, easybuild/easyconfigs/c/CMake/CMake-3.7.1-GCCcore-6.2.0.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-5.4.0.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.2.0.eb
CMake in the GCCcore will support all foss, intel and pomkl toolchains
using that GCCcore.
PR contains matching ncurses.
=> Fileset for recent CMake versions in GCCcore compilers

easybuild/easyconfigs/n/numpy/numpy-1.9.2-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/s/scipy/scipy-0.16.0-intel-2016b-Python-2.7.12.eb
https://github.com/hpcugent/easybuild-easyblocks/pull/1067 revealed that the shadowing of the `numpy`/`scipy` in the parent Python installation didn't actually work yet...
follow-up for #3905
=> install numpy/scipy as .egg to ensure shadowing of numpy/scipy in parent Python installation

easybuild/easyconfigs/m/Mono/Mono-4.6.2.7-intel-2016b.eb, easybuild/easyconfigs/m/Mono/Mono-4.6.2.7.eb
- Added Mono 4.6.2.7 with both dummy and intel-2016b toolchains
- No longer using mono.py easyblock, only ConfigureMake instead
=> {lang}[dummy,intel/2016b] Mono 4.6.2.7 (REVIEW)

easybuild/easyconfigs/h/h5py/h5py-2.6.0-foss-2016b-Python-3.5.2-HDF5-1.10.0-patch1.eb, easybuild/easyconfigs/h/h5py/h5py-2.6.0-foss-2016b-Python-3.5.2-HDF5-1.8.18.eb, easybuild/easyconfigs/h/h5py/h5py-2.6.0-intel-2016b-Python-2.7.12-HDF5-1.10.0-patch1.eb, easybuild/easyconfigs/h/h5py/h5py-2.6.0-intel-2016b-Python-2.7.12-HDF5-1.8.18.eb, easybuild/easyconfigs/h/h5py/h5py-2.6.0-intel-2016b-Python-3.5.2-HDF5-1.10.0-patch1.eb, easybuild/easyconfigs/h/h5py/h5py-2.6.0-intel-2016b-Python-3.5.2-HDF5-1.8.18.eb, easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016b-Python-3.5.2.eb
This is a follow up on the earlier PR #3900 the provides the latest HDF5 versions
1.8.18 and 1.10.0-patch1.  This new PR contains python bindings for Python
3.5 in foss 2016b and Python 2.7 & 3.5 in Intel 2016b
=> h5py for Python 3.5 in foss 2016b and h5py for intel 2016b

easybuild/easyconfigs/l/libharu/libharu-2.3.0-foss-2016a.eb
Based on the easyconfig for 2.2.0, but with two additional changes (besides the version and toolchain):
- removed patches, these things have already been patched in 2.3.0.
- changed category from bio to lib: since this is a library for generating pdfs, it seemed more appropriate to me
=> libharu 2.3.0 with foss2016a

easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-foss-2016a-Mesa-11.2.1.eb, easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-foss-2016a.eb, easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-intel-2016a-Mesa-11.2.1.eb, easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-intel-2016a.eb, easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-intel-2016b.eb
Mesa has stopped including glu.h in its newer versions (as stated in their easyconfigs), this causes freeglut to complain when it is not present. Including the libGLU dependency fixed this problem in my case.
=> libGLU dep for freeglut

easybuild/easyconfigs/m/Mono/Mono-4.6.2.7-intel-2016b.eb, easybuild/easyconfigs/m/Mono/Mono-4.6.2.7.eb
This is required for memory-intensive Mono applications, see also http://stackoverflow.com/questions/7248980/mono-too-many-heap-sections-increase-maxhincr-or-max-heap-sects-when-app-takes
cc @backelj
=> build Mono with --with-large-heap=yes

easybuild/easyconfigs/r/RASPA2/RASPA2-2.0.3-intel-2016b-Python-2.7.12.eb
libraspa2 stub loader confuses the direct command `simulate`, therefore it is deleted after installation.
=> RASPA2 direct running problem solution

easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-foss-2015b.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-intel-2015b.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-intel-2016a.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-intel-2016b.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.8-goolf-1.4.10.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.8-ictce-5.3.0.eb
The `bison` and `byacc` dependencies cover the same ground, only one is necessary.
=> Remove unnecessary dependency in libmatheval

easybuild/easyconfigs/p/PEAR/PEAR-0.9.8-foss-2016b.eb
Starting from version 0.9.8 there is no `-src` suffix for the source files.
Tested also with `--try-software-version=0.9.10` which is the latest version.
Should I add checksums?
=> added easyconfig for PEAR 0.9.8

easybuild/easyconfigs/c/CD-HIT/CD-HIT-4.6.6-foss-2016b.eb
Changed `source_url` to archive subdirectory. Files there have no `versionsuffix` which prevents the use of
`--try-software-version`.
=> added CD-HIT 4.6.6

easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.0c-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCC-5.4.0-2.26.eb
Added OpenSSL 1.1.0c easyconfig file for GCC 5.4.0-2.26.
Since a recent version of Perl may be necessary for the correct execution of OpenSSL tests, I also added  the missing easyconfig file at the GCC 5.4.0-2.26 toolchain level.
=> Add OpenSSL 1.1.0c and Perl 5.24.0 for GCC 5.4.0-2.26

easybuild/easyconfigs/r/Rosetta/Rosetta-2015.31.58019-intel-2015a.eb, easybuild/easyconfigs/r/Rosetta/Rosetta-2016.13.58602-foss-2016a.eb, easybuild/easyconfigs/r/Rosetta/Rosetta-3.7-foss-2016b.eb
requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1092~~
=> remove incorrect definition for $ROSETTA3_DB, now (correctly) defined via Rosetta easyblock

easybuild/easyconfigs/b/Bazel/Bazel-0.4.4.eb, easybuild/easyconfigs/j/Java/Java-1.8.0_121.eb
=> {devel}[Java] Bazel 0.4.4

easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-foss-2017a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-intel-2017a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1_gcc-6.patch
While this isn't needed by anything yet, I'm sure people will run into this rather sooner than later...
=> {devel}[foss-/intel-2017a,GCCcore-6.3.0] pkg-config: Work around build failure with GCC 6

easybuild/easyconfigs/r/RNAz/RNAz-2.1-foss-2016b.eb
[GCC changed the default C standard from gnu89 to gnu11](https://gcc.gnu.org/gcc-5/changes.html), RNAz needs gnu89, otherwise it fails during the build, see also https://github.com/wash/rnaz/issues/8.
I added the C standard like that: `buildopts = 'CFLAGS="-std=gnu89 $CFLAGS"'`.
@wookietreiber: you mentioned in the issue on RNAz that `-g -O2` should also be added? Compilation now looks like this: `gcc -DHAVE_CONFIG_H -I. -I..   -I/beegfs/easybuild/16.04/software/OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1/include -I/beegfs/easybuild/16.04/software/ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1/include -I/beegfs/easybuild/16.04/software/FFTW/3.3.4-gompi-2016b/include  -std=gnu89 -O2 -march=corei7 -fPIC -MT fold_vars.o -MD -MP -MF .deps/fold_vars.Tpo -c -o fold_vars.o …
=> {bio}[foss/2016b] RNAz v2.1

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-6.3.0.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-GCCcore-6.3.0.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-GCCcore-6.3.0.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-6.3.0.eb, easybuild/easyconfigs/e/expat/expat-2.2.0-GCCcore-6.3.0.eb, easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/f/freetype/freetype-2.7.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.28-GCCcore-6.3.0.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-GCCcore-6.3.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.4-GCCcore-6.3.0.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.3.0.eb, easybuild/easyconfigs/x/X11/X11-20170129-GCCcore-6.3.0.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.3-GCCcore-6.3.0.eb
- Bumped components and dependencies to the latest available versions (fixes a number of CVEs, see https://lists.x.org/archives/xorg-announce/2016-October/002720.html)
- Added libXfont2
=> {vis}[GCCcore/6.3.0] Updated X11 bundle and dependencies for GCCcore-6.3.0

easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-foss-2016b.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-intel-2016b.eb
Both `libpthread-stubs` and `libpciaccess` are included as components in `X11`, so we can safely remove them here.
=> libdrm: clean up dependencies

easybuild/easyconfigs/x/X11/X11-20160819-foss-2015a.eb, easybuild/easyconfigs/x/X11/X11-20160819-foss-2016b.eb, easybuild/easyconfigs/x/X11/X11-20160819-intel-2016b.eb
On a fairly minimal system, X11 failed to build due to missing build dependencies:
- libxkbcommon failed due to missing yacc/Bison
- libXpm failed due to missing `xgettext` (provided by gettext)
Both `foss` versions have been tested and suffer from the same issue (and the fix has been confirmed to work); the `intel` version has been extrapolated.
=> X11: Add Bison and gettext as build deps

easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.20-intel-2016b.eb
In the `configure`  file the search order is local, system, so bundled linraryes are renamed.
=> {vis}[intel/2016b] Ghostscript 9.20 use external freetype, libpng, jpeg, and zlib (REVIEW)

easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb
Probably a leftover from some experimentation?
=> {mpi}[GCC/6.3.0-2.27] OpenMPI: Remove duplicate sources specification

easybuild/easyconfigs/c/Cantera/Cantera-2.2.1-intel-2016b-Python-2.7.12.eb
`buildopts` was redefined twice, second time with `scons install`, so that should have been `installopts` being defined
this was mostly harmless for Cantera 2.2.1, but proved not to work with Cantera 2.3.0 (see #4133 & https://github.com/Cantera/cantera/issues/432)
=> fix definition of buildopts/installopts in Cantera easyconfig

easybuild/easyconfigs/x/XZ/XZ-5.2.2-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-GCCcore-4.9.3.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2015a.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2016.04.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2016a-gettext-0.19.7.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2016a.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-foss-2016b.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-goolf-1.4.10.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-ictce-5.3.0.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-intel-2016a-gettext-0.19.7.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-intel-2016a.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-intel-2016b.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2_compat-libs.patch
fix for #4036
cc @verdurin, @hajgato: please test whether this also fixes the problem for you?
=> add patch for XZ 5.2.2 to include 5.1.2alpha symbols required by 'rpm' command on CentOS 7.x

easybuild/easyconfigs/m/meshio/meshio-1.7.1-intel-2016b-Python-2.7.12.eb
follow-up for #4178, cfr. #4187 
depends on #4186
=> bump VTK to 7.1.0 in meshio easyconfig for compatibility with Yade 2017.01a

easybuild/easyconfigs/b/Boost/Boost-1.61.0-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/b/Boost/Boost-1.61.0-intel-2016a.eb, easybuild/easyconfigs/b/Boost/Boost-1.61.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/b/Boost/Boost-1.61.0-intel-2016b.eb, easybuild/easyconfigs/b/Boost/Boost-1.61_fix-make_array-icpc.patch, easybuild/easyconfigs/b/Boost/Boost-1.62.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/b/Boost/Boost-1.63.0-intel-2016b-Python-2.7.12.eb
This fixes a problem that manifests itself with Yade, as follows:
```
$ ml Yade/2016.06a-intel-2016b-Python-2.7.12 
$ python -c "import yade"
File "<string>", line 1, in <module>
File "/prefix/software/Yade/2016.06a-intel-2016b-Python-2.7.12/lib64/yade-2016.06a/py/yade/__init__.py", line 65, in <module>
import boot
ImportError: /prefix/software/Yade/2016.06a-intel-2016b-Python-2.7.12/lib64/yade-2016.06a/libyade.so: undefined symbol: _ZN5boost13serialization10make_arrayImEEKNS0_13array_wrapperIN5Eigen6MatrixIdLi2ELi1ELi0ELi2ELi1EEEEEPS5_T_
```
The problem does not occur if Boost & Yade were built with GCC rather than Intel compilers.
=> add patch for Boost v1.61-1.63 to fix problem with make_array/array_wrapper in boost serialization library

easybuild/easyconfigs/l/libxc/libxc-2.0.1-goolf-1.4.10.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.1-ictce-5.3.0.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.1-ictce-5.5.0.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.1-intel-2014b.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.3-goolf-1.4.10.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.0-intel-2014b.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-CrayGNU-2015.06.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-CrayGNU-2015.11.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-intel-2015a.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.2-CrayGNU-2015.11.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.2-foss-2015b.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.2-intel-2015a.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.2-intel-2015b.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.3-foss-2016b.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2016a.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2016b.eb, easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2016a.eb, easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2016b.eb
I've noticed that some functionals in LibXC give significantly different results with too much compiler optimization. For example, the energy of a water molecule computed with the TPSS functional changes by 6.5 kJ/mol with lowopt=False. (The problem is in the TPSS correlation functional, somewhere in mgga_c_pkzb.c. I've ruled out numerical integration issues. Similar relative errors appear on every grid point of the tpss_c energy density.)
I can only test with libx-2.2.* and intel compilers at the moment. I'll make similar changes for other versions and compilers when the opportunity arises.
Can someone check if the combination `{'opt': False, 'lowopt': True}` is meaningful for `toolchainopts`? It seems to work for me.
=> Switch to lowopt=True for libxc v2.2.* and v3.*

easybuild/easyconfigs/e/ea-utils/ea-utils-1.04.807-foss-2016a.eb, easybuild/easyconfigs/e/ea-utils/ea-utils-1.04.807-foss-2016b.eb
when looking into #4204, I noticed that `ea-utils` now available with a proper version on GitHub, so we don't need to use the commit as a version anymore...
Originally contributed by @RvDijk (#3634), and updatd by @verdurin (#3834), so feedback from the both of you would be great since this is a 'breaking' change.
As far as I can tell `ea-utils` is not used as a dependency somewhere else, so changing the version like we do here is acceptable imho (since it won't break other easyconfigs).
=> fix version (& homepage) in ea-utils easyconfigs

easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-goolf-1.4.10.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-ictce-5.3.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.1.3_fix-Szip-link-check.patch
I have a use case for an old netCDF version, so I figured out why it didn't build anymore.
Not sure how this ever worked without the patch, maybe because an old Szip library that provides `-lszip` was installed system-wide?
=> fix check for Szip library in configure script for netCDF 4.1.3

easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb
OpenMPI builds now warn they don't know --with-threads.
See OpenMPI commit at
https://github.com/open-mpi/ompi/commit/7a55d49ca78bcc157749c04027515f12b026ec33
sed -i 's/--with-threads=posix //' OpenMPI-2*.eb
=> OpenMPI-2.*: remove --with-threads configure option.

easybuild/easyconfigs/p/PBSuite/PBSuite-15.8.24-intel-2016b-Python-2.7.12.eb
I managed to screw up the sources spec in #4224 by manually downloading the tarball and my browser automagically renaming the `.tgz` to `.tar.gz`... >_<
=> fix source spec in PBSuite easyconfig

easybuild/easyconfigs/o/OrthoMCL/OrthoMCL-1.4-intel-2016b-Perl-5.24.0.eb
follow-up for #4134 and #4182
This is getting a bit messy, but since this is an old unsupported version of OrthoMCL, I won't spend much more time on this...
This version works, with the following workflow:
```
$ eb OrthoMCL-1.4-intel-2016b-Perl-5.24.0.eb -dfr --read-only-installdir
$ module load OrthoMCL/1.4-intel-2016b-Perl-5.24.0
$ cp -a $EBROOTORTHOMCL/sample_data .
$ orthomcl.pl --mode 1 --fa_files Ath.fa,Sce.fa
```
=> fix hardcoded paths in OrthoMCL 1.4 installation

easybuild/easyconfigs/m/miRDeep2/miRDeep2-2.0.0.8-intel-2016b.eb
follow-up for #4229, two scripts are missing execution rights by default:
```
$ ls -l $EASYBUILD_PREFIX/software/miRDeep2/2.0.0.8-intel-2016b/bin | grep -v 'r-x'
total 1472
-rwxr--r-- 1 vsc40023 vsc40023   5950 Apr 20  2016 get_mirdeep2_precursors.pl
-rwxr--r-- 1 vsc40023 vsc40023    686 Apr 20  2016 mirdeep2bed.pl
```
=> enable execution permissions on all Perl scripts in /bin for miRDeep2

easybuild/easyconfigs/g/GDAL/GDAL-1.10.1-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/g/GDAL/GDAL-2.1.1-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/g/GDAL/GDAL-2.1.2-intel-2016b-Python-2.7.12.eb
Replaced $EBROOTLIBJPEGTURBO by $EBROOTLIBJPEGMINTURBO in 3 .eb-files for GDAL, cfr issue #4264.
=> Correct libjpeg turbo references

easybuild/easyconfigs/r/ROOT/ROOT-v6.08.02-foss-2016a-Python-2.7.11.eb
as ROOT compiles a ROOT.py module as well and put it in the lib folder, we need to set the PYTHONPATH as well.
=> fix missing PYTHONPATH in ROOT v6.08.02 easyconfig

easybuild/easyconfigs/q/QGIS/QGIS-2.14.12-intel-2016b-Python-2.7.12.eb
these were missing in #4307, 
depends on ~~#4317~~, ~~#4319~~
=> add requests and psycopg2 as dependencies for QGIS

easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.0.7-goolf-1.4.10.eb, easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.0.7-ictce-5.3.0.eb, easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.1.6-ictce-5.5.0.eb, easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.2.3-intel-2016b.eb, easybuild/easyconfigs/v/ViennaRNA/ViennaRNA-2.3.4-foss-2016b.eb
The homepage of ViennaRNA has changed and the old link has no redirection. Also the source_urls have changed. They now use a different directory for each minor version.
=> {bio}[foss/2016b] ViennaRNA 2.3.4 + fixed homepage and source_urls

easybuild/easyconfigs/h/HDF5/HDF5-1.10.0-patch1-goolfc-2016.10.eb, easybuild/easyconfigs/s/Szip/Szip-2.1-goolfc-2016.10.eb
HDF5 1.10.0 patch 1 for goolfc 2016.10.  No GPU magic here, just a copy over from foss/2016b.  Includes the Szip dependency.
=> {data][goolfc/2016.10] HDF5 1.10.0-patch1

easybuild/easyconfigs/f/FFTW/FFTW-3.3.5-intel-2016b.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.6-intel-2017a.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/1142
=> use 'use_fma4' rather than deprecated 'use_fma' easyconfig parameter in FFTW easyconfigs using intel toolchain

easybuild/easyconfigs/n/ncurses/ncurses-6.0-goolf-1.4.10.eb, easybuild/easyconfigs/s/SAMtools/SAMtools-1.4-goolf-1.4.10.eb
Added SAMtools-1.4-goolf-1.4.10.eb and ncurses-6.0-goolf-1.4.10.eb, the second one is a dependece of the first. By Daniel Navarro-Gomez, MEEI Bioinformatics Center
new file:   easyconfigs/n/ncurses/ncurses-6.0-goolf-1.4.10.eb
new file:   easyconfigs/s/SAMtools/SAMtools-1.4-goolf-1.4.10.eb
=> SAMtools-1.4-goolf-1.4.10.eb and ncurses-6.0-goolf-1.4.10.eb

easybuild/easyconfigs/g/GMP/GMP-6.1.2-GCCcore-6.3.0.eb, easybuild/easyconfigs/l/libreadline/libreadline-7.0-GCCcore-6.3.0.eb, easybuild/easyconfigs/p/Python/Python-2.7.13-intel-2017a.eb, easybuild/easyconfigs/p/Python/numpy-1.12.0-mkl.patch, easybuild/easyconfigs/s/SQLite/SQLite-3.17.0-GCCcore-6.3.0.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.6-GCCcore-6.3.0.eb
This Python easyconfig deliberately does not include `Tk` as a dependency (and hence doesn't support 'import Tkinter'), following the example in #4225 by @verdurin, to avoid requiring `X11` as an indirect dependency for `Python`.
I intend to also open a separate PR for a cleaned up version of the `Tkinter` easyconfig in #4225.
TODO:
* ~~[ ] strip out `Tkinter.py` to make it crystal clear that this Python installation doesn't provide it?~~
* ~~[ ] include a sanity check command to ensure that `Tkinter` support isn't added accidentally, e.g. by picking up `Tk` from the OS?~~
In any case, `_tkinter.so` is not a part of the Python installation I obtained using these easyconfigs.
edit: update on TODO: enhanced `Python` easyblock that makes sure that `Tkinter` is there when `Tk` is included as …
=> {lang}[intel/2017a] Python v2.7.13 (REVIEW)

easybuild/easyconfigs/l/libdrm/libdrm-2.4.76-intel-2017a.eb, easybuild/easyconfigs/m/Mesa/Mesa-17.0.2-intel-2017a.eb
follow-up for ~~#4416~~, requires ~~#4428~~
triggered by `libpng` version conflict in #4425
=> bump X11 to version 20170314 in Mesa 17.0.2 easyconfig

easybuild/easyconfigs/r/R/R-3.3.3-foss-2016b-X11-20160819.eb
to sync it up with #4427, cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/4427#pullrequestreview-30860122
=> bump imager extension to 0.40.1 in R 3.3.3 easyconfig

easybuild/easyconfigs/q/Qhull/Qhull_pkgconfig.patch
see https://cmake.org/cmake/help/latest/command/configure_file.html
otherwise it replaces ${...} by empty strings which is not what we want and broke our Octave compilation.
=> Fix pkgconfig patch for Qhull to only let CMake substitute @

easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2017a.eb, easybuild/easyconfigs/r/R/R-3.3.3-intel-2017a-X11-20170314.eb
It needs the NLopt library. It worked until now because it downloads and builds the lib silently. It failed for me with a corrupt download.
=> Fix for R extension nloptr

easybuild/easyconfigs/c/configparser/configparser-3.5.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/c/configparser/configparser-3.5.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/c/configparser/configparser-3.5.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/c/configparser/configparser-3.5.0-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/c/configparser/configparser-3.5.0_no-backports-namespace.patch, easybuild/easyconfigs/e/entrypoints/entrypoints-0.2.2-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/i/IPython/IPython-5.1.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/i/IPython/IPython-5.1.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/i/IPython/IPython-5.2.2-intel-2016b-Python-2.7.12.eb
fix for #3825
requires ~~https://github.com/hpcugent/easybuild-framework/pull/2194~~, since `nbconvert` 5.1.1 requires that `use_pip` is enabled
=> fix issue with configparser and backports namespace blocking inclusion of nbconvert with IPython

easybuild/easyconfigs/g/Go/Go-1.8.1.eb
Used the binary distribution, since building from source requires you to already have an older Go compiler.
=> Go 1.8.1 binary release

easybuild/easyconfigs/m/METIS/METIS-5.1.0-foss-2016b.eb
Needed for OpenFOAM
patches = ['METIS-5.1.0-use-doubles.patch']
=> also use patch for METIS 5.1.0 to enable use of doubles in easyconfig for foss/2016b

easybuild/easyconfigs/m/METIS/METIS-5.1.0-foss-2016a.eb
Needed for https://github.com/hpcugent/easybuild-easyconfigs/pull/3131
=> use patch to enable use of double precision floating point in METIS 5.1.0 foss/2016a easyconfig

.travis.yml
For now, this will just print a list of changed files to the Travis log.
The idea is to see if we can use this to get a list of changes files for a PR, so we can do a partial style check, or check whether `SHA256` checksums are available for only the files touched by a PR rather than everything at once...
The `sed` is required because of https://github.com/travis-ci/travis-ci/issues/4596.
=> use 'git diff --name-only' and $TRAVIS_COMMIT_RANGE in Travis config to get list of changed files

easybuild/easyconfigs/s/Singularity/Singularity-2.2.1-GCC-6.3.0-2.27.eb
next steps after instalations
```console
```
=> {tools}Singularity-2.2.1-GCC-6.3.0 added

.travis.yml
We should be comparing with `HEAD` to include the merge commit that Travis creates when testing PRs, otherwise the list of changes files is not what we expect to be if the branch used for the PR is not in sync with `develop`.
follow-up for #4606
=> run 'git diff --name-only' from target branch to current HEAD in Travis config to get relevant list of changed files

easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.26.eb
Adds an EasyConfig for BEDOPS 2.4.26. The existing one for 2.4.20 fails with `--try-software-version=2.4.26` because the old easyconfig has `.v2` in the `source_urls`.
=> {bio}[dummy] BEDOPS 2.4.26

easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.1-GCC-4.7.2.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.1-goolf-1.4.10.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.1-ictce-5.3.0.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.1-ictce-5.5.0.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.1-intel-2015a.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.3-intel-2015a.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-foss-2016a.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-foss-2016b.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-gimkl-2.11.5.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-intel-2015b.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-intel-2016a.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-intel-2016b.eb
source URLS for `libpciaccess` were fixed in #3960, but new downloaded source tarballs are not identical as the old downloads which required to run `autogen.sh` (which  is now no longer included)
Added checksums allow to recognise that the source tarballs needs to be redownloaded.
=> add SHA256 checksums for libpciaccess

easybuild/easyconfigs/n/nettle/nettle-2.6-goolf-1.4.10.eb, easybuild/easyconfigs/n/nettle/nettle-3.1.1-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/nettle/nettle-3.1.1-foss-2016a.eb, easybuild/easyconfigs/n/nettle/nettle-3.1.1-intel-2016a.eb, easybuild/easyconfigs/n/nettle/nettle-3.2-foss-2016b.eb, easybuild/easyconfigs/n/nettle/nettle-3.2-intel-2016b.eb, easybuild/easyconfigs/n/nettle/nettle-3.3-intel-2017a.eb
Fixed `nettle` easyconfig files. Sanity check library paths must include `lib/*` in order to pass on Debian and Ubuntu systems. See #4696
=> Added lib sanity check paths for debian compatibility

easybuild/easyconfigs/a/ANSYS/ANSYS-15.0.eb, easybuild/easyconfigs/m/MATLAB/MATLAB-2012b.eb, easybuild/easyconfigs/m/MATLAB/MATLAB-2015a.eb, easybuild/easyconfigs/m/MATLAB/MATLAB-2016a.eb, easybuild/easyconfigs/m/MATLAB/MATLAB-2017a.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/1195 to retain backward compatibility
(required to make #2506 eligible for merging)
=> avoid use of import in ANSYS & MATLAB easyconfigs

easybuild/easyconfigs/c/CP2K/CP2K-20111205-goolf-1.4.10-psmp.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/1196
(required to make #2506 eligible for merging)
=> set $OMP_NUM_THREADS during CP2K test step via dedicated easyconfig parameter

easybuild/easyconfigs/a/ABINIT/ABINIT-7.0.3-x86_64_linux_gnu4.5.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-7.0.5-x86_64_linux_gnu4.5.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-7.2.1-x86_64_linux_gnu4.5.eb, easybuild/easyconfigs/a/Aspera-CLI/Aspera-CLI-3.7.2.354.010c3b8.eb, easybuild/easyconfigs/a/ack/ack-2.14.eb, easybuild/easyconfigs/g/GATE/GATE-6.2-goolf-1.4.10.eb, easybuild/easyconfigs/g/GATE/GATE-6.2-intel-2015a.eb, easybuild/easyconfigs/g/GATE/GATE-6.2-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/g/GATE/GATE-7.0-intel-2015a.eb, easybuild/easyconfigs/g/GATE/GATE-7.1-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/g/GATE/GATE-7.2-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/g/GIMPS/GIMPS-p95v279-GCC-4.8.2.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-4.9.4-2.25-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.3.0-2.26-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-gompi-2016.07-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-GCC-5.4.0-2.26-LAPACK-3.7.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-GCC-6.3.0-2.27-LAPACK-3.7.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompi-2016.09-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompic-2016.10-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016a.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016b.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016a.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016b.eb, easybuild/easyconfigs/p/pbbam/pbbam-20170508-intel-2017a.eb, easybuild/easyconfigs/s/SURF/SURF-1.0-goolf-1.4.10-LINUXAMD64.eb, easybuild/easyconfigs/s/SURF/SURF-1.0-ictce-5.3.0-LINUXAMD64.eb, easybuild/easyconfigs/v/VarScan/VarScan-2.3.6-Java-1.7.0_80.eb
cfr. http://easybuild.readthedocs.io/en/develop/Deprecated-functionality.html#depr-sources-2-element-tuple
requires ~~https://github.com/hpcugent/easybuild-framework/pull/2223~~
=> stop using deprecated 2-element tuple format in sources, use equivalent dict format instead

easybuild/easyconfigs/c/Circos/Circos-0.69-5-foss-2016b-Perl-5.24.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-foss-2016b.eb
Follow up for #4357. This adds Circos with toolchain `foss-2016b`. Also adds two new modules to the existing Perl EasyConfig. The `SVG` module only depends on core modules (http://deps.cpantesters.org/?module=SVG;perl=latest) and `Statistics::Basic` depends on core modules and `Number::Format` which is already included (http://deps.cpantesters.org/?module=Statistics%3A%3ABasic;perl=latest). Should the new Perl modules also be added to other Perl EasyConfigs for consistency?
=> {bio}[foss/2016b] Circos 0.69-5

easybuild/easyconfigs/b/Boost/Boost-1.54.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/b/Boost/Boost-1.54.0_fix-allocator.patch, easybuild/easyconfigs/b/Boost/Boost-1.54.0_fix-int64_t-support.patch, easybuild/easyconfigs/b/Boost/Boost-1.54.0_fix-make_tuple-namespace.patch
This adds `boost` in the ancient version `1.54.0` for the `foss-2016b` toolchain. This version is needed by [bcl2fastq](https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html) which I will add later in another pull request.
=> {devel}[foss-2016b] Boost 1.54.0

easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-goolfc-2017.01.eb
Tests were broken in `develop` after #4585 was merged (cc @verdurin).
@easybuilders/easybuild-easyconfigs-maintainers The tests have been made stricter recently (e.g. style tests), so it's important to re-trigger tests for PRs that were tested a while ago (by closing/opening the PR, Travis supports no other way of re-triggering tests without adding an extra commit...).
I'll look into better Travis notifications, since I wasn't notified of the breakage either; were you @verdurin?
=> fix reference to github.com/hpcugent in GROMACS easyconfig

easybuild/easyconfigs/b/BLAST+/BLAST+-2.6.0-foss-2016b-Python-2.7.12.eb
This adds the current `BLAST+` for the `foss-2016b` toolchain.
=> {bio}[foss/2016b] BLAST+ 2.6.0

setup.py
Recent versions of setuptools require the `description` field to be a single line, or else:
```
Upload failed (400): summary: Multiple lines are not allowed.
error: Upload failed (400): summary: Multiple lines are not allowed.
```
=> use single-line description in setup.py

easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-foss-2016b-GPU-enabled-build.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-foss-2016b-GPU-enabled.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3_amend_search_for_nvml_lib.patch
I selected toolchain foss2016 and not foss2017 because CUDA doesn't support GCC 6.3 at its latest version.
The NVML library location depends on driver version. On my system the NVML library is located in /usr/lib64/nvidia. Therefore, I include it in patch file that modifies FindNVML.cmake.
=> {bio}[foss/2016b] GROMACS v2016.3 (REVIEW)

easybuild/easyconfigs/b/Bowtie/Bowtie-1.1.2-GCCcore-6.3.0.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.2-foss-2017a.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-foss-2017a.eb, easybuild/easyconfigs/t/Trinity/Trinity-2.4.0-foss-2017a.eb, easybuild/easyconfigs/t/tbb/tbb-2017_U6-GCCcore-6.3.0.eb
intel/2017a fails with inchworm
similar errors like:
```
GCCcore/6.3.0/bin/../include/c++/6.3.0/bits/stl_multimap.h(972): note: this candidate was rejected because at least one template argument could not be deduced
operator==(const multimap<_Key, _Tp, _Compare, _Alloc>& __x,
^
```
I did not have time to look into more details into the problem, bit it might be intel 17.0 compiler problem/C++ incompatibility
See https://software.intel.com/en-us/forums/intel-c-compiler/topic/703133
=> {bio}[foss/2017a] Trinity 2.4.0 (REVIEW)

easybuild/easyconfigs/p/Perl/Perl-5.24.1-intel-2017a.eb
An easyconfig file for Perl 5.24.1 with `foss/2017a` was added in #4973 which includes checksums, so they should be included in the existing easyconfig using `intel/2017a` as well.
=> also add checksums to Perl 5.24.1 easyconfig using intel/2017a

easybuild/easyconfigs/r/R/R-3.4.0-intel-2017a-X11-20170314.eb, easybuild/easyconfigs/s/Seurat/Seurat-1.4.0.16-intel-2017a-R-3.4.0.eb
Loading Seurat in R results in the following error:
```
> library(Seurat)
Error: package ‘Seurat’ was built for x86_64-apple-darwin13.4.0
```
This went undetected because of a bug in the EasyBuild framework where the `library(...)` import checks for R extensions were basically being skipped, see https://github.com/easybuilders/easybuild-framework/pull/2276.
The problem was the we were using the binary release of Seurat, rather than the source tarball...
As it turns out, several R extensions were also missing as dependencies.
=> fix version and source for Seurat, add extensions required by Seurat in R 3.4.0 easyconfig

easybuild/easyconfigs/b/Bowtie/Bowtie-1.2.1.1-foss-2016b.eb
This adds the current `Bowtie` for the `foss-2016b` toolchain.
One thing I mentioned after the build is that the options (`-O2 -march=corei7 -fPIC`) are passed twice (build with `eb --buildpath=/dev/shm --optarch=march=corei7 --prefix=/easybuild/test Bowtie-1.2.1.1-foss-2016b.eb -dr` on Ubuntu 16.04 and EasyBuild 3.3.1):
```
> bowtie --version
bowtie-align version 1.2.1.1
64-bit
Built on node018
Tue Jul 18 09:37:50 CEST 2017
Compiler: gcc version 5.4.0 (GCC) 
Options: -O3 -m64  -Wl,--hash-style=both -DWITH_TBB -DPOPCNT_CAPABILITY -O2 -march=corei7 -fPIC  -O2 -march=corei7 -fPIC 
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
```
Maybe something in the EasyBlock? Should I open an issue for this?
=> {bio}[foss/2016b] Bowtie 1.2.1.1

easybuild/easyconfigs/g/GLib/GLib-2.44.0-GCC-4.9.2.eb
After checking, it's not needed at all to update `$CPATH` like this for `GLib`...
(see also https://github.com/easybuilders/easybuild-easyconfigs/pull/5037/files#r134147655)
This is the only `GLib` easyconfig that includes this.
=> remove superfluous $CPATH update in GLib 2.44.0 easyconfig

easybuild/easyconfigs/l/libyaml/libyaml-0.1.7-GCCcore-6.4.0.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.20.1-GCCcore-6.4.0.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.7-GCCcore-6.4.0.eb
follow-up for #5073, fleshed out from #5072
=> bump version for libyaml, SQLite & Tcl easyconfigs that use GCCcore/6.4.0

easybuild/easyconfigs/b/BWA/BWA-0.7.15-GCCcore-5.4.0.eb, easybuild/easyconfigs/b/Bowtie/Bowtie-1.1.2-GCCcore-5.4.0.eb, easybuild/easyconfigs/b/Bowtie/Bowtie-1.1.2-GCCcore-6.3.0.eb, easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.11-GCCcore-5.4.0.eb, easybuild/easyconfigs/g/gSOAP/gSOAP-2.8.48-GCCcore-6.3.0.eb, easybuild/easyconfigs/g/gzip/gzip-1.8-GCCcore-6.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-4.9.3.eb, test/easyconfigs/easyconfigs.py
I've been bitten by forgetting to include `binutils` as a build dep a couple of times, leading to rather obscure build errors sometimes. This should hopefully help...
=> add check to see whether binutils is included as build dep when GCCore toolchain is used

easybuild/easyconfigs/r/R/R-3.3.3-intel-2017a-X11-20170314.eb, easybuild/easyconfigs/r/R/R-3.4.0-intel-2017a-X11-20170314.eb
Without the patch the `Rmpi` build fails since it tries to link against `libmpich` instead of `libmpi`.
=> Added Rmpi patch file for R built with intel toolchains incl. impi 5.x)

easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-3.0-goolf-1.4.10-20140227.eb, easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-3.1-gimkl-2.11.5.eb, easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-3.1-goolf-1.4.10.eb, easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-3.2-gimkl-2.11.5.eb, easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-3.2-intel-2016a.eb
see recently merged changes to OpenFOAM easyblock in https://github.com/easybuilders/easybuild-easyblocks/pull/780
=> clean up use of wcleanAll in OpenFOAM-Extend easyconfigs, now handled by OpenFOAM easyblock

easybuild/easyconfigs/b/BUSCO/BUSCO-1.22-intel-2017a-Python-2.7.13.eb
=> {bio}[intel/2017a] BUSCO 1.22 (REVIEW)

easybuild/easyconfigs/p/PyCUDA/PyCUDA-2016.1.2-intel-2016b-Python-2.7.12.eb
This version does not work:
PyCUDA-2016.1.2-intel-2017a-Python-2.7.13.eb
=> {lang} [intel/2016b] PyCUDA/2016.1.2 (REVIEW)

easybuild/easyconfigs/g/g2clib/g2clib-1.6.0-intel-2017a.eb, easybuild/easyconfigs/g/g2lib/g2lib-1.4.0-intel-2017a.eb
When trying to build g2lib-1.4.0-intel-2017a, I got an error about `png.h` not being found. With this fix, the build succeeds.
=> BUG: add missing libpng dependency to g2lib-1.4.0 for intel-2017a

easybuild/easyconfigs/a/ABINIT/ABINIT-7.10.4-intel-2015a-incl-deps.eb
I was checking whether the fix in https://github.com/easybuilders/easybuild-framework/pull/2323 was going to affect this easyconfig, but it turns out the `--with-fft-incs` can just be dropped (probably because the headers are available through `$CPATH` already).
=> remove unneeded --with-fft-incs configure option for ABINIT

easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-5.4.0-Perl-5.24.0.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-GCCcore-6.3.0-Perl-5.24.1.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-foss-2015a-Perl-5.22.0.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-foss-2016b-Perl-5.24.0.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-gimkl-2017a-Perl-5.24.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-5.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-foss-2017a.eb, easybuild/easyconfigs/x/X11/X11-20160819-GCCcore-5.4.0.eb, easybuild/easyconfigs/x/X11/X11-20160819-foss-2015a.eb, easybuild/easyconfigs/x/X11/X11-20160819-foss-2016b.eb, easybuild/easyconfigs/x/X11/X11-20160819-intel-2016b.eb, easybuild/easyconfigs/x/X11/X11-20170129-GCCcore-6.3.0.eb, easybuild/easyconfigs/x/X11/X11-20170129-gimkl-2017a.eb, easybuild/easyconfigs/x/X11/X11-20170314-GCCcore-6.3.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44-foss-2015a-Perl-5.22.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-5.4.0-Perl-5.24.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-6.3.0-Perl-5.24.1.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-foss-2015a-Perl-5.22.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-foss-2016b-Perl-5.24.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-gimkl-2017a-Perl-5.24.0.eb
(WIP because this change should be made consistently also in the other X11 easyconfigs; the `intltool` build dep, which in turns required `Perl`, is a bit of a PITA though...)
=> add xkeyboard-config component in X11 bundle + intltool as required build dep (REVIEW)

easybuild/easyconfigs/p/plotly/plotly-4.7.1-intel-2017a-R-3.4.0.eb
The sanity check for `plotly` fails because `$R_LIBS` does not get updated with the install location.
This went undetected because of the bug that was fixed in https://github.com/easybuilders/easybuild-framework/pull/2276
=> update $R_LIBS in plotly easyconfig

easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.5.1-intel-2017a.eb
During the regression test for EasyBuild v3.4.1, the installation of `libjpeg-turbo` 1.5.1 with `intel/2017a` failed on Intel Haswell because of failing tests on CentOS 7.4, while it still worked fine on Intel Sandy Bridge.
It seems this started occurring after our updates from CentOS 7.3 to CentOS 7.4.
Since the tests only fail on some architectures, some architecture-specific optimisation is likely to blame.
Disabling `optarch` fixes the issue.
=> disable optarch for libjpeg-turbo 1.5.1 built with intel/2017a

easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2015a.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2015b.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2016a.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-foss-2016b.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-goolf-1.4.10.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-goolf-1.7.20.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2015a.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2015b.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2016a.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2016b.eb, easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-intel-2017a.eb, easybuild/easyconfigs/r/R/R-3.1.3-foss-2015a.eb, easybuild/easyconfigs/r/R/R-3.1.3-intel-2015a.eb, easybuild/easyconfigs/r/R/R-3.2.0-goolf-1.7.20.eb, easybuild/easyconfigs/r/R/R-3.2.1-foss-2015b.eb, easybuild/easyconfigs/r/R/R-3.2.1-intel-2015a.eb, easybuild/easyconfigs/r/R/R-3.2.1-intel-2015b.eb, easybuild/easyconfigs/r/R/R-3.2.3-foss-2015b.eb, easybuild/easyconfigs/r/R/R-3.2.3-foss-2016a.eb, easybuild/easyconfigs/r/R/R-3.2.3-foss-2016b.eb, easybuild/easyconfigs/r/R/R-3.2.3-intel-2016a-libX11-1.6.3.eb, easybuild/easyconfigs/r/R/R-3.2.3-intel-2016a.eb, easybuild/easyconfigs/r/R/R-3.3.1-foss-2016a.eb, easybuild/easyconfigs/r/R/R-3.3.1-foss-2016b.eb, easybuild/easyconfigs/r/R/R-3.3.1-intel-2016b.eb, easybuild/easyconfigs/r/R/R-3.3.3-foss-2016b-X11-20160819.eb
Same fix as in #4481, applied consistently in all R easyconfigs that include `nloptr` extension.
Without this, the installation of the R easyconfigs that don't include `NLopt` as a dependency go into some kind of infinite loop when installing the `nloptr` extension...
=> include NLopt as a dependency in R easyconfigs that include nloptr as extension

easybuild/easyconfigs/p/Python/Python-3.6.3-foss-2017b.eb
I need to build a few packages with Python support in foss/2017b and noticed the Python 3 in intel/2017b is "newer" than the one in foss/2017b
=> [lang]{foss/2017b) version push for Python 3 in foss/2017b

easybuild/easyconfigs/m/MultiQC/MultiQC-1.2-intel-2017b-Python-2.7.14.eb
The MultiQC installation provided via the easyconfig in #5229 doesn't work:
```
$ multiqc --help
File "/user/home/gent/vsc400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/MultiQC/1.2-intel-2017b-Python-2.7.14/bin/multiqc", line 4, in <module>
__import__('pkg_resources').run_script('multiqc==1.2', 'multiqc')
File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 748, in run_script
File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1517, in run_script
File "/user/scratchphanpy/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/MultiQC/1.2-intel-2017b-Python-2.7.14/lib/python2.7/site-packages/multiqc-1.2-py2.7.egg/EGG-INFO/scripts/multiqc", line 33, in <module>
from multiqc.plots import table
File …
```
=> add missing extensions required by MultiQC & stick to networkx

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-intel-2017a.eb
The checksum included in #5233 was wrong because I determined it using a source tarball I downloade on Sept 5th 2017, which was before the GitHub-generated tarballs slightly changed (cfr. #5151)
=> fix checksum for OpenFOAM 5.0 source tarball

easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-2.7.14.eb
Installing `matplotlib` 2.1.0 automagically pulls in `subprocess32` and `backports.functools_lru_cache` (only with Python 2.x, since these are backported modules from Python 3.x), we should be doing that ourselves to support offline installation.
=> avoid downloads when installing matplotlib 2.1.0 w/ Python 2.7.14

easybuild/easyconfigs/s/Stacks/Stacks-1.47-foss-2016a.eb
Version 1.47 of Stacks using the foss-2016a toolchain. hstacks and estacks are no longer included in this version.
=> Version 1.47 of Stacks using the foss-2016a toolchain.

easybuild/easyconfigs/i/imkl/imkl-2017.3.196-gompi-2017b.eb
@boegel For a project I needed gcc with openmpi and MKL, which so far was not available in EasyBuild.  So I quickly created a config for MKL building.  We may want to grow that into a gomkl toolchain in future, but right now I do not have the time for that.  So just a quick one here.
=> {numlib}[gompi/2017b] imkl 2017.3.196

easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.5.0-intel-2017b.eb
See also #5077 & https://github.com/easybuilders/easybuild-easyblocks/issues/1233 .
During the review of #5353 we discovered that some recently merged netCDF easyconfigs were missing the `Autotools` build dep...
=> consistently add Autotools build dep in recent netCDF easyconfigs

test/easyconfigs/easyconfigs.py
check got broken due to flawed logic via #4136 (cc @ocaisa)
discovered by @wpoely86 in #4136
=> fix check for binutils build dep when GCCcore used as toolchain

easybuild/easyconfigs/o/OpenMM/OpenMM-7.1.1-intel-2017b-Python-3.6.3.eb
I'm trying to make an EasyConfig for the latest OpenMM version with recent Intel compilers.
I run into a rather silly issue. Easybuild complains that it cannot find `CMake/3.9.5-intel-2017b` but it should actually find `CMake/3.9.5-GCCcore-6.4.0`. There is something going wrong with the dependency resolution but I don't see how I can fix this. Any ideas?
=> {bio}[intel/2017b] OpenMM 7.1.1

easybuild/easyconfigs/u/util-linux/util-linux-2.31-GCCcore-6.4.0.eb
Installation of `util-linux` 2.31 fails on systems with older kernel with:
```
sys-utils/rfkill.c:67:12: error: 'RFKILL_TYPE_FM' undeclared here (not in a function)
{ .type = RFKILL_TYPE_FM,        .name = "fm",           .desc = "FM" },
^~~~~~~~~~~~~~
CC       sys-utils/setarch.o
make[2]: *** [sys-utils/rfkill-rfkill.o] Error 1
```
Recent kernel is required for this to work:
```
$ grep RFKILL_TYPE_FM  /usr/include/linux/rfkill.h
* @RFKILL_TYPE_FM: switch is on a FM radio device.
RFKILL_TYPE_FM,
$ rpm -q --whatprovides /usr/include/linux/rfkill.h
kernel-headers-3.10.0-693.5.2.el7.ug.x86_64
```
`rfkill` feature (disabling/enabling of wireless devices) is utterly useless in HPC context imho, so OK to disable.
cc @verdurin, @migueldiascosta
=> disable new rfkill feature in util-linux that requires recent kernel

easybuild/easyconfigs/o/Octave/Octave-4.2.1-intel-2017a.eb, easybuild/easyconfigs/o/Octave/signal-1.3.2_fix-formula.patch
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1318 for patch to be actually picked up
=> add patch for signal package in Octave 4.2.1 easyconfigs (+ add SHA256 checksums)

easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-6.4.0.eb
Apparently the `szip-2.1.1.tar.gz` have been updated in place...
The new tarball is a cleaned up version, here's a comparison with the previous one:
```
$ diff -u szip-2.1.1.orig szip-2.1.1 | grep -A 1 '^diff'
diff --git a/szip-2.1.1.orig/autom4te.cache/output.0 b/szip-2.1.1.orig/autom4te.cache/output.0
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/output.1 b/szip-2.1.1.orig/autom4te.cache/output.1
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/output.2 b/szip-2.1.1.orig/autom4te.cache/output.2
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/requests b/szip-2.1.1.orig/autom4te.cache/requests
deleted file mode 100644
--
diff --git a/szip-2.1.1.orig/autom4te.cache/traces.0 b/szip-2.1.1.orig/autom4te.cache/traces.0 …
```
=> fix checksum for Szip 2.1.1

easybuild/easyconfigs/f/FSLeyes/FSLeyes-0.15.0-intel-2017a-Python-2.7.13.eb
Installation of FSLeyes is now broken because of the wrong order.
A newer version of `fslpy` is pulled in when installing `fsleyes-props`, which doesn't work...
=> fix order of extensions for FSLeyes, add missing MarkupSafe (dep for Jinja2)

easybuild/easyconfigs/r/ROI_PAC/ROI_PAC-3.0.1-intel-2017a-Perl-5.24.1.eb
only has `rwxr--r--` by default...
=> fix permissions on make_raw_alos.pl script in ROI_PAC installation

easybuild/easyconfigs/b/BCFtools/BCFtools-1.6-foss-2016b.eb, easybuild/easyconfigs/h/HTSlib/HTSlib-1.6-foss-2016b.eb
This adds BCFtools 1.6 for foss-2016b with the missing dependency HTSlib 1.6.
=> {bio}[foss/2016b] BCFtools 1.6 and HTSlib 1.6

easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
fix for this issue that pops up when trying to run an analysis with `diveRsity`:
```
Error: Please install HWxtest: devtools::install_github('wrengels/HWxtest', 
subdir='pkg')
Execution halted
```
=> include HWxtest as extension to fix issue with diveRsity in R 3.4.3 easyconfig file

easybuild/easyconfigs/m/MapSplice/MapSplice-2.2.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/m/MapSplice/MapSplice-2.2.1_fix-build-gcc.patch
This adds MapSplice.
The patch is needed because since GCC version 4.9 default arguments on the definition are not allowed and have to be moved to the declaration. I also submitted the patch to the developers.
=> {bio}[foss/2016b] MapSplice 2.2.1

easybuild/easyconfigs/b/BamTools/BamTools-2.2.3-goolf-1.4.10.eb, easybuild/easyconfigs/b/BamTools/BamTools-2.2.3-ictce-5.3.0.eb, easybuild/easyconfigs/b/BamTools/BamTools-2.4.0-foss-2015b.eb, easybuild/easyconfigs/b/BamTools/BamTools-2.4.0-foss-2016b.eb, easybuild/easyconfigs/b/BamTools/BamTools-2.4.0-goolf-1.7.20.eb, easybuild/easyconfigs/b/BamTools/BamTools-2.4.1-intel-2017a.eb
`files_to_copy` was required, but not anymore thanks to updated `BamTools` easyblock in ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1332~~
=> clean up BamTools easyconfigs to rely on updated easyblock + add SHA256 checksums

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2-intel-2017b.eb
New config for 6.2. Dropped several previously used third party modules as they didn't immediately build cleanly, and the person requesting the installation didn't have any interest in them.
Downloads are problematic, and requires manual downloading to work due to easybuilders/easybuild#390
edit: depends on ~~#5496~~
=> {chem} [intel/2017b] QuantumESPRESSO v6.2

easybuild/easyconfigs/b/BamTools/BamTools-2.5.0-foss-2016b.eb
This adds version 2.5.0 of BamTools `--try-software-version` doesn't work because they changed some paths.
=> {bio}[foss/2016b] BamTools 2.5.0

easybuild/easyconfigs/n/NextGenMap/NextGenMap-0.5.5-foss-2016b.eb
This adds NextGenMap.
I can't think of a good `sanity_check_commands` line because printing the help message returns with non-zero exit code (says: `unrecognized option` :/ I opened an issue for this: https://github.com/Cibiv/NextGenMap/issues/29) and a real example would need additional data.
One other thing to note: by default the binaries are placed under `bin/ngm-<version>/` so I copy them with `installopts` one directory up. Is this ok?
=> {bio}[foss/2016b] NextGenMap 0.5.5

easybuild/easyconfigs/g/GlimmerHMM/GlimmerHMM-3.0.4-foss-2016b.eb
This adds GlimmerHMM.
It has two directories, `source` and `train`, where source files are located. Currently, the EasyConfig only builds glimmerhmm from the `source` directory and copies the precompiled binaries from the `train` directory to bin. What would be a proper way to also trigger the build in the train directory, `buildopts` with `cd` to and `make` in the train directory?
=> {bio}[foss/2016b] GlimmerHMM 3.0.4

easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016b.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.1-intel-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.2-goolf-1.7.20.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.2-intel-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-4.9.3.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-5.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-foss-2016b.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-intel-2016b.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-foss-2017a.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-intel-2017a.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-GCCcore-6.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-foss-2017b.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2017b.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.00.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.01.eb
This module is used by `QUAST`. See https://github.com/easybuilders/easybuild-easyconfigs/pull/5610#issuecomment-356604042.
=> Add Time::HiRes to recent Perl versions

easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
Without the fix, this will not build on our CentOS7 cluster
=> add rdma-core-devel to OS dependencies for OpenMPI 3.0.0

RELEASE_NOTES
Not sure how these were included wrongly, but they should be fixed before #5650 is merged.
=> fix PR refs for 2018a toolchain definitions

easybuild/easyconfigs/p/PLUMED/PLUMED-2.3.0-foss-2016b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.3.0-foss-2017a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.3.0-intel-2016b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.3.4-intel-2017b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-intel-2017b.eb
without this:
```
$ plumed config show | grep ^module | grep off
module adjmat off (default-off)
module crystallization off (default-off)
module drr off (default-off)
module eds off (default-off)
module manyrestraints off (default-off)
module ves off (default-off)
```
with this:
```
$ plumed config show | grep ^module | grep off
module adjmat on (default-off)
module crystallization on (default-off)
module drr on (default-off)
module eds on (default-off)
module manyrestraints on (default-off)
module ves on (default-off)
```
=> build recent PLUMED versions with all modules enabled

easybuild/easyconfigs/e/Emacs/Emacs-25.3-GCCcore-6.3.0.eb
Add latest emacs, more or less in the prior style (X/png/jpeg).
The existing Emacs configs all slightly vary in minor ways--this is intended to be a reasonable compromise of those.
=> add Emacs-25.3

easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-3.1.1-foss-2017a-nodejs-8.9.4.eb, easybuild/easyconfigs/i/IPython/IPython-6.2.1-foss-2017a-Python-3.6.4.eb, easybuild/easyconfigs/j/jupyterhub/jupyterhub-0.8.1-foss-2017a-Python-3.6.4.eb, easybuild/easyconfigs/n/nodejs/nodejs-8.9.4-foss-2017a.eb, easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2017a.eb
This includes:
- current IPython (v6.2.1) bundled with the notebook as well as nbconvert, nbformat, jupyter and all the dependencies
- current jupyterhub (v0.8.1) with dependencies
Both rely on Python 3.6.4 (included as well).
=> Add IPython 6.2.1 with jupyterhub 0.8.1.

easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.1.2-foss-2018a-Python-2.7.14.eb
New module.  This version is cpu-only.  It's also possible to compile
this with CUDA, but it seems useful to have two separate
versions.  (Still working on getting a CUDA version to compile.)
=> {bio}[foss/2018a] add MEGAHIT-1.1.2

easybuild/easyconfigs/o/Octave/Octave-4.2.1-intel-2017a-mt.eb, easybuild/easyconfigs/o/Octave/Octave-4.2.1-intel-2017a.eb
(requires https://github.com/easybuilders/easybuild-easyblocks/pull/1355 to correctly install only additional extensions in an existing Octave 4.2.1 installation using `--skip`)
=> include io and statistics extensions to Octave 4.2.1 easyconfigs

easybuild/easyconfigs/e/Emacs/Emacs-25.3-GCCcore-6.4.0.eb
It turns out to be very inconvenient to not have emacs and git that
share a toolchain.
=> Update emacs 25.3 to gcccore 6.4

easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.2-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.2-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.3-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.3-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.0-intel-2017a-Python-2.7.13.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.1-intel-2017a-Python-3.6.1.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-2.7.13-Qt-4.8.7.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-2.7.13-libpng-1.6.29.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-2.7.13.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-intel-2017a-Python-3.6.1-libpng-1.6.29.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-3.6.3.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-3.6.3.eb, easybuild/easyconfigs/t/Tkinter/Tkinter-2.7.14-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.1-intel-2017a-Python-3.6.1.eb, easybuild/easyconfigs/t/Tkinter/Tkinter-3.6.3-intel-2017b-Python-3.6.3.eb
follow-up for ~~#5689~~ (cc @schiotz)
I was forced to also fiddle with the `freetype` dependency in some `matplotlib` easyconfig to avoid introducing conflicts (since `Tkinter` indirectly depends on `freetype`).
We usually don't do that, but here that was the more sensible option, especially since it doesn't introduce any conflicts elsewhere (where `matplotlib` is used as a dependency).
=> add sanity check command in matplotlib easyconfigs built with intel toolchain to ensure Tkinter is available

easybuild/easyconfigs/k/Keras/Keras-2.1.3-foss-2017b-Python-3.6.3.eb
Now that we can properly build `TensorFlow` from source (cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1287), we should also use `TensorFlow` as backend for Keras (which is the default), since it performs a lot better than `Theano` (which is pretty much end of life).
requires ~~#5819~~ (`TensorFlow`)
cc @JensTimmerman
=> switch to using TensorFlow as backend for recent versions of Keras

easybuild/easyconfigs/a/ABINIT/ABINIT-8.0.8b-foss-2016b.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-8.0.8b-intel-2016b.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-8.2.2-foss-2016b.eb, easybuild/easyconfigs/a/ABINIT/ABINIT-8.2.2-intel-2016b.eb
triggered by @vanzod's PR #5760
cfr. https://www.abinit.org/packages
I couldn't find a new download location for ABINIT 8.0.8, so I left that as is
=> fix source_urls for recent versions of ABINIT

easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-GCCcore-6.4.0.eb
cfr. https://lists.ugent.be/wws/arc/easybuild/2018-03/msg00000.html
=>  add missing --enable-ld-version-script configure option for LibTIFF 4.0.9 built with GCCcore/6.4.0

easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-gcccuda-2017.01.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017.02.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017b.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
=> hard disable UCX support in recent OpenMPI versions, to dance around bug in OpenMPI configure script

easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
This change is required to avoid that two different types of gettext are used as dependency in easyconfigs using a `*-2018a` toolchain, cfr. check being added in #5970 .
We usually refrain from updating dependencies in existing easyconfig files, but I consider it acceptable in this particular case.
This changes the`OpenMPI` easyconfig included by @edmondac in #5878, so it would be great to get some feedback from him on this change.
=> bump hwloc dep for OpenMPI 2.1.2 that is part of iomkl/2018a to v1.11.8

easybuild/easyconfigs/g/git/git-2.16.1-foss-2018a.eb
This change is required to avoid that two different types of `gettext` are used as dependency in easyconfigs using a `*-2018a` toolchain, cfr. check being added in #5970 .
We usually refrain from updating dependencies in existing easyconfig files, but I consider it acceptable in this particular case.
This changes the `git` easyconfig contributed by @RvDijk in #5750, so it would be great to get some feedback from him on this change.
=> use gettext 0.19.8.1 on top of libxml2 2.9.7 as dep for git built with foss/2018a

easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.22-GCCcore-6.4.0-cairo-1.14.12.eb, easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.28-foss-2018a.eb
PR #5982 should have been using `libjpeg-turbo` 1.5.3, for compatibility with `gnuplot` (cfr. #5955)...
=> use latest libjpeg-turbo 1.5.3 in GraphicsMagick/Ghostscript foss/2018a easyconfigs

test/easyconfigs/easyconfigs.py
enhancement for the check added in #5970, to allow dependencies for both Python 2.x & Python 3.x
For example (from #6020):
```
FAIL: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 236, in test_dep_versions_per_toolchain_generation
self.assertFalse(multi_dep_vars, error_msg)
AssertionError: No multi-variant deps found for '^.*-(?P<tc_gen>201[89][ab]).*\.eb$' easyconfigs:
found 2 variants of 'pkgconfig' dependency in easyconfigs using '2018a' toolchain generation
* version: 1.3.1; versionsuffix: -Python-2.7.14 as dep for …
```
=> allow two dependency variants if one is for Python 2.x, other is for Python 3.x

easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-3.6.4.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-3.6.4.eb
Without this, you run into this error (ever since including `Tkinter` as dependency to restore interactive plotting capabilities, cfr. #5658, #5689) when trying to make plots in an environment where X11 forwarding is not enabled.
```
>>> import numpy as np
>>> import matplotlib.pyplot as pl
>>> pl.plot(np.random.random(3), np.random.random(3))
File "<stdin>", line 1, in <module>
File "/apps/gent/CO7/skylake-ib-PILOT/software/matplotlib/2.1.2-intel-2018a-Python-2.7.14/lib/python2.7/site-packages/matplotlib-2.1.2-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 3250, in plot
ax = gca()
File "/apps/gent/CO7/skylake-ib-PILOT/software/matplotlib/2.1.2-intel-2018a-Python-2.7.14/lib/python2.7/site-packages/matplotlib-2.1.2-py2.7-linux-x86_64.egg/matplotlib/pyp …
```
=> use non-interactive plotting backend by default for matplotlib 2.1.2

easybuild/easyconfigs/g/git/git-2.16.1-foss-2018a.eb
Using a bare Perl (i.e. without extensions) as dependency is problematic, since then this `git` module is incompatible with other modules that use a non-bare Perl as dependency.
Easiest solution is to just use the full Perl as dependency for `git`.
=> don't use bare Perl as dependency for 'git' with foss/2018a, use variant with extensions

easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.1-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-GCC-6.1.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.3-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.4-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-GCC-6.1.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.3-iccifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-PGI-16.7-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-iccifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb
cfr. #5716
The use of `--disable-dlopen` was originally introduced in #186 to fix a problem with `Rmpi` (see also https://www.mail-archive.com/devel@lists.open-mpi.org/msg10852.html).
I retested the installation of `Rmpi` on top of both `foss/2017b` and `foss/2016a` after rebuilding the `OpenMPI` component of those toolchains *without* `--disable-dlopen`, and I could not reproduce the `Rmpi` problem, so it seems like our original motivation for including `--disable-dlopen` is no longer valid anyway...
cc @m0zes, @chrissamuel, @akesandgren
=> drop use of --disable-dlopen in (recent) OpenMPI easyconfigs due to negative performance impact

easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb, easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
These easyconfigs were contributed in #5678 with the `XZ` dependency missing, probably because they were based on Python 2.7.14 easyconfigs (where `XZ` is not required).
=> add missing XZ dep in Python 3.6.4 easyconfigs built with */2018a toolchain

easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-intel-2017b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-intel-2018a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.1-iomkl-2018a.eb
PLUMED 2.4.1 in iomkl toolchain and checksum included for PLUMED 2.4.0
easy-configs.  2.4.0 configs completely lacked the checksum tests.
=> {chem}[iomkl/2018a] PLUMED v 2.4.1

easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
to sync up with recent changes in R 3.4.3 easyconfigs, cfr. #6099
=> add svd, Rssa, JBTools, RUnit, DistributionUtils and gapfill extensions for R 3.4.4

easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016b.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.1-intel-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.2-goolf-1.7.20.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.2-intel-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-4.9.3.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-5.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-foss-2016b.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.0-intel-2016b.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-foss-2017a.eb, easybuild/easyconfigs/p/Perl/Perl-5.24.1-intel-2017a.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-GCCcore-6.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-foss-2017b.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2017b.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.00.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.0-intel-2018.01.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
This reverts #5616 .
Including `Time::HiRes` as extension doesn't make sense, since it's a core Perl module (that is, it's always available).
Moreover, the `Time::HiRes` version that was included in #5616 is an ancient version, or some kind of customised fork of the official `Time::HiRes`.
Some installations are currently failing because of this:
* `BioPerl`: `"tv_interval" is not exported by the Time::HiRes module`
* `proovread`: `"usleep" is not exported by the Time::HiRes module`
This change was done for `QUAST` (cfr. #5610), but `QUAST-4.6.0-foss-2016b-Python-3.5.2.eb` builds just fine on top of `Perl/5.24.0-foss-2016b` that doesn't include `Time::HiRes` as an extension...
=> don't include (ancient version of) Time::HiRes as Perl extension, since it's a core Perl module

easybuild/easyconfigs/l/libdrm/libdrm-2.4.88-GCCcore-6.4.0.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.91-GCCcore-6.4.0.eb
As discussed during yesterday's conf call, `libdrm` fails to build on systems where `pkg-config` isn't available through the OS.  Thus, adding it as a build dependency.
I've only touched `libdrm-2.4.88-GCCcore-6.4.0.eb` and `libdrm-2.4.91-GCCcore-6.4.0.eb` as I don't have all the other toolchains available.  However, older versions are likely to also be affected.
=> libdrm: add `pkg-config` as build dependency

easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-pompi-2016.04.eb, easybuild/easyconfigs/i/imkl/imkl-2017.0.098-iimpi-2017.00-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-2017.1.132-gimpi-2017a.eb, easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iimpi-2017.01-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iimpi-2017a.eb, easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iompi-2017.01.eb, easybuild/easyconfigs/i/imkl/imkl-2017.1.132-iompi-2017a.eb, easybuild/easyconfigs/i/imkl/imkl-2017.2.174-iimpi-2017.02-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/i/imkl/imkl-2017.3.196-gompi-2017b.eb, easybuild/easyconfigs/i/imkl/imkl-2017.3.196-iimpi-2017b.eb, easybuild/easyconfigs/i/imkl/imkl-2017.3.196-iompi-2017b.eb, easybuild/easyconfigs/i/imkl/imkl-2017.4.239-iimpi-2017.09.eb, easybuild/easyconfigs/i/imkl/imkl-2018.0.128-iimpi-2018.00.eb, easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iimpi-2018.01.eb, easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iimpi-2018a.eb, easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iompi-2018a.eb, easybuild/easyconfigs/i/imkl/imkl-2018.2.199-iimpi-2018.02.eb, easybuild/easyconfigs/i/imkl/imkl-2018.2.199-iompi-2018.02.eb
`components = ['intel-mkl']` is already included in some (older) `imkl` easyconfigs, but not consistently
Having this there helps with avoiding problems when people use an alternate installation tarball, cfr. https://github.com/easybuilders/easybuild-framework/issues/2469
=> consistently specify 'intel-mkl' component in recent Intel MKL easyconfigs

easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb
fix for #6246 reported by @hajgato
It seems like the `network-2.1.tar.gz` source tarball is no longer available on PyPI.
Cfr. https://pypi.org/project/networkx/#files
This may be related to the recent switch to new PyPI, but maybe the `.tar.gz` never was available...
cc @RvDijk (since this relates to an easyconfig he added in #5925)
=> fix source spec for networkx 2.1 extension in scikit-image easyconfig

easybuild/easyconfigs/l/Libint/Libint-2.4.2-intel-2018a.eb
Libint provides an optional C++11 interface which requires the use of `-std=c++11`, cfr. https://github.com/evaleev/libint/wiki/using-modern-CPlusPlus--interface-v22-or-later
=> fix installation of Libint 2.4.2 by building with -std=c++11

easybuild/easyconfigs/n/NiBabel/NiBabel-2.2.1-intel-2018a-Python-3.6.4.eb, easybuild/easyconfigs/n/Nipype/Nipype-1.0.2-intel-2018a-Python-3.6.4.eb
This started occurring after https://github.com/easybuilders/easybuild-framework/pull/2493 was merged:
```
ERROR: Test for parsing of easyconfig NiBabel-2.2.1-intel-2018a-Python-3.6.4.eb
File "<string>", line 1, in innertest
File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 297, in template_easyconfig_test
ecs = process_easyconfig(spec)
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/easybuild_framework-3.6.1.dev0-py2.6.egg/easybuild/framework/easyconfig/easyconfig.py", line 1263, in process_easyconfig
raise EasyBuildError("Failed to process easyconfig %s: %s", spec, err.msg)
EasyBuildError: 'Failed to process …
```
=> fix typo in Nipype & NiBabel causing failure in test suite due to triggering typo detection

easybuild/easyconfigs/l/libdap/libdap-3.19.1-intel-2017b.eb
This reverts commit 19d037e91a2edbdd26f87a4797e972bcd50d29e4 (PR #5473), since apparently the original tarball was re-instated (on Dec 28th 2017, if the timestamp in https://www.opendap.org/pub/source/ can be trusted).
=> change back checksum for libdap 3.19.1

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0-foss-2018a-Python-3.6.4.eb
=> also include patch + use -mno-avx512f to fix TensorFlow 1.8.0 built with foss/2018a on Intel Skylake (AVX512)

easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-foss-2018a.eb, easybuild/easyconfigs/b/BLAST+/BLAST+-2.7.1-intel-2018a.eb
After running into a version conflict on `Python` when combining `BLAST+` (which currently includes `Python` `2.7.14` as a dependency) with `R` (which indirectly depends on `Python` `3.6.4`), in the context of `Roary`, cfr. #6284), I looked into why we actually have `Python` listed as a dependency for `BLAST+`...
The only reason I could find is the `windowmasker_2.2.22_adapter.py`, which actually has `#!/usr/bin/python` hardcoded (so the `Python` we provide as a dependency is not used).
Moreover, I doubt the script is very relevant, can't seem to find much about it when searching the BLAST+ documentation... Note that there's also a `windowmasker` binary.
So, I propose we drop `Python` as a dependency to `BLAST+`, and rename the easyconfig accordingly. That way, we can also use this …
=> remove Python dependency from BLAST+ 2.7.1 easyconfig using foss/2018a toolchain

easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018a-Python-3.6.4.eb, easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.4.2-foss-2018a.eb, easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
libgeotiff depedency was added to the GDAL module, since the R package `rgdal` was linking to `/usr/lib64/libgeotiff.so`, which resulted in errors.
=> {lang}[foss/2018a] R 3.4.4

easybuild/easyconfigs/c/canu/canu-1.7-intel-2018a.eb
Amendment to #6377
We already have easyconfigs for the same software under the name `canu`...
=> rename 'Canu' to 'canu' for v1.7

easybuild/easyconfigs/p/PANDAseq/PANDAseq-2.11-intel-2018a.eb
A slight adaption of `PANDAseq-2.5-goolf-1.4.10.eb` to install a newer version of PANDASeq with the intel toolchain.
=> {bio} [intel/2018a] PANDASeq 2.11

easybuild/easyconfigs/c/CGAL/CGAL-4.11.1-foss-2018a-Python-2.7.14.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-foss-2018a.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.5-foss-2018a.eb
@boegel it seems to be the case that ParaView is able to build with Qt5, which means that Qt4 from #6394 can be removed again? Also should the intel version of ParaView also adapt to use Qt5?
If you prefer to stay with using Qt4 it is also fine for me.
The documentation of Paraview also states:
> ParaView can still be built with Qt4, though it is not recommended.
=> {cae}[foss/2018a] OpenFOAM-5.0 

easybuild/easyconfigs/g/GDB/GDB-8.1-foss-2018a-Python-2.7.14.eb
It was necessary to add a build dependency upon texinfo since the build failed without access to makeinfo which wasn't installed on our system.
=> {debugger}[foss/2018a] GDB v8.1

easybuild/easyconfigs/g/GCCcore/GCCcore-8.1.0.eb
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1435 to not cause problems on CentOS 6.x
@migueldiascosta Please test this on top of https://github.com/easybuilders/easybuild-easyblocks/pull/1435 on CentOS 6.x?
=> stop including GCCcore 6.4.0 as build dep for GCCcore 8.1.0

easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0_fix-linux-unwind-fix-ucontext.patch
cfr. https://github.com/easybuilders/easybuild-easyconfigs/issues/6374#issuecomment-392257938
cc @geimer
=> add patch for GCCcore 6.4.0 to fix compilation problems on glibc 2.26 systems

test/easyconfigs/easyconfigs.py
Since `GCCcore` 7.3.0 is most likely going to become the base for the `2018b` common toolchains, we should extend the "dependency variants" we're doing for easyconfigs using a common toolchain to also check easyconfigs using a recent version of the `GCCcore` toolchain
cc @hajgato
=> also check for multiple dependency variants in easyconfigs using GCCcore 7.3.0 & newer

easybuild/easyconfigs/v/VTK/VTK-8.1.1-intel-2018a-Python-2.7.14.eb
#6404 was merged a bit prematurely...
We should always build VTK with MPI support enabled from now on imho.
=> drop '-mpi' versionsuffix for VTK 8.1.1

easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
No idea what happened, but when downloading the following files from CRAN now, the checksums are different than before.
That's strange, especially for `pkgmaker_0.22.tar.gz` and `rngtools_1.2.4.tar.gz`, both of which were downloaded on Jan 16th 2015 and haven't changed since (until now, that is).
=> fix checksums for pkgmaker/rngtools/RWeka/RcppProgress extensions in R 3.4.4 easyconfigs

easybuild/easyconfigs/z/zstd/zstd-1.3.4-foss-2016b.eb
For this old toolchain there may be issues related to Lmod loading the same `zlib` version from both `GCCcore` and `foss`. For example see #6450 
The issue is solved by promoting `zstd` from `GCCcore` to `foss`.
=> Move zstd from GCCcore to foss

easybuild/easyconfigs/h/hwloc/hwloc-1.11.10-GCCcore-7.3.0.eb
see also https://github.com/easybuilders/easybuild-easyconfigs/pull/6424#issuecomment-397601063 and https://github.com/open-mpi/hwloc/issues/315
=> build hwloc 1.11.10 with -fno-tree-vectorize to avoid segfaulting lstopo on Intel Skylake

easybuild/easyconfigs/g/Guile/Guile-1.8.8-GCCcore-6.4.0.eb
Because -Werror is added, building this fails with
ramap.c:704:7: error: ‘ras’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
I have added -Wno-error=maybe-uninitialized to circumvent this.
=> Guile 1.8.8: added necessary compiler flag

easybuild/easyconfigs/f/FANN/FANN-2.2.0-GCCcore-6.4.0.eb, easybuild/easyconfigs/f/FANN/FANN-2.2.0-intel-2018a.eb
I'm not sure both an intel/2018a flavour and a GCCcore/6.4.0 one is needed, so I can remove the intel one if that's thought to be better practice.
=> {lib} [GCCcore/6.4.0, intel/2018a] FANN v2.2.0

easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.9.0-intel-2018a.eb
Doesn't build with `configopts = '--enable-shared'` so only static libraries (as is also the case in the only other `PnetCDF` eb file).
=> {data} [intel/2018a] PnetCDF v1.9.0

easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-7.3.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-8.1.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.30.eb, easybuild/easyconfigs/b/binutils/binutils-2.30_fix-assertion-fail-elf.patch
ran into this `binutils` bug when testing the rebuild of `PLUMED-2.4.0-intel-2018a.eb` with the WIP definition for `intel/2018b` (cfr. #6409)
```
ld: BFD (GNU Binutils) 2.30 assertion fail elf.c:3564
```
which is known issue, see https://sourceware.org/bugzilla/show_bug.cgi?id=22836
It's worth pulling in this patch since the plan is to use `binutils` 2.30 as a part of the `2018b` toolchains.
=> add patch for binutils 2.30 to fix assertion failure

easybuild/easyconfigs/p/Python/Python-3.6.1-intel-2017a.eb, easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2018.00.eb, easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2018.01.eb, easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
fix for #6484
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1441
=> enable checking/setting of unlimited stack limit in Python 3.6.x easyconfigs using an 'intel' toolchain

easybuild/easyconfigs/m/MAJIQ/MAJIQ-1.1.1-intel-2018a-Python-3.6.4.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-intel-2018a-Python-3.6.4.eb
follow-up for #5983, tests fail because of multiple variants of Pysam being found without this
=> bump Pysam dep for MAJIQ to 0.14.1 to fix compatibility with other 2018a easyconfigs

easybuild/easyconfigs/f/fastq-tools/fastq-tools-0.8-foss-2016b.eb
This adds fastq-tools.
I had one issue with the easyconfig during the build. The `LIBS` variable somehow becomes `LIBS = -lm -lpthread-lm` and this obviously results in `error: cannot find -lpthread-lm` during linking. Here is the log of the build: [easybuild-fastq-tools-0.8-20171123.134323.HYgMZ.log](https://github.com/easybuilders/easybuild-easyconfigs/files/1499421/easybuild-fastq-tools-0.8-20171123.134323.HYgMZ.log)
=> {bio}[foss/2016b] fastq-tools 0.8

easybuild/easyconfigs/p/Perl/Perl-5.26.1-GCCcore-6.4.0.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.1-foss-2018a.eb
(cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1449)
=> fix missing dependencies for Perl modules included as extensions for Perl 5.26.1

easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
(cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/1449)
=> fix missing dependencies for Perl modules included as extensions for Perl 5.28.0

easybuild/easyconfigs/g/gtest/gtest-1.8.0-GCCcore-6.3.0.eb, easybuild/easyconfigs/g/gtest/gtest-1.8.0-GCCcore-6.4.0.eb
Previous versions were installed as binary, `1.8.0` is a source version, so it have to be compiled.
=> Fix gtest 1.8.0 - compile gtest

easybuild/easyconfigs/c/coevol/coevol-20180201-goolf-1.7.20.eb
follow-up for #6589 
@pescobar `20180201` matches date of used commit (Feb 1st 2018), and sorts properly
=> use sortable version for coevol

easybuild/easyconfigs/b/Boost/Boost-1.68.0-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/b/Boost/Boost-1.68.0-foss-2018b-Python-3.7.0.eb, easybuild/easyconfigs/b/Boost/Boost-1.68.0-intel-2018b-Python-2.7.15.eb, easybuild/easyconfigs/b/Boost/Boost-1.68.0-intel-2018b-Python-3.7.0.eb
Configuration files for Boost 1.68.0 for foss/2018b and intel/2018b.  With Python 2/3 support.
Requires modified easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/1472
=> {devel}[foss-2018b,intel-2018b] Boost v1.68.0 with Python support

easybuild/easyconfigs/b/Boost/Boost-1.68.0-foss-2018b-Python-3.6.6.eb, easybuild/easyconfigs/b/Boost/Boost-1.68.0-intel-2018b-Python-3.6.6.eb, easybuild/easyconfigs/h/h5py/h5py-2.8.0-foss-2018b-Python-3.6.6.eb, easybuild/easyconfigs/h/h5py/h5py-2.8.0-intel-2018b-Python-3.6.6.eb, easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-foss-2018b-Python-3.6.6.eb, easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-intel-2018b-Python-3.6.6.eb
=> switch to Python 3.6.6 (instead of 3.7.0) for 2018b toolchain generation

easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-foss-2018b.eb, easybuild/easyconfigs/m/Mesa/Mesa-18.1.1-intel-2018b.eb
Adding explicit expat build dependency.
If absent, Mesa v18.1.1 configure step fails on `centos-release-7-5.1804.1.el7.centos.x86_64`:
`...`
`checking for expat... no`
`checking for expat21... no`
`configure: error: Package requirements (expat21) were not met`
`...`
=> {vis}[foss/2018b] Mesa v18.1.1 - add expat dep

easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.6.2-intel-2018a.eb
So then `arpack` libraries can be linked not only from `Fortran` but from `C` and `C++` , see https://github.com/opencollab/arpack-ng point 4.
=> Add iso_c_binding support to arpack-ng 3.6.2

easybuild/easyconfigs/p/PyTorch/PyTorch-0.3.1-intel-2018a-Python-3.6.4.eb
This was inherited from `PyTorch-0.3.1-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb` via #6152, but it doesn't make any sense to have it there...
cc @wpoely86, @smoors, @zao
=> remove useless definition of TORCH_CUDA_ARCH_LIST in PyTorch easyconfig that doesn't use CUDA

easybuild/easyconfigs/g/GCCcore/GCCcore-6.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.3.0_fix-linux-unwind-fix-ucontext.patch, easybuild/easyconfigs/g/GCCcore/GCCcore-6.3.0_fix-sanitizer_linux.patch
Fixes issue #5758 by using backported patches from 6.4.0:
- https://git.yoctoproject.org/cgit/cgit.cgi/poky/plain/meta/recipes-devtools/gcc/gcc-6.3/0055-unwind_h-glibc26.patch?id=4cb2af5af804393c80ed4d76b2ff34187d5a4d5b
- https://github.com/gcc-mirror/gcc/commit/72edc2c02f8b4768ad660f46a1c7e2400c0a8e06.patch
=> Fix builing GCCcore-6.3.0 by backporting patches from 6.4.0

easybuild/easyconfigs/l/libgd/libgd-2.1.0-ictce-5.5.0.eb, easybuild/easyconfigs/l/libgd/libgd-2.1.1-foss-2016a.eb, easybuild/easyconfigs/l/libgd/libgd-2.1.1-intel-2015b.eb, easybuild/easyconfigs/l/libgd/libgd-2.1.1-intel-2016a.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.3-foss-2016b.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.3-intel-2016b.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.4-GCCcore-6.4.0.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.4-foss-2016b.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.4-intel-2017a.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.5-GCCcore-6.4.0.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.5-intel-2017b.eb, easybuild/easyconfigs/l/libgd/libgd-2.2.5-intel-2018a.eb
fix for problem reported by @crubb (via IRC)
=> specify location of dependencies in configure options for libgd (to avoid system libraries being used instead)

easybuild/easyconfigs/c/CMake/CMake-3.11.4-GCCcore-6.4.0.eb, easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-6.4.0.eb
for compatibility with easyconfigs using a */2017b or */2018a toolchain
see https://github.com/easybuilders/easybuild-easyconfigs/pull/6724/files#r212670349
=> stick to ncurses 6.0 as dependency for CMake built with GCCcore/6.4.0

easybuild/easyconfigs/e/Eigen/Eigen-3.3.4.eb
required because of change to `Eigen` easyblock, see https://github.com/easybuilders/easybuild-easyblocks/pull/1482
=> add CMake build dep for Eigen 3.3.4

easybuild/easyconfigs/c/CMake/CMake-3.12.1.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.3.5.eb
config for the latest Eigen, with a new CMake 3.12.1, both to be installed with a dummy toolchain
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1482, already merged.
=> {math}[dummy/dummy] Eigen v3.3.5

easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-5.5.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.4.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.2.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.1.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-system.eb
Now that I built Doxygen, which depends on flex, I found that we need to add `-D_GNU_SOURCE` to `preconfigopts` not only for the dummy flex, but also the `GCCcore-7.3.0` flex. Otherwise, flex will segfault when building Doxygen.
Please refer to #5792.
Should we add the `preconfigopts` to the other `flex-2.6.4-GCCcore-*.eb` as well?
=> Use -D_GNU_SOURCE for flex-2.6.4-GCCcore-7.3.0 as well

.travis.yml
requires because of changes in https://github.com/easybuilders/easybuild-framework/pull/2575
=> bump Lmod version used in Travis config to 6.6.3 (now required by framework)

easybuild/easyconfigs/h/hwloc/hwloc-1.11.10-GCCcore-7.3.0.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.7-GCCcore-5.4.0.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.7-GCCcore-6.4.0.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-GCCcore-6.4.0.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-GCCcore-7.2.0.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-intel-2017a.eb
This utility is only built on x86 architectures. I left the check for the intel toolchain, as in that case the sanity check should be fine.
edit (by @boegel): cfr. #6833
=> {system}[GCCcore/5.4.0,GCCcore/6.4.0,GCCcore/7.3.0] Do not check if hwloc-dump-hwdata utility was installed

easybuild/easyconfigs/t/Tk/Tk-8.6.8-GCCcore-6.4.0.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.8-GCCcore-7.3.0.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.8-foss-2018a.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.8-iomkl-2018a.eb
Tk only installs an executable named "wish8.6", but other software (e.g. FSL) usually looks for just "wish" without the version number. OS packages from e.g. RHEL also install a "wish" executable instead of the versioned one, so with this change, the EasyConfig creates a symlink in the bin dir from "wish" -> "wish8.6".
=> add wish -> wish8.6 symlink to Tk

easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb, easybuild/easyconfigs/r/R/hdf5r-1.0.0_fix-HDF5-1.10.2.patch
requires https://github.com/easybuilders/easybuild-easyblocks/pull/1513 to ensure that `preinstallopts` for `hdf5r` is picked up
=> add various additional extensions to recent R easyconfigs

easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-GCCcore-6.3.0.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-foss-2016.04.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-foss-2016a.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-foss-2016b.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-iccifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-intel-2016b.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.6-GCCcore-4.9.3.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.6-GCCcore-6.3.0.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.7-GCCcore-6.4.0.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.8-GCCcore-6.4.0.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.8-GCCcore-7.3.0.eb
The installation only provides the `tclsh8.6` executable. Scripts that call `tclsh` (e.g. building `FSL`'s `fslio`) will fail unless available from the underlying OS.
With this PR the symlink `tclsh -> tclsh8.6` is created in the binaries installation path.
=> add tclsh symlink to recent Tcl easyconfigs

easybuild/easyconfigs/f/fastStructure/fastStructure-1.0-foss-2016a-Python-2.7.11.eb
The current fastStructure easyconfig only makes the main script (structure.py) executable. This PR also makes the additional scripts (chooseK.py, distruct.py, see https://rajanil.github.io/fastStructure/#choosing-model-complexity) executable, so they can be easily run without having to prefix them with the installation path.
edit: now requires https://github.com/easybuilders/easybuild-easyblocks/pull/1529
=> change fastStructure easyconfig to use custom easyblock

easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-foss-2016b-GPU-enabled.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-goolfc-2017.01.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3_amend_search_for_nvml_lib.patch, easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3_fix_search_for_nvml_include.patch
Update GROMACS 2016.3 easyconfigs with nvml include search patch.
Update GROMACS-2016.3 nvml lib search patch to be more generic.
Add nmvl include search patch.
Update checksums.
=> Update gromacs 2016.3 for nvml patches

easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.5.0-intel-2017b.eb
Some 2017b easyconfigs for netCDF was missing the Szip dependency.
=> Add missing dep for Szip in 2017b builds of netCDF.

easybuild/easyconfigs/o/OpenBabel/OpenBabel-2.4.1-fix-link-path-tests.patch, easybuild/easyconfigs/o/OpenBabel/OpenBabel-2.4.1-intel-2017b-Python-2.7.14.eb
=> Fix missing comment from OpenBabel-2.4.1-fix-link-path-tests.patch

easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.0-GCCcore-6.4.0.eb, easybuild/easyconfigs/f/fontconfig/fontconfig-2.13.0-GCCcore-7.3.0.eb
This removes LibUUID which causes several system programs to fail, see discussion on the mailing list:
https://lists.ugent.be/wws/arc/easybuild/2018-10/msg00011.html
The dependency of LibUUID is replaced by util-linux.  The change only affects fontconfig-2.13.0 as older versions do not depend on LibUUID.  Rebuilding this module is enough to solve the issues, no need to rebuild the entire X11 stack.
CC: @OleHolmNielsen
=> Eliminate dependency on problematic LibUUID library.

easybuild/easyconfigs/a/ADMIXTURE/ADMIXTURE-1.3.0.eb
correct download URL is (unfortunately) `http://` rather than `https://`
SHA256 checksum matches what I downloaded on Aug 10th 2016
=> fix source URL for ADMIXTURE (no https) + add SHA256 checksum

easybuild/easyconfigs/b/Bazel/Bazel-0.16.0-GCCcore-6.4.0.eb
A updated version of Bazel to make sure that a newer TensorFlow builds without issues.
=> Bazel 0.16.0 with GCCcore 6.4.0

easybuild/easyconfigs/g/GATK/GATK-4.0.10.0-foss-2018b-Python-3.6.6.eb
GATK-4.0.10.0 - Edited to make pep8 compliant, added javaver, pyver.
Update GATK for 2018b, using Java 1.8.0_181 with 2018b
=> {bio}[foss/2018b] GATK-4.0.10.0 w/ Python 3.6.6

easybuild/easyconfigs/d/DBus/DBus-1.13.6-GCCcore-6.4.0.eb, easybuild/easyconfigs/d/DBus/DBus-1.13.6-GCCcore-7.3.0.eb, easybuild/easyconfigs/n/NSPR/NSPR-4.20-GCCcore-6.4.0.eb, easybuild/easyconfigs/n/NSPR/NSPR-4.20-GCCcore-7.3.0.eb, easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-6.4.0.eb, easybuild/easyconfigs/n/NSS/NSS-3.39-GCCcore-7.3.0.eb, easybuild/easyconfigs/n/NSS/NSS-3.39_pkgconfig.patch, easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018a.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018b.eb
(strictly speaking requires https://github.com/easybuilders/easybuild-easyblocks/pull/1544)
cfr. #5600
note: similar fix for `Qt5-5.10.1-intel-2018a.eb` is more complex, it also involves some patches, will open a separate PR for that
=> add missing NSS/DBus dependencies to Qt 5.10.1 easyconfigs built with foss toolchain to ensure that QtWebEngine component gets installed

easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb
This is mainly done because picking up the most recent `PyNaCl` version (1.3.0) is problematic with this generation of Intel compilers (cfr. #6971)
=> add missing extensions to Python 2.7.14 easyconfigs using toolchain of 2017b generation

easybuild/easyconfigs/r/RTG-Tools/RTG-Tools-3.9.1-Java-1.8.eb
addition for #6862
Without this, the user is prompted with interactive Q&A when running `rtg`, which tries to create `rtg.cfg` in the installation directory, which usually fails because of permission problems...
cc @smoors
=> create default configuration for RTG-Tools

easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb
Somehow the missing checksum slipped through in #7022, even though the tests are supposed to catch missing checksums in easyconfigs being touched...
Works as expected with `--check-contrib` though, which uses the same code as the tests...
```
$ eb --check-contrib  easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb --ignore-osdeps
== temporary log file in case of crash /Users/kehoste/work/TMP/eb-OW6INh/easybuild-5MuZoZ.log
Running style check on 1 easyconfig(s)...
[PASS] /Volumes/work/easybuild-easyconfigs/easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb
>> All style checks PASSed!
Checking for SHA256 checksums in 1 easyconfig(s)...
[FAIL] /Volumes/work/easybuild-easyconfigs/easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb
Checksums missing for one or more …
```
=> add missing checksums for ipaddress Python extension (+ reformatting)

.travis.yml, test/easyconfigs/easyconfigs.py
fix for failure to catch missing checksum issue in #7022 (which is fixed in #7033)
=> also run checks on changed files when target branch for PR is something different than 'develop'

easybuild/easyconfigs/x/X11/X11-20180131-GCCcore-6.4.0.eb
=> add libXp component to X11 bundle for GCCcore 6.4.0

easybuild/easyconfigs/l/LZO/LZO-2.06-goolf-1.4.10.eb, easybuild/easyconfigs/l/LZO/LZO-2.06-ictce-5.3.0.eb, easybuild/easyconfigs/l/LZO/LZO-2.09-intel-2016b.eb, easybuild/easyconfigs/l/LZO/LZO-2.09-intel-2017b.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-6.4.0.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2016a.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2016b.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2017a.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2018a.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-foss-2018b.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-intel-2017a.eb
while installing an application that needs the dynamic library `liblzo2.so.2` I realized that the easyconfig for LZO only provides static libraries because that's the default in the build system provided by LZO
```
lzo-2.10]$ ./configure --help |grep -i shared
--enable-shared[=PKGS]  build shared libraries [default=no]
```
I have enabled the dynamic build for all the easyconfigs and extended the sanity check
@boegel I guess you are the only one who has all these toolchains installed. Can you trigger a test build please?
=> also install shared libraries for LZO

easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-foss-2017b-Python-3.6.3.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-2.7.13.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-intel-2017a-Python-3.6.1.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2017b-Python-3.6.3.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-intel-2017b-Python-2.7.14.eb
installation now fails with a weird error like:
```
Processing dependencies for scikit-image==0.13.1
Searching for PyWavelets>=0.4.0
Reading https://pypi.python.org/simple/PyWavelets/
Downloading https://files.pythonhosted.org/packages/b4/42/074c6adcd1586926650d8365bcc3e1ab42f81a68c620c4242aa9297b01d9/PyWavelets-1.0.1.tar.gz#sha256=3c5cece36d4e17d395be6e9ac6b80ce7b774a1f71c251756c6163e63b6d878dc
Best match: PyWavelets 1.0.1
Processing PyWavelets-1.0.1.tar.gz
Writing /tmp/eb-9U_o_7/easy_install-8hzs3oix/PyWavelets-1.0.1/setup.cfg
Running PyWavelets-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/eb-9U_o_7/easy_install-8hzs3oix/PyWavelets-1.0.1/egg-dist-tmp-o5hds8fq
Partial import of skimage during the build process.
File …
```
=> fix installation of scikit-image 0.13.x by including missing required PyWavelets extension

easybuild/easyconfigs/q/Qt5/Qt5-5.10.1-foss-2018a.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.11.2-foss-2018b.eb
configs QT5.10.1 (bugfix) and QT5.11.2 (new) for foss/2018b
This replaces PR #7082, which got corrupted when attempting a merge conflict resolution.
=> {devel,vis}[foss/2018b] add missing gperf dep for Qt5 5.10.1 and new config for Qt5 5.11.2

easybuild/easyconfigs/p/Python/Python-2.7.13-foss-2017a.eb, easybuild/easyconfigs/p/Python/Python-2.7.13-intel-2017a.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2017b.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-foss-2018a.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-fosscuda-2018a.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018.01.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-intel-2018a.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-iomkl-2018a.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-foss-2018b.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-fosscuda-2018b.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-intel-2018b.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-iomkl-2018b.eb, easybuild/easyconfigs/p/Python/Python-3.6.3-foss-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.3-goolfc-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.3-intel-2018.01.eb
`pip check` reports that `PyNacl`, `bcrypt` and `cryptography` require `cffi` to be installed, but it's not...
This isn't picked up by `download_dep_fail` for some reason, but `pip check` does pick up on it (cfr. #1565), for example:
```
pynacl 1.2.1 requires cffi, which is not installed.
bcrypt 3.1.4 requires cffi, which is not installed.
cryptography 2.2.2 requires cffi, which is not installed.
```
=> add missing cffi & pycparser extensions to recent Python easyconfigs

easybuild/easyconfigs/p/picard/picard-2.10.1-Java-1.8.0_131.eb, easybuild/easyconfigs/p/picard/picard-2.18.11-Java-1.8.0_162.eb, easybuild/easyconfigs/p/picard/picard-2.18.5-Java-1.8.0_162.eb, easybuild/easyconfigs/p/picard/picard-2.2.4-Java-1.8.0_92.eb, easybuild/easyconfigs/p/picard/picard-2.6.0-Java-1.8.0_131.eb
see also https://easybuild.readthedocs.io/en/latest/Writing_easyconfig_files.html#loading-of-modules-for-dependencies-with-a-dummy-toolchain
=> use empty toolchain version in picard easyconfigs to ensure Java dependency is loaded during installation

easybuild/easyconfigs/l/libxc/libxc-4.2.3-foss-2017b.eb, easybuild/easyconfigs/l/libxc/libxc-4.2.3-foss-2018a.eb, easybuild/easyconfigs/l/libxc/libxc-4.2.3-foss-2018b.eb, easybuild/easyconfigs/l/libxc/libxc-4.2.3-gimkl-2017a.eb, easybuild/easyconfigs/l/libxc/libxc-4.2.3-intel-2018a.eb
It seems like the enforcing `lowopt` for recent `libxc` versions, which was added in #4199, is no longer required with `libxc` 4.2.3.
~~We're not~~ We are running `make check`, which should be sufficient to catch any problems with compiling with `-O2` (`defaultopt`) rather than `-O1` (`lowopt`).
cc @akesandgren, @tovrstra (cfr. #4199), @migueldiascosta (cfr. #5250)
=> stop using lowopt in libxc 4.2.3 easyconfigs

easybuild/easyconfigs/a/ARCH/ARCH-4.5.0-intel-2018a-Python-3.6.4.eb
strictly required in case https://github.com/easybuilders/easybuild-easyblocks/pull/1567 gets merged, to avoid failing `pip check`
=> add missing 'patsy' extension in ARCH easyconfig + switch to using PythonBundle easyblock

easybuild/easyconfigs/n/NeuroKit/NeuroKit-0.2.7-intel-2018a-Python-3.6.4.eb
strictly required if https://github.com/easybuilders/easybuild-easyblocks/pull/1567 gets merged to avoid `pip check` failure..
=> add missing (dummy) sklearn extension in NeuroKit easyconfig

easybuild/easyconfigs/p/Python/Python-3.6.1-foss-2017a.eb, easybuild/easyconfigs/p/Python/Python-3.6.1-intel-2017a.eb, easybuild/easyconfigs/p/Python/Python-3.6.2-foss-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2017b.eb, easybuild/easyconfigs/p/Python/Python-3.6.2-intel-2018.00.eb, easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2017a.eb
cfr. #7105
strictly required in case https://github.com/easybuilders/easybuild-easyblocks/pull/1567 gets merged, to avoid failing `pip check`
=> also add missing cffi extension to Python 3.6.1 & 3.6.2 easyconfigs

easybuild/easyconfigs/c/CP2K/CP2K-2.4.0-goolf-1.4.10-ipi.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.4.0-goolf-1.4.10.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.4.0-ictce-5.5.0.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.5.1-intel-2014b.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-2015.06.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-2015.11.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-intel-2015a.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.1-foss-2015b.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.1-intel-2015b.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-CrayGNU-2015.11-cuda-7.0.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-CrayGNU-2015.11.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016a.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016b-psmp.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016b.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2017b.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2018a.eb, easybuild/easyconfigs/c/CP2K/CP2K-4.1-foss-2016b-psmp.eb, easybuild/easyconfigs/c/CP2K/CP2K-4.1-intel-2016b.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-foss-2018a.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-intel-2017b.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-intel-2018a.eb
fix for #7239 reported by @sassy-crick
The source tarballs that can be downloaded from GitHub are exactly the same as the ones that used to be on SourceForge (same SHA256 checksums).
=> fix source_urls in CP2K easyconfigs (for official releases)

easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.45-intel-2018b.eb
- recent cfitsio from `https://heasarc.gsfc.nasa.gov/fitsio/` built with intel2018b toolchain
- added dependency to current cURL for HTTPs support in cfitsio
- added `make shared` statement to produce shared lib too
=> {lib}[intel/2018b] CFITSIO v3.45

easybuild/easyconfigs/d/DOLFIN/DOLFIN-2018.1.0.post1-foss-2018a-Python-3.6.4.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-foss-2018a.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-intel-2018a.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-foss-2018b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6-intel-2018a.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1806-foss-2018b.eb, easybuild/easyconfigs/p/PETSc/PETSc-3.9.3-foss-2018a.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-foss-2018a.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-foss-2018b.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-intel-2018a.eb, easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-foss-2018a-Python-3.6.4.eb
fix for problem reported by @smoors in #7154
see also enhanced `SCOTCH` easyblock in ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1580~~
WIP since needs thorough testing (which is under way); test reports welcome!
=> update SCOTCH 6.0.5 easyconfigs in-place to 6.0.6 to fix wrong download URL

easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-5.1.2-intel-2017b-METIS-5.1.0.eb, easybuild/easyconfigs/t/Trilinos/Trilinos-12.12.1-intel-2017b-Python-2.7.14.eb
Depends upon https://github.com/easybuilders/easybuild-easyblocks/pull/1601 for correctly building against MKL.
=> {numlib}[intel/2017b] Trilinos v12.12.1

easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.5-10-foss-2016b.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.5-4-intel-2017a.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-14-foss-2017b.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-14-intel-2017b.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-15-GCCcore-6.4.0.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-26-foss-2018a.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0-Ghostscript-9.22-cairo-1.14.12.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-39-GCCcore-6.4.0-Ghostscript-9.23-cairo-1.14.12.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-8-intel-2017a-JasPer-1.900.1.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.8-11-GCCcore-7.3.0.eb
fix for #7274, based on the feedback in https://imagemagick.org/discourse-server/viewtopic.php?f=2&t=35150
There's little point in using https://www.imagemagick.org/download/releases/ as source URL, since source tarballs disappear there when new releases are available.
For versions prior to and including 7.0.8-5, original tarballs can be downloaded from https://launchpad.net/imagemagick/+download.
For newer version, we can use the tags from GitHub, see https://github.com/ImageMagick/ImageMagick/releases/
cc @sassy-crick
=> fix ImageMagick source URLs: use launchpad.net for old versions, switch to GitHub for 7.0.8-* onwards

easybuild/easyconfigs/d/DCMTK/DCMTK-3.6.3-GCCcore-7.3.0.eb, easybuild/easyconfigs/l/libiconv/libiconv-1.15-GCCcore-7.3.0.eb
This PR adds DCMTK v3.6.3 and adds libiconv-1.15 for GCCcore/7.3.0.
> DCMTK is a collection of libraries and applications implementing large parts the DICOM standard. It includes software for examining, constructing and converting DICOM image files, handling offline media, sending and receiving images over a network connection, as well as demonstrative image storage and worklist servers.
=> {bio}[GCCcore/7.3.0] Add DCMTK v3.6.3

easybuild/easyconfigs/e/expect/expect-5.45.4-GCCcore-7.3.0.eb
+recent expect. It's great tool anyway - but here I need it as build-dep of `texlive` which is part of dependency hell of cadabra.science. 
=> {lang}[GCCcore/7.3.0] expect v5.45.4

easybuild/easyconfigs/a/ATK/ATK-2.26.1-foss-2018b.eb
`ATK` is dependency of `GTK+3`.
As specified here, https://www.gtk.org/download/linux.php, `ATK 2.26` is the proper version for stable `GTK+ 3.22`.
=> {vis}[foss/2018b] ATK v2.26.1 (GTK+3)

easybuild/easyconfigs/o/OpenColorIO/OpenColorIO-1.1.0-foss-2018b.eb
(fix for problem reported by @JackPerdue in #7342)
I tested this in an environment where `python-devel` (and hence `Python.h`) is not available, which led to the same problem as reported in #7342.
Building of Python bindings is enabled by default, but they shouldn't be unless Python is included as a dependency.
=> disable building of OpenColorIO Python bindings since Python is not included as a dependency

easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-5.5.0.eb, easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-6.3.0.eb, easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-6.4.0.eb, easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-7.2.0.eb, easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-8.1.0.eb, easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-system.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-5.5.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.4.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.2.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-7.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.1.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-system.eb
Currently flex-2.6.4.eb has Bison-3.0.4.eb as a build dependency.  Bison-3.0.4.eb has M4-1.4.17.eb as a build dependency. 
However,  flex-2.6.4.eb also has M4-1.4.18.eb as a regular dependency.
Hence, the present PR proposes to bump the buiild dependency of flex-2.6.4.eb from  Bison-3.0.4 to  Bison-3.0.5. This would on the one hand remove the implicit dependency on M4-1.4.17.eb.
On the other hand M4-1.4.18 and Bison-3.0.4 do not compile on systems with the recent glibc 2.28.
As M4-1.4.18 is the most recent version of M4, a patch is required and has been proposed in PR https://github.com/easybuilders/easybuild-easyconfigs/pull/7384.
In contrast, Bison-3.0.5 compiles fine on glibc 2.28 and we do not require a patch but a change from  Bison-3.0.4 to Bison-3.0.5 would automatically also solve …
=> bump up build dependency of flex-2.6.4 from Bison-3.0.4 to Bison-3.0.5

easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.2.7-foss-2016a.eb, easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.2.7-intel-2016a.eb, easybuild/easyconfigs/p/Pango/Pango-1.40.1-foss-2016a.eb, easybuild/easyconfigs/p/Pango/Pango-1.40.1-intel-2016a.eb
These easyconfigs used to build fine on the systems at HPC-UGent I'm testing on, but now don't anymore most likely because some system packages got removed.
Introducing these header-only dependencies as build dependencies fixes the problem.
=> add missing build dependencies in old Harfbuzz/Pango easyconfigs (2016a generation)

easybuild/easyconfigs/i/icc/icc-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iimpi-2018a.eb, easybuild/easyconfigs/i/impi/impi-2018.1.163-iccifort-2018.1.163-GCC-6.4.0-2.28.eb
`intel2018a` is not so old and as I need it for #7425 anyway, let's do it in _correct_ way..
=> +download URL for intel2018a components

easybuild/easyconfigs/g/Guile/Guile-1.8.8-GCCcore-6.4.0.eb, easybuild/easyconfigs/g/Guile/Guile-1.8.8-GCCcore-7.3.0.eb
Replaces #7446. Corrects for uniform `configopts` to all `Guile-1.8.8` easyconfig files.
=> Use uniform configopts for Guile 1.8.8

easybuild/easyconfigs/x/X11/X11-20160819-GCCcore-5.4.0.eb, easybuild/easyconfigs/x/X11/X11-20170129-GCCcore-6.3.0.eb, easybuild/easyconfigs/x/X11/X11-20170314-GCCcore-6.3.0.eb, easybuild/easyconfigs/x/X11/X11-20171023-GCCcore-6.4.0.eb, easybuild/easyconfigs/x/X11/X11-20180131-GCCcore-6.4.0.eb, easybuild/easyconfigs/x/X11/X11-20180604-GCCcore-7.3.0.eb
Added `printproto` and `libXp` to the easyconfig files that were missing them.
Also added `xbitmaps` which is required by `motif`.
=> Add printproto, libXp and xbitmaps to X11

easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-add_ompi_datatype_attribute_to_release_ucp_datatype.patch, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-backported_patches.patch, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
Includes:
From 4763822a64c9002f24429aef95d87f6abfc45c06 Mon Sep 17 00:00:00 2001
From: Yossi Itigin <yosefe@mellanox.com>
Date: Tue, 9 Oct 2018 16:38:49 +0300
Subject: [PATCH] pml_ucx: add ompi datatype attribute to release ucp_datatype
From 40ac9e477165616ab98085e2d590dbbbe4874b9f Mon Sep 17 00:00:00 2001
From: Yossi Itigin <yosefe@mellanox.com>
Date: Wed, 10 Oct 2018 12:10:28 +0300
Subject: [PATCH] pml_ucx: fix return code from mca_pml_ucx_init()
=> {lib}[GCC/8.2.0-2.31.1,iccifort-2019.1.144-GCC-8.2.0-2.31.1] OpenMPI v3.1.3: Fix ucx memory leak and init

easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r241-intel-2018a.eb
Note that latest source is now on github.  Killed 'optarch' (which
defaults to True anyway?) and 'pic' (seems unnecessary).
=> {bio}[intel/2018a] update SOAPdenovo2-r241

test/easyconfigs/easyconfigs.py
tested via #7753, works as intended...
=> run various checks on easyconfigs that are touched in pull requests and involve Python packages

test/easyconfigs/easyconfigs.py
follow-up of checksums check for `R-*` that was temporarily disabled in #7791
=> restore checksums check for R-* easyconfigs 

easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.0-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-gcccuda-2018b.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.2-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1_fix-ib-query.patch
I ran into this error during the sanity check for TensorFlow 1.13.1 (cfr. #7785)
=> add patch for OpenMPI 3.1.x to fix ib-query 'Invalid argument' error

.travis.yml
We're frequently building up a backlog on Travis w.r.t. easyconfig tests, and it's becoming quite annoying...
I can't recall seeing just one of the tests fail, so I think it's safe to trim down the test configuration to just the following two (rather than the 7 current configurations we have)
* Python 2.6 w/ Lmod 6.6.3 & Tcl syntax
* Python 2.7 w/ Lmod 6.6.3 & Lua syntax
I don't see the value of testing with other module tools, since none of the tests we use actually involve the modules tool at all...
Besides, we already extensively test the different flavors of modules tool we support in the framework tests.
The easyconfigs tests are mostly about parsing the easyconfigs, and checking for patches, checksums, missing dependencies, conflicts, dependency variants, etc.
Since this is …
=> trim down test configuration: only test with Lmod 6.x with Tcl/Lua on Python 2.6/2.7

easybuild/easyconfigs/s/SIP/SIP-4.16.4-goolf-1.5.14-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-intel-2014b-Python-2.7.8.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-intel-2015a-Python-2.7.9.eb
For some reason unclear to me, parsing of these old `SIP` easyconfigs fails when using `eb` on top of Python 3.6, with:
```
easybuild.tools.build_log.EasyBuildError: "Failed to process easyconfig /home/travis/build/easybuilders/easybuild-easyconfigs/easybuild/easyconfigs/s/SIP/SIP-4.16.4-goolf-1.5.14-Python-2.7.9.eb: Parsing easyconfig file failed: name 'pyshortver' is not defined (line 27)"
```
I'm not sure why this happens, it seems to be some kind of scoping problem?
In any case, switching to using the `%(pyshortver)s template rather than relying on a self-constructed `pyshortver` local variable should fix the problem...
=> use %(pyshortver)s template in (old) SIP easyconfigs

.travis.yml
Turns out only *one* configuration is being tested after #7795 got merged, which was certainly not the intention...
=> fix Travis config to test with both Python 2.6 & 2.7

easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
Apparently the source tarball for `boot` 1.3-20 was updated in-place recently... 😡
=> add mlegp extension + fix checksum for boot extension in R 3.5.1 easyconfigs

.travis.yml
May trim this down again to only Python 3.5 (or 3.6?) later, but want to make sure now everything passes with the Python 3.x versions we plan to support with EasyBuild 4.x...
=> also run easyconfigs tests using Python 3.5 and 3.7

test/easyconfigs/easyconfigs.py
relevant for #7603 and various other current (& future) `PyTorch` PRs since we've put #7754 in place...
=> add PyTorch to whitelist for not having 'use_pip' enabled

easybuild/easyconfigs/s/StringTie/StringTie-1.3.5-foss-2018b.eb
cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/7736/files#r260261055
=> use correct buildopts + add missing zlib dependency in StringTie 1.3.5 easyconfig

easybuild/easyconfigs/c/CMake/CMake-3.12.1.eb, easybuild/easyconfigs/c/CMake/CMake-3.6.1.eb, easybuild/easyconfigs/c/CMake/CMake-3.9.1.eb, easybuild/easyconfigs/c/CMake/CMake-3.9.6.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.1.eb
These `CMake` easyconfigs using `dummy` toolchain are used as a build dependency for `Eigen` (which uses `cmake` for installation, but it's just a bunch of header files, so nothing gets compiled which means using the `dummy` toolchain is OK).
Requires `ncurses-devel` is stupid/annoying though, we can work around that by including `ncurses` a a *build* dependency and statically linking to it.
It's important that `ncurses` is a *build* dep, otherwise we may run into a version conflict on `ncurses` when these `CMake` easyconfigs are used to build something that has a runtime dependency on (another version of) `ncurses`...
=> replace ncurses-devel OS dependency in CMake easyconfigs using dummy toolchain with proper ncurses dependency

easybuild/easyconfigs/p/PyQt/PyQt-4.12.3-fosscuda-2018b-Python-2.7.15.eb
Parsing `PyQt-4.12.3-fosscuda-2018b-Python-2.7.15.eb` on top of Python 3 (using the `4.x` branches) fails with:
```
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/easybuild_framework-3.9.0.dev0-py3.6.egg/easybuild/framework/easyconfig/format/pyheaderconfigobj.py", line 187, in parse_pyheader
exec(pyheader, global_vars, local_vars)
File "<string>", line 60, in <module>
File "<string>", line 60, in <listcomp>
NameError: name 'pylibdir' is not defined
```
This issue is similar to the one we danced around with #7797.
The underlying issue is probably that list comprehensions have their own scope in Python 3, see also https://portingguide.readthedocs.io/en/latest/comprehensions.html .
Another way to fix this is to declare `pylibdir` as `global` in the easyconfig, but I'd …
=> don't use local variable 'pylibdir' in list comprehension in PyQt easyconfig, since that doesn't work in Python 3

easybuild/easyconfigs/v/VCF-kit/VCF-kit-0.1.6-intel-2018b-Python-2.7.15.eb
=> stick to intervaltree 2.1.0 as required extension for VCF-kit + fix stripping out of hardcoded versions for dependencies

easybuild/easyconfigs/p/Python/Python-3.7.2-GCCcore-8.2.0.eb
The `typing` Python package should not be included as an extension to Python 3.7.x, since it's a backport of the standard library `typing` module to Python versions older than 3.5...
Having it around causes problems like `AttributeError: type object 'Callable' has no attribute '_abc_registry'` (cfr. https://github.com/GNS3/gns3-server/issues/1414)
=> remove outdated 'typing' Python package from Python 3.7.2 easyconfig

easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.12.1-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.12.1_fix-prepend-PATH.patch
It turns out that symlinking leaves the door open to let `MetaBAT` add stuff in the `SAMtools` installation, cfr. discussion in https://github.com/easybuilders/easybuild-easyconfigs/pull/7746#issuecomment-473893319
One other thing I noticed is that during the installation an old version of `SAMtools` is being downloaded, rather than using the one included as a dependency...
=> fix problems in MetaBAT easyconfig

easybuild/easyconfigs/a/ANTs/ANTs-2.3.1-foss-2018b-Python-3.6.6.eb
Fix for an issue I ran into when playing around with `FMRIprep` (which depends on `ANTs`), the `antsBrainExtraction.sh` was reported missing...
Even though there's a dedicated `COPY_SCRIPT_FILES_TO_BIN_DIR` option for `cmake` (which doesn't seem to do anything), just copying seems to be the correct way, see also documentation at https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#copy-scripts .
=> also install ANTs scripts (and set $ANTSPATH as required by those scripts)

easybuild/easyconfigs/m/Mawk/Mawk-1.3.4-goolf-1.4.10-20150503.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20141206-GCC-4.9.2.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20171017-foss-2018a.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20171017-foss-2018b.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20171017-foss-2019a.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20171017-intel-2018a.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20171017-intel-2018b.eb, easybuild/easyconfigs/m/mawk/mawk-1.3.4-20171017-intel-2019a.eb
The "source_urls" for mawk changed from:
"ftp://ftp.invisible-island.net/mawk/"
To:
"ftp://ftp.invisible-island.net/mawk/"
but "ftp://ftp.invisible-island.net/mawk/" is a symlink,
so easybuild is unable to retreive the source archive.
cURL has problems with it too:
$ curl -v ftp://ftp.invisible-island.net/mawk/
* About to connect() to ftp.invisible-island.net port 21 (#0)
*   Trying 216.194.196.78...
* Connected to ftp.invisible-island.net (216.194.196.78) port 21 (#0)
< 220 ProFTPD Server (ftp.invisible-island.net) [216.194.196.78]
> USER anonymous
< 331 Anonymous login ok, send your complete email address as your password
> PASS ftp@example.com
< 230 Anonymous access granted, restrictions apply
> PWD
< 257 "/" is the current directory
* Entry path is '/'
> CWD mawk
* ftp_perform ends …
=> Fix "source_urls" for mawk.

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.12.0-fosscuda-2018b-Python-2.7.15.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.12.0-fosscuda-2018b-Python-3.6.6.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.12.0_remove_usrbin_from_linker_bin_path_flag.patch
Added extra patch to remove -B/usr/bin from linker_bin_path_flag in 
tensorflow-1.12.0/third_party/gpus/cuda_configure.bzl
This prevents the wrong linker from being used.
=> extra patch for TensorFlow 1.12.0 to remove -B/usr/bin from linker_bin_path_flag in cuda_configure.bzl

easybuild/easyconfigs/g/GATE/GATE-8.1.p01-foss-2018b-Python-2.7.15.eb
These were added in (some of) the `GATE` 8.0 easyconfigs, and are also used in the GATE 8.2 easyconfig added in #7999, so just enabling it here too for consistency sake...
=> add missing configopts in GATE 8.1 easyconfig to enable Davis feature

easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.0-GCC-5.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-GCC-6.2.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-iccifort-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27-opa.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-gcccuda-2017.01.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.2-iccifort-2017.1.132-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.0-GCC-6.3.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017.02.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-gcccuda-2017b.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.1-iccifort-2017.4.196-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-gcccuda-2018a.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.3-iccifort-2018.2.199-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.0-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-gcccuda-2018b.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.1-iccifort-2018.3.222-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.2-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.3-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1-hpcx.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.0-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.1-GCC-8.3.0-2.32.eb
fixes `OpenMPI` part of #7943 (except for OpenMPI 1.x easyconfigs)
cc @patbel-pwr
=> use https:// in homepage & source_urls for recent OpenMPI 2.x, 3.x & 4.x easyconfigs

easybuild/easyconfigs/b/bokeh/bokeh-1.0.4-intel-2018b-Python-3.6.6.eb, easybuild/easyconfigs/d/dask/dask-1.0.0-foss-2018b-Python-3.6.6.eb, easybuild/easyconfigs/d/dask/dask-1.0.0-intel-2018b-Python-3.6.6.eb
Parts of dask need bokeh, so added it as a dep. Also added `dask-jobqueue` extension to dask.
And added foss version of it all as that seems to work more stable.
=> add missing bokeh dependency for dask 1.0.0 (+ add dask-jobqueue) + add easyconfig for dask 1.0.0 with foss/2018b

test/easyconfigs/easyconfigs.py
When `multi_deps` is involved, we must use the `.builddependencies()` method rather than accessing the `builddependencies` easyconfig parameter directly, to avoid hitting a list of lists of build dependencies, cfr. https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/framework/easyconfig/easyconfig.py#L888
This will fix the failing test in #7929 (cc @Micket)
=> fix checking of binutils build dep in easyconfig tests

easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb, easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb, easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb, test/easyconfigs/easyconfigs.py
wrapper PR for #8052 and #8053, since both need to combined in order to submit a working test report (with `eb --fetch`) since `R-3.5.0-iomkl-2018a-X11-20180131.eb` is touched in both...
=> fix checksums for boot/nlme extensions in R easyconfigs

easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb
source tarball for https://cran.r-project.org/src/contrib/Archive/nlme/ was replaced in-place, but no real code changes:
```
$ diff -ru nlme.bk nlme
diff -ru nlme.bk/DESCRIPTION nlme/DESCRIPTION
--- nlme.bk/DESCRIPTION	2018-04-07 14:20:47.000000000 +0200
+++ nlme/DESCRIPTION	2018-04-07 14:20:28.000000000 +0200
@@ -33,4 +33,4 @@
R-core [aut, cre]
Maintainer: R-core <R-core@R-project.org>
Repository: CRAN
-Date/Publication: 2018-04-07 12:20:47 UTC
+Date/Publication: 2018-04-07 12:20:28 UTC
diff -ru nlme.bk/MD5 nlme/MD5
--- nlme.bk/MD5	2018-04-07 14:20:47.000000000 +0200
+++ nlme/MD5	2018-04-07 14:20:28.000000000 +0200
@@ -1,5 +1,5 @@
7d7f0fc1c5268d14ec1ff68056134762 *ChangeLog
-0a665589610bdc521aab8358ba2a96f9 *DESCRIPTION
+e5cbc2946848be223376e91ba52f513c *DESCRIPTION …
```
=> fix checksum for nlme in R 3.5.* easyconfigs

easybuild/easyconfigs/g/GTK+/GTK+-3.24.8-GCCcore-8.2.0.eb, easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-GCCcore-8.2.0.eb, easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-post-install-bin.patch, easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-2.4.0-GCCcore-8.2.0.eb, easybuild/easyconfigs/l/libepoxy/libepoxy-1.5.3-GCCcore-8.2.0.eb, easybuild/easyconfigs/p/Pango/Pango-1.43.0-GCCcore-8.2.0.eb
depends on ~~#8079~~ ~~#8080~~ ~~#7947~~
=> {vis}[GCCcore/8.2.0] GTK+ v3.24.8, Gdk-Pixbuf v2.38.1, libepoxy v1.5.3, Pango v1.43.0, HarfBuzz v2.4.0

easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb
https://pypi.org/project/singledispatch is a backport of stuff in Python 3.4 to Python 2.x (and older Python 3.x versions)
It is required for installing `numba` with Python 2.x, but it shouldn't be installed when using Python >= 3.4.
This complicates installing `numba` for both Python 2.7.15 and 3.7.2 via `multi_deps`, especially since the "native" equivalent in `singledispatch` is provided via `functools.singledispatch` (so you can't just check with `import singledispatch` whether it's available already and the installation of it can be skipped)
=> add singledispatch extension to Python 2.7.15 easyconfig using GCCcore/8.2.0

easybuild/easyconfigs/p/PCMSolver/PCMSolver-1.2.3-foss-2018b-Python-3.6.6.eb
This is not working yet and I need some help to fix it. When I try to install PCMSolver with this config, I get the following error:
```
== 2019-02-28 11:15:40,570 build_log.py:162 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " cmake -DCMAKE_INSTALL_PREFIX=/data/gent/vo/000/gvo00003/vsc40019/apps_private/victini/software/PCMSolver/1.2.3-foss-2018b-Python-3.6.6 -DCMAKE_C_COMPILER='gcc' -DCMAKE_Fortran_FLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno' -DCMAKE_CXX_FLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_C_FLAGS='-O2 -ftree-vectorize -march=native -fno-math-errno' -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DEIGEN3_ROOT=$EBROOTEIGEN -DCMAKE_CXX_FLAGS="$CXXFLAGS …
```
=> {chem}[foss-2018b] PCMSolver-1.2.3 w/ Python 3.6.6

test/easyconfigs/easyconfigs.py
depends on https://github.com/easybuilders/easybuild-easyblocks/pull/1709
required for #8133
=> allow use of 'use_pip = False' in easyconfigs if pip doesn't work

easybuild/easyconfigs/l/libcerf/libcerf-1.7-GCCcore-7.3.0.eb
checksum is also different because source tarball at new location is not exactly the same:
```
$ diff -ru libcerf-1.7 libcerf-v1.7
Only in libcerf-v1.7: .gitignore
Only in libcerf-1.7/man: pod2htmd.tmp
Only in libcerf-1.7/man: podstyle.css
```
=> fix source URLs for libcerf 1.7

.travis.yml
I would like to temporarily run the easyconfigs test suite with only Python 2.6 + Lmod, to avoid that Travis becomes a bottleneck during the merge sprint we have planned Wed May 8th 2019.
@migueldiascosta Please merge this when you start your day, since you'll be the first... ;)
=> temporarily only test with Python 2.6 + Lmod

easybuild/easyconfigs/p/Pysam/Pysam-0.12.0.1-intel-2017a-Python-2.7.13.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.12.0.1-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.12.0.1-intel-2017b-Python-3.6.3.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.13-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.13.0-intel-2017b-Python-3.6.3.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.14-intel-2018a-Python-3.6.4.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-foss-2018a-Python-3.6.4.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-intel-2018a-Python-2.7.14.eb, easybuild/easyconfigs/p/Pysam/Pysam-0.14.1-intel-2018a-Python-3.6.4.eb
From version 0.12 `XZ` is required as dependency. Otherwise the following error may appear:
```
htslib/hts_os.c(30): catastrophic error: cannot open source file "os/rand.c"
#include "os/rand.c"
```
=> Pysam - Add XZ dependency for versions > 0.12

easybuild/easyconfigs/m/motif/motif-2.3.7-intel-2017a.eb, easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2018a.eb, easybuild/easyconfigs/m/motif/motif-2.3.8-foss-2018b.eb, easybuild/easyconfigs/m/motif/motif-2.3.8-intel-2017b.eb, easybuild/easyconfigs/m/motif/motif-2.3.8-intel-2018a.eb
The `xbitmaps` dependency is no longer needed since it is now included in the X11 bundle (see ~~#7494~~)
=> Remove xbitmaps dependency from motif

easybuild/easyconfigs/f/FlexiDot/FlexiDot-1.06-foss-2018b-Python-2.7.15.eb
& avoid use of funky character in 'sed' command which breaks parsing of the easyconfig file
follow-up for #8228
=> add missing ptyprocess extension in FlexiDot easyconfig

easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6-foss-2018b.eb, easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6-intel-2018a.eb, easybuild/easyconfigs/l/LUSCUS/LUSCUS-0.8.6_config-dir.patch
I couldn't find another way than using a patch file, the `$HOME/.luscus` is hardwired, no way to override it using an option to `cmake`...
=> prevent LUSCUS from installing it's configuration into $HOME/.luscus

setup.py
Old style exceptions are syntax errors in Python 3 but new style exceptions work as expected in both Python 2 and Python 3.
=> Old style exceptions are syntax errors in Python 3
