easybuild/easyconfigs/i/IMB/IMB-4.0.1-goolf-1.5.14-no-OFED.eb, easybuild/easyconfigs/i/IMB/IMB-4.0.1-goolf-1.6.10.eb, easybuild/easyconfigs/i/IMB/IMB-4.0.1-intel-2015a.eb
=> add easyconfigs for IMB with different toolchains

easybuild/easyconfigs/h/horton/horton-1.0.2-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/h/horton/horton-1.0.2-ictce-4.1.13-Python-2.7.3.eb, easybuild/easyconfigs/h/horton/horton-1.1.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/h/horton/horton-1.1.0-ictce-4.1.13-Python-2.7.3.eb, easybuild/easyconfigs/h/horton/horton-1.2.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/h/horton/horton-1.2.0-ictce-4.1.13-Python-2.7.3.eb, easybuild/easyconfigs/l/Libint/Libint-2.0.3-goolf-1.4.10.eb, easybuild/easyconfigs/l/Libint/Libint-2.0.3-ictce-4.1.13.eb, easybuild/easyconfigs/l/Libint/Libint-2.0.3-ictce-5.5.0.eb, easybuild/easyconfigs/l/Libint/Libint-2.0.3-intel-2014b.eb
This renaming should be discussed. There is a corresponding easyblock PR. https://github.com/hpcugent/easybuild-easyblocks/pull/489
=> libint2 renamed to Libint

easybuild/easyconfigs/l/Libint/Libint-1.1.4-intel-2014b.eb
=> style fixes in Libint v1.1.4 intel/2014b easyconfig

easybuild/easyconfigs/b/Bison/Bison-3.0.2-intel-2015a.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-ifort-compiler-bug-fix.patch, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-intel-2015a.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2015a.eb, easybuild/easyconfigs/l/Libint/Libint-1.1.4-intel-2015a.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-intel-2015a.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2015a.eb
=> add easyconfigs for CP2K v2.6.0 + deps with intel/2015a

easybuild/easyconfigs/c/Chapel/Chapel-1.10.0-goolf-1.4.10.eb, easybuild/easyconfigs/c/Chapel/Chapel-1.10.0-goolf-1.6.10.eb, easybuild/easyconfigs/c/Chapel/Chapel-1.9.0-goolf-1.4.10.eb, easybuild/easyconfigs/c/Chapel/Chapel-1.9.0-goolf-1.6.10.eb, easybuild/easyconfigs/g/Greenlet/Greenlet-0.4.2-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/g/gnuplot/gnuplot-4.6.6-intel-2014b.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-gpsolf-2014.12.eb, easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.2-linux-x86_64-static.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-intel-2014b.eb, easybuild/easyconfigs/n/netaddr/netaddr-0.7.10-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/n/netifaces/netifaces-0.8-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-goolf-1.4.10.eb, easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-ictce-4.1.13.eb, easybuild/easyconfigs/s/SAMtools/SAMtools-1.1-foss-2014b.eb, easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r240-goolf-1.4.10.eb, easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r240-ictce-5.3.0.eb, easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r240-ictce-5.5.0.eb
Signed-off-by: Fotis Georgatos <fotis@cern.ch>
=> add moduleclass, wherever it was missing; fix typos

easybuild/easyconfigs/g/GSL/GSL-1.15-goolf-1.5.14.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-goolf-1.4.10.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-goolf-1.5.14.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-goolfc-1.3.12.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-goolfc-2.6.10.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-ictce-5.3.0.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-ictce-5.4.0.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-ictce-6.2.5.eb
New easyconfigs for GSL with different toolchains.
=> Supplememtary easyconfigs for GSL

easybuild/easyconfigs/p/Perl/Perl-5.20.1-intel-2015a-bare.eb
cc @hpcleuven, @gjbex, @sbecuwe, @hajgato
=> [intel/2015a] Perl v5.20.1 (bare) (ready)

easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.11.337.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/538
@wpoely86: please review?
=> add easyconfig for FDTD_Solutions 8.11.337

easybuild/easyconfigs/f/FoldX/FoldX-2.5.2.eb, easybuild/easyconfigs/f/FoldX/FoldX-3.0-beta5.1.eb, easybuild/easyconfigs/f/FoldX/FoldX-3.0-beta6.eb
thanks to @gjbex for pointing this out
=> fix double http:// in FoldX easyconfigs

easybuild/easyconfigs/b/Bison/Bison-2.7-intel-2014b.eb, easybuild/easyconfigs/c/CP2K/CP2K-20131211-intel-2014b.eb, easybuild/easyconfigs/l/libxc/libxc-2.0.1-intel-2014b.eb
@wpoely86: please review/test?
=> {chem}[intel/2014b] CP2K 20131211 (OK)

easybuild/easyconfigs/l/libtool/libtool-2.4.2-GCC-4.9.2.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.10-GCC-4.9.2.eb
This should work to get foss-2015a back working.
=> {tools}[foss/2015a,GCC/4.9.2] numactl 2.0.10 (OK)

easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2015a.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-foss-2015a.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-foss-2015a-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-foss-2015a.eb, easybuild/easyconfigs/s/Szip/Szip-2.1-foss-2015a.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-foss-2015a.eb
Easyconfigs (foss 2015a) for:
* zlib
* bzip2
* Szip
* ncurses
* libreadline
* Python-bare
* Python
=> [foss/2015a] Python 2.7.9 + deps (OK)

easybuild/easyconfigs/g/GLib/GLib-2.40.0-goolf-1.5.14.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.2-goolf-1.5.14.eb, easybuild/easyconfigs/l/libffi/libffi-3.1-goolf-1.5.14.eb, easybuild/easyconfigs/l/libffi/libffi-3.1-intel-2014b.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.6-goolf-1.5.14.eb
depends on ~~#1317~~ for Python 2.7.9 build dep
=> {devel}[goolf/1.5.14] Qt 4.8.6 + deps (REVIEW)

easybuild/easyconfigs/g/GDB/GDB-7.8.2-GCC-4.9.2.eb
Add easyconfig for latest GDB version.
=> {debugger}[GCC/4.9.2] GDB 7.8.2 (OK)

easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.0.2-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.1.1-ictce-5.5.0.eb
Explicit add linking to boost_system
Fix for #1333
=> {bio} Fix linkage error for Cufflinks 2.0.2 (REVIEW)

easybuild/easyconfigs/s/SQLite/SQLite-3.8.8.1-intel-2015a.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.3-intel-2015a.eb
Latest version of SQLite, Tcl.
=> {devel}[intel/2015a] SQLite + deps (REVIEW)

easybuild/easyconfigs/j/Java/Java-1.8.0_31.eb
Added most recent Java version 1.8u33.
=> {lang}[dummy] Oracle Java (REVIEW)

easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.9.1-GCC-4.9.2.eb, easybuild/easyconfigs/e/Emacs/Emacs-24.4-GCC-4.9.2.eb
=> {tools}[GCC/4.9.2] Emacs and Doxygen (REVIEW)

easybuild/easyconfigs/b/Boost/Boost-1.57.0-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/e/expat/expat-2.1.0-foss-2015a.eb, easybuild/easyconfigs/g/GMP/GMP-5.1.3-foss-2015a.eb, easybuild/easyconfigs/g/GMP/GMP-6.0.0a-foss-2015a.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-foss-2015a.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-foss-2015a.eb, easybuild/easyconfigs/m/MPC/MPC-1.0.2-foss-2015a.eb, easybuild/easyconfigs/m/MPFR/MPFR-3.1.2-foss-2015a.eb
For foss-2015a:
* Boost
* GSL
* GMP (both latest 5.x and 6.x)
* MPFR
* MPC
* expat
* libxml2
=> {mix}[foss/2015a] smattering of libraries (REVIEW)

easybuild/easyconfigs/c/cURL/cURL-7.40.0-foss-2015a.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-foss-2015a.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-intel-2015a.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.28-foss-2015a.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.28-intel-2015a.eb, easybuild/easyconfigs/x/XQilla/XQilla-2.3.0-foss-2015a.eb, easybuild/easyconfigs/x/XQilla/XQilla-2.3.0-intel-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.1-foss-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.1-intel-2015a.eb
* libxml2
* libxslt
* Xerces C++
* XQilla
* cURL (foss)
=> {lib}[intel/2015a,foss/2015a] XML related libaries + deps (REVIEW)

easybuild/easyconfigs/p/Python/Python-2.7.9-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-goolf-1.5.14.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-intel-2015a.eb
inspired by the changes to the Python 2.7.9 easyconfig in #1368 by @ehiggs
=> {lang}[intel/foss/goolf] Python 2.7.9 inetfaces/inetaddr pkgs (REVIEW)

easybuild/easyconfigs/c/cutadapt/cutadapt-1.4.1-foss-2014b-Python-2.7.8.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.5-foss-2014b-Python-2.7.8.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.6-foss-2014b-Python-2.7.8.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.7-foss-2014b-Python-2.7.8.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.7.1-foss-2014b-Python-2.7.8.eb
=> {bio} [foos/2014b] cutadapt (REVIEW)  

easybuild/easyconfigs/h/HPL/HPL-2.1-iomkl-2015.02.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-iccifort-2015.2.164-GCC-4.9.2.eb, easybuild/easyconfigs/i/imkl/imkl-11.2.2.164-iompi-2015.02.eb, easybuild/easyconfigs/i/iomkl/iomkl-2015.02.eb, easybuild/easyconfigs/i/iompi/iompi-2015.02.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.2.164-GCC-4.9.2.eb
this one relies in this other PR for icc and ifort easyconfigs 
https://github.com/hpcugent/easybuild-easyconfigs/pull/1393
=> {toolchain} [iomkl/2015.02] (REVIEW)

easybuild/easyconfigs/w/worker/worker-1.5.1-intel-2015a.eb
@gjbex: please review, since you're the expert on this one?
=> {tools}[dummy] worker v1.5.1 (REVIEW)

easybuild/easyconfigs/h/Hoard/Hoard-3.10-intel-2015a.eb, easybuild/easyconfigs/h/Hoard/Hoard-3.x_CXX.patch
=> {lib}[intel/2015a] Hoard 3.10 (REVIEW)

easybuild/easyconfigs/j/jemalloc/jemalloc-3.6.0-intel-2015a.eb
=> {lib}[intel/2015a] jemalloc 3.6.0 (REVIEW)

easybuild/easyconfigs/c/CMake/CMake-3.1.3.eb, easybuild/easyconfigs/h/Hadoop/Hadoop-2.4.0-seagate-722af1-native.eb, easybuild/easyconfigs/j/Java/Java-1.7.0_76.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9.eb, easybuild/easyconfigs/p/protobuf/protobuf-2.5.0.eb
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/563
=> {tools}[dummy] Hadoop w/ native libs (REVIEW)

easybuild/easyconfigs/s/SAMtools/SAMtools-1.2-foss-2015a.eb, easybuild/easyconfigs/s/SAMtools/SAMtools-1.2-goolf-1.4.10.eb
=> {bio}[foss-2015a,goolf-1.4.10] Samtools 1.2 update (REVIEW)

test/easyconfigs/easyconfigs.py
This fixes a false negative for conflict detection that occurred in https://github.com/hpcugent/easybuild-easyconfigs/pull/1431, because build dependencies weren't being handled correctly (too aggressive filtering).
```
$ python -m test.easyconfigs.suite
Couldn't import dot_parser, loading of dot files will not be possible.
Running tests...
.................................................................................................................................................................................................................................................................................................................................................................................................. …
```
=> fix conflict detection by considering build deps separately from runtime deps

easybuild/easyconfigs/b/Bison/Bison-2.7-iccifort-2011.13.367.eb, easybuild/easyconfigs/m/M4/M4-1.4.16-iccifort-2011.13.367.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-iccifort-2011.13.367.eb
@wpoely86: please review, fixes a screwup w.r.t. toolchains/deps in an MVAPICH2 easyconfig
=> fix Bison build dep in MVAPICH2 easyconfig

easybuild/easyconfigs/h/HPCBIOS_Bioinfo/HPCBIOS_Bioinfo-20130829-goolf-1.4.10.eb, easybuild/easyconfigs/h/HPCBIOS_Bioinfo/HPCBIOS_Bioinfo-20130829-ictce-5.3.0.eb, easybuild/easyconfigs/h/HPCBIOS_Debuggers/HPCBIOS_Debuggers-20130829-goolf-1.4.10.eb, easybuild/easyconfigs/h/HPCBIOS_LifeSciences/HPCBIOS_LifeSciences-20130829-goolf-1.4.10.eb, easybuild/easyconfigs/h/HPCBIOS_LifeSciences/HPCBIOS_LifeSciences-20130829-ictce-5.3.0.eb, easybuild/easyconfigs/h/HPCBIOS_Math/HPCBIOS_Math-20130829-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/h/HPCBIOS_Math/HPCBIOS_Math-20130829-goolf-1.4.10.eb, easybuild/easyconfigs/h/HPCBIOS_Math/HPCBIOS_Math-20130829-ictce-5.3.0.eb, easybuild/easyconfigs/h/HPCBIOS_Profilers/HPCBIOS_Profilers-20130829-goolf-1.4.10.eb
Hi,
this is just what $subject says.
As discussed elsewhere, HPCBIOS_Debuggers is a little bit more involved story, however it's future work.
Signed-off-by: Fotis Georgatos <fotis@cern.ch>
=> {toolchains} [goolf, goalf, ictce] convert HPCBIOS toolchains to bundles (REVIEW)

RELEASE_NOTES, setup.py
just a sync with easyblocks, due to hpcugent/easybuild-easyblocks#573
=> bump version to v1.16.2.0, update release notes

easybuild/easyconfigs/p/Python/Python-2.7.8-goolf-1.5.14.eb, easybuild/easyconfigs/u/UFL/UFL-1.5.0-goolf-1.5.14-Python-2.7.8.eb
wrapper PR around @Bart-CER's #1365
=> {cae}[goolf/1.5.14] UFL 1.5.0 (REVIEW)

easybuild/easyconfigs/h/Hoard/Hoard-3.10-intel-2015a.eb, easybuild/easyconfigs/j/jemalloc/jemalloc-3.6.0-intel-2015a.eb
@JensTimmerman: please review?
=> include setting of LD_PRELOAD in Haord/jemalloc easyconfigs

easybuild/easyconfigs/f/FLUENT/FLUENT-14.5.eb, easybuild/easyconfigs/f/FLUENT/FLUENT-15.0.7.eb, easybuild/easyconfigs/f/FLUENT/FLUENT-16.0.eb
=> add easyconfig for FLUENT 16.0

easybuild/easyconfigs/c/Chapel/Chapel-1.9.0-goolf-1.5.14.eb
Chapel-1.9.0 compiled with goolf-1.5.14
=> Chapel-1.9.0

easybuild/easyconfigs/m/Minimac3/Minimac3-1.0.10-foss-2015a.eb, easybuild/easyconfigs/m/Minimac3/Minimac3-1.0.10-intel-2015a.eb
=> {bio}[foss/2015a, intel/2015a] Minimac 3 (REVIEW)

easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.7.3-GCC-4.8.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.7.3-gcccuda-2.6.10.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.1-GCC-4.8.3.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-iccifort-2013_sp1.4.211-no-OFED.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.3-iccifort-2013_sp1.4.211.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.8.4.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.1.133-GCC-4.9.2.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.4-iccifort-2015.2.164-GCC-4.9.2.eb
=> use --with-verbs rather than the deprecated --with-openib for OpenMPI

easybuild/easyconfigs/a/ABAQUS/ABAQUS-6.12.1-linux-x86_64.eb, easybuild/easyconfigs/a/ABAQUS/ABAQUS-6.13.5-linux-x86_64.eb, easybuild/easyconfigs/a/ABAQUS/ABAQUS-6.14.1-linux-x86_64.eb
=> add easyconfig for ABAQUS v6.13.5

easybuild/easyconfigs/a/AFNI/AFNI-linux_openmp_64-intel-2015a-20141023.eb, easybuild/easyconfigs/p/PyQt/PyQt-4.11.3-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.4-intel-2015a-Python-2.7.9.eb
=> {bio}[intel/2015a] AFNI, PyQt and SIP (REVIEW)

easybuild/easyconfigs/r/RSEQtools/RSEQtools-0.6-goolf-1.4.10.eb
cfr. https://github.com/hpcugent/easybuild-framework/pull/1060 and https://github.com/hpcugent/easybuild-easyblocks/pull/590
=> replace use of $root with %(installdir)s

easybuild/easyconfigs/w/WIEN2k/WIEN2k-14.1-intel-2014b.eb, easybuild/easyconfigs/w/WIEN2k/WIEN2k-14.1-intel-2015a.eb, easybuild/easyconfigs/w/WIEN2k/WIEN2k-14.1_fix-tetra.patch, easybuild/easyconfigs/w/WIEN2k/WIEN2k-14.1_fix-x_lapw.patch, easybuild/easyconfigs/w/WIEN2k/WIEN2k-14.1_lapw5-main-accuracy-fix.patch, easybuild/easyconfigs/w/WIEN2k/WIEN2k-14.2-intel-2015a.eb
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/486
=> add easyconfig for WIEN2k v14.1 with intel/2014b

easybuild/easyconfigs/p/pymatgen/pymatgen-3.0.13-intel-2015a-Python-2.7.9-gmatteo-20150407.eb, easybuild/easyconfigs/p/pymatgen/pymatgen-3.0.13-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/spglib/spglib-1.7.3-intel-2015a.eb
=> {chem}[intel/2015a] pymatgen 3.0.13 + spglib 1.7.3 (REVIEW)

easybuild/easyconfigs/f/FSL/FSL-5.0.8-intel-2015a.eb, easybuild/easyconfigs/f/FSL/FSL-5.0.8_ictce-wd803.patch, easybuild/easyconfigs/f/FSL/FSL-5.0.8_makefile_fixes.patch, easybuild/easyconfigs/f/fixesproto/fixesproto-5.0-intel-2015a.eb, easybuild/easyconfigs/f/freeglut/freeglut-2.8.1-intel-2015a.eb, easybuild/easyconfigs/i/inputproto/inputproto-2.3-intel-2015a.eb, easybuild/easyconfigs/l/libXfixes/libXfixes-5.0.1-intel-2015a.eb, easybuild/easyconfigs/l/libXi/libXi-1.7.4-intel-2015a.eb
=> {bio}[intel/2015a] FSL 5.0.8 + deps (REVIEW)

easybuild/easyconfigs/r/ROOT/ROOT-v5.34.01-ictce-4.0.6.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.01-intel-2015a.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.18-ictce-5.5.0.eb
cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/576
=> stop relying on $MKLROOT in ROOT easyconfigs

easybuild/easyconfigs/s/Spark/Spark-1.3.0.eb
This supports Spark 1.3 and is prebuilt for Hadoop 2.3.
=> Support Spark 1.3.0

easybuild/easyconfigs/c/CMake/CMake-3.2.1-intel-2015a.eb, easybuild/easyconfigs/f/FIAT/FIAT-1.5.0-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/h/Hypre/Hypre-2.10.0b-intel-2015a.eb, easybuild/easyconfigs/m/METIS/METIS-5.1.0-intel-2015a.eb, easybuild/easyconfigs/n/numpy/numpy-1.8.1-mkl.patch, easybuild/easyconfigs/n/numpy/numpy-1.8.2-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/p/PETSc/PETSc-3.5.3-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SLEPc/SLEPc-3.5.3-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/sympy/sympy-0.7.6-intel-2015a-Python-2.7.9.eb
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/593
=> {numlib}[intel/2015a] PETSc & SLEPc 3.5.3 (REVIEW)

easybuild/easyconfigs/h/HPL/HPL-2.1-intel-2014.06.eb, easybuild/easyconfigs/i/iimpi/iimpi-5.5.0-GCC-4.8.3.eb, easybuild/easyconfigs/i/imkl/imkl-11.0.5.192-iimpi-5.5.0-GCC-4.8.3.eb, easybuild/easyconfigs/i/impi/impi-4.1.1.036-iccifort-2013.5.192-GCC-4.8.3.eb, easybuild/easyconfigs/i/intel/intel-2014.06.eb
Hope in-time for 2.1 release :-)
=> Toolchain intel-2014.06 including HPL-2.1

easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.4.0-goolf-1.7.20.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.16-goolf-1.7.20.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-goolf-1.7.20.eb, easybuild/easyconfigs/n/NASM/NASM-2.11.06-goolf-1.7.20.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-goolf-1.7.20.eb, easybuild/easyconfigs/r/R/R-3.2.0-goolf-1.7.20-bare.eb
requires https://github.com/hpcugent/easybuild-easyblocks/issues/602
=> {bio} [goolf-1.7.20]  R-3.2.0-bare (REVIEW)

easybuild/easyconfigs/c/Cube/Cube-4.2-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/c/Cube/Cube-4.2_fix-with-qt-check.patch, easybuild/easyconfigs/c/Cube/Cube-4.3-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.0-gompi-1.4.12-no-OFED.eb
This change will make it possible to use `--try-software-version` and `--filter-deps=Qt` for Cube.
Requires https://github.com/hpcugent/easybuild-easyblocks/pull/552
=> Adjusted Cube download URL and tweaked build

easybuild/easyconfigs/h/HPL/HPL-2.1-ictce-7.3.5.eb, easybuild/easyconfigs/i/icc/icc-2015.3.187.eb, easybuild/easyconfigs/i/iccifort/iccifort-2015.3.187.eb, easybuild/easyconfigs/i/ictce/ictce-7.3.5.eb, easybuild/easyconfigs/i/ifort/ifort-2015.3.187.eb, easybuild/easyconfigs/i/iimpi/iimpi-7.3.5.eb, easybuild/easyconfigs/i/imkl/imkl-11.2.3.187-iimpi-7.3.5.eb, easybuild/easyconfigs/i/impi/impi-5.0.3.048-iccifort-2015.3.187.eb
Latest ictce toolchain as of today.
Tested on Debian 7.
=> {toolchain}[dummy] ictce 7.3.5 (REVIEW)

easybuild/easyconfigs/g/GROMACS/GROMACS-5.0.4-intel-2015a-hybrid.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-5.0.4-intel-2015a-mt.eb
depends on https://github.com/hpcugent/easybuild-easyblocks/pull/513
=> {bio}[intel/2015a] GROMACS 5.0.4 (mt, hybrid) (REVIEW)

easybuild/easyconfigs/s/SaguaroGW/SaguaroGW-20150315-intel-2015a.eb, easybuild/easyconfigs/s/SaguaroGW/SaguaroGW_icpc-drop-const.patch
@pescobar or @wpoely86: please review?
=> {bio}[intel/2015a] SaguaroGW (REVIEW)

easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.1m-intel-2015a.eb, easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.1m_fix-parallel.patch, easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.1m_icc-fixes.patch
=> {system}[intel/2015a] OpenSSL 1.0.1m (REVIEW)

easybuild/easyconfigs/p/Python/Python-3.4.1-intel-2015a.eb
bumped python 3.4.1 too intel 2015a toolchain.
=> {lang} [intel-2015a] python 3.4.1

easybuild/easyconfigs/g/GROMACS/GROMACS-4.6.7-CrayGNU-5.1.29-mpi.eb
=> enable usempi in GROMACS Cray easyconfig, the easyblock enables MPI support on it

easybuild/easyconfigs/b/Bison/Bison-3.0.2-CrayGNU-5.2.40.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-5.2.40.eb, easybuild/easyconfigs/c/CMake/CMake-3.2.2-CrayGNU-5.2.40.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-5.2.40.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-CrayGNU-5.2.40.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-4.6.7-CrayGNU-5.2.40-mpi.eb, easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-CrayGNU-5.2.40.eb, easybuild/easyconfigs/l/Libint/Libint-1.1.4-CrayGNU-5.2.40.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-CrayGNU-5.2.40.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-CrayGNU-5.2.40.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-CrayGNU-5.2.40.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-CrayGNU-5.2.40.eb, easybuild/easyconfigs/n/numpy/numpy-1.9.2-CrayGNU-5.2.40-Python-2.7.9.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-5.2.40-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-5.2.40.eb, easybuild/easyconfigs/s/Szip/Szip-2.1-CrayGNU-5.2.40.eb, easybuild/easyconfigs/s/scipy/scipy-0.15.1-CrayGNU-5.2.40-Python-2.7.9.eb, easybuild/easyconfigs/t/tcsh/tcsh-6.18.01-CrayGNU-5.2.40.eb, easybuild/easyconfigs/w/WRF/WRF-3.6.1-CrayGNU-5.2.40-dmpar.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-CrayGNU-5.2.40.eb
@pforai: please review?
only toolchain was changed, nothing else
test report is coming up
=> add easyconfigs using CrayGNU/5.2.40 toolchain

easybuild/easyconfigs/b/Bison/Bison-3.0.2-CrayGNU-5.2.25.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-5.2.25.eb, easybuild/easyconfigs/c/CMake/CMake-3.2.2-CrayGNU-5.2.25.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-5.2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-CrayGNU-5.2.25.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-4.6.7-CrayGNU-5.2.25-mpi.eb, easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-CrayGNU-5.2.25.eb, easybuild/easyconfigs/l/Libint/Libint-1.1.4-CrayGNU-5.2.25.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-CrayGNU-5.2.25.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-CrayGNU-5.2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-CrayGNU-5.2.25.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-CrayGNU-5.2.25.eb, easybuild/easyconfigs/n/numpy/numpy-1.9.2-CrayGNU-5.2.25-Python-2.7.9.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-5.2.25-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-5.2.25.eb, easybuild/easyconfigs/s/Szip/Szip-2.1-CrayGNU-5.2.25.eb, easybuild/easyconfigs/s/scipy/scipy-0.15.1-CrayGNU-5.2.25-Python-2.7.9.eb, easybuild/easyconfigs/t/tcsh/tcsh-6.18.01-CrayGNU-5.2.25.eb, easybuild/easyconfigs/w/WRF/WRF-3.6.1-CrayGNU-5.2.25-dmpar.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-CrayGNU-5.2.25.eb
=> add easyconfigs using CrayGNU/5.2.25 toolchain

easybuild/easyconfigs/r/R/R-3.1.3-foss-2015a.eb, easybuild/easyconfigs/r/R/R-3.1.3-intel-2015a.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.4-foss-2015a.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.4-intel-2015a.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-foss-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2015a-no-X11.eb
see http://r.789695.n4.nabble.com/Where-is-the-tcltk-package-td3434915.html
=> include Tcl and Tk as dependencies in R easyconfig (REVIEW)

easybuild/easyconfigs/c/Clang/Clang-3.6.1-GCC-4.9.2.eb
depends on #1635 for the GMP fix
=> {lang} [GCC/4.9.2] Clang 3.6.1 (REVIEW)

easybuild/easyconfigs/p/Python/Python-2.7.10-foss-2015a.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.8.10.2-foss-2015a.eb
=> {lang}[foss/2015a] Python 2.7.10 (REVIEW)

easybuild/easyconfigs/c/CLHEP/CLHEP-2.2.0.5-intel-2015a.eb, easybuild/easyconfigs/g/Geant4/Geant4-10.01.p01-intel-2015a.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/615
=> {phys}[intel/2015a] Geant4 10.01.p01 (REVIEW)

easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.2-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.3-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-2.2.4-intel-2015a-Python-2.7.9.eb
Add hanythinogndemand eb files that could otherwise be installed using --try-software-version.
=> Add hanythingondemand eb files. 2.2.[234]

easybuild/easyconfigs/a/ABySS/ABySS-1.5.2-goolf-1.4.10.eb
Hi, here is the easyconfig to build ABySS 1.5.2 with the goolf 1.4.10 toolchain.
=> {bio} [goolf 1.4.10] ABySS-1.5.2-goolf-1.4.10 (REVIEW)

easybuild/easyconfigs/b/BEDTools/BEDTools-2.23.0-goolf-1.4.10.eb
Hi, here is the easyconfig for BEDTools 2.23.0 using the goolf 1.4.10 toolchain.
=> {bio} [goolf 1.4.10] BEDTools 2.23.0 (REVIEW)

easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.2.1-goolf-1.4.10.eb
Hi, here is the easyconfig for Cufflinks 2.2.1 using the goolf 1.4.10 toolchain.
=> {bio} [goolf 1.4.10] Cufflinks 2.2.1 (REVIEW)

easybuild/easyconfigs/c/Cython/Cython-0.22-goolf-1.4.10-Python-2.7.3.eb
Hi, here is the easyconfig for Cython 0.22 using the goolf 1.4.10 toolchain.
=> {lang} [goolf 1.4.10] Cython-0.22-Python-2.7.3 (REVIEW)

easybuild/easyconfigs/b/Bowtie/Bowtie-1.1.1-goolf-1.4.10.eb
...goolf 1.4.10
Adding an author name so that users can complain more directly
fixed compared to https://github.com/hpcugent/easybuild-easyconfigs/pull/1186
=> {bio} [goolf/1.4.10] bumping bowtie version 1.1.1 (REVIEW)

easybuild/easyconfigs/g/GROMACS/GROMACS-5.0.5-intel-2015a-hybrid.eb
Add easyconfig for Gromacs 5.0.5 with intel/2015a
=> Gromacs 5.0.5-intel2015a easycofig

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-goalf-1.1.0-no-OFED-hybrid.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-goolf-1.4.10-hybrid.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-ictce-4.0.6-hybrid.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-ictce-4.0.6.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-ictce-5.3.0-hybrid.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-ictce-5.5.0-hybrid.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.0.2-ictce-5.5.0.eb
issue uncovered in https://github.com/hpcugent/easybuild-easyconfigs/pull/1644, also relates to https://github.com/hpcugent/easybuild-easyblocks/pull/618
=> fix source_urls in QuantumESPRESSO 5.0.2 easyconfigs

easybuild/easyconfigs/f/fontconfig/fontconfig-2.11.93-intel-2015a.eb, easybuild/easyconfigs/k/kbproto/kbproto-1.0.7-intel-2015a.eb, easybuild/easyconfigs/l/libXScrnSaver/libXScrnSaver-1.2.2-intel-2015a.eb, easybuild/easyconfigs/l/libXft/libXft-2.3.2-intel-2015a-libX11-1.6.3.eb, easybuild/easyconfigs/l/libXrender/libXrender-0.9.8-foss-2014b.eb, easybuild/easyconfigs/l/libXrender/libXrender-0.9.8-intel-2014b.eb, easybuild/easyconfigs/l/libXrender/libXrender-0.9.9-intel-2015a.eb, easybuild/easyconfigs/r/renderproto/renderproto-0.11-intel-2015a.eb
=> {vis}[intel/2015a] libXScrnSaver 1.2.2 + libXft 2.3.2

easybuild/easyconfigs/h/HDF5/HDF5-1.8.14-intel-2015a.eb, easybuild/easyconfigs/h/HDF5/HDF5-1.8.15-intel-2015a.eb, easybuild/easyconfigs/h/h5py/h5py-2.5.0-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/m/Meep/Meep-1.3-intel-2015a.eb, easybuild/easyconfigs/x/Xmipp/Xmipp-3.1-intel-2015a.eb
=> drop gpfs versionsuffix and use no longer existing --enable-gpfs configopt for recent HDF5 versions

easybuild/easyconfigs/d/DendroPy/DendroPy-3.12.0-goolf-1.4.10-Python-2.7.3.eb
Adding DendroPy (Python Package) in EasyBuild
=> Contributing DendroPy

easybuild/easyconfigs/t/Theano/Theano-0.6.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/t/Theano/Theano-0.6.0-ictce-5.3.0-Python-2.7.3.eb
Contributing Theano v 0.6.0 with goolf 1.4.10 and ictce 5.3.0
=> Contrib Theano v.0.6.0

easybuild/easyconfigs/g/GATK/GATK-3.0-0-Java-1.7.0_10.eb
Contributing GATK version 3.0.0
=> Contrib GATK v.3.0.0

easybuild/easyconfigs/b/blasr/blasr-git-smrt2.1-goolf-1.4.10.eb, easybuild/easyconfigs/b/blasr/non-static.patch
This is a config for BLASR from the PacBio SMRT 2.1 analysis toolkit plus patch.
=> contrib blasr configs.

easybuild/easyconfigs/s/SAMtools/SAMtools-1.1-intel-2015a.eb
latest SAMtools build with intel
=> {bio}[intel/2015a] SAMtools (REVIEW)

easybuild/easyconfigs/c/CONTRAfold/CONTRAfold-2.02-goolf-1.4.10.eb, easybuild/easyconfigs/c/CONTRAfold/contrafold-gcc47.patch
added required patch to compile with gcc-4.7.2
=> CONTRAfold-2.02-goolf-1.4.10.eb

easybuild/easyconfigs/q/Qt/Qt-4.8.4-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.4-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.4-goolf-1.4.10.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.4-ictce-4.0.6.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.4-ictce-4.1.13.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.4-ictce-5.3.0.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.5-gmpolf-1.4.8.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.5-goolf-1.5.14.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.5-ictce-4.1.13.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.6-foss-2015a.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.6-goolf-1.5.14.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.6-intel-2014b.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.6-intel-2015a.eb
- changed source_urls and homepage
=> {devel}  QT changed urls (REVIEW)

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.5-goolf-1.7.20.eb
Now to the develop branch, sorry about that
=> .eb file for Bowtie2 2.2.5 goolf 1.7.20 

easybuild/easyconfigs/c/cairo/cairo-1.12.18-goolf-1.7.20.eb, easybuild/easyconfigs/p/pixman/pixman-0.32.6-goolf-1.7.20.eb
depends on #1710, #1711, #1714, #1715
=> .eb file for cairo-1.12.18-goolf-1.7.20

easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25.eb, easybuild/easyconfigs/g/GCC/GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/g/GNU/GNU-5.1.0-2.25.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCC-5.1.0-binutils-2.25.eb
useful information for stuff that will be built on top of this: https://lists.fedoraproject.org/pipermail/devel/2015-February/207549.html
=> {toolchain} GNU 5.1.0-2.25 (REVIEW)

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GNU-5.1.0-2.25.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-GNU-5.1.0-2.25.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-GNU-5.1.0-2.25.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-GNU-5.1.0-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GNU-5.1.0-2.25.eb
=> {devel}[GNU-5.1.0-2.25] Autotools 20150215 (REVIEW)

easybuild/easyconfigs/x/Xmipp/Xmipp-3.1-goolf-1.4.10-with-incl-deps.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/630 AND ~~https://github.com/hpcugent/easybuild-easyblocks/pull/631~~
=> {vis}[goolf/1.4.10] Xmipp 3.1

easybuild/easyconfigs/g/GLib/GLib-2.40.0-goolf-1.7.20.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.2-goolf-1.7.20.eb, easybuild/easyconfigs/l/libffi/libffi-3.1-goolf-1.7.20.eb
=> {bio}[goolf-1.7.20] GLib-2.40.0 (OK)

easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.3.eb
@riccardomurri: any remarks on visual inspection?
=> {tools}[dummy] GC3Pie 2.3

easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.2-goolf-1.4.10.eb, easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.2-ictce-4.1.13-mt.eb, easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.2-ictce-4.1.13.eb, easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.2-ictce-5.3.0.eb, easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.2-iqacml-3.7.3.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-goolf-1.4.10.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-goolf-1.5.14.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-ictce-3.2.2.u3.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-ictce-4.1.13-mt.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-ictce-4.1.13.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-ictce-5.3.0.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.2-iqacml-3.7.3.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.0-foss-2014b.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.0-foss-2015a.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.0-intel-2014b.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.0-intel-2015a.eb
http URL no longer works
see also #1766
=> fix source_urls in netCDF-C++ and netCDF-Fortran easyconfigs

easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-goolf-1.4.10.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-ictce-3.2.2.u3.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-ictce-4.1.13.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.1.3-ictce-5.3.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2-goolf-1.4.10.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2-ictce-3.2.2.u3.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2-ictce-5.3.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-goolf-1.4.10.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-goolf-1.5.14.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-4.1.13-mt.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-4.1.13.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-5.3.0-zlib-1.2.5.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-5.3.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-ictce-5.5.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-intel-2014b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.2.1.1-iqacml-3.7.3.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.0-ictce-5.5.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.2-foss-2014b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.2-foss-2015a.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.2-intel-2014b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.2-intel-2015a.eb
the http URL no longer works...
see also #1767
=> fix source_urls in netCDF easyconfigs

easybuild/easyconfigs/b/Biggus/Biggus-0.11.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/b/Biggus/Biggus-0.5.0-goolf-1.4.10-Python-2.7.3.eb
=> Contributing Biggus Python Package

easybuild/easyconfigs/h/Hadoop/Hadoop-2.5.0-cdh5.3.1-native.eb
[Requires #638 from easyblocks](https://github.com/hpcugent/easybuild-easyblocks/pull/638)
=> Glob the lib so.

easybuild/easyconfigs/e/EMAN2/EMAN2-2.11-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/e/EMAN2/EMAN2-2.11-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4-foss-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4-intel-2015a.eb
=> {bio}[*/2015a] EMAN 2.11 + LibTIFF 4.0.4 (REVIEW)

easybuild/easyconfigs/p/PDT/PDT-3.19-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/p/PDT/PDT-3.19-ictce-5.3.0.eb, easybuild/easyconfigs/p/PDT/PDT-3.20-foss-2015a.eb
**ATTENTION**: This PR requires https://github.com/hpcugent/easybuild-easyblocks/pull/624
Changes:
- removed config parameter hackery now taken care of by custom easyblock
- add checksums
- cosmetic changes
=> {perf}[*] Updated PDT easyconfigs using custom easyblock (REVIEW)

easybuild/easyconfigs/c/CMake/CMake-3.2.3-intel-2015a.eb
=> Add support for https

easybuild/easyconfigs/h/HDF/HDF-4.2.7-patch1-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.7-patch1-goolf-1.4.10.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.7-patch1-ictce-3.2.2.u3.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.7-patch1-ictce-5.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.8-ictce-4.1.13.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.8-ictce-5.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.8-iqacml-3.7.3.eb, easybuild/easyconfigs/i/IsoInfer/IsoInfer-0.9.1-goolf-1.4.10.eb, easybuild/easyconfigs/i/IsoInfer/IsoInfer-0.9.1-ictce-6.2.5.eb, easybuild/easyconfigs/n/ngspice/ngspice-26-intel-2014b.eb, easybuild/easyconfigs/r/RELION/RELION-1.3-foss-2014b.eb, easybuild/easyconfigs/r/RELION/RELION-1.3-intel-2014b.eb
fixes small issues with templates, most importantly the broken `source_urls` entry in the `ngspice` easyconfig
=> fix templating issues

easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.4.0-ictce-7.3.5.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.17-ictce-7.3.5.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-ictce-7.3.5.eb, easybuild/easyconfigs/n/NASM/NASM-2.11.06-ictce-7.3.5.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-ictce-7.3.5.eb, easybuild/easyconfigs/r/R/R-3.2.0-ictce-7.3.5-bare.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.4-ictce-7.3.5.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-ictce-7.3.5-no-X11.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-ictce-7.3.5.eb
Hi, here is the easyconfigs for R and its dependencies using the ictce 7.3.5 toolchain.
=> {lang} [ictce 7.3.5] R-3.2.0 + dependencies (REVIEW)

easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.4.5-ictce-5.5.0.eb
=> no mca_common_sm in OpenMPI 1.4.5 w/ ictce/5.5.0

easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.1.eb
=> {tools}[dummy] GC3Pie 2.4.1

easybuild/easyconfigs/p/PCRE/PCRE-8.12-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.12-goolf-1.4.10.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.12-ictce-4.0.6.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.12-ictce-5.3.0.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.12-ictce-5.5.0.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.35-intel-2014b.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.36-foss-2015a.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.36-intel-2015a.eb, easybuild/easyconfigs/x/XZ/XZ-5.0.5-GCC-4.8.2.eb, easybuild/easyconfigs/x/XZ/XZ-5.0.5-goolf-1.4.10.eb, easybuild/easyconfigs/x/XZ/XZ-5.0.5-ictce-5.3.0.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.0-GCC-4.9.2.eb
(triggered by #1830)
@fgeorgatos, @rjeschmi, @wpoely86: please review?
=> style fixes in PCRE and XZ easyconfigs

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GNU-4.9.3-2.25.eb
=> {devel}[GNU-4.9.3-2.25] Autotools 20150215 (REVIEW)

easybuild/easyconfigs/g/gompi/gompi-2015b.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.8-GNU-4.9.3-2.25.eb
this should have been part of #1694...
cc @hajgato, @gjbex, @backelj
=> use OpenMPI 1.8.8 in gompi/2015b

easybuild/easyconfigs/g/GATK/GATK-3.3-0-Java-1.7.0_80.eb, easybuild/easyconfigs/p/picard/picard-1.119-Java-1.7.0_80.eb
Update two easyconfigs to use the current release of Java 1.7
=> 1856 java dep updates

easybuild/easyconfigs/c/cairo/cairo-1.14.2-intel-2015a.eb, easybuild/easyconfigs/f/fontconfig/fontconfig-2.11.94-intel-2015a.eb, easybuild/easyconfigs/g/GLib/GLib-2.44.1-intel-2015a.eb, easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.16-intel-2015a.eb, easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.3.1-intel-2015a.eb, easybuild/easyconfigs/n/NASM/NASM-2.11.05-intel-2015a.eb
synced with #1705 by @npklein, equivalent easyconfigs with `intel/2015a`
=> {tools,vis}[intel/2015a] Ghostscript 9.16 + cairo 1.14.2 + GLib 2.44.1 (REVIEW)

easybuild/easyconfigs/f/FDS/FDS-r18915-intel-2015a.eb
only different toolchain compared to existing easyconfig
=> {phys}[intel/2015a] FDS r18915 (REVIEW)

easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.42.0-intel-2014b.eb, easybuild/easyconfigs/p/Pango/Pango-1.36.7-intel-2014b.eb
fix remark by @JensTimmerman in other easyconfigs where it's applicable
=> use FTPGNOME_SOURCE where applicable

easybuild/easyconfigs/m/MACS/MACS-1.4.2-1-goolf-1.4.10-Python-2.7.5.eb
wrapper PR for #1247 by @pescobar 
removed broken `source_urls` and some minor style issues
=> {bio}[goolf/1.4.10] MACS 1.4.2-1 (REVIEW)

easybuild/easyconfigs/b/Boost/Boost-1.59.0-intel-2015a-Python-2.7.10.eb
on hold until #1858 is merged in
=> {devel}[intel/2015a] Boost 1.59.0 (REVIEW)

easybuild/easyconfigs/p/PSI/PSI-4.0b6-20150814-fix-gitversion.patch, easybuild/easyconfigs/p/PSI/PSI-4.0b6-20150814-intel-2015a-mt-maxam7.eb
=> PSI4 version with maxam=7

easybuild/easyconfigs/m/Molpro/Molpro-2012.1.27-intel-2015a.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/665
=> {chem}[intel/2015a] Molpro 2012.1.27 (REVIEW)

easybuild/easyconfigs/i/IPython/IPython-3.2.1-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/l/libsodium/libsodium-1.0.3-intel-2015a.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-14.7.0-intel-2015a-Python-2.7.10-zmq4.eb, easybuild/easyconfigs/u/util-linux/util-linux-2.26.2-intel-2015a.eb, easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.1.3-intel-2015a.eb
=> {tools}[intel/2015a] IPython 3.2.1 w/ Python 2.7.10 (REVIEW)

easybuild/easyconfigs/f/FPM/FPM-1.3.3-Ruby-2.1.6.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/667 (see also https://github.com/hpcugent/easybuild-easyblocks/issues/646)
=> add sanity check paths for FPM

easybuild/easyconfigs/p/PyQt/PyQt-4.11.3-goolf-1.5.14-Python-2.7.9.eb, easybuild/easyconfigs/p/PyQt/PyQt-4.11.3-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/p/PyQt/PyQt-4.11.4-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/p/PyQt/PyQt-4.11.4-intel-2015a-Python-2.7.9.eb
required now because of https://github.com/hpcugent/easybuild-framework/pull/1366
=> add custom sanity check paths for PyQt

easybuild/easyconfigs/x/XML/XML-3.95-0.1-goalf-1.1.0-no-OFED-R-2.15.2.eb, easybuild/easyconfigs/x/XML/XML-3.95-0.1-goolf-1.4.10-R-2.15.2.eb, easybuild/easyconfigs/x/XML/XML-3.95-0.1-ictce-4.0.6-R-2.15.2.eb, easybuild/easyconfigs/x/XML/XML-3.95-0.1-ictce-5.3.0-R-2.15.2.eb
=> add custom sanity check paths in R XML easyconfigs

easybuild/easyconfigs/c/cURL/cURL-7.44.0-foss-2015a.eb, easybuild/easyconfigs/c/cURL/cURL-7.44.0-goolf-1.7.20.eb, easybuild/easyconfigs/c/cURL/cURL-7.44.0-intel-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.2-foss-2015a.eb, easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.1.2-intel-2015a.eb
Simple version update for Xerces-C++
=> {lib}[*/2015a] Xerces 3.1.2 (REVIEW)

easybuild/easyconfigs/m/MDP/MDP-3.3-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/m/MDP/MDP-3.3-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/m/MDP/MDP-3.3-ictce-4.0.6-Python-2.7.3.eb, easybuild/easyconfigs/m/MDP/MDP-3.3-ictce-5.3.0-Python-2.7.3.eb
=> add custom sanity check paths in MDP easyconfigs

easybuild/easyconfigs/b/Biggus/Biggus-0.11.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/b/Biggus/Biggus-0.5.0-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/b/bibtexparser/bibtexparser-0.5-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/b/bibtexparser/bibtexparser-0.5-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/b/bibtexparser/bibtexparser-0.6.0-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/b/bibtexparser/bibtexparser-0.6.0-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/n/netifaces/netifaces-0.10.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/n/netifaces/netifaces-0.8-ictce-5.5.0-Python-2.7.6.eb, easybuild/easyconfigs/n/networkx/networkx-1.10-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/n/networkx/networkx-1.9.1-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/o/ordereddict/ordereddict-1.1-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/p/PyQuante/PyQuante-1.6.4-ictce-5.5.0-Python-2.7.5.eb, easybuild/easyconfigs/p/Pyke/Pyke-1.1.1-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/p/pycosat/pycosat-0.6.0-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/p/pygraphviz/pygraphviz-1.3rc2-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/r/rpy2/rpy2-2.4.3-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/r/rpy2/rpy2-2.4.3-goolf-1.4.10-Python-3.2.3.eb
=> add custom sanity check paths in various easyconfigs for Python packages

easybuild/easyconfigs/f/FoldX/FoldX-3.0-beta6.1.eb, easybuild/easyconfigs/f/FoldX/FoldX-3.0-beta6.eb
They renamed the binary, but didn't rename the 'source' tarball. Great.
=> {bio}[dummy] FoldX 3.0 beta 6.1 (REVIEW)

easybuild/easyconfigs/m/MCR/MCR-R2014a.eb, easybuild/easyconfigs/m/MCR/MCR-R2015a.eb
Needs https://github.com/hpcugent/easybuild-easyblocks/pull/623
=> {math} [binary] MCR 2014b (REVIEW) 

easybuild/easyconfigs/n/NFFT/NFFT-3.3.0-foss-2015a.eb, easybuild/easyconfigs/n/NFFT/NFFT-3.3.0-intel-2015a.eb
=> {lib}[*/2015a] NFFT 3.3.0 (REVIEW)

easybuild/easyconfigs/s/SOAPdenovo2/SOAPdenovo2-r240-intel-2015a.eb
Add SOAPdenovo2-r240-intel-2015a.eb
=> Add SOAPdenovo2-r240-intel-2015a.eb

easybuild/easyconfigs/a/ABySS/ABySS-1.3.7-intel-2015a-Python-2.7.9.eb
add ABySS-1.3.7-intel-2015a-Python-2.7.9.eb
=> add ABySS-1.3.7-intel-2015a-Python-2.7.9.eb

easybuild/easyconfigs/f/flex/flex-2.5.39-foss-2015b.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-intel-2015b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1-foss-2015b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1-intel-2015b.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.4-foss-2015b.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.4-intel-2015b.eb
depends on #1724 and #1725 for `libreadline` + `ncurses` easyconfigs
=> {cae}[*/2015b] OpenFOAM 2.3.1 + deps

easybuild/easyconfigs/s/Samcef/Samcef-17.0-03.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/678
=> {cae}[dummy] Samcef 17.0-03 (REVIEW)

easybuild/easyconfigs/s/Samcef/Samcef-17.0-03.eb
Thanks for catching this one @fgeorgatos!
=> don't hardwire Samcef version in sources

easybuild/easyconfigs/b/BEDTools/BEDTools-2.25.0-goolf-1.7.20.eb
Update to latest BEDTools release and use newer release of goolf toolchain
=> Add BEDTools 2.25.0 for goolf 1.7.20

easybuild/easyconfigs/o/Oases/Oases-0.2.08-intel-2015a.eb
add Oases-0.2.08-intel-2015a.eb
=> add Oases-0.2.08-intel-2015a.eb

easybuild/easyconfigs/r/Rosetta/Rosetta-2015.31.58019-intel-2015a.eb, easybuild/easyconfigs/s/SCons/SCons-2.3.6-intel-2015a-Python-2.7.9.eb
needs https://github.com/hpcugent/easybuild-easyblocks/pull/677
=> {bio} [intel-2015a] Rosetta 2015.31 (REVEW) 

easybuild/easyconfigs/g/gperftools/gperftools-2.4-foss-2015a.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.1-foss-2015a.eb, easybuild/easyconfigs/m/MIRA/MIRA-4.0.2-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/m/MIRA/MIRA-4.0.2-quirks.patch
{bio}[foss-2015a] MIRA-4.0.2 together with deps and patch.
=> add MIRA-4.0.2-foss-2015a-Python-2.7.9.eb and deps

easybuild/easyconfigs/c/CP2K/CP2K-20150904-ifort-compiler-bug-fix.patch, easybuild/easyconfigs/c/CP2K/CP2K-20150904-intel-2015a-PLUMED-2.1.3.eb, easybuild/easyconfigs/c/CP2K/CP2K-20150904-intel-2015a-PLUMED.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.0.4_eb-env-vars.patch, easybuild/easyconfigs/p/PLUMED/PLUMED-2.1.3-intel-2015a.eb
Needs hpcugent/easybuild-easyblocks#681
=> {chem} [intel/2015a] CP2k-20150904 with PLUMED

easybuild/easyconfigs/g/Go/Go-1.4.2-GCC-4.8.4.eb, easybuild/easyconfigs/g/Go/Go-1.5-GCC-4.8.4.eb
1.4.2 is needed to compile the latest (1.5) version
=> Added new Go versions 1.4.2 and 1.5

easybuild/easyconfigs/s/Spark/Spark-1.5.0.eb
Made available using Java 1.7 since Hadoop eb files use that too.
=> Spark 1.5.0 

easybuild/easyconfigs/m/MUMPS/MUMPS-5.0.1-intel-2015a-metis.eb, easybuild/easyconfigs/m/MUMPS/MUMPS-5.0.1-intel-2015a-parmetis.eb
test case for ~~https://github.com/hpcugent/easybuild-easyblocks/pull/657~~ https://github.com/hpcugent/easybuild-easyblocks/pull/686
=> {math}[intel/2015a] MUMPS 5.0.1 w/ METIS/ParMETIS (REVIEW)

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-goolf-1.7.20-R-3.2.0.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-intel-2015a-R-3.2.1.eb
cc @verdurin (please include it in your Bioconductor PR #1962 too)
=> add Rsubread in Bioconductor easyconfigs

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.4.0-intel-2015b.eb, easybuild/easyconfigs/o/OpenFOAM/cleanup-OpenFOAM-2.4.0.patch, easybuild/easyconfigs/o/OpenFOAM/cleanup-ThirdParty-2.4.0.patch
requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/688~~ and ~~https://github.com/hpcugent/easybuild-easyblocks/pull/692~~
=> {cae}[intel/2015b] OpenFOAM 2.4.0 (REVIEW)

easybuild/easyconfigs/c/CMake/CMake-3.2.1-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/networkx/networkx-1.10-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/p/Pillow/Pillow-2.9.0-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/q/Qhull/Qhull-2012.1-intel-2015b.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.11.3-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.16.1-intel-2015b-Python-2.7.10.eb
requires ~~#1975~~ (for Qhull patch)
=> {data,vis}[intel/2015b] scikit-image 0.11.3, scikit-learn 0.16.1, Pillow 2.9.0

easybuild/easyconfigs/g/GMP/GMP-6.0.0a-GCC-4.7.2.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-goolf-1.4.10.eb, easybuild/easyconfigs/p/Python/Python-2.7.10-goolf-1.4.10.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.8.10.2-goolf-1.4.10.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.4-goolf-1.4.10.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-goolf-1.4.10-no-X11.eb
=> {lang}[goolf/1.4.10] Python 2.7.10 (REVIEW)

easybuild/easyconfigs/g/GDAL/GDAL-2.0.0-intel-2015a.eb, easybuild/easyconfigs/g/GMT/GMT-5.1.0-goolf-1.4.10.eb, easybuild/easyconfigs/g/GMT/GMT-5.1.2-intel-2015a.eb, easybuild/easyconfigs/g/GMT/GMT-5.1.2_netCDF.patch, easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-intel-2015a.eb
Needs ~~https://github.com/hpcugent/easybuild-easyblocks/pull/674~~
=> {geo} [intel-2015a] GMT 5.1.2 (REVIEW) 

easybuild/easyconfigs/c/cutadapt/cutadapt-1.5-goolf-1.4.10-Python-2.7.10.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.5-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/f/FastQC/FastQC-0.10.1-goolf-1.4.10.eb, easybuild/easyconfigs/t/Trim_Galore/Trim_Galore-0.3.7-goolf-1.4.10.eb
Contributing Trim Galore, a wrapper tool around Cutadapt and FastQC to consistently apply quality and adapter trimming to FastQ files, with some extra functionality for MspI-digested RRBS-type.
edit: now requires #1982
=> Contrib Trim Galore

easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/p/Python/Python-2.7.10-GNU-4.9.3-2.25-bare.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.8.10.2-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.4-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-GNU-4.9.3-2.25-no-X11.eb
=> [GNU/4.9.3-2.25] Python bare 2.7.10 for clang (REVIEW)

easybuild/easyconfigs/h/HBase/HBase-1.0.2.eb
necessary for new HBase support in hanythingondemand
=> add HBase/1.0.2

easybuild/easyconfigs/a/APR-util/APR-util-1.5.4-foss-2015a.eb, easybuild/easyconfigs/a/APR/APR-1.5.2-foss-2015a.eb, easybuild/easyconfigs/s/SCons/SCons-2.3.6-foss-2015a-Python-2.7.10.eb, easybuild/easyconfigs/s/SCons/SCons-2.3.6-foss-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/SCons/SCons-2.3.6-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/s/Serf/Serf-1.3.8-foss-2015a.eb, easybuild/easyconfigs/s/Serf/Serf-1.3.8_SCons_ld_lib.patch, easybuild/easyconfigs/s/Serf/Serf-1.3.8_remve_c99_comment.patch, easybuild/easyconfigs/s/Subversion/Subversion-1.8.14-foss-2015a.eb
Needs ~~https://github.com/hpcugent/easybuild-easyblocks/pull/689~~ (Serf EasyBlock)
Inspired by PR #758 
edit: now requires https://github.com/hpcugent/easybuild-easyblocks/pull/700
=> {tools}[foss-2015a] Subversion 1.8.14 (REVIEW)

easybuild/easyconfigs/h/HTSlib/HTSlib-1.2.1-intel-2015b.eb, easybuild/easyconfigs/s/SAMtools/SAMtools-1.2-intel-2015b-HTSlib-1.2.1.eb
=> {bio}[intel/2015b] SAMtools 1.2 + HTSlib 1.2.1 (REVIEW)

easybuild/easyconfigs/l/libdrm/libdrm-2.4.27-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.27-goolf-1.4.10.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.27-ictce-4.0.6.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.27-ictce-4.1.13.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.27-ictce-5.3.0.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.27-ictce-5.5.0.eb
onfigopts = '--enable-nouveau-experimental-api' deleted, plus some polishing
Fleshed out form closed PR #1166
=> libdrm Noveau deleted + some polishing

easybuild/easyconfigs/p/PyQt/PyQt-4.11.4-intel-2014b-Python-2.7.8.eb, easybuild/easyconfigs/s/SIP/SIP-4.16.8-intel-2014b-Python-2.7.8.eb
PyQt 4.11.4 with deps using intel/2014b
=> {vis} [intel-2014b] PyQt 4.11.4 (REVIEW)

easybuild/easyconfigs/l/libxslt/libxslt-1.1.28-intel-2014b.eb, easybuild/easyconfigs/l/lxml/lxml-3.4.2-intel-2014b-Python-2.7.8.eb
lxml 3.4.2 with intel2014b plus deps.
=> {lib} [intel-2014b] lxml 3.4.2 (REVIEW) 

easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-intel-2015b.eb
=> {chem}[intel/2015b] CHARMM 37b2 (REVIEW)

easybuild/easyconfigs/s/spglib/spglib-1.7.4-intel-2015b.eb
- added easyconfig for spglib 1.7.4 and toolchain intel 2015b
(note: start_dir directive no longer needed)
=> {chem} [intel/2015b] spglib 1.7.4 (REVIEW)

easybuild/easyconfigs/p/PhyloCSF/PhyloCSF-20150118-foss-2015a-OCaml-4.02.3.eb
=> {bio}[foss/2015a} PhyloCSF 20150118 (REVIEW)

easybuild/easyconfigs/l/libICE/libICE-1.0.9-intel-2015b.eb, easybuild/easyconfigs/l/libSM/libSM-1.2.2-intel-2015b.eb, easybuild/easyconfigs/l/libXrender/libXrender-0.9.9-intel-2015b.eb, easybuild/easyconfigs/l/libXt/libXt-1.1.5-intel-2015b.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.7-intel-2015b.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.7_phonon-export.patch, easybuild/easyconfigs/r/renderproto/renderproto-0.11-intel-2015b.eb
=> {devel} [intel-2015b] Qt 4.8.7 (REVIEW)

easybuild/easyconfigs/l/libdrm/libdrm-2.4.64-intel-2015b.eb, easybuild/easyconfigs/l/libpciaccess/libpciaccess-0.13.4-intel-2015b.eb, easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-intel-2015b.eb
=> {lib} [intel-2015b] libdrm 2.4.64 (REVIEW)

easybuild/easyconfigs/c/CGAL/CGAL-4.6.3-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/c/CMake/CMake-3.2.3-intel-2015b.eb
Needs PR ~~#2024~~ ~~#2025~~ ~~#2026~~ ~~#2027~~
=> {numlib} [intel-2015b] CGAL 4.6.3 (REVIEW)

easybuild/easyconfigs/c/CUDA/CUDA-7.5.18.eb
depends on PR https://github.com/hpcugent/easybuild-easyblocks/pull/708
=> add CUDA-7.5.18.eb

easybuild/easyconfigs/b/Bison/Bison-3.0.4-intel-2015b.eb, easybuild/easyconfigs/f/fixesproto/fixesproto-5.0-intel-2015b.eb, easybuild/easyconfigs/f/fontsproto/fontsproto-2.1.3-intel-2015b.eb, easybuild/easyconfigs/f/freetype/freetype-2.6.1-intel-2015b.eb, easybuild/easyconfigs/g/glproto/glproto-1.4.17-intel-2015b.eb, easybuild/easyconfigs/l/libXdamage/libXdamage-1.1.4-intel-2015b.eb, easybuild/easyconfigs/l/libXdmcp/libXdmcp-1.1.2-intel-2015b.eb, easybuild/easyconfigs/l/libXext/libXext-1.3.3-intel-2015b.eb, easybuild/easyconfigs/l/libXfixes/libXfixes-5.0.1-intel-2015b.eb, easybuild/easyconfigs/l/libXfont/libXfont-1.5.1-intel-2015b.eb, easybuild/easyconfigs/l/libfontenc/libfontenc-1.1.3-intel-2015b.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.18-intel-2015b.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2015b.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.0.2-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/makedepend/makedepend-1.0.5-intel-2015b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29-intel-2015b.eb
=> {vis} [intel-2015b] Mesa 11.0.2 (REVIEW)

easybuild/easyconfigs/p/pandas/pandas-0.16.2-foss-2015a-Python-2.7.10.eb
Simple port of the intel-2015a version to foss-2015a. 
Has built locally and is under user testing.
=> Add foss-2015a version of pandas

easybuild/easyconfigs/p/pandas/pandas-0.16.2-intel-2015b-Python-2.7.10.eb
=> {lib}[intel/2015b] pandas 0.16.2 (REVIEW)

easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2015b.eb, easybuild/easyconfigs/p/Paraview/Paraview-4.4.0-intel-2015b-mpi.eb, easybuild/easyconfigs/p/Paraview/Paraview-4.4.0-intel-2015b.eb, easybuild/easyconfigs/p/Paraview/Paraview-4.4.0_missingheader.patch
=> {vis} [intel-2015b] Paraview 4.4.0 (REVIEW)

easybuild/easyconfigs/c/Cufflinks/Cufflinks-1.3.0-goolf-1.4.10.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.0.2-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.1.1-ictce-5.5.0.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.2.1-goolf-1.4.10.eb, easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.2.1-goolf-1.7.20.eb
cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/2058/files#r42091017
cc @rjeschmi
=> correct homepage in Cufflinks easyconfigs

easybuild/easyconfigs/j/Java/Java-1.8.0_60.eb
another try with an easy contribution
=> Java update

easybuild/easyconfigs/n/NWChem/NWChem-6.5.revision26243-intel-2015b-2014-09-10-Python-2.7.10.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/720
=> {chem}[intel/2015b] NWChem 6.5 (REVIEW)

easybuild/easyconfigs/j/Java/Java-1.8.0_65.eb
=> JDK 1.8.0_65

easybuild/easyconfigs/j/Java/Java-1.8.0_66.eb
fixing my errors (push the correct file into the correct branch)...
=> JDK 1.8.0_66

easybuild/easyconfigs/c/cairo/cairo-1.14.2-intel-2015b.eb, easybuild/easyconfigs/f/fontconfig/fontconfig-2.11.94-intel-2015b.eb, easybuild/easyconfigs/p/pixman/pixman-0.32.8-intel-2015b.eb, easybuild/easyconfigs/p/pycairo/pycairo-1.10.0-intel-2015b-Python-2.7.10.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/722
=> {vis}[intel/2015b] pycairo 1.10.0 for cairo 1.14.2 w/ Python 2.7.10 (REVIEW)

test/easyconfigs/easyconfigs.py
changed in https://github.com/hpcugent/easybuild-framework/pull/1388
=> fix import for set_tmpdir

easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-5.1.0-binutils-2.25.eb
workaround for https://github.com/hpcugent/easybuild-framework/issues/1402, since it may not be trivial to fix
cc @ocaisa
=> don't use %(version)s template in toolchain version, causes problems with HMNS

easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-3.0.1-cli.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-3.0.1-intel-2015b-Python-2.7.10.eb
=> Bump hod to 3.0.1.

easybuild/easyconfigs/h/HTSlib/HTSlib-1.2.1-goolf-1.7.20.eb
Simple addition of HTSlib 1.2.1 for goolf 1.7.20
=> Add goolf 1.7.20 version of HTSlib 1.2.1

easybuild/easyconfigs/s/SAMtools/SAMtools-0.1.20-goolf-1.7.20.eb, easybuild/easyconfigs/s/SAMtools/SAMtools-0.1.20_Makefile-ncurses.patch
A simple addition of SAMtools 0.1.20, which is required by some of the PanCancer tools.
=> Add SAMtools 0.1.20 for goolf 1.7.20

easybuild/easyconfigs/c/ChIP-Seq/ChIP-Seq-1.5-1-goolf-1.4.10.eb, easybuild/easyconfigs/c/ChIP-Seq/ChIP-Seq-1.5-1-goolf-1.7.20.eb
@boegel I just noticed I missed the url :P
=> updated homepage url for chip-seq easyconfigs

easybuild/easyconfigs/l/LuaJIT/LuaJIT-2.0.2-GCC-4.9.2.eb
=> {tools}[GCC/4.9.2] LuaJIT 2.0.2 (REVIEW) 

easybuild/easyconfigs/o/Octave/Octave-4.0.0-foss-2015a.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.37-foss-2015a.eb
=> {math}[foss/2015a] Octave 4.0.0 (REVIEW)

easybuild/easyconfigs/m/MultiNest/MultiNest-3.10-intel-2015b.eb
=> {tools}[intel/2015b} MultiNest 3.10 (REVIEW)

easybuild/easyconfigs/m/MultiNest/MultiNest-3.10-intel-2015b.eb
=> add CMake as missing build dep for MultiNest

easybuild/easyconfigs/r/rhdf5/rhdf5-2.14.0-intel-2015b-R-3.2.1.eb, easybuild/easyconfigs/s/sleuth/sleuth-0.28.0-intel-2015b-R-3.2.1.eb, easybuild/easyconfigs/z/zlibbioc/zlibbioc-1.16.0-intel-2015b-R-3.2.1.eb
=> {bio}[intel/2015b] sleuth 0.28.0 w/ R 3.2.1

easybuild/easyconfigs/k/kallisto/kallisto-0.42.4-intel-2015b.eb
=> {bio}[intel/2015b] kallisto 0.42.4 (REVIEW)

easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.17-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.17-intel-2015b-Python-3.5.0.eb
=> {data} [intel-2015b] scikit-learn 0.17 Python-{2.7.10,3.5.0} (REVIEW)

easybuild/easyconfigs/m/MIGRATE-N/MIGRATE-N-3.6.11-intel-2015a.eb
=> {bio} [intel-2015a] MIGRATE-N 3.6.11 (REVIEW)

easybuild/easyconfigs/g/GeoIP-C/GeoIP-C-1.6.7-intel-2015a.eb, easybuild/easyconfigs/g/GeoIP/GeoIP-1.3.2-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/v/vincent/vincent-0.4.4-intel-2015a-Python-2.7.10.eb
=> {lib,vis}[intel/2015a] GeoIP 1.3.2 + vincent 0.4.4 (REVIEW)

easybuild/easyconfigs/c/Cufflinks/Cufflinks-2.2.1-intel-2015b-Python-2.7.10-Boost-1.59.0.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-intel-2015b.eb, easybuild/easyconfigs/s/SAMtools/SAMtools-0.1.20-intel-2015b.eb
Cufflinks should now work w/ Boost 1.59.0, cfr. https://github.com/cole-trapnell-lab/cufflinks/issues/3
=> {bio}[intel/2015b] Cufflinks 2.2.1 + Eigen 3.2.7 + SAMtools 0.1.20 (REVIEW)

easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-3.0.3-cli.eb, easybuild/easyconfigs/h/hanythingondemand/hanythingondemand-3.0.3-intel-2015b-Python-2.7.10.eb
=> {tools}[intel/2015b] HOD 3.0.3 w/ Python 2.7.10 (REVIEW)

easybuild/easyconfigs/i/Intltool/Intltool-0.51.0-intel-2015b.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-intel-2015b.eb, easybuild/easyconfigs/l/libXcursor/libXcursor-1.1.14-intel-2015b.eb, easybuild/easyconfigs/l/libXinerama/libXinerama-1.1.3-foss-2014b.eb, easybuild/easyconfigs/l/libXinerama/libXinerama-1.1.3-intel-2014b.eb, easybuild/easyconfigs/l/libXinerama/libXinerama-1.1.3-intel-2015b.eb, easybuild/easyconfigs/l/libXrandr/libXrandr-1.5.0-intel-2015b.eb, easybuild/easyconfigs/l/libxkbcommon/libxkbcommon-0.5.0-intel-2015b.eb, easybuild/easyconfigs/q/Qt/Qt-5.5.1-intel-2015b.eb, easybuild/easyconfigs/q/Qt/Qt5-5.5.1-intel-2015b.eb, easybuild/easyconfigs/r/randrproto/randrproto-1.5.0-intel-2015b.eb, easybuild/easyconfigs/x/XKeyboardConfig/XKeyboardConfig-2.16-intel-2015b.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-goolf-1.4.10-Perl-5.16.3.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-intel-2014b-Perl-5.20.0.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-intel-2015b-Perl-5.20.3.eb, easybuild/easyconfigs/x/xcb-util-image/xcb-util-image-0.4.0-intel-2015b.eb, easybuild/easyconfigs/x/xcb-util-keysyms/xcb-util-keysyms-0.4.0-intel-2015b.eb, easybuild/easyconfigs/x/xcb-util-renderutil/xcb-util-renderutil-0.3.9-intel-2015b.eb, easybuild/easyconfigs/x/xcb-util-wm/xcb-util-wm-0.4.1-intel-2015b.eb, easybuild/easyconfigs/x/xcb-util/xcb-util-0.4.0-intel-2015b.eb, easybuild/easyconfigs/x/xineramaproto/xineramaproto-1.2.1-foss-2014b.eb, easybuild/easyconfigs/x/xineramaproto/xineramaproto-1.2.1-intel-2014b.eb, easybuild/easyconfigs/x/xineramaproto/xineramaproto-1.2.1-intel-2015b.eb
Needs ~https://github.com/hpcugent/easybuild-easyblocks/pull/740~~
(Sorry for this, it became a monster)
=> {devel} [intel-2015b] Qt 5.5.1 (REVIEW)

easybuild/easyconfigs/i/ipp/ipp-9.0.1.150.eb
Mostly intended as a test case for https://github.com/hpcugent/easybuild-easyblocks/pull/759
cc @jas02
=> {perf}[dummy] ipp 9.0.1.150 (REVIEW)

easybuild/easyconfigs/c/CGAL/CGAL-4.7-intel-2015b-Python-2.7.10.eb
=> {numlib} [intel-2015b] CGAL 4.7 (REVIEW)

easybuild/easyconfigs/g/GMP/GMP-6.1.0-intel-2015b.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2015b.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.9.2-intel-2015b.eb
all Python packages included as extensions have been updated to the latest version
(I stuck to v1.x for mpi4py, since mpi4py 2.0 has API changes)
=> {lang}[intel/2015b] Python 2.7.11 (REVIEW)

easybuild/easyconfigs/t/tbb/tbb-4.4.2.152.eb
=> Add tbb-4.4.2.152.eb (Intel Parallel Studio 2016)

easybuild/easyconfigs/l/libXtst/libXtst-1.2.2-goolf-1.4.10.eb, easybuild/easyconfigs/l/libXtst/libXtst-1.2.2-goolf-1.5.14.eb, easybuild/easyconfigs/l/libXtst/libXtst-1.2.2-ictce-4.1.13.eb, easybuild/easyconfigs/l/libXtst/libXtst-1.2.2-ictce-5.3.0.eb, easybuild/easyconfigs/l/libXtst/libXtst-1.2.2-intel-2015a.eb
=> added libXtst easyconfigs

easybuild/easyconfigs/a/Advisor/Advisor-2016_update2.eb
Works with https://github.com/hpcugent/easybuild-easyblocks/pull/767
=> Add Advisor-2016_update2 easyconfig

easybuild/easyconfigs/a/ATK/ATK-2.16.0-intel-2015b.eb, easybuild/easyconfigs/a/Atkmm/Atkmm-2.22.7-intel-2015b.eb, easybuild/easyconfigs/c/cairomm/cairomm-1.10.0-intel-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.41.2-intel-2015b.eb, easybuild/easyconfigs/g/GLibmm/GLibmm-2.41.2-intel-2015b.eb, easybuild/easyconfigs/g/Gtkmm/Gtkmm-2.24.4-intel-2015b.eb, easybuild/easyconfigs/g/gdk-pixbuf/gdk-pixbuf-2.31.4-intel-2015b.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.2-intel-2015b.eb, easybuild/easyconfigs/g/gtk+/gtk+-2.24.28-intel-2015b.eb, easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-0.9.41-intel-2015b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-intel-2015b.eb, easybuild/easyconfigs/l/libffi/libffi-3.1-intel-2015b.eb, easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.4.0-intel-2015b.eb, easybuild/easyconfigs/l/libsigc++/libsigc++-2.4.1-intel-2015b.eb, easybuild/easyconfigs/n/NASM/NASM-2.11.06-intel-2015b.eb, easybuild/easyconfigs/p/Pango/Pango-1.37.1-intel-2015b.eb, easybuild/easyconfigs/p/Pangomm/Pangomm-2.36.0-intel-2015b.eb
=> {vis}[intel/2015b] Gtkmm 2.24.4 (REVIEW)

easybuild/easyconfigs/g/gtkglext/gtkglext-1.2.0-intel-2015b.eb, easybuild/easyconfigs/g/gtkglext/gtkglext-1.2.0_fix-gtk-compat.patch, easybuild/easyconfigs/m/MRtrix/MRtrix-0.2.12-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/MRtrix/MRtrix-0.2.12_fix-hardcoding.patch, easybuild/easyconfigs/m/MRtrix/MRtrix-0.2.12_no-system-wide-cfg.patch, easybuild/easyconfigs/p/pangox-compat/pangox-compat-0.0.2-intel-2015b-Pango-1.37.1.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/772 and https://github.com/hpcugent/easybuild-easyconfigs/pull/2215
=> {bio}[intel/2015b] MRtrix 0.2.12 (REVIEW)

easybuild/easyconfigs/g/gettext/gettext-0.19.6-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/g/gnutls/gnutls-3.4.7-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/g/guile/guile-1.8.8-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/lftp/lftp-4.6.4-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/libffi/libffi-3.2.1-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/libidn/libidn-1.32-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/libtasn1/libtasn1-4.7-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/nettle/nettle-3.1.1-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/p/p11-kit/p11-kit-0.23.2-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.28-GNU-4.9.3-2.25.eb
I know it is big, but mainly versionbumps. 
Needs ~~https://github.com/hpcugent/easybuild-framework/pull/1505~~
=> {tools} [GNU-4.9.3-2.25] lftp 4.6.4 (REVIEW)

easybuild/easyconfigs/m/MRtrix/MRtrix-0.3.12-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/MRtrix/MRtrix-0.3.12_fix-hardcoding.patch
requires https://github.com/hpcugent/easybuild-easyblocks/pull/772
=> {bio}[intel/2015b] MRtrix 0.3.12 (REVIEW)

easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25.eb
Like [Paraver](http://www.bsc.es/computer-sciences/performance-tools/paraver)
edit: requires ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2220~~
=> Shared libraries for binutils are needed by some apps

easybuild/easyconfigs/c/cURL/cURL-7.45.0-intel-2015b.eb, easybuild/easyconfigs/d/Doxygen/Doxygen-1.8.10-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.2-intel-2015b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-intel-2015b.eb
Needs https://github.com/hpcugent/easybuild-easyblocks/pull/734
=> {data} [intel-2015b] netCDF 4.3.3.1 and netCDF-Fortran 4.4.2 (REVIEW)

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.6-foss-2015b.eb
Easyconfig for installing Bowtie2-2.2.6-foss-2015b
=> Easyconfig for installing Bowtie2-2.2.6-foss-2015b

easybuild/easyconfigs/b/BioKanga/BioKanga-3.4.5-foss-2015b.eb, easybuild/easyconfigs/g/GSL/GSL-2.1-foss-2015b.eb
Easyconfigs for installing BioKanga 3.4.5 as requested in #2246
=> {bio}[foss/2015b] BioKanga 3.4.5 (REVIEW)

easybuild/easyconfigs/b/Boost/Boost-1.60.0-foss-2015b.eb
Working on Easyconfigs for Boost-1.60.0-foss-2015b
=> {devel}[foss/2015b] Boost 1.60.0 (REVIEW)

easybuild/easyconfigs/b/Bowtie/Bowtie-1.1.2-foss-2015b.eb
Easyconfig for installing Bowtie-1.1.2-foss-2015b
=> {bio}[foss/2015b] Bowtie 1.1.2 (REVIEW)

easybuild/easyconfigs/g/Greenlet/Greenlet-0.4.2-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/s/SCOOP/SCOOP-0.6.2-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/v/vsc-mympirun-scoop/vsc-mympirun-scoop-3.3.0-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/v/vsc-processcontrol/vsc-processcontrol-1.0-vsc-base-2.1.2.eb
(created with --new-pr)\n\nrequires #2268
=> {tools}[intel/2015b] vsc-mympirun-scoop v3.3.0, SCOOP v0.6.2 (REVIEW)

easybuild/easyconfigs/s/Spark/Spark-1.6.0.eb
Pretty simple version bump.
r @boegel
=> Add support for Spark 1.6

easybuild/easyconfigs/p/PETSc/PETSc-3.6.3-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/s/SLEPc/SLEPc-3.6.2-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.4.6-intel-2015b-ParMETIS-4.0.3.eb
(created using --new-pr)
requires https://github.com/hpcugent/easybuild-easyblocks/pull/800
=> {numlib}[intel/2015b] SLEPc v3.6.2, PETSc v3.6.3, SuiteSparse v4.4.6

easybuild/easyconfigs/s/SAMtools/SAMtools-1.2-foss-2015b.eb
Easyconfig for installing SAMtools-1.2-foss-2015b
=> {bio}[foss/2015b] SAMtools 1.2 (OK)

easybuild/easyconfigs/c/CPLEX/CPLEX-12.4.eb
- added download location
- updated homepage
=> CPLEX 12.4

easybuild/easyconfigs/l/libX11/libX11-1.6.3-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/l/libXdamage/libXdamage-1.1.4-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/l/libXext/libXext-1.3.3-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/l/libXfont/libXfont-1.5.1-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.66-intel-2015b.eb, easybuild/easyconfigs/l/libxcb/libxcb-1.11.1-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.0.8-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/x/xcb-proto/xcb-proto-1.11-intel-2015b-Python-2.7.11.eb
requires ~~#2293~~, ~~#2294~~, #2295
=> {vis}[intel/2015b] Mesa v11.0.8 + deps (REVIEW)

easybuild/easyconfigs/c/CONTRAfold/CONTRAfold-2.02-goolf-1.4.10.eb, easybuild/easyconfigs/g/GLibmm/GLibmm-2.41.2-intel-2015a.eb, easybuild/easyconfigs/g/GLibmm/GLibmm-2.41.2-intel-2015b.eb, easybuild/easyconfigs/l/libsigc++/libsigc++-2.4.1-intel-2015a.eb, easybuild/easyconfigs/l/libsigc++/libsigc++-2.4.1-intel-2015b.eb, easybuild/easyconfigs/p/psmpi/psmpi-5.1.0-1-GCC-4.9.2.eb, easybuild/easyconfigs/p/psmpi/psmpi-5.1.0-1-iccifort-2015.1.133.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.5-gmpolf-1.4.8.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.5-goolf-1.5.14.eb, easybuild/easyconfigs/r/R/R-2.15.2-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/r/R/R-2.15.2-goolf-1.4.10.eb, easybuild/easyconfigs/r/R/R-2.15.2-ictce-4.0.10.eb, easybuild/easyconfigs/r/R/R-2.15.2-ictce-4.0.6.eb, easybuild/easyconfigs/r/R/R-2.15.2-ictce-5.3.0.eb, easybuild/easyconfigs/r/R/R-2.15.3-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/r/R/R-2.15.3-goolf-1.4.10.eb, easybuild/easyconfigs/r/R/R-2.15.3-ictce-4.1.13.eb, easybuild/easyconfigs/r/R/R-2.15.3-ictce-5.3.0.eb, easybuild/easyconfigs/r/R/R-3.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/r/R/R-3.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/r/R/R-3.0.2-ictce-5.5.0.eb, easybuild/easyconfigs/r/R/R-3.1.0-ictce-5.5.0.eb, easybuild/easyconfigs/r/R/R-3.1.1-intel-2014b.eb
I'm working on a script that does some automatic style checking on easyconfigs, and ran into a bunch of tabs...
=> get rid of tabs

easybuild/easyconfigs/p/pigz/pigz-2.3.3-foss-2015b.eb, easybuild/easyconfigs/p/pigz/pigz-2.3.3_Makefile.patch
Working on Easyconfigs for pigz-2.3.3-foss-2015b
=> {tools}[foss/2015b] pigz 2.3.3 (REVIEW)

easybuild/easyconfigs/a/argtable/argtable-2.13-foss-2015b.eb, easybuild/easyconfigs/c/Clustal-Omega/Clustal-Omega-1.2.0-foss-2015b.eb
Working on Easyconfigs for Clustal-Omega-1.2.0-foss-2015b
=> {bio}[foss/2015b] Clustal-Omega 1.2.0, argtable 2.13 (OK)

easybuild/easyconfigs/t/Trilinos/Trilinos-12.4.2-intel-2015b-Python-2.7.11.eb
cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/805
=> re-enable Kokkos/Tpetra, disable STKDoc_tests

easybuild/easyconfigs/m/Molpro/Molpro-mpp-2015.1.0.linux_x86_64_intel.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/807
=> {chem}[dummy] Molpro mpp-2015.1.0.linux_x86_64_intel

easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-goalf-1.5.12-no-OFED.eb, easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-ictce-5.5.0-mt.eb, easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-ictce-5.5.0.eb, easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-intel-2015a.eb, easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-intel-2015b.eb, easybuild/easyconfigs/c/CHARMM/CHARMM-37b2-intel-2016a.eb
=> {chem} [intel/2016a] CHARMM 37b2 (REVIEW)

easybuild/easyconfigs/i/IMPUTE2/IMPUTE2-2.3.2_x86_64_dynamic.eb, easybuild/easyconfigs/i/IMPUTE2/IMPUTE2-2.3.2_x86_64_static.eb
Simple version update to 2.3.2
=> Update IMPUTE2 to 2.3.2

easybuild/easyconfigs/p/Perl/Perl-5.22.1-intel-2016a-bare.eb
=> Correct Perl download URL

easybuild/easyconfigs/b/byacc/byacc-20150711-foss-2015b.eb, easybuild/easyconfigs/b/byacc/byacc-20150711-intel-2015b.eb, easybuild/easyconfigs/g/GMP/GMP-6.0.0a-foss-2015b.eb, easybuild/easyconfigs/g/GSL/GSL-1.16-foss-2015b.eb, easybuild/easyconfigs/g/guile/guile-1.8.8-foss-2015b.eb, easybuild/easyconfigs/g/guile/guile-1.8.8-intel-2015b.eb, easybuild/easyconfigs/l/libffi/libffi-3.0.13-foss-2015b.eb, easybuild/easyconfigs/l/libffi/libffi-3.0.13-intel-2015b.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-foss-2015b.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-intel-2015b.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-foss-2015b.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-intel-2015b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.1.4-foss-2015b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.2.0-intel-2015b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.2.1-foss-2015b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.2.1-intel-2015b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-foss-2015b.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.27.1-intel-2015b.eb
Part of #2126 together with new version of Plumed.
@boegel please review
=> {chem} [foss+intel/2015b] Plumed 2.2.1 2.1.3

easybuild/easyconfigs/a/animation/animation-2.4-intel-2015b-R-3.2.1.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-2.4-intel-2014.06.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-2.4-intel-2014b.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-2.8-intel-2015b.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-2.4.9-intel-2014.06.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-2.4.9-intel-2014b.eb
as discussed on EasyBuild mailing list, (partially) fleshed out from #2425 
cc @valtandor
=> rename ffmpeg to FFmpeg

easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-goolf-1.4.10-mt-kmer_31.eb, easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-goolf-1.4.10-mt-kmer_57.eb, easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-goolf-1.4.10-mt-kmer_63.eb, easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-intel-2015b-mt-kmer_100.eb, easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-intel-2015b-mt-kmer_31.eb
MetaVelvet is part of Velvet's contrib scripts. It needs to be built.
=> Build MetaVelvet.

easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.1.4-foss-2015a.eb
=> New EasyConfig for ZeroMQ 4.1.4 with the foss-2015a toolchain

easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.1.0-foss-2015a-Python-2.7.11-zmq4.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.2.0-foss-2015a-Python-2.7.11-zmq4.eb
=> New EasyConfig for PyZMQ 15.2.0 with foss-2015a toolchain and Python 2.7.11

easybuild/easyconfigs/i/IPython/IPython-3.2.3-foss-2015a-Python-2.7.11.eb
=> New EasyConfig for IPython 3.2.3 with Python 2.7.11 and foss-2015

easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-goolf-1.4.10-hybrid-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-goolf-1.4.10-mpi-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-goolf-1.4.10-mt-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-goolf-1.4.10-seq-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-4.1.13-hybrid-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-4.1.13-mpi-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-4.1.13-mt-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-4.1.13-seq-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-5.3.0-hybrid-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-5.3.0-mpi-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-5.3.0-mt-sse3.eb, easybuild/easyconfigs/r/RAxML/RAxML-7.2.6-ictce-5.3.0-seq-sse3.eb
=> add source URL in RAxML 7.2.6 easyconfigs

easybuild/easyconfigs/u/USEARCH/USEARCH-5.2.236-i86linux32.eb, easybuild/easyconfigs/u/USEARCH/USEARCH-6.1.544-i86linux32.eb
=> add easyconfigs for USEARCH 5.2.236 and 6.1.544

easybuild/easyconfigs/r/R/R-3.2.0-goolf-1.7.20.eb
required for #2553, cfr. ~~#2547~~
=> add additional deps required for Bioconductor extensions

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-goolf-1.7.20-R-3.2.0.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-intel-2015a-R-3.2.1.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.1-intel-2015b-R-3.2.1.eb
depends on ~~#2547~~, ~~#2556~~
=> add HCsnip to Bioconductor bundles

easybuild/easyconfigs/f/fastqc/fastqc-0.11.4.eb
Simple update of this dummy toolchain EB to the latest release.
=> Update fastqc dummy to 0.11.4

easybuild/easyconfigs/p/picard/picard-2.1.0.eb
Update dependency to Java 1.8.0.
=> Update picard to 2.1.0 including move to GitHub

easybuild/easyconfigs/s/STAR/STAR-2.5.1b-foss-2015b.eb
=> Port STAR 2.5.1b to foss-2015b

easybuild/easyconfigs/c/cutadapt/cutadapt-1.5-goolf-1.4.10-Python-2.7.10.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.5-intel-2014b-Python-2.7.8.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.8.1-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/c/cutadapt/cutadapt-1.9.1-foss-2015b-Python-2.7.10.eb
Update homepage/description and authors.
=> Update cutadapt to 1.9.1 for foss-2015b

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.7-foss-2015b.eb
Worth considering whether to point to GitHub rather than SourceForge.
=> {bio}[foss-2015b] Bowtie2 2.2.7

easybuild/easyconfigs/g/GROMACS/GROMACS-5.1.2-foss-2015b-hybrid.eb
Simple update to latest upstream, using the latest CMake available for foss-2015b.
=> {bio}[foss-2015b] GROMACS 5.1.2

easybuild/easyconfigs/p/PLINK/PLINK-1.07-foss-2015b.eb, easybuild/easyconfigs/p/PLINK/PLINK-1.07_redeclaration.patch
Ignore the branch name. It's version 1.07 (1.9 is still in beta).
=> {bio}[foss-2015b] PLINK 1.07

easybuild/easyconfigs/b/Bison/Bison-3.0.2-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/c/CMake/CMake-3.2.2-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-4.6.7-CrayGNU-2015.11-XC-mpi.eb, easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/l/Libint/Libint-1.1.4-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/n/NFFT/NFFT-3.3.0-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/n/numpy/numpy-1.9.2-CrayGNU-2015.11-XC-Python-2.7.9.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-2015.11-XC-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/s/Szip/Szip-2.1-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/s/scipy/scipy-0.15.1-CrayGNU-2015.11-XC-Python-2.7.9.eb, easybuild/easyconfigs/s/spglib/spglib-1.7.3-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/t/tcsh/tcsh-6.18.01-CrayGNU-2015.11-XC.eb, easybuild/easyconfigs/w/WRF/WRF-3.6.1-CrayGNU-2015.11-XC-dmpar.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-CrayGNU-2015.11-XC.eb
The saga continues..  
This replaces PR #2403 
Now trying from a clean git branch (without git rm on the history...)
=> new CrayGNU files for 2015.11-XC

easybuild/easyconfigs/b/Bison/Bison-3.0.2-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/c/CMake/CMake-3.2.2-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/c/CP2K/CP2K-2.6.0-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-4.6.7-CrayGNU-2015.06-XC-mpi.eb, easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/l/Libint/Libint-1.1.4-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.1-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/n/NFFT/NFFT-3.3.0-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/n/numpy/numpy-1.9.2-CrayGNU-2015.06-XC-Python-2.7.9.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-2015.06-XC-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/s/Szip/Szip-2.1-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/s/scipy/scipy-0.15.1-CrayGNU-2015.06-XC-Python-2.7.9.eb, easybuild/easyconfigs/s/spglib/spglib-1.7.3-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/t/tcsh/tcsh-6.18.01-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/w/WRF/WRF-3.6.1-CrayGNU-2015.06-XC-dmpar.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-CrayGNU-2015.06-XC.eb
=> new CrayGNU files for 2015.06-XC 

easybuild/easyconfigs/a/ATSAS/ATSAS-2.7.1-1.el7.x86_64.eb
=> {bio}[dummy] ATSAS-2.7.1-1

easybuild/easyconfigs/b/BWA/BWA-0.7.13-foss-2015b.eb
Where there is a custom easyblock, should that be specified in the easyconfig, just to make things clearer?
=> {bio}[foss-2015b] BWA 0.7.13

easybuild/easyconfigs/f/freetype/freetype-2.6.2-foss-2015b.eb, easybuild/easyconfigs/h/HTSeq/HTSeq-0.6.1p1-foss-2015b-Python-2.7.10.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.21-foss-2015b.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-foss-2015b-Python-2.7.10.eb
Port HTSeq and matplotlib dep to foss-2015b.
Changed moduleclass of HTSeq from `data` to `bio`.
=> {bio} [foss,2015b] HTSeq-0.6.1p1

easybuild/easyconfigs/g/gnutls/gnutls-3.3.21-intel-2016a.eb, easybuild/easyconfigs/g/guile/guile-1.8.8-intel-2016a.eb, easybuild/easyconfigs/l/libidn/libidn-1.32-intel-2016a.eb, easybuild/easyconfigs/l/libtasn1/libtasn1-4.7-intel-2016a.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.3-intel-2016a.eb, easybuild/easyconfigs/n/nettle/nettle-3.1.1-intel-2016a.eb, easybuild/easyconfigs/p/p11-kit/p11-kit-0.23.2-intel-2016a.eb
=> {system} [intel/2016a] gnutls (REVIEW)

easybuild/easyconfigs/v/VCFtools/VCFtools-0.1.14-foss-2015b-Perl-5.20.3.eb
Remove unnecessary files_to_copy after easyblock change, following suggestion by @pescobar on IRC
=> {bio}[foss, 2015b] VCFtools-0.1.14 bugfix

easybuild/easyconfigs/h/h5py/h5py-2.4.0-intel-2015a-Python-2.7.9-serial.eb, easybuild/easyconfigs/h/h5py/h5py-2.5.0-intel-2015b-Python-2.7.10-HDF5-1.8.15-patch1-serial.eb, easybuild/easyconfigs/h/h5py/h5py-2.5.0-intel-2016a-Python-2.7.11-HDF5-1.8.16-serial.eb
=> {data} [intel/2016a] h5py/2.5.0 serial (REVIEW)

easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-foss-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.46.2-foss-2015b.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.7-foss-2015b.eb, easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2015b.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-foss-2015b.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.8.8.1-foss-2015b.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.3-foss-2015b.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-foss-2015b-no-X11.eb
Working on Easyconfigs for Exonerate-2.4.0-foss-2015b
=> {bio}[foss/2015b] libff1 3.2.1, gettext 0.19.7, GLib 2.46.2, Python 2.7.9, Exonerate 2.4.0 (REVIEW)

easybuild/easyconfigs/p/picard/picard-1.120-Java-1.8.0_66.eb, easybuild/easyconfigs/p/picard/picard-1.141-Java-1.8.0_74.eb, easybuild/easyconfigs/p/picard/picard-2.0.1-Java-1.8.0_66.eb, easybuild/easyconfigs/p/picard/picard-2.1.0-Java-1.8.0_74.eb
Easyconfig for installing picard-2.0.1-Java-1.8.0_66
edit: depends on https://github.com/hpcugent/easybuild-easyblocks/pull/796
=> {bio}[dummy/dummy] picard 1.120, picard 2.0.1 (REVIEW)

easybuild/easyconfigs/p/Python/Python-2.7.11-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-foss-2016a.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2015b.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2016a-libX11-1.6.3.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2016a.eb
to be in sync with https://github.com/hpcugent/easybuild-easyconfigs/pull/2608
@boegel  can you test the intel ones?
=> add virtualenv for python 2.7.11

easybuild/easyconfigs/f/FastQC/FastQC-0.10.1-Java-1.7.0_80.eb, easybuild/easyconfigs/f/FastQC/FastQC-0.11.2-Java-1.7.0_60.eb, easybuild/easyconfigs/f/FastQC/FastQC-0.11.3-Java-1.7.0_80.eb, easybuild/easyconfigs/f/FastQC/FastQC-0.11.4-Java-1.8.0_66.eb, easybuild/easyconfigs/f/FastQC/FastQC-0.11.4-Java-1.8.0_74.eb
follow-up for @nathanhaigh's remarks in #2267, after #2657 got merged
=> remove unneeded specs in FastQC easyconfigs

easybuild/easyconfigs/p/Perl/Perl-5.22.1-intel-2016a.eb
with updated extension versions
=> {lang}[intel/2016a] Perl 5.22.1 (REVIEW)

easybuild/easyconfigs/c/csvkit/csvkit-0.9.1-foss-2015b-Python-2.7.10.eb
=> {tool}[foss-2015b] csvkit 0.9.1 (REVIEW)

easybuild/easyconfigs/n/ncurses/ncurses-5.9-CrayGNU-2015.06-XC.eb, easybuild/easyconfigs/n/ncurses/ncurses-5.9-CrayGNU-2015.11-XC.eb
=> ncurses update to new defaults on cray

easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.0-gmpolf-1.4.8-withparmetis.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.0-goalf-1.1.0-no-OFED-withparmetis.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.0-goolf-1.4.10-withparmetis.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.0-ictce-4.0.6-withparmetis.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.0-ictce-5.3.0-withparmetis.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.1-goolf-1.4.10-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-3.7.1-ictce-5.5.0-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.2.1-goolf-1.4.10-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.2.1-ictce-5.5.0-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.2.1-intel-2014b-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.4.3-intel-2015a-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.4.5-intel-2015b-METIS-5.1.0.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.4.6-intel-2015b-ParMETIS-4.0.3.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.1-intel-2016a-METIS-5.1.0.eb
The old link is broken. It looks like the whole website moved.
=> Update dead link for SuiteSparse

easybuild/easyconfigs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25.eb, easybuild/easyconfigs/f/flex/flex-2.5.39-GCCcore-4.9.3.eb, easybuild/easyconfigs/f/flex/flex-2.5.39.eb
wrapper PR for #2528 by @sguera, fixing minor style issues (replacing tabs with spaces)
=> add M4 as build dep for binutils & flex

easybuild/easyconfigs/i/itac/itac-9.0.3.051.eb
=> {tools} [dummy] itac 9.0.3.051

easybuild/easyconfigs/p/PRINSEQ/PRINSEQ-0.20.4-foss-2015b-Perl-5.20.3.eb, easybuild/easyconfigs/p/PRINSEQ/PRINSEQ-0.20.4-foss-2015b-Perl-5.22.0.eb
Simple port to foss-2015b, including the latest bare Perl available for that toolchain.
=> {bio} [foss-2015b] PRINSEQ-0.20.4

easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.7-GCC-4.6.3-hwloc-chkpt.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.7-GCC-4.6.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.8.1-GCC-4.7.2.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-ClangGCC-1.1.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-ClangGCC-1.2.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-GCC-4.7.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9-iccifort-2011.13.367.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9a2-GCC-4.7.2.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9b-GCC-4.7.2.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9rc1-ClangGCC-1.1.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-1.9rc1-GCC-4.7.3.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-2.0.1-GCC-4.8.4.eb
combo of #2626 and #2699 by @besserox (with fix merge conflict)
requires https://github.com/hpcugent/easybuild-easyblocks/pull/853 and ~~https://github.com/hpcugent/easybuild-easyblocks/pull/854~~
=> fix (OS) deps, add checksums, remove parameter definition with default values in MVAPICH2 easyconfigs

easybuild/easyconfigs/e/Exonerate/Exonerate-2.2.0-foss-2015b.eb, easybuild/easyconfigs/g/GLib/GLib-2.34.3-foss-2015b.eb, easybuild/easyconfigs/g/gettext/gettext-0.18.2-foss-2015b.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.2-foss-2015b.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.1-foss-2015b.eb, easybuild/easyconfigs/p/Python/Python-2.7.3-foss-2015b.eb
Port Exonerate to 2.2.0, including dependencies.
=> {bio}[foss-2015b] Exonerate-2.2.0

easybuild/easyconfigs/s/sratoolkit/sratoolkit-2.5.7.eb
This is an attempt to address the maintainability concerns noted in #1790
=> {bio}[dummy] sratoolkit 2.5.7 

easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-intel-2015b-mt-kmer_100.eb, easybuild/easyconfigs/v/Velvet/Velvet-1.2.10-intel-2015b-mt-kmer_31.eb
=> reinstate building MetaVelvet and copying contrib in Velvet easyconfigs

easybuild/easyconfigs/t/TAMkin/TAMkin-1.0.8-intel-2015b-Python-2.7.10.eb
I've tested this easyconfig some time ago, so I don't expect troubles.
=> New TAMkin easyconfig

easybuild/easyconfigs/b/BEDTools/BEDTools-2.25.0-foss-2015b.eb, easybuild/easyconfigs/b/BEDTools/BEDTools-2.25.0-foss-2016a.eb
Simple port of `2.25.0` to `foss-2015b` and `foss-2016a`
=> {bio} [foss-2015b,2016a] BEDTools-2.25.0

easybuild/easyconfigs/n/NGS-Python/NGS-Python-1.2.3-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/n/NGS-Python/NGS-Python-1.2.3_fix-prefix.patch
=> {bio}[intel/2016a] NGS-Python 1.2.3 (REVIEW)

easybuild/easyconfigs/g/Greenlet/Greenlet-0.4.9-intel-2016a-Python-3.5.1.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.2.0-intel-2016a-Python-3.5.1-zmq4.eb, easybuild/easyconfigs/s/SCOOP/SCOOP-0.7.1.1-intel-2016a-Python-3.5.1.eb
depends on #2813 for dependencies
=> {tools}[intel/2016a] SCOOP 0.7.1.1 w/ Python 3.5.1 (REVIEW)

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.8-foss-2015b.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.8-foss-2016a.eb
Simple update to 2.2.8 for the two recent `foss` toolchains.
=> {bio} [foss-2015b,foss-2016a] Bowtie2-2.2.8

easybuild/easyconfigs/m/M4/M4-1.4.17-CrayGNU-2015.06.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-CrayGNU-2015.11.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.7.2.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.8.2.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.8.4.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.9.2.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-4.9.3.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GNU-4.9.2-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-GNU-5.1.0-2.25.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-foss-2014b.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-foss-2015a.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-foss-2015b.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-gimkl-2.11.5.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-ictce-5.4.0.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-ictce-5.5.0.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-ictce-7.1.2.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2014b.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2015a.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2015b.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-2016a.eb, easybuild/easyconfigs/m/M4/M4-1.4.17-intel-para-2014.12.eb, easybuild/easyconfigs/m/M4/M4-1.4.17.eb
consistent fix for #529, see also ~~#2774~~ and ~~#2779~~
=> consistently specify to use -fgnu89-inline flag in M4 1.4.17 easyconfigs

easybuild/easyconfigs/t/Tk/Tk-8.5.12-foss-2014b.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.12-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.12-goolf-1.4.10.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.12-ictce-4.0.10.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.12-ictce-4.0.6.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.12-ictce-5.3.0.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.12-intel-2014b.eb, easybuild/easyconfigs/t/Tk/Tk-8.5.15-ictce-5.3.0.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.1-ictce-5.3.0.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-GCC-4.9.2-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-foss-2015.05-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-foss-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-foss-2015b-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-gompi-1.5.16-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-goolf-1.5.14-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-goolf-1.7.20-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-intel-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-GCC-4.9.3-2.25-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-GNU-4.9.3-2.25-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-foss-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-foss-2015b-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-gimkl-2.11.5-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-goolf-1.4.10-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-goolf-1.7.20-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-ictce-7.3.5-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2015a-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2015b-no-X11.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2016a-libX11-1.6.3.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2016a-no-X11.eb
consistently apply fix done in #2778, using zlib version already used in corresponding Tcl easyconfig
=> add zlib as explicit dep in Tk easyconfigs (REVIEW)

easybuild/easyconfigs/l/libXrandr/libXrandr-1.5.0-foss-2016a.eb, easybuild/easyconfigs/r/randrproto/randrproto-1.5.0-foss-2016a.eb
libXrandr 1.5.0 easyconfig for foss-2016a toolchain
=> {vis}[foss/2016a] libXrandr 1.5.0 (REVIEW)

easybuild/easyconfigs/l/libICE/libICE-1.0.9-foss-2016a.eb, easybuild/easyconfigs/l/libSM/libSM-1.2.2-foss-2016a.eb
=> use XORG_LIB_SOURCE in libICE/libSM easyconfigs

easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-gmpolf-1.4.8-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-ictce-4.0.6-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-ictce-5.2.0-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8.1-intel-2014b-Python-2.7.8.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-intel-2015b-Python-2.7.11.eb
The previous url not contain the source. it cannot be downloaded.
=> Update source_urls parameter in ScientificPython easyconfig files

easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-gmpolf-1.4.8-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-goalf-1.1.0-no-OFED-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-ictce-4.0.6-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-ictce-5.2.0-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.8.1-intel-2014b-Python-2.7.8.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/s/ScientificPython/ScientificPython-2.9.4-intel-2015b-Python-2.7.11.eb
follow-up for #2847, where one source URL was blatently wrong...
=> add checksums in SuiteSparse easyconfigs

easybuild/easyconfigs/f/fixesproto/fixesproto-5.0-foss-2016a.eb, easybuild/easyconfigs/l/libXfixes/libXfixes-5.0.1-foss-2016a.eb, easybuild/easyconfigs/l/libXi/libXi-1.7.6-foss-2016a.eb, easybuild/easyconfigs/x/xorg-macros/xorg-macros-1.19.0-foss-2016a.eb
libXi 1.7.6 for foss-2016a toolchain
=> {vis}[foss/2016a] libXi 1.7.6 (REVIEW) 

easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.42.0-intel-2014b.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.44.0-intel-2015a.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.47.1-intel-2015b.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.47.1-intel-2016a.eb
wrapper PR for #2840 by @hajgato, also fixes sync issues with easyconfigs for version 1.47.1
=> fix build deps for GObject-Introspection + sync easyconfigs for version 1.47.1

easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016a.eb
This easyconfig file needs mesa 11.1.2 before.
needs PR #2758 by @hajgato
=> {vis}[foss/2016a] libGLU 9.0.0 (WIP)

easybuild/easyconfigs/i/IGVTools/IGVTools-2.3.72-Java-1.7.0_80.eb
=> {bio} [dummy] IGVTools-2.3.72

easybuild/easyconfigs/f/FLTK/FLTK-1.3.3-foss-2016a.eb, easybuild/easyconfigs/l/libXcursor/libXcursor-1.1.14-foss-2016a.eb, easybuild/easyconfigs/l/libXinerama/libXinerama-1.1.3-foss-2016a.eb, easybuild/easyconfigs/x/xineramaproto/xineramaproto-1.2.1-foss-2016a.eb, easybuild/easyconfigs/x/xprop/xprop-1.2.2-foss-2016a.eb
wrapper PR for #2763 by @hajgato, fixes minor style remark
=> {vis}[foss/2016a] FLTK v1.3.3 (REVIEW)

easybuild/easyconfigs/d/DBus/DBus-1.10.8-intel-2016a.eb, easybuild/easyconfigs/d/dbus-glib/dbus-glib-0.106-intel-2016a.eb, easybuild/easyconfigs/g/GConf/GConf-3.2.6-intel-2016a.eb, easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-0.10.36-intel-2016a.eb, easybuild/easyconfigs/g/GStreamer/GStreamer-0.10.36-intel-2016a.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-intel-2016a-Perl-5.22.1.eb, easybuild/easyconfigs/l/libXxf86vm/libXxf86vm-1.1.4-intel-2016a.eb, easybuild/easyconfigs/w/wxPython/wxPython-3.0.2.0-intel-2016-Python-2.7.11.eb, easybuild/easyconfigs/w/wxPython/wxPython_3.0.2.0_intel.patch, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44-intel-2016a-Perl-5.22.1.eb, easybuild/easyconfigs/x/xf86vidmodeproto/xf86vidmodeproto-2.3.1-intel-2016a.eb
Needs EasyBlock https://github.com/hpcugent/easybuild-easyblocks/pull/515
and PR ~~#2840~~
=> {vis}[intel-2016a] wxPython 3.0.2.0 (REVIEW)

easybuild/easyconfigs/b/bam-readcount/bam-readcount-0.7.4-cmake_install_prefix.patch, easybuild/easyconfigs/b/bam-readcount/bam-readcount-0.7.4-foss-2015b.eb
New easyconfig for bam-readcount.
The patch fixes hardcoding of the installation prefix.
=> {bio} [foss-2015b] bam-readcount-0.7.4 (REVIEW)

easybuild/easyconfigs/g/GROMACS/GROMACS-5.1.2-foss-2016a-hybrid.eb
=> {bio} [foss-2016a] GROMACS-5.1.2

easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.1-foss-2016a-Python-2.7.11.eb
matplotlib 1.5.1 for foss 2016a
=> {vis}[foss/2016a] matplotlib 1.5.1(REVIEW)

easybuild/easyconfigs/g/gettext/gettext-0.19.7-foss-2016a.eb, easybuild/easyconfigs/g/git/git-2.8.0-foss-2016a.eb, easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a-bare.eb
=> {tool}[foss/2016a] git 2.8.0 (REVIEW)

easybuild/easyconfigs/a/ABySS/ABySS-1.9.0-foss-2016a.eb
=> ABySS foss2016a

easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.23-intel-2016a.eb
=> {vis}[intel-2016a] GraphicsMagick 1.3.23 - Octave needs PIC (REVIEW) 

easybuild/easyconfigs/c/cairo/cairo-1.14.6-intel-2016a.eb, easybuild/easyconfigs/l/libXext/libXext-1.3.3-intel-2016a.eb, easybuild/easyconfigs/l/libXrender/libXrender-0.9.9-foss-2016a.eb
=> fix (build) deps for intel/2016a easyconfigs of cairo, libXext, libXrender

easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-foss-2016a-Python-2.7.11.eb
=> ANTLR foss2016a

easybuild/easyconfigs/b/BayesAss/BayesAss-3.0.4-foss-2016a.eb
=> BayesAss with foss 2016a

easybuild/easyconfigs/p/Python/Python-2.7.11-foss-2015a.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-foss-2016a.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-gimkl-2.11.5.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2015b.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2016a-libX11-1.6.3.eb, easybuild/easyconfigs/p/Python/Python-2.7.11-intel-2016a.eb
replacement PR for #2819, reported by @stachon (& others, cfr. EasyBuild ML)
=> fix bitstring 3.1.3 download URL

easybuild/easyconfigs/b/BCFtools/BCFtools-1.3-foss-2016a.eb
=> Bcftools foss2016a

easybuild/easyconfigs/o/OptiX/OptiX-3.8.0-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/o/OptiX/OptiX-3.9.0-GNU-4.9.3-2.25.eb
OptiX library is a VMD requirement
=> add Nvidia OptiX 3.x easyconfig

easybuild/easyconfigs/w/worker/worker-1.5.1-intel-2015a.eb
fix for #2845, depends on ~~#2883~~
=> fix Perl dependency in worker, it required non-standard Perl modules

easybuild/easyconfigs/c/CUDA/CUDA-7.0.28.eb
Preferred CUDA version for some software (VMD, OpenMM, etc.)
=> add easyconfig for CUDA 7.0.28

easybuild/easyconfigs/s/SIONlib/SIONlib-1.6.1-foss-2016a-tools.eb, easybuild/easyconfigs/s/SIONlib/SIONlib-1.6.1-foss-2016a.eb
SIONlib is a scalable I/O library.  The tools version is an optional dependency of OTF2, used by Score-P and Scalasca.
=> {lib}[foss/2016a] Add easyconfigs for SIONlib (regular and tools) (REVIEW)

easybuild/easyconfigs/p/packmol/packmol-16.103-intel-2016a.eb
This is a relatively trivial update and fix for packmol. Works for me.
=> Fix packmol eb and add newest version

easybuild/easyconfigs/e/Eigen/Eigen-3.2.7-foss-2016a.eb
add Eigen 3.2.7 easyconfig for foss 2016a
=> {math}[foss/2016a] Eigen 3.2.7 (REVIEW)

easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCCcore-4.9.2.eb
Requires https://github.com/hpcugent/easybuild-easyconfigs/pull/2911
=> New EasyConfig for zlib with the GCCcore 4.9.2 compiler

easybuild/easyconfigs/m/M4/M4-1.4.17-GCCcore-4.9.2.eb
Requires https://github.com/hpcugent/easybuild-easyconfigs/pull/2911.
=> New EasyConfig for M4 1.4.17 with the GCCcore 4.9.2 toolchain

easybuild/easyconfigs/w/Wannier90/Wannier90-1.2-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/w/Wannier90/Wannier90-2.0.1-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/w/Wannier90/Wannier90_1x_ignore_makesys.patch, easybuild/easyconfigs/w/Wannier90/Wannier90_2x_ignore_makesys.patch
Using "MakeCp" easyblock since there is no configure step, still needs an ugly hack to skip the need for a make.sys file...
=> Wannier90-1.2 and 2.0.1 using toolchain intel-2016.02-GCC-4.9

easybuild/easyconfigs/g/GDB/GDB-7.10.1-foss-2016a-Python-2.7.11.eb
add gdb easyconfig for foss 2016a toolchain
=> {debugger}[foss/2016a] GDB 7.10.1 (REVIEW)

easybuild/easyconfigs/f/FSL/FSL-5.0.9-intel-2016a.eb, easybuild/easyconfigs/f/FSL/FSL-5.0.9_missing_lib.patch
=> {bio} [intel/2016a] FSL 5.0.9 (REVIEW)

.travis.yml
depends on ~~https://github.com/hpcugent/easybuild-framework/pull/1733~~
=> add test configuration for Travis

.travis.yml
just like https://github.com/hpcugent/easybuild-easyblocks/pull/897
=> also test with Lmod as modules tool on Travis

.travis.yml
cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/900
=> install easybuild-framework & easybuild-easyblocks via git clone && easy_install

easybuild/easyconfigs/f/FASTX-Toolkit/FASTX-Toolkit-0.0.14-foss-2016a.eb
=> FASTX-Toolkit-0.0.14 with foss 2016a

test/easyconfigs/easyconfigs.py
required after https://github.com/hpcugent/easybuild-framework/pull/1735 gets merged
=> fix use of resolve_dependencies in tests

easybuild/easyconfigs/v/VarScan/VarScan-2.3.6-Java-1.7.0_80.eb
Cleanup macros and provide legacy version
=> {bio} [dummy] VarScan-2.3.6,2.4.1-1.7.0_80.eb

easybuild/easyconfigs/m/MuTect/MuTect-1.1.7-Java-1.7.0_80.eb
Update MuTect for 1.1.7 from new download site.
=> {bio} [dummy] MuTect-1.1.7-1.7.0_80.eb

easybuild/easyconfigs/l/libQGLViewer/libQGLViewer-2.6.3-foss-2016a.eb
libQGLViewer easyconfig for foss
needs easyblock [hpcugent/easybuild-easyblocks#890 ](https://github.com/hpcugent/easybuild-easyblocks/pull/890)
=> {lib}[foss/2016a] libQGLViewer 2.6.3 (REVIEW)

easybuild/easyconfigs/i/IPython/IPython-3.2.3-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/l/libsodium/libsodium-1.0.8-foss-2016a.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-foss-2016a.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.2.0-foss-2016a-Python-2.7.11-zmq4.eb, easybuild/easyconfigs/u/util-linux/util-linux-2.27.1-foss-2016a.eb, easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.1.4-foss-2016a.eb
support for IPython 3.2.3 with foss 2016a toolchain
=> {tools}[foss/2016a] IPython 3.2.3 (REVIEW)

easybuild/easyconfigs/c/CMake/CMake-3.5.2-foss-2016a.eb, easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-foss-2016a-Mesa-11.2.1.eb, easybuild/easyconfigs/f/freetype/freetype-2.6.3-foss-2016a.eb, easybuild/easyconfigs/g/GL2PS/GL2PS-1.3.9-foss-2016a-Mesa-11.2.1.eb, easybuild/easyconfigs/l/LLVM/LLVM-3.8.0-foss-2016a.eb, easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016a-Mesa-11.2.1.eb, easybuild/easyconfigs/l/libXfont/libXfont-1.5.1-foss-2016a-freetype-2.6.3.eb, easybuild/easyconfigs/l/libdrm/libdrm-2.4.68-foss-2016a.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.2.1-foss-2016a.eb, easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.0.1s-foss-2016a.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1-foss-2016a.eb
=> {vis}[foss/2016a] GL2PS-1.3.9-Mesa-11.2.1(REVIEW)

easybuild/easyconfigs/c/Commet/Commet-20150415-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/c/Commet/Commet-20160422-foss-2016a-Python-2.7.11.eb
Source has to be downloaded manually. Source is renamed to Commet-20160422.zip
=> Commet with foss2016a

easybuild/easyconfigs/w/worker/worker-1.5.1-intel-2015a.eb, easybuild/easyconfigs/w/worker/worker-1.6.4-intel-2016a.eb
#2997 was missing a `../` in the added sed command...
=> correct sed command in worker easyconfig files to fix module_path in conf/worker.conf

easybuild/easyconfigs/g/GLib/GLib-2.48.0-foss-2016a.eb, easybuild/easyconfigs/g/GTS/GTS-0.7.6-foss-2016a.eb, easybuild/easyconfigs/p/PyGTS/PyGTS-0.3.1-foss-2016a-Python-2.7.11.eb
add PyGTS easyconfig it's a dependency needed by Yade 1.20.0
=> {vis}[foss/2016a] PyGTS 0.3.1 (REVIEW)

easybuild/easyconfigs/l/libQGLViewer/libQGLViewer-2.6.3-foss-2016a-Mesa-11.2.1.eb, easybuild/easyconfigs/q/Qt/Qt-4.8.7-foss-2016a-GLib-2.48.0.eb
using Mesa 11.2.1 and GLib 2.48.0
needs PR #2969 to get GLib 2.48.0
=> {lib}[foss/2016a] LibQGLViewer 2.6.3-mesa 11.2.1 (REVIEW)

easybuild/easyconfigs/b/binutils/binutils-2.22-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/b/binutils/binutils-2.22-gompi-1.4.12-no-OFED.eb, easybuild/easyconfigs/b/binutils/binutils-2.22-goolf-1.4.10.eb, easybuild/easyconfigs/b/binutils/binutils-2.22-goolf-1.5.14.eb, easybuild/easyconfigs/b/binutils/binutils-2.24-foss-2014b.eb, easybuild/easyconfigs/b/binutils/binutils-2.24-intel-2014b.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.2.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCCcore-4.9.2.eb, easybuild/easyconfigs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb, easybuild/easyconfigs/b/binutils/binutils-2.25.1.eb, easybuild/easyconfigs/b/binutils/binutils-2.25.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/907
=> clean up binutils easyconfigs to use binutils easyblock

easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-foss-2016a.eb
=> Yasm with foss 2016a

easybuild/easyconfigs/n/NASM/NASM-2.12.01-foss-2016a.eb
=> NASM with foss 2016a

easybuild/easyconfigs/f/FLASH/FLASH-1.2.11-foss-2016a.eb
=> FLASH with foss 2016a

easybuild/easyconfigs/f/FLANN/FLANN-1.8.4-intel-2016a-Python-2.7.11.eb, test/easyconfigs/easyconfigs.py
this slipped through in #3015 
tests are enhanced to make sure it doesn't occur again...
=> fix empty moduleclass in FLANN easyconfig, make sure it doesn't happen again

easybuild/easyconfigs/b/Boost/Boost-1.60.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.8-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/e/expat/expat-2.1.1-foss-2016a.eb, easybuild/easyconfigs/f/fontconfig/fontconfig-2.11.95-foss-2016a.eb, easybuild/easyconfigs/i/intltool/intltool-0.51.0-foss-2016a-Perl-5.22.1.eb, easybuild/easyconfigs/l/libxkbcommon/libxkbcommon-0.6.1-foss-2016a.eb, easybuild/easyconfigs/m/MPFR/MPFR-3.1.4-foss-2016a.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.6.0-foss-2016a.eb, easybuild/easyconfigs/x/XKeyboardConfig/XKeyboardConfig-2.17-foss-2016a.eb, easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44-foss-2016a-Perl-5.22.1.eb, easybuild/easyconfigs/x/xcb-util-image/xcb-util-image-0.4.0-foss-2016a.eb, easybuild/easyconfigs/x/xcb-util-keysyms/xcb-util-keysyms-0.4.0-foss-2016a.eb, easybuild/easyconfigs/x/xcb-util-renderutil/xcb-util-renderutil-0.3.9-foss-2016a.eb, easybuild/easyconfigs/x/xcb-util-wm/xcb-util-wm-0.4.1-foss-2016a.eb, easybuild/easyconfigs/x/xcb-util/xcb-util-0.4.0-foss-2016a.eb
easyconfig CGAL 4.8 with foss_2016a toolchain
=> {numlib}[foss/2016a] CGAL 4.8 (REVIEW)

easybuild/easyconfigs/h/HPL/HPL-2.1-intel-2016.03-GCC-5.3.eb, easybuild/easyconfigs/i/icc/icc-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/iccifort/iccifort-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.03-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/impi/impi-5.1.3.181-iccifort-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/intel/intel-2016.03-GCC-5.3.eb
=> {toolchain}[dummy] intel/2016.03-GCC-5.3

easybuild/easyconfigs/n/NBO/NBO-1.1-intel-2016a.eb, easybuild/easyconfigs/n/NBO/projection-1.1.2_MKL95.patch
=> also build projection.exe tool in NBO easyconfig

easybuild/easyconfigs/h/HPL/HPL-2.1-pomkl-2016.03.eb
see discussion in https://github.com/hpcugent/easybuild-easyconfigs/pull/2900
requires: https://github.com/hpcugent/easybuild-framework/pull/1761
cc @bartoldeman
=> remove hack in HPL pomkl easyconfig for linking with -ldl

easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.1-intel-2016a-METIS-5.1.0.eb, easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.2-intel-2016a-METIS-5.1.0.eb
After the update of SuiteSparse easyblock in https://github.com/hpcugent/easybuild-easyblocks/pull/863, remove the now-unnecessary lines.
=> Update SuiteSparse easyconfigs

easybuild/easyconfigs/v/VASP/VASP-5.4.1-intel-2016.02-GCC-4.9.eb
Not sure if you're interested in this one (if not, just go ahead and reject the pull request).
On one hand, it's proprietary, so you can only test it if you have access to the package and put it the sources folder (but there are other cases like this in the repository).
On the other hand, again, I couldn't get completely away from some nasty overrides.
=> [phys]{intel/2016.02-GCC-4.9} VASP 5.4.1

easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2016-05-01-foss-2016a.eb
=> GMAP-GSNAP with foss2016a

easybuild/easyconfigs/h/HPL/HPL-2.1-pomkl-2016.04.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-PGI-16.3-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-PGI-16.4-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-pompi-2016.04.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-5.3.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.3-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.2-PGI-16.4-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/p/PGI/PGI-16.4-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/p/pomkl/pomkl-2016.04.eb, easybuild/easyconfigs/p/pompi/pompi-2016.04.eb
PGI-based toolchain for latest PGI 16.4 on top of GCC 5.3.0 and binutils 2.26
requires ~~https://github.com/hpcugent/easybuild-easyblocks/pull/916~~ and ~~https://github.com/hpcugent/easybuild-framework/pull/1761~~
=> {toolchain}[pomkl/2016.04] HPL 2.1 (REVIEW)

easybuild/easyconfigs/c/CrayPGI/CrayPGI-2016.04.eb
PrgEnv-pgi support
- depends on https://github.com/hpcugent/easybuild-framework/pull/1729
=> PrgEnv-pgi support

easybuild/easyconfigs/m/MRtrix/MRtrix-0.3.14-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/m/MRtrix/MRtrix-0.3.14_intel-fixes.patch
requires https://github.com/hpcugent/easybuild-easyblocks/pull/932
=> {bio}[intel/2016a] MRtrix 0.3.14 (REVIEW)

easybuild/easyconfigs/b/Boost/Boost-1.60.0-intel-2016a.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-5.1.2-intel-2016a-hybrid.eb
=> {bio} [intel/2016a] Gromacs/5.1.2

easybuild/easyconfigs/v/VTune/VTune-2013_update10.eb, easybuild/easyconfigs/v/VTune/VTune-2013_update11.eb, easybuild/easyconfigs/v/VTune/VTune-2013_update12.eb, easybuild/easyconfigs/v/VTune/VTune-2013_update6.eb, easybuild/easyconfigs/v/VTune/VTune-2013_update8.eb, easybuild/easyconfigs/v/VTune/VTune-2013_update9.eb, easybuild/easyconfigs/v/VTune/VTune-2016_update3.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/935
=> 	add easyconfigs for VTune versions 2013 update 11, 2013 update 12 and 2016 update 3

easybuild/easyconfigs/i/Inspector/Inspector-2013_update6.eb, easybuild/easyconfigs/i/Inspector/Inspector-2013_update7.eb, easybuild/easyconfigs/i/Inspector/Inspector-2016_update3.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/934
=> add easyconfigs for Inspector versions 2013 update 7 and 2016 update 3

easybuild/easyconfigs/e/ESMF/ESMF-7.0.0-foss-2016a.eb, easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.2-foss-2016a.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.3-foss-2016a.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.0-foss-2016a.eb
In addition to `ESMF-7.0.0-foss-2016a.eb` I've also included the dependent `*.eb` files I needed for a successful build (in separate commits so they can be cherry-picked, or not, as needed.)
=> ESMF-7.0.0-foss-2016a and netCDF dependencies

easybuild/easyconfigs/b/byacc/byacc-20160324-intel-2016a.eb, easybuild/easyconfigs/c/CP2K/CP2K-3.0-intel-2016a.eb, easybuild/easyconfigs/l/Libint/Libint-1.1.4-intel-2016a.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-intel-2016a.eb, easybuild/easyconfigs/l/libxc/libxc-2.2.3-intel-2016a.eb, easybuild/easyconfigs/l/libxc/libxc-3.0.0-intel-2016a.eb, easybuild/easyconfigs/l/libxsmm/libxsmm-1.4-intel-2016a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.2.2-intel-2016a.eb
Fleshed out from PR #2889 
Needs https://github.com/hpcugent/easybuild-easyblocks/pull/942
=> {chem} [intel/2016a] CP2K 3.0 default popt version  (REVIEW)

easybuild/easyconfigs/h/HPL/HPL-2.1-intel-2016.03-GCC-5.4.eb, easybuild/easyconfigs/i/icc/icc-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iccifort/iccifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.03-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpi-2016.03-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/impi/impi-5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/intel/intel-2016.03-GCC-5.4.eb
=> {toolchain}[dummy] intel/2016.03-GCC-5.4 (REVIEW)

easybuild/easyconfigs/j/jemalloc/jemalloc-4.2.0-intel-2016a.eb, easybuild/easyconfigs/m/MariaDB/MariaDB-10.1.14-intel-2016a.eb, easybuild/easyconfigs/m/MySQL-python/MySQL-python-1.2.5-intel-2016a-Python-2.7.11-MariaDB-10.1.14.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2-intel-2016a-gettext-0.19.7.eb
=> {data,lib}[intel/2016a] MariaDB 10.1.14 + MySQL-python 1.2.5

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.2.2-intel-2016a.eb, easybuild/easyconfigs/o/OpenFOAM/cleanup-OpenFOAM-2.2.2.patch
=> {cae} [intel/2016a] OpenFOAM 2.2.2 (REVIEW)

easybuild/easyconfigs/p/pip/pip-8.1.2-foss-2016a-Python-2.7.11.eb
Pip 8.1.2 config using the foss 2016a toolchain.
=> Pip 8.1.2 for foss 2016a

easybuild/easyconfigs/w/wheel/wheel-0.29.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/w/wheel/wheel-0.29.0-foss-2016a-Python-3.5.1.eb
Easyconfigs for installing the python wheel module.
=> Easyconfigs for wheel using the foss 2016a toolchain.

easybuild/easyconfigs/g/Gurobi/Gurobi-6.5.1.eb
Requires the Gurobi easyblock from the following PR:
https://github.com/hpcugent/easybuild-easyblocks/pull/962
=> Gurobi 6.5.1

easybuild/easyconfigs/s/SWIG/SWIG-3.0.8-foss-2016a-Python-3.5.1.eb
Foss 2016a version of SWIG for Python 3.5.1
=> Foss 2016a version of SWIG for Python 3.5.1

easybuild/easyconfigs/c/CrayGNU/CrayGNU-2016.04.eb, easybuild/easyconfigs/h/HPL/HPL-2.1-CrayGNU-2016.04.eb
Tested on Piz Daint and Titan (to build EBs from https://github.com/hpcugent/easybuild-easyconfigs/pull/3219)
=> {toolchain}[dummy/dummy] CrayGNU v2016.04

easybuild/easyconfigs/i/IMa2p/IMa2p-20151123-foss-2016a.eb
=> IMa2p built using foss 2016a

easybuild/easyconfigs/a/ant/ant-1.9.6-Java-1.8.0_77.eb
Version of ant for Java 1.8.0_77
=> Version of ant for Java 1.8.0_77

easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.2.3.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.3.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.0.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.1.eb, easybuild/easyconfigs/g/GC3Pie/GC3Pie-2.4.2.eb
=> add python-dev(el) to osdeps in GC3Pie easyconfigs

easybuild/easyconfigs/h/HMMER/HMMER-3.0-goalf-1.1.0-no-OFED.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.0-goolf-1.4.10.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.0-ictce-4.0.6.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.0-ictce-5.3.0.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.1b1-goolf-1.4.10.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.1b1-ictce-5.3.0.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.1b1-ictce-6.2.5.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-foss-2016a.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-intel-2015a.eb
=> fix homepage & source_urls in HMMER easyconfigs

easybuild/easyconfigs/g/GDAL/GDAL-2.1.0-foss-2016b.eb, easybuild/easyconfigs/g/GDAL/GDAL-2.1.0-intel-2016b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-foss-2016b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-intel-2016b.eb, easybuild/easyconfigs/r/R/R-3.3.1-foss-2016b.eb, easybuild/easyconfigs/r/R/R-3.3.1-intel-2016b.eb
=> add SQLite as dep to GDAL 2.1.0 easyconfigs, add zlib/SQLite/LibTIFF as dep to R 3.3.1 easyconfigs

easybuild/easyconfigs/p/PLINKSEQ/PLINKSEQ-0.10-goolf-1.7.20.eb, easybuild/easyconfigs/p/protobuf/protobuf-2.5.0-goolf-1.7.20.eb
wrapper PR for #1480 by @pescobar, only adds minor style fixes
=> {bio}[goolf-1.7.20] PLINKSEQ-0.10 (REVIEW)

easybuild/easyconfigs/p/ProbABEL/ProbABEL-0.5.0.eb
Created an EasyConfig for ProbABEL v0.5.0
=> ProbABEL v0.5.0

easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-5.3.0.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016.04.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0_gcc-5.patch
Also included patch from ncurses upstream to fix the actual problem.
=> Add easyconfigs for ncurses when building with gcc 5

easybuild/easyconfigs/b/BayeScEnv/BayeScEnv-1.1-foss-2016a.eb
Based on the existing BayeScEnv-1.1-goolf-1.4.10.eb.
=> {bio}[foss/2016a] BayeScEnv 1.1

easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-foss-2016a.eb
JasPer 1.900.1 using the foss 2016a toolchain.
=> JasPer 1.900.1 using the foss 2016a toolchain.

easybuild/easyconfigs/g/gflags/gflags-2.1.2-foss-2016a.eb, easybuild/easyconfigs/g/glog/glog-0.3.4-foss-2016a.eb, easybuild/easyconfigs/l/LMDB/LMDB-0.9.18-foss-2016a.eb, easybuild/easyconfigs/l/LevelDB/LevelDB-1.18-foss-2016a.eb
combo of #3370, #3371, #3374, #3372 by @FokkeDijkstra with minor style fixes on top
=> {*}[foss/2016b] gflags 2.1.2, glog 0.3.4, LevelDB 1.18, LMDB 0.9.18

easybuild/easyconfigs/g/gflags/gflags-2.1.2-foss-2016a.eb
gflags compiled using the foss 2016a toolchain.
=> gflags compiled using the foss 2016a toolchain.

easybuild/easyconfigs/g/glog/glog-0.3.4-foss-2016a.eb
glog 0.3.4 compiled using foss 2016a toolchain.
=> glog 0.3.4 compiled using foss 2016a toolchain.

easybuild/easyconfigs/l/LMDB/LMDB-0.9.18-foss-2016a.eb
LMDB compiled using foss 2016a
=> LMDB compiled using foss 2016a

easybuild/easyconfigs/l/LevelDB/LevelDB-1.18-foss-2016a.eb
LevelDB compiled using the foss 2016a toolchain.
=> LevelDB compiled using the foss 2016a toolchain.

easybuild/easyconfigs/d/DMTCP/DMTCP-2.4.5.eb
wrapper PR for #3383, includes minor style fixes on top
=> {tools}[dummy] DMTCP 2.4.5

easybuild/easyconfigs/c/configparser/configparser-3.5.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/e/entrypoints/entrypoints-0.2.2-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/i/IPython/IPython-5.1.0-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/l/libsodium/libsodium-1.0.11-intel-2016b.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-intel-2016b.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-15.4.0-intel-2016b-Python-2.7.12-zmq4.eb, easybuild/easyconfigs/p/path.py/path.py-8.2.1-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/pip/pip-8.1.2-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/prompt-toolkit/prompt-toolkit-1.0.6-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/t/testpath/testpath-0.3-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/u/util-linux/util-linux-2.28.1-intel-2016b.eb, easybuild/easyconfigs/w/wcwidth/wcwidth-0.1.7-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.1.5-intel-2016b.eb
based on #3368, with updated software versions and for `intel/2016b` toolchain
=> {lang}[intel/2016b] IPython 5.1.0 w/ Python 2.7.12

easybuild/easyconfigs/h/hwloc/hwloc-1.11.3-intel-2016b.eb, easybuild/easyconfigs/m/mympingpong/mympingpong-0.7.1-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-intel-2016b.eb
=> Add missing dep to mympingpong

easybuild/easyconfigs/s/Stacks/Stacks-1.42-foss-2016a.eb
Stacks version 1.42 compiled with the foss 2016a toolchain.
=> Stacks 1.42 compiled with the foss 2016a toolchain.

easybuild/easyconfigs/m/mpi4py/mpi4py-2.0.0-intel-2016b-Python-2.7.12.eb
Second attempt of a PR into the EB main develop branch
=> mpi4py 2.0.0 version for python 2.7.12 and intel 2016b

easybuild/easyconfigs/a/AutoGrid/AutoGrid-4.2.5.1-GCC-5.2.0.eb
An easyconfig for AutoGrid 4.2.5.1 built with the toolchain GCC 5.2.0.
Also, see #3465.
=> {tools}[GCC/5.2.0] AutoGrid 4.2.5.1

easybuild/easyconfigs/p/py/py-1.4.31-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/pyGIMLi/pyGIMLi-20160803-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/pygccxml/pygccxml-20160706-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/pyplusplus/pyplusplus-20160707-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/pytest/pytest-3.0.1-foss-2016a-Python-2.7.11.eb
=> {geo}[foss-2016a] pyGIMLi - Python 2.7.11 (REVIEW)

easybuild/easyconfigs/p/pandas/pandas-0.18.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/pandas/pandas-0.18.0-foss-2016a-Python-3.5.1.eb
For both version 2.7.x and 3.5.x version of python
=> {lib}[foss/2016a] pandas v0.18.0

easybuild/easyconfigs/n/NAMD/NAMD-2.10b1-ictce-5.5.0-ibverbs.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.10b1-ictce-5.5.0-mpi.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.9-gmvapich2-1.7.12-ibverbs.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.9-gmvolf-1.7.12-ibverbs.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.9-goolf-1.4.10-ibverbs.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.9-ictce-5.5.0-ibverbs.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.9-ictce-5.5.0-mpi.eb
cfr. https://github.com/hpcugent/easybuild/issues/225
=> add tcsh as OS dep in NAMD easyconfigs

easybuild/easyconfigs/c/cairo/cairo-1.14.6-foss-2016a-GLib-2.48.0.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.48.0-foss-2016a.eb, easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.6.4-foss-2016a.eb, easybuild/easyconfigs/g/GStreamer/GStreamer-1.6.4-foss-2016a.eb
GStreamer 1.6.4 built using the foss 2016a toolchain and the GST base plugins.
=> GStreamer 1.6.4 using the foss 2016a toolchain and the base plugins.

easybuild/easyconfigs/h/HPL/HPL-2.1-pomkl-2016.09.eb, easybuild/easyconfigs/h/HPL/HPL-2.2-pomkl-2016.09.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-PGI-16.7-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-pompi-2016.09.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.10.4-PGI-16.7-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/p/pomkl/pomkl-2016.09.eb, easybuild/easyconfigs/p/pompi/pompi-2016.09.eb
Both included HPL give good performance on our local cluster
=> First complete fileset for an pomkl, using openmpi 1.10.4 and mkl

easybuild/easyconfigs/c/cppcheck/cppcheck-1.75-intel-2015b.eb
This needs https://github.com/hpcugent/easybuild-easyblocks/pull/983
Using 2015b because it is the only toolchain with Qt5, but it should work with Qt4 as well.
=> Cppcheck easyconfig

easybuild/easyconfigs/p/Pango/Pango-1.40.1-foss-2016a.eb
The config is based on the intel 2016a version.
=> Version of Pango compiled using the foss 2016a toolchain.

easybuild/easyconfigs/g/GTK+/GTK+-2.24.30-foss-2016a.eb
The config is based on the intel 2016a version.
=> Version of GTK+ using the foss 2016a toolchain.

easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.0.2-foss-2016a.eb
FFmpeg 3.0.2 compiled using the foss 2016a toolchain.
=> FFmpeg 3.0.2 compiled using the foss 2016a toolchain.

easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016a.eb
Gstreamer has been added as an extra dependency compared to the intel 2016a toolchain.
=> Version of OpenCV 3.1.0 using the foss 2016a toolchain

easybuild/easyconfigs/b/Blender/Blender-2.77a-intel-2016b-Python-3.5.2.eb
=> make sure EasyBuild is in full control over optimization flags in Blender easyconfig

easybuild/easyconfigs/p/PSI4/PSI4-1.0-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/p/PSI4/PSI4-1.0-intel-2016a-mt-Python-2.7.11.eb
hpcugent/easybuild-easyblocks#967
=> Adjust PSI4 easyconfigs for updated easyblock

easybuild/easyconfigs/b/BayeScan/BayeScan-2.1-foss-2016a.eb
Based on the easyconfig in #2748 and includes a fix for the Makefile
=> {bio}[foss/2016a] BayeScan 2.1

easybuild/easyconfigs/r/R/R-3.2.3-intel-2016a-libX11-1.6.3.eb
cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/995
=> remove --with-tcl-config/--with-tk-config from R easyconfig, already done in R easyblock

easybuild/easyconfigs/h/h5py/h5py-2.6.0-intel-2016b-Python-3.5.2-HDF5-1.8.17.eb, easybuild/easyconfigs/k/Keras/Keras-1.0.8-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016b-Python-3.5.2.eb
=> {data} [intel/2016b] Keras/1.0.8 (REVIEW)

easybuild/easyconfigs/g/Graphviz/Graphviz-2.38.0-intel-2014b.eb, easybuild/easyconfigs/g/Graphviz/Graphviz-2.38.0-intel-2015a-Python-2.7.10.eb
=> make sure & check that Graphviz does not install Tcl bindings in Tcl install prefix

easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCC-4.8.4.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-GCC-4.8.2.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3-GCC-4.8.4.eb, easybuild/easyconfigs/l/libreadline/libreadline-6.3.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-GCC-4.8.4.eb, easybuild/easyconfigs/p/Python/Python-2.7.9-GCC-4.8.4-bare.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.8.8.1-GCC-4.8.4.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.3-GCC-4.8.4.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.3-GCC-4.8.4-no-X11.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCC-4.7.3.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8-GCC-4.8.4.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.8.eb
missing build deps for Clang 3.6.0 in #1410
=> {lang,lib}[GCC/4.8.4] Python 2.7.9 (bare) + libxml2 2.9.2

easybuild/easyconfigs/n/networkx/networkx-1.11-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/n/networkx/networkx-1.11-foss-2016a-Python-3.5.1.eb
networkx 1.11 compiled using the foss 2016a toolchain.
=> networkx 1.11 compiled using the foss 2016a toolchain.

easybuild/easyconfigs/a/angsd/angsd-0.910-foss-2016a.eb
Easyconfig for angsd 0.910 using the foss 2016a toolchain.
=> Easyconfig for angsd 0.910 using the foss 2016a toolchain.

easybuild/easyconfigs/l/LeadIT/LeadIT-2.1.9.eb
this easyconfig was added in #3345, but (accidentally) removed in #3385
=> LeadIT 2.1.9

easybuild/easyconfigs/g/GCCcore/GCCcore-6.2.0.eb
=> fix source URL in GCCcore 6.2.0 easyconfig

easybuild/easyconfigs/g/GSL/GSL-2.2.1-intel-2016a.eb, easybuild/easyconfigs/g/GSL/GSL-2.2.1-intel-2016b.eb, easybuild/easyconfigs/s/STAMP/STAMP-1.3-intel-2016b.eb
the bump of GSL to 2.2.1 should have been part of #3613...
=> {bio}[intel/2016a,intel/2016b] add STAMP 1.3 with dep on GSL 2.2.1

easybuild/easyconfigs/r/RAxML/RAxML-8.2.9-foss-2016a-hybrid-avx2.eb
=> {bio}[foss/2016a] RAxML 8.2.9

easybuild/easyconfigs/p/Pillow/Pillow-3.2.0-foss-2016a-Python-2.7.11-freetype-2.6.3.eb, easybuild/easyconfigs/p/Pillow/Pillow-3.2.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.12.3-foss-2016a-Python-2.7.11.eb
scikit-image built with the foss-2016a toolchain, including the Pillow dependency.
=> scikit-image built with the foss-2016a toolchain

easybuild/easyconfigs/i/icc/icc-2017.0.35-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iccifort/iccifort-2017.0.35-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.0.35-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017.00-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-2017.0.098-iimpi-2017.00-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/imkl/imkl-2017.0.98-iimpi-2017.00-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/impi/impi-2017.0.98-iccifort-2017.0.35-GCC-5.4.0-2.26.eb
Installer currently doesn't work (invalid components).
=> {dev} [dummy] intel/2017.00 (REVIEW)

easybuild/easyconfigs/f/FLTK/FLTK-1.3.3-foss-2016b.eb, easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016b.eb, easybuild/easyconfigs/x/xprop/xprop-1.2.2-foss-2016b.eb
=> {vis}[foss/2016b] FLTK 1.3.3 (REVIEW)

easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.5-intel-2016b.eb
=> {vis}[intel/2016b] gnuplot 5.0.5 (REVIEW)

easybuild/easyconfigs/b/behave/behave-1.2.5-foss-2016b-Python-2.7.12.eb
This is a nice little piece of software.
We use it for our vasp test suite, developed by Peter Larsson, NSC LiU
Description of behave:
Behavior-driven development (or BDD) is an agile software development
technique that encourages collaboration between developers, QA and
non-technical or business participants in a software project.
=> {tools}[foss/2016b] behave 1.2.5 w/ Python 2.7.12

easybuild/easyconfigs/o/Octave/Octave-4.0.3-intel-2016b.eb, easybuild/easyconfigs/o/Octave/Octave-4.0.3_intel.patch
Needs PRs ~~#3704 #3705 #3706 #3707 #3708 #3709 #3710 #3711 #3712 #3713 #3714 #3715 #3716~~
Replaces #2684 and #2766
=> {math}[intel/2016b] Octave 4.0.3 (REVIEW)

easybuild/easyconfigs/f/FFTW/FFTW-3.3.5-gompic-2016.10.eb, easybuild/easyconfigs/g/gcccuda/gcccuda-2016.10.eb, easybuild/easyconfigs/g/gompic/gompic-2016.10.eb, easybuild/easyconfigs/g/goolfc/goolfc-2016.10.eb, easybuild/easyconfigs/h/HPL/HPL-2.2-goolfc-2016.10.eb, easybuild/easyconfigs/h/hwloc/hwloc-1.11.4-gcccuda-2016.10.eb, easybuild/easyconfigs/n/numactl/numactl-2.0.11-gcccuda-2016.10.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompic-2016.10-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.0.1-gcccuda-2016.10.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2016.10-OpenBLAS-0.2.19-LAPACK-3.6.1.eb
=> reversion goolfc 2016.10.0 to goolfc 2016.10 + add HPL easyconfig as testcase

easybuild/easyconfigs/c/CUDA/CUDA-8.0.44-iccifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iccifortcuda/iccifortcuda-2016.10.0.eb, easybuild/easyconfigs/i/iimpic/iimpic-2016.10.0.eb, easybuild/easyconfigs/i/imkl/imkl-11.3.3.210-iimpic-2016.10.0.eb, easybuild/easyconfigs/i/impi/impi-5.1.3.181-iccifortcuda-2016.10.0.eb, easybuild/easyconfigs/i/intelc/intelc-2016.10.0.eb, easybuild/easyconfigs/i/intelc/intelcuda-2016.10.0.eb
Modeled after the goolfc toolchain.
Depends on framework PR https://github.com/hpcugent/easybuild-framework/pull/1976
=> Add an intel-cuda toolchain.

easybuild/easyconfigs/n/ncurses/ncurses-6.0-CrayGNU-2016.03.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-4.9.3.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016a.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016b.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016a.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016b.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-iomkl-2016.07.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-iomkl-2016.09-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0.eb
@eediaz1987 ran into this with `ncurses-6.0-foss-2016b.eb`...
=> consistently apply patch for ncurses 6.0

easybuild/easyconfigs/a/Autotools/Autotools-20150215-intel-2015a.eb, easybuild/easyconfigs/b/beagle-lib/beagle-lib-20120124-goolf-1.4.10.eb, easybuild/easyconfigs/b/beagle-lib/beagle-lib-20120124-ictce-5.3.0.eb, easybuild/easyconfigs/b/beagle-lib/beagle-lib-20141202-intel-2015a.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-intel-2015a.eb, easybuild/easyconfigs/m/MrBayes/MrBayes-3.1.2-goolf-1.4.10.eb, easybuild/easyconfigs/m/MrBayes/MrBayes-3.1.2-ictce-5.3.0.eb, easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.0-goolf-1.4.10.eb, easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.0-ictce-5.3.0.eb, easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.5-intel-2015a.eb, easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-foss-2016a.eb
=> include Autotools as build dependency in all beagle-lib and MrBayes easyconfigs

easybuild/easyconfigs/l/libxml2/libxml2-2.9.2-goolf-1.5.16.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.28-foss-2016a.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.28-goolf-1.5.16.eb, easybuild/easyconfigs/x/XMLStarlet/XMLStarlet-1.6.1-foss-2016a.eb, easybuild/easyconfigs/x/XMLStarlet/XMLStarlet-1.6.1-goolf-1.5.16.eb
Easyconfig files for XMLStarlet for goolf/1.5.16 and foss/2016a toolchains (and dependencies).
=> {data}[goolf/1.5.16,foss/2016a] XMLStarlet 1.6.1 (REVIEW)

easybuild/easyconfigs/g/GCC/GCC-4.8.1-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.2-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.3-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.4-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.8.4-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.0-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.1-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG-multilib.eb, easybuild/easyconfigs/g/GCC/GCC-4.9.2-CLooG.eb, easybuild/easyconfigs/g/GCC/GCC-5.1.0-binutils-2.25.eb, easybuild/easyconfigs/g/GCC/GCC-5.1.0.eb, easybuild/easyconfigs/g/GCC/GCC-5.2.0.eb, easybuild/easyconfigs/g/GCC/GCC-5.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-5.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.1.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.2.0.eb
wrapper PR for #3629 which applies the fix consistently
=> include original download URL for ISL source tarball

easybuild/easyconfigs/r/RELION/RELION-1.4-intel-2016b-single.eb, easybuild/easyconfigs/r/RELION/RELION-1.4-intel-2016b.eb, easybuild/easyconfigs/r/RELION/RELION-1.4_fltk-config.patch, easybuild/easyconfigs/r/RELION/RELION-2.0.1-intel-2016b.eb
=> {bio}[intel/2016b] RELION {1.4,2.0.1} (REVIEW)

easybuild/easyconfigs/g/GROMACS/GROMACS-2016-foss-2016b-hybrid.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2016-foss-2016b-mt.eb
wrapper PR for #3665 for @akesandgren, fixes/syncs copyright/author headers
=> {bio}[foss/2016b] GROMACS 2016

easybuild/easyconfigs/b/BLAST/BLAST-2.2.26-Linux_x86_64.eb
fix for issue reported in #3727
=> fix download URL in BLAST 2.2.26 easyconfig

RELEASE_NOTES, setup.py
Thanks for the help with preparing the release notes @migueldiascosta!
=> release EasyBuild v3.0.1

easybuild/easyconfigs/d/DL_POLY_Classic/DL_POLY_Classic-1.9-ictce-5.3.0-no-gui.eb, easybuild/easyconfigs/d/DL_POLY_Classic/DL_POLY_Classic-1.9-intel-2016b-PLUMED-2.2.3.eb, easybuild/easyconfigs/d/DL_POLY_Classic/DL_POLY_Classic-1.9-intel-2016b.eb, easybuild/easyconfigs/d/DL_POLY_Classic/DL_POLY_Classic-1.9_fix-PLUMED-integration.patch
requires https://github.com/hpcugent/easybuild-easyblocks/pull/829
=> {chem}[intel/2016b] DL_POLY_Classic v1.9 w/ PLUMED 2.2.3 (REVIEW)

easybuild/easyconfigs/n/ncview/ncview-2.1.7-intel-2016b.eb
`ncview` needs `X11` develop libraries.
=> ncview needs X11 develop libs

easybuild/easyconfigs/u/USPEX/USPEX-9.4.4-intel-2016b-Python-2.7.12.eb
I did not have better idea what `Toolchain` to use. The program itself is in binary, `AWK` and `MATLAB` codes. It also depends on `Python`. Since MATLAB is not widely available, I "interfaced" the program with `Octave` (works with it, although `MATLAB` is recommended).
Suggestions for the `Toolchain` are welcome. (Any `Octave`/`Python` version would do.)
=> {phys}[intel/2016b] USPEX 9.4.4 (REVIEW)

easybuild/easyconfigs/a/Advisor/Advisor-2017_update1.eb, easybuild/easyconfigs/v/VTune/VTune-2017_update1.eb
Easy config for next update.  Still need to check the vtune works on our cluster.
=> version push for 2017 update 1

easybuild/easyconfigs/l/libsodium/libsodium-1.0.11-foss-2016b.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-foss-2015a.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-foss-2016a.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-foss-2016b.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-goolf-1.4.10.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-goolf-1.7.20.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-ictce-5.3.0.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-ictce-5.5.0.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-intel-2015a.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-intel-2015b.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-intel-2016a.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-intel-2016b.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-16.0.2-foss-2016b-Python-2.7.12-zmq4.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-16.0.2-foss-2016b-Python-3.5.2-zmq4.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-16.0.2-intel-2016b-Python-2.7.12-zmq4.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-16.0.2-intel-2016b-Python-3.5.2-zmq4.eb, easybuild/easyconfigs/u/util-linux/util-linux-2.29-foss-2016b.eb, easybuild/easyconfigs/u/util-linux/util-linux-2.29-intel-2016b.eb, easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.0-foss-2016b.eb, easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.0-intel-2016b.eb
Set of easyconfig files for ZeroMQ 4.2.0 and PyZMQ 16.0.2, incl pre-requisites.  
Supporting 
- foss/2016b and intel/2016b  
- Python bindings for 2.7.12 and 3.5.2.
- URL update for OpenPGM
=> Pyzmq 16.0.2

test/easyconfigs/easyconfigs.py
This change is required because of making `robot` fall back to using subtoolchains even without `--minimal-toolchains` in EasyBuild v3.0.0, cfr. https://github.com/hpcugent/easybuild-framework/pull/1973 .
An example PR that is blocked because of this is https://github.com/hpcugent/easybuild-easyconfigs/pull/3929, where the `CMake` dependency is being resolved via the available easyconfig using the `GCCcore` subtoolchain, leading to this error (without having the patch in this PR applied):
```
======================================================================
FAIL: Test for parsing of easyconfig libharu-2.3.0-foss-2016a.eb
File "<string>", line 1, in innertest
File …
```
=> fix test that verifies dumped easyconfig, take into account that dumped dependencies may include hardcoded dependency

easybuild/easyconfigs/c/cuDNN/cuDNN-5.1-CUDA-8.0.44.eb
=> add easyconfig for cuDNN 5.1 for CUDA 8.0.44

easybuild/easyconfigs/i/Infernal/Infernal-1.1-goolf-1.4.10.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1-ictce-5.3.0.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1rc1-goolf-1.4.10.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1rc1-ictce-5.3.0.eb
the URL of infernals homepage and the download link changed, therefore
fetching files fails
=> fix broken links to infernal

easybuild/easyconfigs/b/Boost/Boost-1.63.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/b/Boost/Boost-1.63.0-foss-2016b-Python-3.5.2.eb, easybuild/easyconfigs/b/Boost/Boost-1.63.0_python3.patch
Note: SOURCEFORGE_SOURCE returned a wrong tarball with missing files
=> [foss/2016b] Boost 1.63.0

easybuild/easyconfigs/c/CGAL/CGAL-4.8.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/c/CMake/CMake-3.7.1-foss-2016b.eb, easybuild/easyconfigs/e/Eigen/Eigen-3.2.9-foss-2016b.eb, easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-foss-2016b.eb, easybuild/easyconfigs/g/GDB/GDB-7.11.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/g/GL2PS/GL2PS-1.3.9-foss-2016b.eb, easybuild/easyconfigs/g/GTS/GTS-0.7.6-foss-2016b.eb, easybuild/easyconfigs/i/IPython/IPython-5.1.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/l/Loki/Loki-0.1.7-foss-2016b.eb, easybuild/easyconfigs/l/libQGLViewer/libQGLViewer-2.6.3-foss-2016b.eb, easybuild/easyconfigs/m/MPFR/MPFR-3.1.4-foss-2016b.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-1.5.2-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/m/minieigen/minieigen-0.5.3-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/PyGTS/PyGTS-0.3.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/path.py/path.py-8.2.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/pip/pip-8.1.2-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/p/prompt-toolkit/prompt-toolkit-1.0.6-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.7.0-foss-2016b.eb, easybuild/easyconfigs/t/testpath/testpath-0.3-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/v/VTK/VTK-6.3.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/v/VTK/VTK-7.0.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/w/wcwidth/wcwidth-0.1.7-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/y/Yade/Yade-2016.06a-foss-2016b-Python-2.7.12.eb
bump to lasted release of Yade (2016.06a) with foss 2016b
=> {devel}[foss/2016b] Yade 2016.06a (REVIEW)

easybuild/easyconfigs/p/perl-app-cpanminus/perl-app-cpanminus-1.7039.eb
I'm adding the conda-forge channel to the perl-app-cpanminus config.
=> adding channel to perl-app-cpanminus

easybuild/easyconfigs/i/ImageJ/ImageJ-1.51i.eb
=> fix ImageJ version (1.51i rather than 1.5.1i)

easybuild/easyconfigs/c/cclib/cclib-1.5-foss-2016b-Python-3.5.2.eb
=> {tools}[foss/2016b] cclib 1.5 (REVIEW)

easybuild/easyconfigs/c/Clang/Clang-3.8.1-foss-2016b.eb, easybuild/easyconfigs/c/cairo/cairo-1.14.6-foss-2016b.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.49.1-foss-2016b.eb, easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.20-foss-2016b.eb, easybuild/easyconfigs/g/Graphviz/Graphviz-2.38.0-foss-2016b.eb, easybuild/easyconfigs/g/graphviz/graphviz-0.5.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.3.1-foss-2016b.eb, easybuild/easyconfigs/p/Pango/Pango-1.40.3-foss-2016b.eb, easybuild/easyconfigs/p/pixman/pixman-0.34.0-foss-2016b.eb
All configs are derived from older foss and intel/2016b easyconfigs.
=> {vis}[foss/2016b] graphviz 0.5.1 w/ Python 2.7.12 (REVIEW)

easybuild/easyconfigs/o/OrthoMCL/OrthoMCL-1.4-intel-2016b-Perl-5.24.0.eb
should have been part of #4169
=> also update $PATH in OrthoMCL 1.4 easyconfig

easybuild/easyconfigs/y/Yade/Yade-1.20.0-foss-2016a-Python-2.7.11.eb, easybuild/easyconfigs/y/Yade/Yade-1.20.0-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/y/Yade/Yade-2016.06a-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/y/Yade/Yade-2016.06a-intel-2016b-Python-2.7.12.eb
add sanity check command to catches problem in Yade caused by bug in Boost (cfr. #4192)
=> add sanity check command to Yade easyconfig to make sure that 'import yade' works, include bzip2 as dep

easybuild/easyconfigs/r/R/R-2.15.2-goolf-1.4.10-bare.eb, easybuild/easyconfigs/r/R/R-2.15.2-goolf-1.4.10.eb, easybuild/easyconfigs/r/R/R-2.15.2-ictce-5.3.0-bare.eb, easybuild/easyconfigs/r/R/R-2.15.2-ictce-5.3.0.eb, easybuild/easyconfigs/r/R/R-2.15.3-goolf-1.4.10.eb, easybuild/easyconfigs/r/R/R-2.15.3-ictce-5.3.0.eb, easybuild/easyconfigs/r/R/R-3.0.1-goolf-1.4.10-bare.eb, easybuild/easyconfigs/r/R/R-3.0.1-ictce-5.3.0-bare.eb, easybuild/easyconfigs/r/R/R-3.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/r/R/R-3.0.2-ictce-5.3.0-bare.eb, easybuild/easyconfigs/r/R/R-3.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/r/R/R-3.0.2-ictce-5.5.0.eb, easybuild/easyconfigs/r/R/R-3.1.1-ictce-6.2.5-bare-mt.eb, easybuild/easyconfigs/r/R/R-3.1.1-ictce-6.2.5-default-mt.eb
Ran into this while working on the style cleanup effort...
=> remove custom sanity_check_paths, since it's identical to that used by the R easyblock

easybuild/easyconfigs/a/ATK/ATK-2.22.0-foss-2016b.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.1.3-foss-2016b.eb, easybuild/easyconfigs/g/GTK+/GTK+-2.24.31-foss-2016b.eb, easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.0-foss-2016b.eb, easybuild/easyconfigs/j/JasPer/JasPer-1.900.1-foss-2016b.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-foss-2016b.eb, easybuild/easyconfigs/x/x264/x264-20160614-foss-2016b.eb, easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-foss-2016b.eb
created from intel/2016b and older foss configs.
needs PR ~~#4119~~
=> {vis}[foss/2016b] OpenCV 3.1.0 (REVIEW)

easybuild/easyconfigs/h/HTSlib/HTSlib-1.2.1-foss-2016b.eb, easybuild/easyconfigs/p/PileOMeth/PileOMeth-0.1.11-foss-2016b.eb, easybuild/easyconfigs/p/PileOMeth/PileOMeth-0.1.11.eb
New easyconfig file for PileOMeth added
=> {bio}[foss/2016b] PileOMeth v0.1.11

easybuild/easyconfigs/r/ROOT/ROOT-v5.30.06-goolf-1.4.10.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.01-goolf-1.4.10.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.01-intel-2015a.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.13-ictce-5.5.0.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.18-ictce-5.5.0.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.26-intel-2015a.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.34-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.34-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/r/ROOT/ROOT-v5.34.36-intel-2016a-Python-2.7.11.eb, easybuild/easyconfigs/r/ROOT/ROOT-v6.06.02-intel-2016b-Python-2.7.12.eb
follow-up for #4239
wraps around #4320, #4321, #4322, #4323, #4324, #4325, #4326, #4327, #4328, #4329 PRs by @ysagon
=> correctly set $PYTHONPATH in ROOT easyconfigs

easybuild/easyconfigs/r/ROOT/ROOT-v5.30.06-goolf-1.4.10.eb, easybuild/easyconfigs/r/ROOT/ROOT-v6.08.02-foss-2016a-Python-2.7.11.eb
=> correctly set $PYTHONPATH for ROOT v5.30.06

easybuild/easyconfigs/r/ROOT/ROOT-v5.34.01-goolf-1.4.10.eb, easybuild/easyconfigs/r/ROOT/ROOT-v6.08.02-foss-2016a-Python-2.7.11.eb
=> Root v5.34.01 goolf 1.4.10

easybuild/easyconfigs/r/ROOT/ROOT-v5.34.13-ictce-5.5.0.eb, easybuild/easyconfigs/r/ROOT/ROOT-v6.08.02-foss-2016a-Python-2.7.11.eb
=> Root v5.34.13 ictce 5.5.0

easybuild/easyconfigs/r/ROOT/ROOT-v5.34.26-intel-2015a.eb
=> fix PYTHONPATH #4239

easybuild/easyconfigs/s/Singularity/Singularity-2.2.1-GCC-6.3.0-2.27.eb
next steps after instalations
```console
```
=> add eb Singularity-2.2.1-GCC-6.3.0-2.27.eb

easybuild/easyconfigs/m/Mesa/Mesa-10.4.5-intel-2015a-Python-2.7.9.eb, easybuild/easyconfigs/m/Mesa/Mesa-10.5.5-intel-2015a-Python-2.7.10.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.0.2-intel-2015b-Python-2.7.10.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.0.8-intel-2015b-Python-2.7.11.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-foss-2016a.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-gimkl-2.11.5.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.1.2-intel-2016a.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.2.1-foss-2016a.eb, easybuild/easyconfigs/m/Mesa/Mesa-11.2.1-intel-2016a.eb, easybuild/easyconfigs/m/Mesa/Mesa-12.0.2-foss-2016b.eb, easybuild/easyconfigs/m/Mesa/Mesa-12.0.2-intel-2016b.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-goolf-1.4.10-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-ictce-5.3.0-Python-2.7.3.eb, easybuild/easyconfigs/m/Mesa/Mesa-7.11.2-ictce-5.5.0-Python-2.7.6.eb
Fixes https://github.com/hpcugent/easybuild-easyconfigs/issues/4352
=> remove include/GL/wglext.h from Mesa sanity check

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.0.2-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.0.2-ictce-5.3.0.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.0.5-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.0.6-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.1.0-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.1.0-ictce-5.5.0.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.0-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.2-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.4-goolf-1.4.10.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.5-goolf-1.7.20.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.5-intel-2015a.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.6-foss-2015b.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.6-intel-2015b.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.7-foss-2015b.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.8-foss-2015b.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.8-foss-2016a.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.9-foss-2016a.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.9-goolf-1.7.20.eb, easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.2.9-intel-2016b.eb
requires https://github.com/hpcugent/easybuild-easyblocks/pull/1146
=> sync Bowtie2 easyconfigs, consistently use Bowtie2 easyblock

easybuild/easyconfigs/r/RepastHPC/RepastHPC-2.2.0-foss-2016a.eb
Added a recipe for the RepastHPC package.
=> {bio}[foss/2016a] RepastHPC 2.2.0

easybuild/easyconfigs/s/Stacks/Stacks-1.45-foss-2016a.eb
Stacks 1.45 build with the foss-2016a toolchain.
=> Stacks 1.45 build with the foss-2016a toolchain.

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-foss-2015b.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2015b.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-foss-2015b.eb, easybuild/easyconfigs/b/BioKanga/BioKanga-4.3.4-foss-2015b.eb, easybuild/easyconfigs/b/BioKanga/BioKanga-4.3.4_configure.patch, easybuild/easyconfigs/b/BioKanga/BioKanga-4.3.5-foss-2015b.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-foss-2015b.eb
- Added EasyConfig for BioKanga 4.3.4; updating location of source and building
=>  {bio}(foss/2015b) BioKanga 4.3.4, 4.3.5 (REVIEW)

easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-foss-2016a.eb, easybuild/easyconfigs/h/HMMER/HMMER-3.1b2-intel-2015a.eb
=> fix sources spec for HMMER 3.1b2 + minor style fixes + better sanity check

easybuild/easyconfigs/b/Bison/Bison-3.0.4-GCCcore-7.1.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.28-GCCcore-7.1.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.3-GCCcore-7.1.0.eb, easybuild/easyconfigs/g/GCC/GCC-7.1.0-2.28.eb, easybuild/easyconfigs/h/help2man/help2man-1.47.4-GCCcore-7.1.0.eb, easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.1.0.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-7.1.0.eb
=> {compiler}[dummy] GCC 7.1.0 w/ binutils 2.28 + deps

easybuild/easyconfigs/i/IMB/IMB-4.1-foss-2016a.eb
=> also build IMB-IO in IMB 4.1 easyconfig using foss/2016a

easybuild/easyconfigs/a/AdapterRemoval/AdapterRemoval-2.2.0-foss-2016b.eb
=> {bio}[foss/2016b] AdapterRemoval

easybuild/easyconfigs/i/imbalanced-learn/imbalanced-learn-0.2.1-intel-2016b-Python-2.7.12.eb
just a `Python` version change
=> {tools}[intel/2016b] imbalanced-learn 0.2.1 /w Python 2.7.12 (REVIEW)

easybuild/easyconfigs/e/ESMF/ESMF-6.3.0rp1-intel-2017a-HDF5-1.8.18.eb, easybuild/easyconfigs/g/GDAL/GDAL-2.2.0-intel-2017a-Python-2.7.13-HDF5-1.8.18.eb, easybuild/easyconfigs/g/GDAL/GDAL-2.2.0_fix-uchar-definition.patch, easybuild/easyconfigs/n/NCL/NCL-6.4.0-intel-2017a.eb, easybuild/easyconfigs/n/NCL/NCL-6.4.0_fix-types.patch
requires ~~#4592~~ and ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1179~~ (or at least the changes in ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1169~~ should not be used)
=> {data}[intel/2017a] NCL 6.4.0 (+ deps)

easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.3.1-foss-2016b.eb, easybuild/easyconfigs/l/LAME/LAME-3.99.5-foss-2016b.eb
ffmpeg 3.3.1 with x265 and LAME
=> {vis}[foss/2016b] FFmpeg V3.3.1 (REVIEW)

easybuild/easyconfigs/k/Keras/Keras-2.0.4-intel-2017a-Python-2.7.13.eb, easybuild/easyconfigs/k/Keras/Keras-2.0.4-intel-2017a-Python-3.6.1.eb, easybuild/easyconfigs/t/Theano/Theano-0.9.0-intel-2017a-Python-2.7.13.eb
Already present for Python 3.x.
=> Keras/2.0.4 for Python 2.7.13

easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-goolf-1.4.10.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-goolf-1.7.20.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-ictce-5.3.0.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-intel-2014.06.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-intel-2014b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-intel-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.3-intel-2015b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4-foss-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4-goolf-1.7.20.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4-intel-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4beta-foss-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.4beta-intel-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-foss-2015a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-foss-2016a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-foss-2016b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-intel-2016a.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.6-intel-2016b.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.7-intel-2017a.eb
cfr. https://lists.ugent.be/wws/arc/easybuild/2017-05/msg00081.html
=> enable inclusion of version symbol by using --enable-ld-version-script configure option for LibTIFF

easybuild/easyconfigs/b/Bio-SamTools/Bio-SamTools-1.43-intel-2017a-Perl-5.24.1.eb, easybuild/easyconfigs/b/Bio-SamTools/Bio-SamTools-1.43.patch, easybuild/easyconfigs/s/SAMtools/SAMtools-0.1.17-intel-2017a.eb
`Bio-SamTools` require `SAMtools` versions between 0.10.0 - 0.17.0
needs https://github.com/hpcugent/easybuild-easyblocks/pull/1189
=> {bio}[intel/2017a] Bio-SamTools 1.43 w/Perl-5.24.1 (REVIEW)

easybuild/easyconfigs/n/ncurses/ncurses-6.0-gimkl-2017a.eb
Done as a separate PR so that it can be referenced by multiple other PRs.
=> Easyconfig for ncurses 6.0 with the gimkl 2017a toolchain
