easybuilders/easybuild-easyconfigs

easybuild/easyconfigs/l/LUMPY/LUMPY-0.2.13-foss-2016b.eb

{bio}[foss/2016b] LUMPY

---

easybuild/easyconfigs/m/MATLAB/MATLAB-2017a.eb

needs https://github.com/hpcugent/easybuild-easyblocks/pull/1182

{math}[binary] MATLAB 2017a (REVIEW)

---

easybuild/easyconfigs/s/segemehl/segemehl-0.2.0-foss-2016b.eb

Adds segemehl 0.2.0 with foss toolchain.

{bio}[foss-2016b] segemehl 0.2.0

---

easybuild/easyconfigs/f/FASTA/FASTA-36.3.5e-foss-2016b.eb

Adds FASTA 36.3.5e with foss toolchain.

{bio}[foss-2016b] FASTA 36.3.5e

---

easybuild/easyconfigs/s/StringTie/StringTie-1.3.3b-foss-2016b.eb

Adds StringTie 1.3.3b with foss toolchain.

{bio}[foss-2016b] StringTie 1.3.3b

---

easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.5-10-foss-2016b.eb
easybuild/easyconfigs/j/JasPer/JasPer-2.0.12-foss-2016b.eb
easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.7-foss-2016b.eb
easybuild/easyconfigs/l/LittleCMS/LittleCMS-2.8-foss-2016b.eb
easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.5.1-foss-2016b.eb

Easyconfig files for ImageMagick with the FOSS 2016b toolchain, and with FFmpeg as a dependency so ImageMagick can create movies.

ImageMagick with FOSS 2016b tool chain and FFmpeg support.

---

easybuild/easyconfigs/r/R/R-3.3.3-foss-2016b-X11-20160819.eb
easybuild/easyconfigs/r/R/R-3.3.3-intel-2017a-X11-20170314.eb
easybuild/easyconfigs/r/R/R-3.4.0-intel-2017a-X11-20170314.eb

cc @verdurin, @hajgato, @vanzod

use --with-x=yes in R easyconfigs that include X11 as a dependency

---

easybuild/easyconfigs/s/SEED/SEED-2015.eb

{bio}{dummy} SEED added

---

easybuild/easyconfigs/f/FFmpeg/FFmpeg-3.2.4-gimkl-2017a.eb
easybuild/easyconfigs/n/NASM/NASM-2.12.02.eb
easybuild/easyconfigs/x/x264/x264-20170406-gimkl-2017a.eb
easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-gimkl-2017a.eb

New Easyconfig for FFmpeg (and dependencies) with the gimkl toolchain

---

easybuild/easyconfigs/t/Tensorflow/Tensorflow-0.12.1-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-0.12.1-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-0.12.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-0.12.1-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-1.0.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-1.0.1-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-1.1.0-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/t/Tensorflow/Tensorflow-1.1.0-intel-2017a-Python-3.6.1.eb

motivation: making it easier to update easyconfigs in the future

use PYPI_SOURCE as source URL in Tensorflow easyconfigs

---

easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb
easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016b.eb
easybuild/easyconfigs/p/Perl/Perl-5.22.1-intel-2016a.eb
easybuild/easyconfigs/p/Perl/Perl-5.22.2-goolf-1.7.20.eb
easybuild/easyconfigs/p/Perl/Perl-5.22.2-intel-2016a.eb
easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/p/Perl/Perl-5.24.0-GCCcore-4.9.3.eb
easybuild/easyconfigs/p/Perl/Perl-5.24.0-intel-2016b.eb
easybuild/easyconfigs/p/Perl/Perl-5.24.1-intel-2017a.eb

This adds two extensions to Perl for consistency. See #4790.

Add SVG and Statistics::Basic to recent Perl versions

---

easybuild/easyconfigs/h/HDF5/HDF5-1.8.18-gimkl-2017a.eb

follow up on PR #4740 by @valtandor, see also #4749
I didn't want to block #4740 any longer for this trivial change, but it's important to keep the HDF5 easyconfigs in sync.

sync/fix source_urls & homepage in HDF5 easyconfig

---

easybuild/easyconfigs/o/OpenCoarrays/OpenCoarrays-1.9.0-gompi-2017a.eb

adding easyconfig for OpenCoarrays ([https://github.com/sourceryinstitute/OpenCoarrays](url)) using gompi-2017a toolchain

adding easyconfig: OpenCoarrays-1.9.0-gompi-2017a.eb

---

easybuild/easyconfigs/g/g2log/g2log-1.0-foss-2016b.eb
easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1_skip-included-Jellyfish.patch

This adds the current version of `Sailfish` for the `foss-2016b` toolchain.

{bio}[foss/2016b] Sailfish 0.10.1

---

easybuild/easyconfigs/p/PLINK/PLINK-1.07-foss-2015b.eb
easybuild/easyconfigs/p/PLINK/PLINK-1.07-foss-2016a.eb
easybuild/easyconfigs/p/PLINK/PLINK-1.07-foss-2016b.eb
easybuild/easyconfigs/p/PLINK/PLINK-1.07-ictce-5.3.0.eb
easybuild/easyconfigs/p/PLINK/PLINK-1.07-ictce-6.2.5.eb

The old URLS were no longer responding.

Updating deprecated PLINK urls

---

easybuild/easyconfigs/s/Singularity/Singularity-2.3.1-GCC-5.4.0-2.26.eb

Adding most recent version of Singularity

{tools}[GCC/5.4.0-2.26] Singularity v2.3.1

---

easybuild/easyconfigs/c/CLISP/CLISP-2.49-GCCcore-6.4.0.eb
easybuild/easyconfigs/c/CLISP/CLISP-2.49_fix-readline.patch

follow-up for #4926
cc @JackPerdue & @verdurin (since you merged it)

rename CLISP patch + add upstream ref + minor style cleanups in easyconfig

---

easybuild/easyconfigs/a/Armadillo/Armadillo-7.950.1-intel-2016b-Python-2.7.12.eb

This PR requires merging https://github.com/easybuilders/easybuild-easyblocks/pull/1213 first

{numlib}[intel/2016b] Armadillo 7.950.1 w/ Python 2.7.12

---

easybuild/easyconfigs/o/ORCA/ORCA-4.0.1-OpenMPI-2.0.2.eb

This version is a bugfix of `4.0.0`

{chem}[dummy] ORCA 4.0.1 (REVIEW)

---

easybuild/easyconfigs/u/util-linux/util-linux-2.29-foss-2016b.eb
easybuild/easyconfigs/u/util-linux/util-linux-2.29-intel-2016b.eb
easybuild/easyconfigs/u/util-linux/util-linux-2.30-GCCcore-6.4.0.eb

follow-up for #4900
cc @vanzod

add zlib as depedency to recent util-linux easyconfigs

---

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.2-foss-2016b.eb

This adds the current `Bowtie2` for the `foss-2016b` toolchain.

{bio}[foss/2016b] Bowtie2 2.3.2

---

easybuild/easyconfigs/p/PLINK/PLINK-1.07-x86_64.eb

This one was overlooked in #4920

also fix URLs in PLINK-1.07-x86_64.eb

---

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.5-intel-2017a-R-3.4.0.eb
easybuild/easyconfigs/r/R/R-3.4.0-intel-2017a-X11-20170314.eb

required for other R packages that are being installed as stand-alone modules (PRs coming up)

add additional extensions for R 3.4.0 and Bioconductor 3.5 bundle

---

easybuild/easyconfigs/h/h5py/h5py-2.7.0-foss-2017a-Python-3.6.1-HDF5-1.10.1.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.0-foss-2017a-Python-3.6.1-HDF5-1.8.19.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-2.0.2-foss-2017a-Python-3.6.1.eb
easybuild/easyconfigs/p/Python/Python-3.6.1-foss-2017a.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017a-Python-3.6.1.eb

Python 3.6.1 for foss 2017a with matplotlib and hdf5 bindings
Also sha256 for Python 3.6.1 in intel 2017a

{lang}[foss/2017a] Python 3.6.1 + h5py 2.7.0, matplotlib 2.0.2, pkgconfig 1.2.2

---

easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-foss-2015a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-foss-2015b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-foss-2016a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-intel-2015a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-intel-2015b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-intel-2016.02-GCC-4.9.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.3.3.1-intel-2016a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.0-foss-2016a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.0-intel-2016a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.0-iomkl-2016.07.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.0-iomkl-2016.09-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1-foss-2016a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1-foss-2016b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1-intel-2016a.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1-intel-2016b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2016b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2016b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017a-HDF5-1.10.1.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017a-HDF5-1.8.18.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017a.eb

cfr. https://github.com/easybuilders/easybuild-easyblocks/issues/1233

include Autotools as build dep for netCDF

---

easybuild/easyconfigs/c/Cookiecutter/Cookiecutter-1.4.0-goolf-1.7.20-Python-2.7.11.eb

I used wrong moduleclass by mistake

fix moduleclass for Cookiecutter

---

easybuild/easyconfigs/t/texinfo/texinfo-6.4-GCCcore-5.4.0.eb

tests are currently broken without this...

add missing binutils build dep for texinfo

---

easybuild/easyconfigs/r/Rcorrector/Rcorrector-1.0.2-intel-2017a.eb

User gave feedback that this files is also required.

also install run_rcorrector.pl with Rcorrector

---

easybuild/easyconfigs/h/HTSlib/HTSlib-1.4.1-foss-2016a.eb

HTSlib 1.4.1 for foss 2016a

---

easybuild/easyconfigs/p/PyCUDA/PyCUDA-2016.1.2-intel-2016b-Python-2.7.12.eb

add sha256 checksum to PyCUDA easyconfig

---

easybuild/easyconfigs/b/Boost/Boost-1.61.0-foss-2016a-Python-3.5.1.eb
easybuild/easyconfigs/b/Boost/Boost-1.61.0_python3.patch

Boost 1.61.0 for foss 2016a and Python 3.5.1.

Boost 1.61.0 for foss 2016a and Python 3.5.1.

---

easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2016b.eb

add Template.pm perl module to the extensions list

{tools} [dummy] Worker/1.6.7: add missing Perl extensions

---

easybuild/easyconfigs/b/Boost/Boost-1.64.0-intel-2017a.eb
easybuild/easyconfigs/b/Boost/Boost-1.64.0_fix-boost-serialization-detail-get_data.patch
easybuild/easyconfigs/b/Boost/Boost-1.64.0_fix-include-array_wrapper.patch

fix for #5146
@jhein32 Can you check whether this fixes the problem you were seeing?

add patches for Boost 1.64.0 to fix known issues

---

easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017a-HDF5-1.10.1.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017a-HDF5-1.8.19.eb

netcdf 4.4.1.1 based on HDF5 1.10.1 and 1.8.19 for foss/2017a

{data} [foss/2017a] netCDF 4.4.1.1 configs

---

easybuild/easyconfigs/b/Beast/Beast-2.4.7-foss-2017a.eb
easybuild/easyconfigs/b/beagle-lib/beagle-lib-2.1.2-foss-2017a.eb

New version, newer Java dependencies, newer toolchain, sha256 checksum

{bio}[foss/2017a] Beast 2.4.7

---

easybuild/easyconfigs/c/CUDA/CUDA-9.0.176.eb

{system}[dummy] CUDA 9.0.176

---

easybuild/easyconfigs/g/GLM/GLM-0.9.7.6-intel-2016a.eb

GLM 0.9.7.6 using the intel 2016a toolchain.

{lib}[intel/2016a] GLM 0.9.7.6

---

easybuild/easyconfigs/c/cuDNN/cuDNN-7.0.2-CUDA-9.0.176.eb

{numlib}[dummy] cuDNN 7.0.2
edit: requires #5180

{numlib}[dummy] cuDNN 7.0.2

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-4.4.0.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-4.2.0.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-4.4.0.eb

version push to anaconda v 4.4.0 and sha256 update of 4.2.0 configs

{lang}[dummy] Anaconda2/3 4.4.0

---

easybuild/easyconfigs/h/HISAT2/HISAT2-2.1.0-intel-2017a.eb
easybuild/easyconfigs/h/HISAT2/HISAT2-2.1.0_intel-fixes.patch

{bio}[intel/2017a] HISAT2 2.1.0 (REVIEW)

{bio}[intel/2017a] HISAT2 2.1.0 (REVIEW)

---

easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-4.9.3.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.2.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.3.0-2.26.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.1.0-2.27.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.2.0-2.27.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.3.0-2.27.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-4.9.2.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-4.9.3.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-5.3.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-5.4.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-6.3.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-6.4.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-foss-2016a.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-gcccuda-2016.10.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-iccifort-2016.3.210-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-intel-2016a.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-intel-2016b.eb

cfr. #5285 and #5286
cc @verdurin, @vanzod

consistently fix source_urls for numactl v2.0.11

---

easybuild/easyconfigs/n/numactl/numactl-2.0.10-GCC-4.8.4.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.10-GCC-4.9.2.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.10-GNU-4.9.2-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.10-GNU-4.9.3-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.10-iccifort-2015.3.187-GNU-4.9.3-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.8-goolf-1.4.10.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.8-ictce-5.3.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.9-GCC-4.8.3.eb

cfr. #5285 and #5286
cc @verdurin, @vanzod

consistently fix source_urls for older numactl versions

---

easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCC-4.9.2.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCCcore-5.4.0.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCCcore-6.3.0.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-GNU-4.9.3-2.25.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2015a.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2015b.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2016.04.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2016a.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-foss-2016b.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-gimkl-2.11.5.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-intel-2015a.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-intel-2015b.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-intel-2016a.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-intel-2016b.eb

fix $CPATH in recent libffi easyconfigs + enhance sanity check & add checksum

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.0.1.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-5.0.1.eb

{lang}[dummy] Anaconda2/3 5.0.1

---

easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-4.9.3.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.2.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.3.0-2.26.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.1.0-2.27.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.2.0-2.27.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCC-6.3.0-2.27.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-4.9.2.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-4.9.3.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-5.3.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-6.3.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-6.4.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-foss-2016a.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-gcccuda-2016.10.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-iccifort-2016.3.210-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-iccifort-2016.3.210-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-intel-2016a.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-intel-2016b.eb

requires ~~#5301~~, cfr. #5299

consistently add Autotools as build dep for numactl 2.0.11

---

easybuild/easyconfigs/g/GLib/GLib-2.53.5-GCCcore-6.4.0.eb
easybuild/easyconfigs/u/util-linux/util-linux-2.31-GCCcore-6.4.0.eb

{vis}[GCCcore/6.4.0] GLib v2.53.5

---

easybuild/easyconfigs/t/TAMkin/TAMkin-1.2.4-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/t/TAMkin/TAMkin-1.2.4-intel-2017b-Python-2.7.14.eb

This easyconfig was originally part of #5317, but was taken out because it was delaying the merge of several other easyconfigs

{chem}[intel/2017b] TAMkin 1.4.2

---

easybuild/easyconfigs/g/GATE/GATE-6.2-goolf-1.4.10.eb
easybuild/easyconfigs/g/GATE/GATE-6.2-intel-2015a.eb
easybuild/easyconfigs/g/GATE/GATE-6.2-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/g/GATE/GATE-7.0-intel-2015a.eb
easybuild/easyconfigs/g/GATE/GATE-7.1-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/g/GATE/GATE-7.2-intel-2016a-Python-2.7.11.eb

(source filename for GATE v6.2 has changed together with source URL, but checksum has remained the same)

fix source_urls (& sources spec) for GATE

---

easybuild/easyconfigs/r/RSEM/RSEM-1.3.0-intel-2017a.eb

{bio}[intel/2017a] RSEM v1.3.0

---

easybuild/easyconfigs/a/arrow/arrow-0.7.1-intel-2017b-Python-3.6.3.eb
easybuild/easyconfigs/b/bat/bat-0.3.3-intel-2017b-Python-3.6.3.eb
easybuild/easyconfigs/j/jemalloc/jemalloc-5.0.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/s/Spark/Spark-2.2.0-intel-2017b-Hadoop-2.6-Java-1.8.0_152-Python-3.6.3.eb
easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.19.1-intel-2017b-Python-3.6.3.eb

Needs:
- ~~easybuilders/easybuild-framework#2353~~
- ~~easybuilders/easybuild-easyblocks#1299~~

{data} [intel/2017b] bat 0.3.3 (REVIEW)

---

easybuild/easyconfigs/m/Mono/Mono-5.4.1.6-intel-2017b.eb

{lang} [intel/2017b] Mono 5.4.1.6

---

easybuild/easyconfigs/l/libdap/libdap-3.19.1-intel-2017b.eb

libdap 3.19.1 checksum changed

---

easybuild/easyconfigs/g/GDAL/GDAL-2.1.0-foss-2016a.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.0-foss-2016b.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.0-intel-2016b.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.1-foss-2016a.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.2-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.3-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.3-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.3-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.1.3-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.0-intel-2017a-Python-2.7.13-HDF5-1.8.18.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.2-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2017b-Python-2.7.14.eb

add missing dep reported by @jhein32 in #5212

add missing PROJ dependency in recent GDAL easyconfigs

---

easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gimpi-2017b-OpenBLAS-0.2.20.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmpich-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmvapich2-1.7.20-OpenBLAS-0.2.13-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmvapich2-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-1.4.10-OpenBLAS-0.2.6-LAPACK-3.4.2.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-1.5.14-OpenBLAS-0.2.8-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-1.5.16-OpenBLAS-0.2.13-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-1.6.10-OpenBLAS-0.2.8-LAPACK-3.4.2.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-1.7.20-OpenBLAS-0.2.13-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2014b-OpenBLAS-0.2.9-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2015.05-OpenBLAS-0.2.14-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2015a-OpenBLAS-0.2.13-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2015b-OpenBLAS-0.2.14-LAPACK-3.5.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.04-OpenBLAS-0.2.18-LAPACK-3.6.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.06-OpenBLAS-0.2.18-LAPACK-3.6.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.07-OpenBLAS-0.2.18-LAPACK-3.6.1.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.09-OpenBLAS-0.2.19-LAPACK-3.6.1.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2017a-OpenBLAS-0.2.19-LAPACK-3.7.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2017b-OpenBLAS-0.2.20.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2016.08-OpenBLAS-0.2.18-LAPACK-3.6.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2016.10-OpenBLAS-0.2.19-LAPACK-3.6.1.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2017.01-OpenBLAS-0.2.19-LAPACK-3.7.0.eb

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1288
cc @akesandgren

enable building ScaLAPACK in parallel with enhanced ScaLAPACK easyblocks

---

easybuild/easyconfigs/o/Octave/Octave-3.8.2-foss-2015a.eb
easybuild/easyconfigs/o/Octave/Octave-3.8.2-intel-2015a.eb
easybuild/easyconfigs/o/Octave/Octave-3.8.2-intel-2015b.eb
easybuild/easyconfigs/o/Octave/Octave-4.0.0-foss-2015a.eb
easybuild/easyconfigs/o/Octave/Octave-4.0.0-foss-2016a.eb
easybuild/easyconfigs/o/Octave/Octave-4.0.3-intel-2016b.eb
easybuild/easyconfigs/o/Octave/Octave-4.2.1-intel-2016b.eb
easybuild/easyconfigs/o/Octave/Octave-4.2.1-intel-2017a.eb

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1304

update Octave easyconfigs to use Octave easyblock, add extensions for latest Octave versions

---

easybuild/easyconfigs/h/Horovod/Horovod-0.9.10-intel-2017b-Python-3.6.3.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.1-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.1.0-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.1.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.2.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.2.1-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017b-Python-3.6.3.eb

The official name is `TensorFlow`, not `Tensorflow`, see https://www.tensorflow.org

fix name in TensorFlow easyconfigs

---

easybuild/easyconfigs/f/FoX/FoX-4.1.2-intel-2017b.eb

New module which is a dependency for newest version of QuantumESPRESSO (starting 6.2).

{lib}[intel/2017b] FoX v4.1.2

---

easybuild/easyconfigs/g/gdc-client/gdc-client-1.3.0-intel-2017b-Python-2.7.14.eb

avoid auto-downloading of parcel in gdc-client 1.3.0 easyconfig

---

easybuild/easyconfigs/c/CUDA/CUDA-9.1.85.eb

{system}[dummy] CUDA 9.1.85

---

easybuild/easyconfigs/l/LocARNA/LocARNA-1.9.2-foss-2016b.eb

{bio}[foss/2016b] LocARNA 1.9.2

---

easybuild/easyconfigs/p/PyCogent/PyCogent-1.5.3-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/PyCogent/PyCogent-1.9-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/PyCogent/PyCogent-1.9-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/PyNAST/PyNAST-1.2.2-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/PyNAST/PyNAST-1.2.2-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/u/UCLUST/UCLUST-1.2.22q-i86linux64.eb

This adds PyNAST and it's dependencies for the foss-2016b toolchain.

{bio}[foss/2016b] PyNAST 1.2.2 PyCogent 1.9

---

easybuild/easyconfigs/b/BEDTools/BEDTools-2.27.1-foss-2016b.eb
easybuild/easyconfigs/c/ChimPipe/ChimPipe-0.9.5-foss-2016b-Python-2.7.12.eb

This adds ChimPipe with a updated BEDTools.
I can't think of a good `sanity_check_commands` line because printing the help message returns with non-zero exit code and a real example would need additional data.

{bio}[foss/2016b] ChimPipe 0.9.5 + BEDTools 2.27.1

---

easybuild/easyconfigs/p/preseq/preseq-2.0.2-foss-2016b.eb

{bio}[foss/2016b] preseq 2.0.2

---

easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-GCCcore-5.4.0.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-GCCcore-6.3.0-libpng-1.6.29.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-GCCcore-6.3.0.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-foss-2015a.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-foss-2016b.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-gimkl-2017a.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.1-intel-2016b.eb
easybuild/easyconfigs/f/fontconfig/fontconfig-2.12.4-GCCcore-6.4.0.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.0-intel-2014b.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.0-intel-2015a.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.1-intel-2015b.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.3-foss-2016a.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.3-intel-2016a.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.5-foss-2016b.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.5-intel-2016b.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.6-intel-2017a.eb
easybuild/easyconfigs/g/gnuplot/gnuplot-5.2.2-foss-2017b.eb
easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.2.7-foss-2016a.eb
easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.2.7-intel-2016a.eb
easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.3.1-foss-2016b.eb
easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.3.1-intel-2016b.eb
easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.3.1-intel-2017a.eb
easybuild/easyconfigs/h/HarfBuzz/HarfBuzz-1.7.1-foss-2017b.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.1-foss-2016a.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.1-intel-2016a.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.12-intel-2017a.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.14-foss-2017b.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.3-foss-2016b.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.3-intel-2016b.eb
easybuild/easyconfigs/p/Pango/Pango-1.40.5-intel-2017a.eb

Reference Issue #5571
first commit

add pkg-config as build dep. for fontconfig, harfbuzz, gnuplot, pango

---

easybuild/easyconfigs/s/SOAPfuse/SOAPfuse-1.27-foss-2016b-Perl-5.24.0.eb

This adds SOAPfuse.
I can't think of a good `sanity_check_commands` line because printing the help message returns with non-zero exit code and a real example would need additional data.
Also the same question regarding the easyblock: Is `PackedBinary` the correct one here? There is also `Tarball` which seems to be very similar?

{bio}[foss/2016b] SOAPfuse 1.27

---

easybuild/easyconfigs/f/FastQ_Screen/FastQ_Screen-0.11.3-foss-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/f/FastQ_Screen/FastQ_Screen-0.11.4-foss-2016b-Perl-5.24.0.eb

This adds FastQ_Screen.
It needs either of Bowtie, Bowtie2 or BWA to work. I mentioned this in the `modloadmsg`. Is this sufficient?

{bio}[foss/2016b] FastQ_Screen 0.11.3 and 0.11.4

---

easybuild/easyconfigs/g/Greenlet/Greenlet-0.4.12-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/p/PyZMQ/PyZMQ-16.0.3-intel-2017b-Python-2.7.14-zmq4.eb
easybuild/easyconfigs/s/SCOOP/SCOOP-0.7.1.1-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.2-intel-2017b.eb

{tools}[intel/2017b]SCOOP v0.7.1.1

---

easybuild/easyconfigs/h/hwloc/hwloc-1.11.8-GCCcore-7.2.0.eb
easybuild/easyconfigs/n/numactl/numactl-2.0.11-GCCcore-7.2.0.eb
easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.0.0-GCC-7.2.0-2.29.eb

so hwloc was being ignored
edit: depends on #5623

fix for dependencies was set twice in OpenMPI 3.0.0 easyconfig

---

easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.5.0-foss-2017b.eb

{numlib} [foss/2017b] arpack-ng v3.5.0

---

easybuild/easyconfigs/p/PaStiX/PaStiX-5.2.3-foss-2017b.eb

version update and foss toolchain

{math}[foss/2017b] PaStiX v5.2.3

---

easybuild/easyconfigs/b/Boost/Boost-1.66.0-foss-2018a-Python-2.7.14.eb
easybuild/easyconfigs/b/Boost/Boost-1.66.0-foss-2018a-Python-3.6.4.eb
easybuild/easyconfigs/b/Boost/Boost-1.66.0-foss-2018a.eb

Depending on ~~#5677~~ and ~~#5678~~

{devel}[foss/2018a] Boost 1.66.0 (with and without Python)

---

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-intel-2017b.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-foss-2017b.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-intel-2017a.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-intel-2017b.eb

fix homepage for OpenFOAM 5.x

---

easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016a-Python-2.7.11.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016a-Python-3.5.1.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2015a-Python-2.7.9.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2015b-Python-2.7.10.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2015b-Python-2.7.11.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.1.0-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017a-Python-2.7.13.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017a-Python-3.6.1.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-foss-2017b-Python-3.6.3.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-intel-2017b-Python-3.6.3.eb

fix pkgconfig moduleclass, 'data' doesn't make much sense

---

easybuild/easyconfigs/h/HPL/HPL-2.2-iomkl-2018a.eb
easybuild/easyconfigs/i/imkl/imkl-2018.1.163-iompi-2018a.eb
easybuild/easyconfigs/i/iomkl/iomkl-2018a.eb
easybuild/easyconfigs/i/iompi/iompi-2018a.eb
easybuild/easyconfigs/o/OpenMPI/OpenMPI-2.1.2-iccifort-2018.1.163-GCC-6.4.0-2.28.eb

Here's a simple iomkl toolchain based on intel2018a.

{toolchain} iomkl/2018a

---

easybuild/easyconfigs/a/ABySS/ABySS-2.0.2-foss-2018a.eb

{bio}[foss/2018a] ABySS 2.0.2

---

easybuild/easyconfigs/g/GDAL/GDAL-2.2.2-intel-2017b-Python-2.7.14-HDF5-1.8.19.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.2-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.2_O1-ceos.patch

add patch for recent GDAL easyconfigs using intel toolchain to fix icc get stuck on compiling ceos.c

---

RELEASE_NOTES
setup.py

(WIP until results of regression test are in)

bump version to 3.5.2 & update release notes

---

easybuild/easyconfigs/p/Pillow/Pillow-5.0.0-foss-2018a-Python-3.6.4.eb
easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.1-foss-2018a-Python-3.6.4.eb

dependencies on ~~#5810~~ (X11), ~~#5743~~ (matplotlib)

{vis}[foss/2018a] scikit-image 0.13.1 + Pillow 5.0 0 w/ Python 3.6.4

---

easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-2.7.14.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-3.6.4.eb

Needs PR ~~#6038~~ -> ~~ #5827~~
Based on PR ~~#5931~~

{vis}[foss/2018a] OpenCV 3.4.1 w/ Python {2.7.14, 3.6.4} (REVIEW)

---

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-intel-2018a-Python-3.6.4.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_icc-fixes.patch
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0_icc-type_casting.patch

{lib}[intel/2018a] TensorFlow v1.6.0 w/ Python 3.6.4

---

easybuild/easyconfigs/b/Biopython/Biopython-1.70-foss-2017a-Python-2.7.13.eb

Biopython v1.70 easyconfig foss2017a

{bio}[foss/2017a] Biopython v1.70 w/ Python 2.7.13 (REVIEW)

---

easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb

fix checksums for R extensions that were updated in place in easyconfigs for R versions 3.4.3 & 3.4.4

---

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-foss-2018a-Python-3.6.4.eb

fix for #6146, see also https://github.com/tensorflow/tensorflow/issues/18424

fix checksum for TensorFlow 1.7.0 after sneaky re-release

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.1.0.eb

{lang}[dummy/dummy] Anaconda2 v5.1.0

---

easybuild/easyconfigs/a/ARAGORN/ARAGORN-1.2.38-foss-2016b.eb

use $CFLAGS rather than hardcoding compiler flags in ARAGORN easyconfig file

---

easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.4.1-intel-2017b.eb

The installation procedure is not ideal, but is justified by the limited number of users (currently).

{chem}[intel/2017b] Multiwfn v3.4.1

---

easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-4.9.3.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-5.3.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-5.4.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.2.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.3.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GCCcore-6.4.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-GNU-4.9.3-2.25.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016.04.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016a.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-foss-2016b.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-gimkl-2017a.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-goolf-1.4.10.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016.02-GCC-4.9.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016a.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-intel-2016b.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-iomkl-2016.07.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-iomkl-2016.09-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.1-GCCcore-7.2.0.eb

add --without-ada configure option in recent ncurses easyconfigs

---

easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.0-foss-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.1-intel-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.1-intel-2017a-Perl-5.24.1.eb
easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.2-intel-2017b-Perl-5.26.0.eb
easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-foss-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-intel-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-LibXML/XML-LibXML-2.0132-intel-2017a-Perl-5.24.1.eb

Also requires #6225 to pass `BioPerl` tests...

add missing XML-LibXML dependency in recent BioPerl easyconfigs

---

easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-GCCcore-5.4.0.eb
easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-foss-2016b.eb
easybuild/easyconfigs/l/libdrm/libdrm-2.4.70-intel-2016b.eb
easybuild/easyconfigs/l/libdrm/libdrm-2.4.76-GCCcore-6.3.0.eb
easybuild/easyconfigs/l/libdrm/libdrm-2.4.76-intel-2017a.eb

add pkg-config build dep to most recent libdrm easyconfigs

---

easybuild/easyconfigs/p/PETSc/PETSc-3.8.3-foss-2017b-downloaded-deps.eb

version bump and foss toolchain

{numlib}[foss/2017b] PETSc v3.8.3 download deps

---

easybuild/easyconfigs/j/Java/Java-1.8.0_172.eb

I needed the new version of Java and made this. Seems to have worked for me so I thought I'd share. :-)

{dummy} Java v1.8.0_172

---

easybuild/easyconfigs/j/Java/README.md

Took me a few minutes to figure out how to install Java with a weird warning about not being able to find the download. I thought I would post my notes for others in the future who might benefit.

add README for Java with information on downloading source tarball

---

easybuild/easyconfigs/p/PGI/PGI-18.4-GCC-6.4.0-2.28.eb

{compiler} PGI v18.4 (REVIEW)

---

easybuild/easyconfigs/m/minimap2/minimap2-2.10-foss-2018a.eb

Simple version and toolchain bump

{bio}[foss/2018a] minimap2 2.10

---

easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb
easybuild/easyconfigs/r/R/matrixStats-0.53.1_O1.patch

add patch to build particular source file of matrixStats extension in R 3.4.4 easyconfig with -O1 to work around ICE in Skylake systems

---

easybuild/easyconfigs/i/icc/README.md
easybuild/easyconfigs/i/ifort/README.md

It took me several tries before I got this one right. I will update the other Intel tools when I get a chance to verify them.
Used the same documentation format as I did for Java. Hopefully it is good.

Create README.md file for installing icc/ifort

---

easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/r/R/R-3.4.3-foss-2017b-X11-20171023.eb
easybuild/easyconfigs/r/R/R-3.4.3-intel-2017b-X11-20171023.eb
easybuild/easyconfigs/r/R/R-3.4.4-foss-2018a-X11-20180131.eb
easybuild/easyconfigs/r/R/R-3.4.4-intel-2018a-X11-20180131.eb
easybuild/easyconfigs/r/R/R-3.4.4-iomkl-2018a-X11-20180131.eb

required for rJava (and gdsfmt in Bioconductor bundle)

include ICU as dependency in recent R easyconfigs (v3.4.3 & v3.4.4)

---

easybuild/easyconfigs/r/RSEM/RSEM-1.3.0-intel-2017a.eb

see also https://github.com/easybuilders/easybuild-easyconfigs/pull/5719#issuecomment-360237978

fix checksum for RSEM 1.3.0 after sneaky re-release

---

easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-GCCcore-7.2.0.eb
easybuild/easyconfigs/c/CMake/CMake-3.10.3-GCCcore-7.2.0.eb
easybuild/easyconfigs/l/libreadline/libreadline-7.0-GCCcore-7.2.0.eb

[GCCcore/7.2.0] bzip2 v1.0.6, CMake v3.10.3, libreadline v7.0

---

easybuild/easyconfigs/h/HDF5/HDF5-1.10.2-PGI-18.4-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/p/PGI/PGI-18.4-GCC-6.4.0-2.28.eb

New `ebfiles` for `HDF5` libraries (v1.10.1 and v1.10.2) built with `PGI/18.4`

{data}[PGI/18.4] HDF5 v1.10.2 (REVIEW)

---

easybuild/easyconfigs/f/fastStructure/fastStructure-1.0-foss-2016a-Python-2.7.11.eb

{bio}[foss/2016a] fastStructure 1.0 w/ Python 2.7.11

---

easybuild/easyconfigs/f/fastStructure/fastStructure-1.0-foss-2016a-Python-2.7.11.eb

Easyconfig for fastStructure. This is basically a python program called structure.py with some C code integrated using Cython. The thing is supposed to be built using:
`python setup.py build_ext --inplace`
This both for the main directory as well as for the directory vars. Since this is not a nicely structured Python package using the PythonPackage easyblock does not work, so I opted for CmdCp.

fastStructure 1.0 built using the foss-2016a toolchain.

---

easybuild/easyconfigs/c/cuDNN/cuDNN-7.0.5.15-goolfc-2017b.eb

Added hint on file name differences

Hint on file name differences between downloaded and expected by config

---

easybuild/easyconfigs/j/jemalloc/jemalloc-5.0.1-GCCcore-6.4.0.eb

skip installing of documentation in easyconfig for jemalloc 5.0.1

---

easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-2.7.14.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.4.1-foss-2018a-Python-3.6.4.eb

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1444

update existing easyconfigs for OpenCV 3.4.1 to use new custom easyblock for OpenCV

---

easybuild/easyconfigs/e/eggnog-mapper/eggnog-mapper-1.0.3-intel-2018a-Python-2.7.14.eb

also copy eggnog-mapper scripts

---

easybuild/easyconfigs/b/Bsoft/Bsoft-1.8.8-goolf-1.5.14.eb

fix software name in Bsoft easyconfig

---

easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.4-iomkl-2018a.eb
easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-iomkl-2018a.eb
easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.7-iomkl-2018a-R-3.5.0.eb

This follows on from #6466 - which needs to be merged first. This will then just contain two easyconfigs.
Extensions updated with easy_update.

Bioconductor 3.7 iomkl 2018a R 3.5.0

---

easybuild/easyconfigs/c/cutadapt/cutadapt-1.16-foss-2018a-Python-3.6.4.eb

Update for cutadapt-1.14-foss-2017a-Python-2.7.13.eb

{bio}[foss/2018a] Cutadapt 1.16

---

easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.3-foss-2016b-ParMETIS-4.0.3.eb
easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.3-intel-2016b-ParMETIS-4.0.3.eb

{numlib}[foss/2016b,intel/2016b] SuiteSparse v4.5.3

---

easybuild/easyconfigs/w/wkhtmltopdf/wkhtmltopdf-0.12.3-Linux-x86_64.eb

Corrected the checksum
edit: follow-up for #6628

fix checksum in wkhtmltopdf-0.12.3-Linux-x86_64.eb

---

easybuild/easyconfigs/h/HDF5/HDF5-1.10.2-iomkl-2018b.eb
easybuild/easyconfigs/n/netCDF-C++4/netCDF-C++4-4.3.0-iomkl-2018b.eb
easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.4-iomkl-2018b.eb
easybuild/easyconfigs/n/netCDF/netCDF-4.6.1-iomkl-2018b.eb

{data}[iomkl/2018b] netCDF{,-Fortran,-C++4} HDF5 (REVIEW)

---

easybuild/easyconfigs/h/h5py/h5py-2.8.0-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/h/h5py/h5py-2.8.0-foss-2018b-Python-3.7.0.eb
easybuild/easyconfigs/h/h5py/h5py-2.8.0-intel-2018b-Python-2.7.15.eb
easybuild/easyconfigs/h/h5py/h5py-2.8.0-intel-2018b-Python-3.7.0.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-foss-2018b-Python-3.7.0.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-intel-2018b-Python-2.7.15.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.3.1-intel-2018b-Python-3.7.0.eb

Configurations for h5py and pkgconfig

{data}[foss-2018b,intel-2018b] h5py v2.8.0 in Python 2 and Python 3

---

easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2017a.eb
easybuild/easyconfigs/p/Python/Python-3.6.4-foss-2018a.eb
easybuild/easyconfigs/p/Python/Python-3.6.4-fosscuda-2018a.eb
easybuild/easyconfigs/p/Python/Python-3.6.4-golf-2018a.eb
easybuild/easyconfigs/p/Python/Python-3.6.4-intel-2018a.eb
easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018.02.eb
easybuild/easyconfigs/p/Python/Python-3.6.4-iomkl-2018a.eb
easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb
easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb
easybuild/easyconfigs/p/Python/Python-3.7.0-iomkl-2018b.eb

add mpmath extension to Python 3.6.4 + 3.7.0 easyconfigs

---

easybuild/easyconfigs/c/cairo/cairo-1.14.12-GCCcore-7.3.0.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.3-foss-2018b-Python-3.7.0.eb
easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-foss-2018b-Python-3.7.0.eb
easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-7.3.0.eb
easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-GCCcore-7.3.0.eb
easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.0.9-GCCcore-7.3.0.eb
easybuild/easyconfigs/l/libsndfile/libsndfile-1.0.28-GCCcore-7.3.0.eb
easybuild/easyconfigs/n/NLopt/NLopt-2.4.2-GCCcore-7.3.0.eb
easybuild/easyconfigs/p/PROJ/PROJ-5.0.0-foss-2018b.eb
easybuild/easyconfigs/p/pixman/pixman-0.34.0-GCCcore-7.3.0.eb
easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-foss-2018b-Python-3.7.0.eb
easybuild/easyconfigs/u/util-linux/util-linux-2.32.1-GCCcore-7.3.0.eb

adding libraries for foss-2018b
edit: depends on ~~#6656~~

various tools & libraries built with foss/2018b

---

easybuild/easyconfigs/j/Java/Java-1.8.0_181.eb

required for R-3.5.1 foss 2018b

{lang}[dummy] Java 1.8.0_181

---

easybuild/easyconfigs/t/Triangle/Triangle-1.6-GCCcore-6.4.0.eb

More general eb file for Triangle v1.6 based on GCCcore 6.4.0.

{numlib} [GCCcore/6.4.0] Triangle v1.6 (REVIEW)

---

easybuild/easyconfigs/g/git/git-2.12.2-foss-2016b.eb
easybuild/easyconfigs/g/git/git-2.13.1-foss-2016b.eb
easybuild/easyconfigs/g/git/git-2.14.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/g/git/git-2.16.1-foss-2018a.eb
easybuild/easyconfigs/g/git/git-2.18.0-GCCcore-7.3.0.eb

fix for #6746 reported by @chrissamuel

also install docs/man pages in recent git easyconfigs (versions 2.1x.y)

---

easybuild/easyconfigs/b/biomart-perl/biomart-perl-0.7_e6db561-GCCcore-6.4.0-Perl-5.26.0.eb

{bio}[GCCcore/6.4.0] biomart-perl v0.7_e6db561

---

easybuild/easyconfigs/c/CMake/CMake-3.12.0-GCCcore-7.3.0.eb
easybuild/easyconfigs/c/CMake/CMake-3.12.1-GCCcore-7.3.0.eb

Cmake easyconfig for version 3.12.0 in GCCcore 7.3.0

{devel}[GCCcore/7.3.0] Cmake v3.12.0

---

easybuild/easyconfigs/b/BWISE/BWISE-20180820-foss-2018a-Python-3.6.4.eb

Needs easybuilders/easybuild-easyblocks#1497

{bio} [foss/2018a] BWISE (REVIEW)

---

easybuild/easyconfigs/s/SearchGUI/SearchGUI-3.3.3-Java-1.8.0_152.eb

easyconfig for SearchGUI

---

easybuild/easyconfigs/p/parallel/parallel-20180822-foss-2018b.eb

This PR updates GNU parallel to the latest version.

Update parallel to 20180822

---

easybuild/easyconfigs/b/Bowtie2/Bowtie2-2.3.4.2-foss-2018b.eb

Bowtie2-2.3.4.2-foss-2018b

---

easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gimkl-2.11.5.eb
easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-goolf-1.4.10.eb
easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-intel-2016a.eb
easybuild/easyconfigs/p/ParMGridGen/ParMGridGen-1.0-intel-2017a.eb

gmake usually doesn't exist.
Update with checksums.

Use make=make in ParMGridGen easyconfigs.

---

easybuild/easyconfigs/g/GlobusConnectPersonal/GlobusConnectPersonal-2.3.6.eb

Easyconfig for Globus Connect Personal version 2.3.6.

Easyconfig for Globus Connect Personal 2.3.6.

---

easybuild/easyconfigs/w/wheel/wheel-0.31.0-fosscuda-2018a-Python-2.7.14.eb

wheel 0.31.0 for fosscuda 2018a and Python 2.7.14

wheel 0.31.0 for fosscuda 2018a and Python 2.7.14

---

easybuild/easyconfigs/b/BBMap/BBMap-38.26-foss-2018b.eb
easybuild/easyconfigs/b/BEDOPS/BEDOPS-2.4.35-foss-2018b.eb
easybuild/easyconfigs/b/BWA/BWA-0.7.17-foss-2018b.eb
easybuild/easyconfigs/b/Beast/Beast-2.5.1-foss-2018b.eb
easybuild/easyconfigs/b/beagle-lib/beagle-lib-3.0.2-foss-2018b.eb

A few Bio Modules that start with B for 2018b
BBMap-38.26-foss-2018b.eb
BEDOPS-2.4.35-foss-2018b.eb
BWA-0.7.17-foss-2018b.eb
Beast-2.5.1-foss-2018b.eb
beagle-lib-3.0.2-foss-2018b.eb

{bio}[foss-2018b] BBMap 38.26, BEDOPS 2.4.35, BWA 0.7.17, Beast 2.5.1, beagle-lib 3.0.2

---

easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb

add openssl OS deps in Perl 5.28.0 easyconfig for Net::ssleay

---

easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb
easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb

Another in-place update of an R package, hooray...
This has happened before for a previous version of this same package `mgcv`, see #6502 .
cc @JoFAM

fix checksum for mgcv extension in R 3.5.* easyconfigs

---

easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018a-Python-2.7.14.eb
easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018a-Python-3.6.4.eb

Version push as a workaround for build issue of ITK 4.13.0
This is a (partial) fix or workaround the issue: https://github.com/easybuilders/easybuild-easyconfigs/issues/7128

{tools}[foss/2018a] EasyConfigs for ITK 4.13.1

---

easybuild/easyconfigs/i/ITK/ITK-4.13.1-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/l/Lua/Lua-5.1.5-GCCcore-7.3.0.eb
easybuild/easyconfigs/s/SimpleITK/SimpleITK-1.1.0-foss-2018b-Python-2.7.15.eb

Hey guys,
I wanted to add SimpleITK 1.1.0 w/ Python 2.7.15. It depends on ITK v4.13.1, which I updated from v4.13.0.
Furthermore, it depends on Lua 5.1.X, but unfortunately Ubuntu Bionic includes 5.2 by default.
Best regards,
-crubb

{tools} [foss/2018b] Add SimpleITK 1.1.0 w/ Python 2.7.15, ITK 4.13.1 and Lua-5.1.5

---

easybuild/easyconfigs/t/Tk/Tk-8.6.8-GCCcore-6.4.0.eb
easybuild/easyconfigs/t/Tk/Tk-8.6.8-GCCcore-7.3.0.eb
easybuild/easyconfigs/t/Tk/Tk-8.6.8-foss-2018a.eb
easybuild/easyconfigs/t/Tk/Tk-8.6.8-iomkl-2018a.eb

See http://www.linuxfromscratch.org/blfs/view/8.2/general/tk.html

Install Tk private headers

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.3.0.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-5.3.0.eb

{lang}[dummy/dummy] Anaconda2 and Anaconda3 version 5.3.0

---

easybuild/easyconfigs/a/angsd/angsd-0.910-foss-2016a.eb
easybuild/easyconfigs/a/angsd/angsd-0.921-foss-2018a.eb

This modification of the angsd easyconfigs makes sure that the additional tools from the misc dir are also installed.

angsd - install misc tools

---

easybuild/easyconfigs/a/ASE/ASE-3.16.2-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/a/ASE/ASE-3.16.2-intel-2018b-Python-3.6.6.eb
easybuild/easyconfigs/a/ASE/ASE-3.16.2-iomkl-2018.02-Python-3.6.4.eb
easybuild/easyconfigs/a/ASE/ASE-3.16.2-iomkl-2018a-Python-3.6.4.eb
easybuild/easyconfigs/a/ASE/ASE-3.16.2-iomkl-2018b-Python-3.6.6.eb

~~WIP since this change should be made consistent across all ASE 3.16.2 easyconfigs, and `PythonBundle` should be used~~

fix missing required Python packages in ASE 3.16.2 easyconfigs

---

easybuild/easyconfigs/a/ADMIXTURE/ADMIXTURE-1.3.0.eb

#7256 fixed URL for ADMIXTURE

---

easybuild/easyconfigs/l/libglade/libglade-2.6.4-foss-2018b.eb
easybuild/easyconfigs/p/PyCairo/PyCairo-1.18.0-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/p/PyGObject/PyGObject-2.28.7-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/p/PyGTK/PyGTK-2.24.0-foss-2018b-Python-2.7.15.eb

{vis}[foss/2018b] PyGTK 1.18.0 w/ Python 2.7.15 (REVIEW)

---

easybuild/easyconfigs/t/TRF/TRF-4.09-linux64.eb

see also discussion in https://github.com/easybuilders/easybuild-easyconfigs/pull/5729/files#r170422991

fix checksum for TRF 4.09

---

easybuild/easyconfigs/a/ARPACK++/ARPACK++-2018.03.26-foss-2017b.eb
easybuild/easyconfigs/a/ARPACK++/ARPACK++-2018.03.26_find-deps.patch
easybuild/easyconfigs/s/SuiteSparse/SuiteSparse-4.5.6-foss-2017b-METIS-5.1.0.eb
easybuild/easyconfigs/s/SuperLU/SuperLU-5.2.1-foss-2017b.eb

needs ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1479~~

{numlib}[foss-2017b] ARPACK++ 2018.03.26 (REVIEW)

---

easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb

This slipped in with #7237, incorrect checksum was added after test reports were submitted...

fix checksum for VMD 1.9.3 patch file

---

easybuild/easyconfigs/p/pigz/pigz-2.3.4-GCCcore-6.4.0.eb
easybuild/easyconfigs/p/pigz/pigz-2.4-GCCcore-6.4.0.eb
easybuild/easyconfigs/p/pigz/pigz-2.4-GCCcore-7.3.0.eb
easybuild/easyconfigs/p/pigz/pigz-2.4-foss-2018a.eb

add fallback source URL for recent pigz versions

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-2018.12.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-2018.12.eb

EasyConfigs for the latest Anaconda distribution.
Remark: Anaconda changed their version numbering scheme

{lang}[dummy/dummy] Anaconda2 and Anaconda3 version 2018.12

---

easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-5.3.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-5.4.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-5.5.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.3.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.4.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.1.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.2.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.3.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.4.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.1.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.2.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-system.eb
easybuild/easyconfigs/m/M4/M4-1.4.18.eb
easybuild/easyconfigs/m/M4/M4-1.4.18_glibc_2.28.patch
easybuild/easyconfigs/m/M4/M4_glibc_2.28.patch

see issue https://github.com/easybuilders/easybuild-easyconfigs/issues/7383

fix issue of M4 1.4.18 with glibc 2.28

---

easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.1-GCCcore-7.3.0.eb

`libsigc++` is dependency of `GTK+3`.

{devel}[GCCcore/7.3.0] libsigc++ v2.10.1 (GTK+3)

---

easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-goolf-1.4.10-Perl-5.16.3.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-intel-2014b-Perl-5.20.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-intel-2015b-Perl-5.20.3.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.41-intel-2016a-Perl-5.20.3.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44-foss-2015a-Perl-5.22.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44-foss-2016a-Perl-5.22.1.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44-intel-2016a-Perl-5.22.1.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-4.9.3-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-5.4.0-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-6.3.0-Perl-5.24.1.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-6.4.0-Perl-5.26.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-6.4.0-Perl-5.26.1.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-GCCcore-7.3.0-Perl-5.28.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-foss-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-gimkl-2017a-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-intel-2016b-Perl-5.24.0.eb
easybuild/easyconfigs/x/XML-Parser/XML-Parser-2.44_01-intel-2017a-Perl-5.24.1.eb

cfr. discussion in #6866
requires ~~https://github.com/easybuilders/easybuild-framework/pull/2728~~

use %(arch)s template rather than hardcoding 'x86_64' in XML-Parser easyconfigs

---

easybuild/easyconfigs/p/PyQt5/PyQt5-5.11.3-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/p/PyQt5/PyQt5-5.7-foss-2016a-Python-2.7.11.eb
easybuild/easyconfigs/p/PyQt5/PyQt5-5.7.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/p/PyQt5/PyQt5-5.8.2-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/p/PyQt5/PyQt5-5.9.2-foss-2018a-Python-3.6.4.eb
easybuild/easyconfigs/p/PyQt5/PyQt5-5.9.2-intel-2018a-Python-3.6.4.eb

fix for problem reported in #7409 by @guest1604

fix configopts in PyQt5 easyconfig files to avoid installation of files in Python/Qt5 installation directories

---

easybuild/easyconfigs/s/sympy/sympy-1.3-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/s/sympy/sympy-1.3-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/s/sympy/sympy-1.3-intel-2018a-Python-2.7.14.eb
easybuild/easyconfigs/s/sympy/sympy-1.3-intel-2018a-Python-3.6.4.eb
easybuild/easyconfigs/s/sympy/sympy-1.3_allpython.patch

`sympy` for `Python-3.6.6` is dependency of [cadabra](https://cadabra.science).
version for `Python 2.7.15` created accidentally.

{math}[foss/2018b] sympy v1.3 w/ Python 2.7.15 & 3.6.6

---

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1812-cleanup.patch
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v1812-foss-2018b.eb

fix for bug reported in #7486 by @guest1604

fix typo in patch for OpenFOAM v1812

---

easybuild/easyconfigs/f/Ferret/Ferret-7.3-intel-2017b.eb

Needs ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1349~~
replaces ~~https://github.com/easybuilders/easybuild-easyconfigs/pull/4633~~

{vis}[intel/2017b] Ferret 7.3 (REVIEW)

---

easybuild/easyconfigs/w/wheel/wheel-0.30.0-fosscuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/w/wheel/wheel-0.30.0-fosscuda-2017b-Python-3.6.3.eb
easybuild/easyconfigs/w/wheel/wheel-0.30.0-intelcuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/w/wheel/wheel-0.30.0-intelcuda-2017b-Python-3.6.3.eb

{tools}[fosscuda/2017b,intelcuda/2017b] wheel v0.30.0

---

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0-fosscuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.8.0-fosscuda-2017b-Python-3.6.3.eb

Depends on:
#7594 (Python) 
#7604 (wheel)
#7480 (cuDNN)

{lib}[fosscuda/2017b] TensorFlow v1.8.0

---

easybuild/easyconfigs/b/Bazel/Bazel-0.10.0-GCCcore-6.4.0.eb
easybuild/easyconfigs/b/Bazel/Bazel-0.10.0_remove_define_DATE.patch

This is part of the attempt of building `Tensorflow/1.8.0` with the Intel compiler

Add remove define DATE patch for Bazel-0.10.0-GCCcore-6.4.0

---

easybuild/easyconfigs/s/SNPhylo/SNPhylo-20160204-foss-2017b-Python-2.7.14-R-3.4.3.eb
easybuild/easyconfigs/s/SNPhylo/SNPhylo-20160204-intel-2017b-Python-2.7.14-R-3.4.3.eb

Depends on:
~~#7608~~ (PHYLIP)
~~#7609~~ (MUSCLE)
~~#7595~~ (R-bundle-Bioconductor)
Also requires changes to the easyblock:
~~https://github.com/easybuilders/easybuild-easyblocks/pull/1632~~

{bio}[foss/2017b,intel/2017b] SNPhylo v20160204

---

easybuild/easyconfigs/s/SCons/SCons-3.0.4-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/s/SCons/SCons-3.0.4_fix-pip-install.patch

~~#7754 should get merged first, after which this PR should be rebased on `develop`...~~

{devel}[foss/2018b] SCons 3.0.4 w/ Python 2.7.15 

---

easybuild/easyconfigs/h/HDF5/HDF5-1.10.1-fosscuda-2017b.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-fosscuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-fosscuda-2017b-Python-3.6.3.eb
easybuild/easyconfigs/k/Keras/Keras-2.2.0-fosscuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/k/Keras/Keras-2.2.0-fosscuda-2017b-Python-3.6.3.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-fosscuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/p/pkgconfig/pkgconfig-1.2.2-fosscuda-2017b-Python-3.6.3.eb

Depends on:
~#7718~ (Theano)
~#7717~ (PyYAML)

{math}[fosscuda/2017b] Keras v2.2.0

---

easybuild/easyconfigs/s/snakemake/snakemake-5.2.4-foss-2018b-Python-3.6.6.eb

as requested by @akesandgren in #7819

use PythonBundle for snakemake-5.2.4-foss-2018b-Python-3.6.6.eb (+ fix moduleclass)

---

easybuild/easyconfigs/__archive__/l/LWM2/LWM2-1.1-gompi-1.4.12-no-OFED.eb
easybuild/easyconfigs/__archive__/o/OPARI2/OPARI2-1.0.7-gompi-1.4.12-no-OFED.eb
easybuild/easyconfigs/__archive__/o/OPARI2/OPARI2-1.1.1-gompi-1.4.12-no-OFED.eb
easybuild/easyconfigs/__archive__/o/OTF2/OTF2-1.2.1-gompi-1.4.12-no-OFED.eb
easybuild/easyconfigs/__archive__/s/Score-P/Score-P-1.2.1-gompi-1.4.12-no-OFED.eb
easybuild/easyconfigs/l/LWM2/LWM2-1.1-ictce-5.3.0.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.1-goolf-1.5.14.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.2-foss-2015a.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-1.1.2-goolf-1.5.14.eb
easybuild/easyconfigs/o/OPARI2/OPARI2-2.0-foss-2016a.eb
easybuild/easyconfigs/o/OTF2/OTF2-1.2.1-goolf-1.5.14.eb
easybuild/easyconfigs/o/OTF2/OTF2-1.2.1-ictce-5.3.0.eb
easybuild/easyconfigs/o/OTF2/OTF2-1.5.1-foss-2015a.eb
easybuild/easyconfigs/o/OTF2/OTF2-2.0-foss-2016a.eb
easybuild/easyconfigs/o/OTF2/OTF2-2.0-foss-2017a.eb
easybuild/easyconfigs/s/Score-P/Score-P-1.2.1-goolf-1.5.14.eb
easybuild/easyconfigs/s/Score-P/Score-P-1.2.3-goolf-1.5.14.eb
easybuild/easyconfigs/s/Score-P/Score-P-1.4-foss-2015a.eb
easybuild/easyconfigs/s/Score-P/Score-P-2.0.1-foss-2016a.eb

The URLs have changed due to an CMS upgrade :unamused:

Fix LWM2, OTF2, OPARI2, and Score-P download URLs

---

easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-GCC-4.9.2.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-iccifort-2015.1.133-GCC-4.9.2.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.10.0-iccifort-2015.2.164-GCC-4.9.2.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.10.1-GCC-4.8.4.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.10.1-GNU-4.9.2-2.25.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.5.1-GCC-4.6.3.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.5.1-ictce-5.3.0.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.6-ictce-5.3.0.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.6.4.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-GCC-4.7.2.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.6.2-ictce-5.3.0.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.7.2-GCC-4.8.2.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.7.2-ictce-5.3.0.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.7.2-ictce-5.5.0.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.8.1-GCC-4.8.2.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.8.1-GCC-4.8.3.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.8.1-iccifort-2013_sp1.2.144.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.9-GCC-4.8.3.eb
easybuild/easyconfigs/h/hwloc/hwloc-1.9-iccifort-2013_sp1.4.211.eb

fixes hwloc part of #7943 for old hwloc easyconfigs
cc @patbel-pwr

use https:// in homepage & source_urls for old hwloc 1.x easyconfigs

---

easybuild/easyconfigs/f/FastANI/FastANI-1.1-foss-2018b.eb
easybuild/easyconfigs/f/FastANI/FastANI-1.1-intel-2018b.eb
easybuild/easyconfigs/f/FastANI/FastANI-1.1-memcpy.patch

based on top of #7365 by @fizwit

{bio}[foss/2018b,intel/2018b] FastANI 1.1

---

easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-foss-2017b-R-3.4.3-Python-2.7.14.eb
easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-intel-2017b-R-3.4.3-Python-2.7.14.eb

{tools}[foss/2017b,intel/2017b] IRkernel v0.8.15

---

easybuild/easyconfigs/a/ATK/ATK-2.32.0-GCCcore-8.2.0.eb
easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.32.0-GCCcore-8.2.0.eb
easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.32.0-GCCcore-8.2.0.eb
easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.32.0_remove-subdir-prefix.patch

{vis}[GCCcore/8.2.0] ATK v2.32.0, at-spi2-core v2.32.0, at-spi2-atk v2.32.0

---

easybuild/easyconfigs/u/unixODBC/unixODBC-2.3.7-foss-2018b.eb

{data}[foss/2018b] unixODBC v2.3.7

---

test/easyconfigs/easyconfigs.py

requires ~~https://github.com/easybuilders/easybuild-framework/pull/2838~~
See for example https://github.com/easybuilders/easybuild-easyconfigs/pull/8074

add check for custom sanity_check_paths in easyconfigs touched in PRs when generic easyblock is used

---

test/easyconfigs/easyconfigs.py

PythonBundle already has a decent customised sanity_check_paths for bundles of Python packages

---

easybuild/easyconfigs/g/gmsh/gmsh-3.0.6-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/g/gmsh/gmsh-4.2.2-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/p/PETSc/PETSc-3.11.0-foss-2018b-downloaded-deps.eb
easybuild/easyconfigs/s/SLEPc/SLEPc-3.11.0-foss-2018b.eb

Easyconfigs required to provide gmsh in foss/2018b.  This includes PETSc 3.11.0 and SLEPc 3.11.0

{math}[foss/2018b] PETSc 3.11.0, SLEPc 3.11.0, gmsh 3.0.6, gmsh 4.2.2

---

easybuild/easyconfigs/p/psmc/psmc-0.6.5-foss-2018a.eb

{bio}[foss/2018a] psmc 0.6.5

---

easybuild/easyconfigs/o/OpenCV/OpenCV-4.0.1-foss-2018b-Python-3.6.6.eb

OpenCV 4.0.1 easyconfig for use with Python 3.6.6

{vis}[foss/2018b] OpenCV v4.0.1 w/ Python 3.6.6

---

easybuild/easyconfigs/c/charmm/charmm-43b2-foss-2017b.eb
easybuild/easyconfigs/c/charmm/charmm-43b2-intel-2017b.eb
easybuild/easyconfigs/c/charmm/charmm-43b2_Use_xhost.patch

The `intel/2017b` build requires the following changes in the easyblock:
~~https://github.com/easybuilders/easybuild-easyblocks/pull/1707~~

{chem}[foss/2017b,intel/2017b] charmm v43b2

---

easybuild/easyconfigs/h/hypothesis/hypothesis-4.5.0-fosscuda-2018b-Python-3.6.6.eb
easybuild/easyconfigs/m/magma/magma-2.5.0-fix-makefile.patch
easybuild/easyconfigs/m/magma/magma-2.5.0-fosscuda-2018b.eb
easybuild/easyconfigs/p/PyTorch/PyTorch-1.0.1-fosscuda-2018b-Python-3.6.6.eb

requires patches from ~~#7603~~

{devel}[fosscuda/2018b] PyTorch v1.0.1 w/ Python 3.6.6

---

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.0-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.0-GCC-7.3.0-2.30.eb
easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.1-GCC-7.3.0-2.30.eb
easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.3-GCC-8.2.0-2.31.1.eb
easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.4-GCC-8.2.0-2.31.1.eb
easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.5-GCC-8.2.0-2.31.1.eb

New easyblock from here https://github.com/easybuilders/easybuild-easyblocks/pull/1697 - so the eb files can be much shorter. This now builds on POWER systems too.

use custom easyblock for OpenBLAS in OpenBLAS 0.3.x easyconfigs

---

easybuild/easyconfigs/e/ELPA/ELPA-2018.11.001-intel-2019a.eb

requires https://github.com/easybuilders/easybuild-easyblocks/pull/1621
cc @micaeljtoliveira

clean up ELPA 2018.11.001 easyconfig to use custom easyblock for ELPA

---

easybuild/easyconfigs/p/PSI4/PSI4-1.2.1-intel-2018b-Python-2.7.15-maxam8.eb
easybuild/easyconfigs/p/PSI4/PSI4-1.2.1-intel-2018b-Python-2.7.15.eb

also adding the `import psi4` check here for consistency (cfr. #8362)

add sanity check command to PSI4 1.2.1 easyconfigs to ensure that 'import psi4' works

---

easybuild/easyconfigs/n/nanopolish/nanopolish-0.10.2-intel-2018b-Python-2.7.15.eb
easybuild/easyconfigs/n/nanopolish/nanopolish-0.9.2-intel-2018a.eb

Eigen is just a bunch of header files, so there's little point in making it a runtime dep...

make Eigen a build dependency for nanopolish

---

easybuild/easyconfigs/c/canu/canu-1.8-foss-2017b-Perl-5.26.0.eb
easybuild/easyconfigs/c/canu/canu-1.8-foss-2018b-Perl-5.28.0.eb

see PR https://github.com/easybuilders/easybuild-easyconfigs/pull/8463

add in Boost dependency to canu-1.8-foss easyconfigs

---

easybuild/easyconfigs/c/ciftify/ciftify-2.3.2.post1-foss-2017b-Python-3.6.3.eb
easybuild/easyconfigs/c/ciftify/ciftify-2.3.2.post1-intel-2017b-Python-3.6.3.eb

{vis}[foss/2017b,intel/2017b] ciftify v2.3.2.post1 w/ Python 3.6.3

---

easybuild/easyconfigs/a/ABINIT/ABINIT-8.10.2-intel-2018b.eb

{chem}[intel/2018b] ABINIT v8.10.2

---

easybuild/easyconfigs/m/Miniconda2/Miniconda2-4.6.14.eb
easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.6.14.eb

Adds easyconfig files for Miniconda2 and Miniconda3 in latest version 4.6.14.
This is my first pull-request ever, so i hope I do it correctly.

adds easyconfig for Miniconda version 4.6.14

---

easybuild/easyconfigs/k/kallisto/kallisto-0.45.1-foss-2019a.eb

Minor update of `kallisto` to version 0.45.1 with no particular changes.

{bio}[foss/2019a] kallisto v0.45.1

---

easybuild/easyconfigs/r/RSEM/RSEM-1.3.2-foss-2018b.eb

{bio}[foss/2018b] RSEM v1.3.2

---

easybuild/easyconfigs/m/magick/magick-2.0-foss-2018b-R-3.5.1.eb

This is a small R package that binds with ImageMagick. I made a specific easyconfig for it to not add yet another dependency into `R-3.5.1`. If you prefer to have it included into the easyconfig of `R`, let me know and I will change it.

{vis}[foss/2018b] R package magick-2.0 for R-3.5.1

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-2019.07.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.07.eb

Version push to the latest Anaconda 2019.07

{lang}[dummy/dummy] Anaconda2 and Anaconda3 version 2019.07

---

easybuild/easyconfigs/i/iompi/iompi-2016.07.eb
easybuild/easyconfigs/i/iompi/iompi-2016.09-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/i/iompi/iompi-2016.09-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/i/iompi/iompi-2017.01.eb
easybuild/easyconfigs/i/iompi/iompi-2017a.eb
easybuild/easyconfigs/i/iompi/iompi-2017b.eb
easybuild/easyconfigs/i/iompi/iompi-2018.02.eb
easybuild/easyconfigs/i/iompi/iompi-2018a.eb
easybuild/easyconfigs/i/iompi/iompi-2018b.eb
easybuild/easyconfigs/i/iompi/iompi-2019.01.eb

fix names of local variables in iompi easyconfigs

---

easybuild/easyconfigs/i/iomkl/iomkl-2016.07.eb
easybuild/easyconfigs/i/iomkl/iomkl-2016.09-GCC-4.9.3-2.25.eb
easybuild/easyconfigs/i/iomkl/iomkl-2016.09-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/i/iomkl/iomkl-2017.01.eb
easybuild/easyconfigs/i/iomkl/iomkl-2017a.eb
easybuild/easyconfigs/i/iomkl/iomkl-2017b.eb
easybuild/easyconfigs/i/iomkl/iomkl-2018.02.eb
easybuild/easyconfigs/i/iomkl/iomkl-2018a.eb
easybuild/easyconfigs/i/iomkl/iomkl-2018b.eb
easybuild/easyconfigs/i/iomkl/iomkl-2019.01.eb

fix names of local variables in iomkl easyconfigs

---

easybuild/easyconfigs/c/CUDA/CUDA-10.1.105-GCC-8.2.0-2.31.1.eb
easybuild/easyconfigs/c/CUDA/CUDA-10.1.105-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
easybuild/easyconfigs/c/CUDA/CUDA-9.0.176-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/c/CUDA/CUDA-9.0.176-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/c/CUDA/CUDA-9.2.148.1.eb
easybuild/easyconfigs/c/CUDA/CUDA-9.2.88-GCC-7.3.0-2.30.eb
easybuild/easyconfigs/g/GNU/GNU-4.9.2-2.25.eb
easybuild/easyconfigs/g/GNU/GNU-4.9.3-2.25.eb
easybuild/easyconfigs/g/GNU/GNU-5.1.0-2.25.eb
easybuild/easyconfigs/g/gcccuda/gcccuda-2016.08.eb
easybuild/easyconfigs/g/gcccuda/gcccuda-2017b.eb
easybuild/easyconfigs/g/gcccuda/gcccuda-2018a.eb
easybuild/easyconfigs/g/gcccuda/gcccuda-2018b.eb
easybuild/easyconfigs/g/gcccuda/gcccuda-2019a.eb

fix names of local variables in CUDA/GNU/gcccuda easyconfigs

---

easybuild/easyconfigs/g/gimkl/gimkl-2.11.5.eb
easybuild/easyconfigs/g/gimkl/gimkl-2017a.eb
easybuild/easyconfigs/g/gimkl/gimkl-2018b.eb
easybuild/easyconfigs/g/gimpi/gimpi-2.11.5.eb
easybuild/easyconfigs/g/gimpi/gimpi-2017a.eb
easybuild/easyconfigs/g/gimpi/gimpi-2017b.eb
easybuild/easyconfigs/g/gimpi/gimpi-2018a.eb
easybuild/easyconfigs/g/gimpi/gimpi-2018b.eb
easybuild/easyconfigs/g/gimpic/gimpic-2017b.eb
easybuild/easyconfigs/g/giolf/giolf-2017b.eb
easybuild/easyconfigs/g/giolf/giolf-2018a.eb
easybuild/easyconfigs/g/giolfc/giolfc-2017b.eb
easybuild/easyconfigs/g/gmpich/gmpich-2016a.eb
easybuild/easyconfigs/g/gmpich/gmpich-2017.08.eb
easybuild/easyconfigs/g/gmpolf/gmpolf-2016a.eb
easybuild/easyconfigs/g/gmpolf/gmpolf-2017.10.eb
easybuild/easyconfigs/g/golf/golf-2018a.eb
easybuild/easyconfigs/g/gomkl/gomkl-2018b.eb
easybuild/easyconfigs/g/gomkl/gomkl-2019a.eb
easybuild/easyconfigs/g/gompic/gompic-2017b.eb
easybuild/easyconfigs/g/gompic/gompic-2018a.eb
easybuild/easyconfigs/g/gompic/gompic-2018b.eb
easybuild/easyconfigs/g/gompic/gompic-2019a.eb

fix names of local variables in gimkl easyconfigs

---

easybuild/easyconfigs/m/MSM/MSM-1.0-foss-2017b.eb
easybuild/easyconfigs/m/MSM/MSM-1.0-intel-2017b.eb
easybuild/easyconfigs/m/MSM/MSM-1.0_Fix_abs_overload.patch

Requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1770~~

{bio}[foss/2017b,intel/2017b] MSM v1.0

---

easybuild/easyconfigs/d/DBG2OLC/DBG2OLC-20170208-intel-2016b.eb
easybuild/easyconfigs/d/DBG2OLC/DBG2OLC-20170208-intel-2017a.eb
easybuild/easyconfigs/d/DBG2OLC/DBG2OLC-20180221-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/d/DBG2OLC/DBG2OLC-20180221-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/d/DFTB+/DFTB+-17.1-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/d/DIAL/DIAL-2011.06.06-foss-2016a.eb
easybuild/easyconfigs/d/DL_POLY_Classic/DL_POLY_Classic-1.9-intel-2016b-PLUMED-2.2.3.eb
easybuild/easyconfigs/d/dropEst/dropEst-0.7.1-intel-2017b-R-3.4.3.eb
easybuild/easyconfigs/e/ED2/ED2-20170201-intel-2017a-serial.eb
easybuild/easyconfigs/e/ED2/ED2-20170201-intel-2017a.eb
easybuild/easyconfigs/e/ELPA/ELPA-2015.02.002-foss-2018a.eb
easybuild/easyconfigs/e/ELPA/ELPA-2015.02.002-gimkl-2017a.eb
easybuild/easyconfigs/e/ELPA/ELPA-2015.02.002-intel-2018a.eb
easybuild/easyconfigs/e/ELPA/ELPA-2016.05.004-intel-2017a.eb
easybuild/easyconfigs/e/ELPA/ELPA-2016.11.001.pre-foss-2018b.eb
easybuild/easyconfigs/e/ELPA/ELPA-2016.11.001.pre-intel-2018b.eb
easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-intel-2018a.eb
easybuild/easyconfigs/e/EMAN2/EMAN2-2.21a-foss-2018a-Python-2.7.14-Boost-1.63.0.eb
easybuild/easyconfigs/e/EMBOSS/EMBOSS-6.6.0-intel-2017a-X11-20170314.eb
easybuild/easyconfigs/e/EasyQC/EasyQC-9.2-intel-2016b-R-3.3.1.eb
easybuild/easyconfigs/e/EvidentialGene/EvidentialGene-2018.01.01-intel-2017a-Perl-5.24.1.eb

fix names of local variables in {d,e}/*/*.eb easyconfigs

---

easybuild/easyconfigs/q/QUAST/QUAST-4.6.0-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/q/QUAST/QUAST-4.6.3-foss-2018a-Python-3.6.4.eb
easybuild/easyconfigs/q/Qt/Qt-4.8.7-foss-2016a-GLib-2.48.0.eb
easybuild/easyconfigs/q/Qt/Qt-4.8.7-intel-2016a-GLib-2.48.0.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.3.0-intel-2016.02-GCC-4.9.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-intel-2016.02-GCC-4.9.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.0-intel-2016b.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1-intel-2017a.eb

fix names of local variables in q/*/*.eb easyconfigs

---

easybuild/easyconfigs/a/ATK/ATK-2.22.0-foss-2016b.eb
easybuild/easyconfigs/a/ATK/ATK-2.22.0-intel-2016b.eb
easybuild/easyconfigs/a/ATK/ATK-2.26.0-intel-2017a.eb
easybuild/easyconfigs/a/ATK/ATK-2.26.1-foss-2018b.eb
easybuild/easyconfigs/a/ATK/ATK-2.26.1-intel-2017b.eb
easybuild/easyconfigs/a/ATK/ATK-2.27.1-foss-2017b.eb
easybuild/easyconfigs/a/ATK/ATK-2.27.1-intel-2017b.eb
easybuild/easyconfigs/a/ATK/ATK-2.28.1-foss-2018a.eb
easybuild/easyconfigs/a/ATK/ATK-2.28.1-foss-2018b.eb
easybuild/easyconfigs/a/ATK/ATK-2.28.1-fosscuda-2018b.eb
easybuild/easyconfigs/a/ATK/ATK-2.28.1-intel-2018a.eb
easybuild/easyconfigs/a/ATK/ATK-2.32.0-GCCcore-8.2.0.eb

Also move GObject-Introspection to builddep where needed.

ATK fix missing dep for pkg config

---

easybuild/easyconfigs/f/FALCON/FALCON-1.8.8-intel-2017b.eb
easybuild/easyconfigs/f/FDS/FDS-6.5.2-intel-2016b.eb
easybuild/easyconfigs/f/FDS/FDS-6.5.3-intel-2017a.eb
easybuild/easyconfigs/f/FDS/FDS-6.6.0-intel-2017b.eb
easybuild/easyconfigs/f/FDS/FDS-6.6.0-intel-2018a.eb
easybuild/easyconfigs/f/FDS/FDS-6.7.0-intel-2018a.eb
easybuild/easyconfigs/f/FIAT/FIAT-2018.1.0-foss-2018a-Python-3.6.4.eb
easybuild/easyconfigs/f/FPM/FPM-1.3.3-Ruby-2.1.6.eb
easybuild/easyconfigs/f/FUNWAVE-TVD/FUNWAVE-TVD-3.1-20170525-intel-2017a-no-storm.eb
easybuild/easyconfigs/f/FUNWAVE-TVD/FUNWAVE-TVD-3.1-20170525-intel-2017a.eb
easybuild/easyconfigs/f/FastQC/FastQC-0.10.1-Java-1.7.0_80.eb
easybuild/easyconfigs/f/FastQC/FastQC-0.11.2-Java-1.7.0_60.eb
easybuild/easyconfigs/f/FastQC/FastQC-0.11.3-Java-1.7.0_80.eb
easybuild/easyconfigs/f/FastQC/FastQC-0.11.4-Java-1.8.0_66.eb
easybuild/easyconfigs/f/FastQC/FastQC-0.11.4-Java-1.8.0_74.eb
easybuild/easyconfigs/f/FlexiDot/FlexiDot-1.06-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/f/faceswap/faceswap-20180212-foss-2017b-Python-3.6.3.eb
easybuild/easyconfigs/f/fastqz/fastqz-1.5-GCC-4.8.2.eb
easybuild/easyconfigs/f/fdstools/fdstools-20160322-foss-2016a-Python-2.7.11.eb
easybuild/easyconfigs/f/find_circ/find_circ-1.2-20170228-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/f/fosscuda/fosscuda-2017b.eb
easybuild/easyconfigs/f/fosscuda/fosscuda-2018a.eb
easybuild/easyconfigs/f/fosscuda/fosscuda-2018b.eb
easybuild/easyconfigs/f/fosscuda/fosscuda-2019a.eb
easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-foss-2016a-Mesa-11.2.1.eb
easybuild/easyconfigs/f/freeglut/freeglut-3.0.0-intel-2016a-Mesa-11.2.1.eb
easybuild/easyconfigs/f/freetype/freetype-2.7.1-GCCcore-6.3.0-libpng-1.6.29.eb

fix names of local variables in f/*/*.eb easyconfigs

---

easybuild/easyconfigs/i/IGV/IGV-2.3.68-Java-1.7.0_80.eb
easybuild/easyconfigs/i/IGV/IGV-2.3.80-Java-1.7.0_80.eb
easybuild/easyconfigs/i/IGVTools/IGVTools-2.3.68-Java-1.7.0_80.eb
easybuild/easyconfigs/i/IGVTools/IGVTools-2.3.72-Java-1.7.0_80.eb
easybuild/easyconfigs/i/IMa2p/IMa2p-20151123-foss-2016a.eb
easybuild/easyconfigs/i/IMa2p/IMa2p-20160804-intel-2016b.eb
easybuild/easyconfigs/i/INTEGRATE-Neo/INTEGRATE-Neo-1.2.1-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/i/IOzone/IOzone-3.434-foss-2016a.eb
easybuild/easyconfigs/i/IPy/IPy-0.83.eb
easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-foss-2017b-R-3.4.3-Python-2.7.14.eb
easybuild/easyconfigs/i/IRkernel/IRkernel-0.8.15-intel-2017b-R-3.4.3-Python-2.7.14.eb
easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-30-GCCcore-6.4.0-Ghostscript-9.22-cairo-1.14.12.eb
easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-39-GCCcore-6.4.0-Ghostscript-9.23-cairo-1.14.12.eb
easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-8-intel-2017a-JasPer-1.900.1.eb
easybuild/easyconfigs/i/IntelPython/IntelPython-2.7.15-2019.2.066.eb
easybuild/easyconfigs/i/IntelPython/IntelPython-3.6.8-2019.2.066.eb
easybuild/easyconfigs/i/i-PI/i-PI-1.0-20160213-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/i/iCount/iCount-20180820-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/i/iccifortcuda/iccifortcuda-2016.10.eb
easybuild/easyconfigs/i/iccifortcuda/iccifortcuda-2019a.eb
easybuild/easyconfigs/i/iimpic/iimpic-2016.10.eb
easybuild/easyconfigs/i/iimpic/iimpic-2017b.eb
easybuild/easyconfigs/i/iimpic/iimpic-2019a.eb
easybuild/easyconfigs/i/imake/imake-1.0.7-intel-2016a.eb
easybuild/easyconfigs/i/intelcuda/intelcuda-2016.10.eb
easybuild/easyconfigs/i/intelcuda/intelcuda-2017b.eb
easybuild/easyconfigs/i/intelcuda/intelcuda-2019a.eb

fix names of local variables in i/*/*.eb easyconfigs

---

easybuild/easyconfigs/t/TVB-deps/TVB-deps-20160618-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-0.12.1-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.1-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.1-intel-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.1.0-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.1.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.2.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.2.1-foss-2016b-GPU-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.2.1-foss-2016b-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.3.0-intel-2017b-Python-3.6.3.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.6.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
easybuild/easyconfigs/t/Tk/Tk-8.6.4-intel-2016a-libX11-1.6.3.eb
easybuild/easyconfigs/t/Transrate/Transrate-1.0.3.eb
easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.32-Java-1.7.0_80.eb
easybuild/easyconfigs/t/Trimmomatic/Trimmomatic-0.36-Java-1.8.0_92.eb
easybuild/easyconfigs/t/tecplot360ex/tecplot360ex-linux64.eb
easybuild/easyconfigs/t/torchvision/torchvision-0.2.0-foss-2018a-Python-3.6.4-CUDA-9.1.85.eb
easybuild/easyconfigs/t/travis/travis-1.8.2-Ruby-2.3.1.eb
easybuild/easyconfigs/t/travis/travis-1.8.4-Ruby-2.3.3.eb
easybuild/easyconfigs/t/tvb-data/tvb-data-20150915-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/t/tvb-framework/tvb-framework-20150921-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/t/tvb-library/tvb-library-20150922-intel-2016a-Python-2.7.11.eb

fix names of local variables in t/*/*.eb easyconfigs

---

easybuild/easyconfigs/m/Miniconda2/Miniconda2-4.7.10.eb
easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.7.10.eb

Just adds easyconfigs for miniconda2 and miniconda3 version 4.7.10

{lang}[dummy/dummy] Miniconda2  v4.7.10, Miniconda3  v4.7.10

---

easybuild/easyconfigs/b/BamM/BamM-1.7.3-foss-2018a-Python-2.7.14.eb

{bio}[foss,2018a] BamM 1.7.3 w/ Python 2.7.14

---

easybuild/easyconfigs/v/VTune/VTune-2019_update5.eb

based on update3, only version and URL updated.

{tools}[dummy/dummy] VTune v2019_update5

---

easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-foss-2015b.eb
easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-foss-2016a.eb
easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-foss-2016b.eb
easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-iccifort-2017.4.196-GCC-6.4.0-2.28.eb
easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb
easybuild/easyconfigs/e/Exonerate/Exonerate-2.4.0-intel-2017a.eb

@vanzod as pointed out in #8437

add missing pkg-config build dep for Exonerate 2.4.0

---

easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.0-foss-2016b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.0-intel-2016b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.10-intel-2017a.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-foss-2017b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-foss-2018a.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-fosscuda-2018b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-intel-2017b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.11-intel-2018a.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.12-foss-2018b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.12-fosscuda-2018b.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.36.8-intel-2017a.eb
easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.38.1-GCCcore-8.2.0.eb

Also move GObject-Introspection to builddeps where appropriate.

Add missing builddep for pkg-config to Gdk-Pixbuf.

---

easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.26.3-fosscuda-2018b.eb
easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.32.0-GCCcore-8.2.0.eb
easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2017b.eb
easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-foss-2018a.eb
easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2017b.eb
easybuild/easyconfigs/g/GTK+/GTK+-2.24.32-intel-2018a.eb
easybuild/easyconfigs/l/libglade/libglade-2.6.4-foss-2018b.eb
easybuild/easyconfigs/l/libglade/libglade-2.6.4-intel-2016a.eb
easybuild/easyconfigs/l/libglade/libglade-2.6.4-intel-2017b.eb
easybuild/easyconfigs/p/PyCairo/PyCairo-1.16.1-foss-2017b-Python-3.6.3.eb
easybuild/easyconfigs/p/PyCairo/PyCairo-1.16.2-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/p/PyGObject/PyGObject-2.28.6-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/p/PyGObject/PyGObject-2.28.7-foss-2018b-Python-2.7.15.eb

at-spi2-atk, GTK+, libglade, and PyCairo

add missing pkg-config build dep for at-spi2-atk, GTK+, libglade, PyCairo, PyGObject

---

easybuild/easyconfigs/p/PyGTK/PyGTK-2.24.0-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/p/PyGTK/PyGTK-2.24.0-intel-2016a-Python-2.7.11.eb
easybuild/easyconfigs/p/PyGTK/PyGTK-2.24.0-intel-2017b-Python-2.7.14.eb

PyGTK: Add missing builddep for pkg-config

---

easybuild/easyconfigs/c/CUDA/CUDA-10.1.168.eb
easybuild/easyconfigs/c/CUDA/CUDA-10.1.243.eb
easybuild/easyconfigs/c/core-counter/core-counter-1.1.1.eb
easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.9.4.eb
easybuild/easyconfigs/i/ieeg-cli/ieeg-cli-1.14.56.eb
easybuild/easyconfigs/m/Miniconda2/Miniconda2-4.7.10.eb
easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.7.10.eb
easybuild/easyconfigs/p/PLINK/PLINK-2.00-alpha2-x86_64.eb
easybuild/easyconfigs/p/PLINK/PLINK-2.00-alpha2-x86_64_avx2.eb
easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.9-foss-2019a-R-3.6.0.eb
easybuild/easyconfigs/s/smallgenomeutilities/smallgenomeutilities-0.2.1-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/v/VTune/VTune-2019_update5.eb

also requires https://github.com/easybuilders/easybuild-framework/pull/2982 to make tests pass...

use SYSTEM toolchain + fix local var names to fix broken tests after collapse of 4.x branch into develop

---

easybuild/easyconfigs/p/PyQt5/PyQt5-5.11.3-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/p/PyQt5/PyQt5-5.12.1-GCCcore-8.2.0-Python-3.7.2.eb
test/easyconfigs/easyconfigs.py

fix incorrect escaping in SIP configure options in PyQt5 easyconfigs

---

easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.10.0-foss-2018b.eb
easybuild/easyconfigs/p/PnetCDF/PnetCDF-1.10.0-intel-2018b.eb

see easybuilders/easybuild-easyblocks/pull/1592

UPD: new version 1.10.0 of PnetCDF

---

easybuild/easyconfigs/l/LOHHLA/LOHHLA-2018.11.05-foss-2018b-R-3.5.1.eb
easybuild/easyconfigs/l/LOHHLA/LOHHLA-2018.11.05_add_shebang.patch

{bio}[foss/2018b] LOHHLA 2018.11.05 w/ R-3.5.1 (REVIEW)

---

easybuild/easyconfigs/b/byacc/byacc-20170709-GCCcore-6.4.0.eb

Link taken from here:
https://bugs.archlinux.org/task/55333
Build succeeded.

fix source_urls in byacc 20170709 easyconfig file

---

easybuild/easyconfigs/b/byacc/byacc-20160324-intel-2016a.eb
easybuild/easyconfigs/b/byacc/byacc-20160606-foss-2016b.eb
easybuild/easyconfigs/b/byacc/byacc-20160606-intel-2016b.eb

Sorry for making second pull request on that, I'm still learning github ;)

fix source_urls in (old) byacc easyconfigs

---

easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.06.eb
easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.06.eb
easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.06.eb
easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.06.eb
easybuild/easyconfigs/h/HPL/HPL-2.3-CrayCCE-19.06.eb
easybuild/easyconfigs/h/HPL/HPL-2.3-CrayGNU-19.06.eb
easybuild/easyconfigs/h/HPL/HPL-2.3-CrayIntel-19.06.eb
test/easyconfigs/easyconfigs.py

Add the following easyconfigs
- CrayCCE-19.06.eb
- CrayGNU-19.06.eb
- CrayIntel-19.06.eb
- CrayPGI-19.06.eb
- HPL-2.3-CrayCCE-19.06.eb
- HPL-2.3-CrayGNU-19.06.eb
- HPL-2.3-CrayIntel-19.06.eb

update CrayCCE, CrayGNU, CrayIntel and CrayPGI toolchains to 19.06

---

easybuild/easyconfigs/j/Java/Java-1.8.eb

update Java/1.8 wrapper to Java/1.8.0_221

---

easybuild/easyconfigs/c/Clang-Python-bindings/Clang-Python-bindings-8.0.0-GCCcore-8.2.0-Python-2.7.15.eb

Required by TRIQS-2.2.0 easyconfig

{lib}[GCCcore/8.2.0] Clang-Python-bindings 8.0.0 w/ Python 2.7.15

---

easybuild/easyconfigs/n/NFFT/NFFT-3.5.1-foss-2018b.eb
easybuild/easyconfigs/n/NFFT/NFFT-3.5.1-foss-2019a.eb

Dependency for TRIQS CTHYB solver.

{lib}[foss/2018b,foss,2019a] NFFT 3.5.1

---

easybuild/easyconfigs/m/Mesa/Mesa-19.0.1-GCCcore-8.2.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-19.1.7-GCCcore-8.3.0.eb

required for building `TurboVNC`

also install include/GL/internal/ for recent Mesa installations

---

easybuild/easyconfigs/m/MoviePy/MoviePy-1.0.1-foss-2019a-Python-3.7.2.eb

Not `multi-deps` as the Python 2 version requires a different versions of some libraries and extra ones compared to Python 3.

{tools}[foss/2019a] MoviePy 1.0.1 w/ Python 3.7.2

---

easybuild/easyconfigs/b/Bismark/Bismark-0.20.1-foss-2018b.eb

Same easyconfig as in #7811 with foss toolchain instead of intel.

{bio}[foss/2018b] Bismark v0.20.1

---

test/easyconfigs/easyconfigs.py

fixes #9180 reported by @paulmelis

ignore commented out lines in easyconfig files when checking for http:// URLs

---

easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.2.0.eb
easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.3.0.eb

Add Bazel 0.29.1 with GCC 8.2 and add Python 3 as build dependency for Bazel 0.29.1

---

easybuild/easyconfigs/a/Arriba/Arriba-1.1.0-foss-2018b.eb

fix for issue highlighted by @JackPerdue in #9226

add missing XZ dep in Arriba easyconfig

---

test/easyconfigs/easyconfigs.py

Tests failed in Travis CI in #9251 because of missing `versionsuffix`, but passed in GitHub's native CI because `test_changed_files_pull_request` was basically being skipped in GitHub Actions context...
This change should fix that.

fix checking of files changed by PR in GitHub Actions context

---

easybuild/easyconfigs/m/MaxQuant/MaxQuant-1.6.10.43-foss-2018b.eb

This PR uses https://github.com/easybuilders/easybuild-easyconfigs/pull/9102.
I could need some guidance on this one. Is `modaliases` the way to go here? ~Is a `sanity_check_commands` with `maxquantcmd --help` helpful?~ (I tried this but the alias doesn't seem to be known during the sanity check) Should `source_urls`  be removed because you need to register and get a link with some hash and an expiration date so a normal download will fail due to error 403?

{bio}[foss/2018b] MaxQuant v1.6.10.43

---

easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.2.0.eb
easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.3.0.eb

fixes #9295 reported by @JackPerdue

add Python 3 as build dep for Bazel 0.26.1

---

easybuild/easyconfigs/g/GCCcore/GCCcore-6.4.0.eb

fixes #9345 reported by @ANaumann85

add missing GCCcore-6.3.0_fix-sanitizer_linux.patch in GCCcore 6.4.0 easyconfig

---

easybuild/easyconfigs/s/SpliceMap/SpliceMap-3.3.5.2-GCC-7.3.0-2.30.eb

follow-up for @lexming's PR #9369 
cc @verdurin

clean up SpliceMap easyconfig: avoid hardcoding '3352' and sort binaries alphabetically

---

easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.12.1-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/m/MetaBAT/MetaBAT-2.12.1_fix-prepend-PATH.patch

fix linker errors when linking with libths.a for MetaBAT 2.12.1

---

easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-foss-2019a-Python-3.7.2.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-fosscuda-2019a-Python-3.7.2.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-intel-2019a-Python-3.7.2.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.3-intelcuda-2019a-Python-3.7.2.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.1.1-foss-2019b-Python-3.7.4.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.1.1-intel-2019b-Python-3.7.4.eb

add sanity check command for matplotlib 3.0.3 & 3.1+ with Python 3 to check import from mpl_toolkits

---

easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-fosscuda-2018b-Python-3.6.6.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-intel-2018b-Python-3.6.6.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-iomkl-2018b-Python-3.6.6.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.2-foss-2018b-Python-3.6.6.eb

(+ switch to using PythonBundle easyblock)
cfr. #9314

add sanity check command for matplotlib 3.0.0 + 3.0.2 with Python 3 to check import from mpl_toolkits

---

easybuild/easyconfigs/a/Anaconda2/Anaconda2-2019.10.eb
easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.10.eb

{lang}[system/system] Anaconda2 and Anaconda3 version 2019.10 

---

easybuild/easyconfigs/a/Armadillo/Armadillo-7.600.2-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/a/Armadillo/Armadillo-7.800.0-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/a/Armadillo/Armadillo-7.950.1-intel-2016b-Python-2.7.12.eb

add missing checksums for Armadillo

---

easybuild/easyconfigs/d/DCMTK/DCMTK-3.6.5-GCCcore-8.2.0.eb

Hey guys,
I updated DCMTK to 3.6.5, respecting some new library versions, and switched it to GCCcore 8.2.0.
Best,
crubb

{data}[GCCcore/8.2.0] DCMTK-3.6.5

---

easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb
easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb

fixes #9602, see also https://github.com/easybuilders/easybuild-easyconfigs/pull/9519#issuecomment-568768235

add additional valid checksum for MASS 7.3-51.4 extension in R 3.6.0 easyconfigs

---

easybuild/easyconfigs/o/ownCloud/ownCloud-2.5.4-GCCcore-8.2.0.eb

{tools}[GCCcore/8.2.0] ownCloud 2.5.4

---

test/easyconfigs/easyconfigs.py

Otherwise this would break a lot of ECs

Allow missing python versionsuffix for existing easyconfig files changed in PRs

---

easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.2.0.eb
easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.3.0.eb

@bogel - Clean version of #9643, sorry ;)

{lib}[GCCcore/8.2.0-8.3.0] ICU 64.2 - Depend on Python3 instead of 2

---

easybuild/easyconfigs/t/tcsh/tcsh-6.22.02-GCCcore-8.2.0.eb

{tools}[GCCcore/8.2.0] tcsh 6.22.02

---

easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-18.09-intel-2018b-Python-3.6.6.eb

Not sure why they changed, but maybe again some license update or so. I don't have an old version to double check, so if anyone can help there

add alternate checksum for OpenMolcas 18.09

---

easybuild/easyconfigs/m/MedPy/MedPy-0.4.0-foss-2019b-Python-3.7.4.eb

Depends on ~~#9747~~
... which provides:
- ITK-5.0.1-foss-2019b-Python-3.7.4.eb
- SimpleITK-1.2.4-foss-2019b-Python-3.7.4.eb

{bio}[foss/2019b] MedPy v0.4.0 w/ Python 3.7.4

---

easybuild/easyconfigs/t/tqdm/tqdm-4.41.1-GCCcore-8.3.0.eb

{lib}[GCCcore/8.3.0] tqdm v4.41.1 w/ Python 2.7.16 + 3.7.4

---

easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016a.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.1.0-intel-2016b.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-2.7.14.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-foss-2017b-Python-3.6.3.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017a-Python-3.6.1.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/o/OpenCV/OpenCV-3.3.0-intel-2017b-Python-3.6.3.eb

fix redefining of preconfigopts in OpenCV easyconfigs

---

easybuild/easyconfigs/c/Caffe/Caffe-1.0-intel-2017b-CUDA-9.1.85-Python-2.7.14.eb
easybuild/easyconfigs/g/Glade/Glade-3.8.6-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.4.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.1.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.2.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-7.3.0.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.1.0.eb
easybuild/easyconfigs/m/MariaDB/MariaDB-10.1.14-foss-2016a.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.0.0-intel-2018b-Python-3.6.6.eb
easybuild/easyconfigs/o/opencv_contrib/opencv_contrib-3.4.1-foss-2018a-Python-3.6.4.eb
easybuild/easyconfigs/p/picard/picard-2.6.0-Java-1.8.0_131.eb
test/easyconfigs/easyconfigs.py

triggered by ~~#9875~~
There are couple more instances of redefined easyconfig parameters we'll need to fix... 
requires ~~#9875~~, ~~#9895~~ (fixes in OpenCV easyconfigs)

check for redefined easyconfig parameters in easyconfig tests

---

easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166-GCC-9.2.0.eb
easybuild/easyconfigs/i/iimpi/iimpi-2020.00.eb
easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166-GCC-9.2.0.eb
easybuild/easyconfigs/i/intel/intel-2020.00.eb

(wrapper PR for #10082, cc @bartoldeman)

add -GCCcore-9.2.0 versionsuffix for intel/2020.00 components

---

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-GCCcore-8.3.0.eb
easybuild/easyconfigs/a/Automake/Automake-1.16.1-GCCcore-8.3.0.eb

needed for https://github.com/easybuilders/easybuild-easyconfigs/issues/8704

[GCCCore/8.3.0] add Perl as a build dependency for Autoconf/Automake

---

.github/workflows/unit_tests.yml

Fixes regression introduced in https://github.com/easybuilders/easybuild-easyconfigs/pull/10326/commits/1ad052ec99a97a563ee65257cad710df321bf122
@boegel

Check sdist with different python versions

---

easybuild/easyconfigs/z/zsh/zsh-5.8-GCC-8.3.0.eb
easybuild/easyconfigs/z/zsh/zsh-5.8-foss-2019b.eb

Upgrading zsh version and to a new version of foss toolchain.

{tools}[GCC/8.3.0] Create zsh-5.8-GCC-8.3.0.eb

---

easybuild/easyconfigs/a/Anaconda3/Anaconda3-2020.02.eb

upgrade to Anaconda3 version 2020.02

{lang}[system/system] Anaconda3 version 2020.02

---

easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/i/ICU/ICU-61.1-GCCcore-7.3.0.eb
easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.2.0.eb
easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.3.0.eb

fix source_urls in ICU easyconfigs

---

easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2018a-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018a-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018b-Python-2.7.15.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2018b-Python-3.6.6.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018.01-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018a-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018a-Python-3.6.4.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2018b-Python-2.7.15.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-iomkl-2018a-Python-2.7.14.eb

fix Mako easyconfigs using a */2018* toolchain

---

easybuild/easyconfigs/g/gmsh/gmsh-3.0.6-foss-2017b-Python-2.7.14.eb
easybuild/easyconfigs/g/gmsh/gmsh-3.0.6-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/g/gmsh/gmsh-4.2.2-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/g/gmsh/gmsh-4.5.6-foss-2019b-Python-3.7.4.eb

config for gmsh 4.5.6 in foss 2019b and Python 3.7.4

{math}[foss/2019b] gmsh v4.5.6 w/ Python 3.7.4

---

easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-foss-2018b-Python-2.7.15.eb
easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-foss-2018b.eb
easybuild/easyconfigs/g/Graphviz/Graphviz-2.40.1-intel-2018a.eb
easybuild/easyconfigs/g/Graphviz/Graphviz-2.42.2-foss-2019b-Python-3.7.4.eb
easybuild/easyconfigs/g/Graphviz/Graphviz-2.42.2-foss-2019b.eb

fix for:
```
yacc: Command not found
```

add missing Bison build dep in Graphviz easyconfigs

---

easybuild/easyconfigs/m/Mako/Mako-1.0.4-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.4-intel-2016b-Python-2.7.12.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.6-foss-2017a-Python-2.7.13.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.6-intel-2017a-Python-2.7.13.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-foss-2017b-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-fosscuda-2017b-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-intel-2017b-Python-2.7.14.eb
easybuild/easyconfigs/m/Mako/Mako-1.0.7-intelcuda-2017b-Python-2.7.14.eb
test/easyconfigs/easyconfigs.py

fix Mako easyconfigs using a 2016 & 2017 toolchain

---

easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-iimpi-2020a.eb

Fix missing M4

---

easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-GCCcore-8.2.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016a-Mesa-11.2.1.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2016b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2017a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2017b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2018a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-foss-2018b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-fosscuda-2017b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-fosscuda-2018a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-fosscuda-2018b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-gimkl-2.11.5.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2016a-Mesa-11.2.1.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2016a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2016b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2017a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2017b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2018a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intel-2018b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-intelcuda-2017b.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.0-iomkl-2018a.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-8.3.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-9.3.0.eb

libGLU now has a https source available. The FTP source failed for me so
updating the easyconfigs to use https source instead of ftp.
closes gh-10624

update: libGLU source URL: use https

---

easybuild/easyconfigs/j/JUBE/JUBE-2.4.0.eb

New release for JUBE. Release notes here: https://apps.fz-juelich.de/jsc/jube/jube2/docu/release_notes.html

{tools}[SYSTEM] JUBE v2.4.0

---

easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.50-gompi-2020a.eb
easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.50_mbrola_location.patch
easybuild/easyconfigs/e/eSpeak-NG/eSpeak-NG-1.50_sonic_fftw.patch
easybuild/easyconfigs/f/festival/festival-2.5.0-GCCcore-9.3.0.eb
easybuild/easyconfigs/f/festival/festival-2.5.0_speech_tools.patch
easybuild/easyconfigs/m/MBROLA/MBROLA-3.3-GCCcore-9.3.0-voices-20200330.eb
easybuild/easyconfigs/m/MBROLA/MBROLA-3.3_makefile.patch
easybuild/easyconfigs/p/phonemizer/phonemizer-2.2.1-gompi-2020a-Python-3.8.2.eb
easybuild/easyconfigs/s/sonic/sonic-20180202-gompi-2020a.eb
easybuild/easyconfigs/s/sonic/sonic-20180202.patch
easybuild/easyconfigs/s/speech_tools/speech_tools-2.5.0-GCCcore-9.3.0.eb
easybuild/easyconfigs/s/speech_tools/speech_tools-2.5.0_easybuild.patch

Python 2 support dropped in earlier version.

{tools}[gompi/2020a] phonemizer 2.2.1 w/ Python-3.8.2 + deps

---

easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-GCCcore-7.3.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-8.2.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-8.3.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-GCCcore-9.3.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.3.1_fix_ppc64_fpreg_t.patch

Fixes an issue when throwing exceptions with libunwind loaded

Add patch to libunwind fixing a failure on POWER

---

easybuild/easyconfigs/h/Horovod/Horovod-0.20.3-fosscuda-2019b-TensorFlow-2.3.1-Python-3.7.4.eb

Follow-up to https://github.com/easybuilders/easybuild-easyconfigs/pull/11375 using an updated horovod as the 0.20.0 had usability issues (some parts were unusable)

in-place update of easyconfig Horovod v0.20.0 to v0.20.3

---

easybuild/easyconfigs/w/worker/worker-1.6.11-intel-2019b.eb

Anyway, using system toolchain and Perl as osdep have no real benefits.

fix worker-1.6.11-intel-2019b installation on RHEL 8.2

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-foss-2019b.eb

This is my first Easybuild config -- in learning process

foss 2019b Quantum Espresso 6.6

---

easybuild/easyconfigs/p/pyFAI/pyFAI-0.19.0-foss-2019b-Python-3.7.4.eb
easybuild/easyconfigs/p/pyFAI/pyFAI-0.19.0-fosscuda-2019b-Python-3.7.4.eb

Adding a new module pyFAI: Python implementation of fast azimuthal integration, https://pyfai.readthedocs.io.

{data}[foss/2019b,fosscuda/2019b] pyFAI 0.19.0 w/ Python 3.7.4

---

easybuild/easyconfigs/p/pymca/pymca-5.6.3-foss-2019b-Python-3.7.4.eb
easybuild/easyconfigs/p/pymca/pymca-5.6.3-fosscuda-2019b-Python-3.7.4.eb

Adding a new module for PyMca X-Ray Fluorescence Toolkit, http://pymca.sourceforge.net/.

{data}[foss/2019b,fosscuda/2019b] pymca 5.6.3 w/ Python 3.7.4

---

easybuild/easyconfigs/b/Biopython/Biopython-1.78-foss-2020a-Python-3.8.2.eb
easybuild/easyconfigs/n/NanopolishComp/NanopolishComp-0.6.11-foss-2020a-Python-3.8.2.eb
easybuild/easyconfigs/n/nanopolish/nanopolish-0.13.2-foss-2020a-Python-3.8.2.eb

… nanopolish-0.13.2-foss-2020a-Python-3.8.2.eb, Biopython-1.78-foss-2020a-Python-3.8.2.eb

{bio}[foss/2020a] NanopolishComp v0.6.11, nanopolish v0.13.2 w/ Python 3.8.2

---

easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-foss-2018b.eb
easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-intel-2018b.eb
easybuild/easyconfigs/c/CESM-deps/CESM-deps-2-iomkl-2018b.eb
easybuild/easyconfigs/g/GitPython/GitPython-2.1.11-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/g/GitPython/GitPython-2.1.11-intel-2018b-Python-3.6.6.eb
easybuild/easyconfigs/g/GitPython/GitPython-3.0.3-GCCcore-8.2.0-Python-3.7.2.eb
easybuild/easyconfigs/g/GitPython/GitPython-3.1.0-GCCcore-8.3.0-Python-3.7.4.eb
easybuild/easyconfigs/g/GitPython/GitPython-3.1.9-GCCcore-9.3.0-Python-3.8.2.eb

{tools} Added git as a dependency to GitPython version 3.x

---

easybuild/easyconfigs/a/Anaconda3/Anaconda3-2020.11.eb

Version push to latest version 2020.11.  Also supporting PowerPC.

{lang}[system/system] Anaconda3 v2020.11

---

test/easyconfigs/easyconfigs.py

The list comprehension in get_deps_for was called about 357k times and iterates over all ~20k(?) ECs to find one by name.
This makes the test VERY long.
The new approach uses a dict and dynamic programming to memorize found dependency mappings making the test VERY fast.
For comparison check the runtime in any other PR: Runtime went from 16-28min down to 6-9min.

Speedup test_dep_versions_per_toolchain_generation

---

easybuild/easyconfigs/r/ReFrame/ReFrame-3.4.1.eb
easybuild/easyconfigs/r/ReFrame/ReFrame-3.4.eb

Fixes https://github.com/eth-cscs/reframe/issues/1749

{devel}[system] ReFrame v3.4.1

---

test/easyconfigs/easyconfigs.py

To avoid issues like #12216 going unnoticed...
~~WIP, needs some more work to cover special cases.~~
requires ~~#12216~~ + ~~#12223~~

verify checksum of all patch files in easyconfigs test suite

---

easybuild/easyconfigs/g/goblf/goblf-2020b.eb
easybuild/easyconfigs/l/LAPACK/LAPACK-3.9.1-GCC-10.2.0.eb
easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020b-bl.eb

This was merged very recently in `develop` (see #12381), not included yet with an EasyBuild release...

update to LAPACK 3.9.1 for goblf/2020b

---

easybuild/easyconfigs/m/mongolite/mongolite-2.3.0-foss-2020a-R-4.0.0.eb
easybuild/easyconfigs/m/mongolite/mongolite-2.3.0-foss-2020b-R-4.0.3.eb
easybuild/easyconfigs/m/mongolite/mongolite-2.3.0-foss-2020b-R-4.0.4.eb

Not sure about the security disadvantages to use a non-systems sasl2, but I got  a super-quick super-important request.

{tools}[foss/2020{a,b}] mongolite w/ R-4.0.{0,3,4}

---

easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.4.0-foss-2020b.eb

Per https://github.com/easybuilders/easybuild-easyconfigs/issues/12660

Add Python dependency to AUGUSTUS-3.4.0-foss-2020b.eb

---

test/easyconfigs/easyconfigs.py

cfr. changes in https://github.com/easybuilders/easybuild-framework/pull/3668

use EasyConfig.disable_templating method in test suite

---

easybuild/easyconfigs/s/scikit-build/scikit-build-0.11.1-intel-2020b.eb
easybuild/easyconfigs/s/scikit-build/scikit-build-0.11.1-intelcuda-2020b.eb

Adding scikit-build for intel-2020b and intelcuda-2020b toolchains.

{lib}[intel/2020b,intelcuda/2020b] scikit-build v0.11.1 w/ Python 3.8.6

---

easybuild/easyconfigs/x/Xerces-C++/Xerces-C++-3.2.3-GCCcore-10.2.0.eb

Update needed for use with Geant4 same toolchain. Very straightforward.

{lib}[GCCcore/10.2.0] Xerces-C++ 3.2.3

---

easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb

Corrected checksum for extension mvabund 4.1.9.

{lang}[foss/2020b] add new cheksum of mvabund to R v4.0.4

---

easybuild/easyconfigs/g/gappa/gappa-0.7.1-GCC-10.3.0.eb

{bio}[GCC/10.3.0] gappa v0.7.1

---

easybuild/easyconfigs/a/ASE/ASE-3.21.1-foss-2020a-Python-3.8.2.eb
easybuild/easyconfigs/s/spglib-python/spglib-python-1.16.0-foss-2020a-Python-3.8.2.eb

add ASE-3.21.1-foss-2020a-Python-3.8.2.eb and its dependency spglib-python-1.16.0-foss-2020a-Python-3.8.2.eb

{chem}[foss/2020a] ASE v3.21.1, spglib-python v1.16.0 w/ Python 3.8.2

---

easybuild/easyconfigs/m/MATLAB/README.md

I restructured the whole thing as i found it difficult to write properly in the bullet list. Also dropped the Java stuff, which we haven't used in long time now.

update README with instructions for MATLAB easyconfigs

---

easybuild/easyconfigs/t/TWL-NINJA/TWL-NINJA-0.97-cluster_only-GCC-10.2.0.eb

Rename NINJA to TWL-NINJA to avoid nameclash

---

easybuild/easyconfigs/a/almosthere/almosthere-2.0.2-GCCcore-10.2.0.eb

Update to new major release and new GCC

{vis}[GCCcore/10.2.0] almosthere v2.0.2

---

easybuild/easyconfigs/b/bgen/bgen-4.1.3-GCCcore-10.2.0.eb

New major version, new toolchain, new sanity checks.
Edit: depends on #13545

{bio}[GCCcore/10.2.0] bgen v4.1.3

---

easybuild/easyconfigs/c/CharLS/CharLS-2.2.0-GCCcore-10.2.0.eb

New minor version, new GCCcore

{lib}[GCC/10.3.0] CharLS v2.2.0

---

easybuild/easyconfigs/f/FreeImage/FreeImage-3.18.0-GCCcore-10.2.0.eb

Update to GCCcore 10.2.0 and binutils 2.35

{vis}[GCCcore/10.2.0] FreeImage v3.18.0

---

easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.2.0.eb

{devel}[GCCcore/10.2.0] gflags v2.2.2

---

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-foss-2018b-Python-3.6.6.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-foss-2019a-Python-3.7.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-fosscuda-2019a-Python-3.7.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_cloud_impotred_w_nogcp.patch
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_icu_sha_changed.patch

add patches for TensorFlow 1.13.1 to fix installation

---

easybuild/easyconfigs/m/MEGA/MEGA-10.0.5.eb

{bio}[SYSTEM] MEGA v10.0.5

---

easybuild/easyconfigs/c/cppy/cppy-1.1.0-GCCcore-10.3.0.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-3.4.2-foss-2021a.eb

pip will ordinarially fetch this automatically during install but not all build systems have internet access.
closes #13809

Added missing depency for matplotlib.

---

easybuild/easyconfigs/r/Racon/Racon-1.4.7-gcccuda-2019b.eb

https://github.com/clara-genomics/ClaraGenomicsAnalysis Repo was renamed to https://github.com/clara-parabricks/GenomeWorks making checksum and source move fail
Move to same approach as pytorch

Fix Racon-1.4.7-gcccuda-2019b.eb

---

easybuild/easyconfigs/s/STACEY/STACEY-1.2.5-GCC-10.2.0.eb

{data}[GCC/10.2.0] STACEY v1.2.5

---

easybuild/easyconfigs/b/Blosc/Blosc-1.21.1-GCCcore-11.2.0.eb
easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-foss-2021b.eb
easybuild/easyconfigs/t/tqdm/tqdm-4.62.3-GCCcore-11.2.0.eb

adding easyconfigs: Blosc-1.21.1-GCCcore-11.2.0.eb, PyTables-3.6.1-foss-2021b.eb, tqdm-4.62.3-GCCcore-11.2.0.eb

{data,lib}[foss/2021b] PyTables v3.6.1 + tqdm v4.62.3 w/ Python 3.9.6 + Blosc v1.21.1

---

easybuild/easyconfigs/j/Julia/Julia-1.6.5-linux-x86_64.eb

{lang}[system/system] Julia v1.6.5

---

easybuild/easyconfigs/j/Julia/Julia-1.7.1-linux-x86_64.eb

{lang}[system/system] Julia v1.7.1

---

easybuild/easyconfigs/g/gengetopt/gengetopt-2.23-GCCcore-10.3.0.eb
easybuild/easyconfigs/o/openCARP/openCARP-8.2-foss-2021a.eb
easybuild/easyconfigs/o/openCARP/openCARP-8.2_build-info.patch

The openCARP build system has changed a bit since the latest easyconfig (openCARP-6.0-foss-2020b.eb), so that's why also a new patch file is included.
It's my first attempt at contributing to EB, so definitely tell me in case I missed to follow any conventions.

{bio,tools}[foss/2021a] openCARP v8.2, gengetopt v2.23

---

easybuild/easyconfigs/j/Java/Java-17.0.2.eb
easybuild/easyconfigs/j/Java/Java-17.eb

Java updated to 17.0.2 due to RHSA-2022:0166 CVEs

{compiler}[system/system] Java 17.0.2

---

easybuild/easyconfigs/l/librsb/librsb-1.2.0.10-GCC-10.2.0.eb
easybuild/easyconfigs/l/librsb/librsb-1.2.0.11-GCC-10.2.0.eb
easybuild/easyconfigs/l/librsb/librsb-1.3.0.0-GCC-10.2.0.eb

Fix #14860 by updated librsb-1.2.0.10/librsb-1.2.0.11/1.3.0.0 files.

{lib}[GCC/10.2.0] librsb v1.2.0.10, v1.2.0.11, v1.3.0.0

---

easybuild/easyconfigs/p/Pysam/Pysam-0.18.0-GCC-11.2.0.eb

{bio}[GCC/11.2.0] Pysam v0.18.0 w/ Python 3.9.6

---

easybuild/easyconfigs/j/Julia/Julia-1.7.2-linux-x86_64.eb

{lang}[system/system] Julia v1.7.2

---

easybuild/easyconfigs/d/Devito/Devito-4.6.1-foss-2020a-Python-3.8.2.eb

update description for Devito

---

test/easyconfigs/easyconfigs.py

add check to verify that patch files touched in PRs have a description in place

---

easybuild/easyconfigs/b/bokeh/bokeh-2.2.3-intelcuda-2020b.eb
easybuild/easyconfigs/d/dask/dask-2021.2.0-intelcuda-2020b.eb
easybuild/easyconfigs/n/networkx/networkx-2.5-intelcuda-2020b.eb
easybuild/easyconfigs/p/PyWavelets/PyWavelets-1.1.1-intelcuda-2020b.eb
easybuild/easyconfigs/s/scikit-image/imread-0.7.4_shlibs_order.patch
easybuild/easyconfigs/s/scikit-image/scikit-image-0.18.1-intelcuda-2020b.eb

Adding scikit-image for intelcuda-2020b and few related dependencies.

{vis}[intelcuda/2020b] scikit-image v0.18.1 w/ Python 3.8.6

---

easybuild/easyconfigs/j/Julia/Julia-1.6.6-linux-x86_64.eb

Title says it all. I checked that it works on our cluster.

Add easyconfig for Julia 1.6.6

---

easybuild/easyconfigs/f/freebayes/freebayes-1.3.6-foss-2021b-R-4.1.2.eb
easybuild/easyconfigs/f/freebayes/freebayes-1.3.6_find-external-libs.patch
easybuild/easyconfigs/f/freebayes/freebayes-1.3.6_install-libs-headers.patch

{bio}[foss/2021b] freebayes v1.3.6 w/ Python 3.9.6

---

easybuild/easyconfigs/p/Python/Python-3.10.4-GCCcore-11.3.0-bare.eb

{lang}[GCCcore/11.3.0] Python v3.10.4 (bare)

---

easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2021-21-17-GCC-11.2.0.eb

added GMAP-GSNAP-2021-21-17-GCC-11.2.0.eb

{bio}[GCC/11.2.0] GMAP-GSNAP-2021-21-17

---

easybuild/easyconfigs/n/ntCard/ntCard-1.2.1-GCC-11.2.0.eb

added ntCard-1.2.1-GCC-11.2.0.eb

{bio}[GCC/11.2.0] ntCard-1.2.1

---

easybuild/easyconfigs/r/RNA-Bloom/RNA-Bloom-1.4.3-GCC-11.2.0.eb

added RNA-Bloom-1.4.3-GCC-11.2.0.eb

{bio}[GCC/11.2.0] RNA-Bloom-1.4.3

---

easybuild/easyconfigs/l/librsb/librsb-1.3.0.1-GCC-10.2.0.eb

adding file for librsb-1.3.0.1

{lib}[GCC/10.2.0] librsb v1.3.0.1

---

easybuild/easyconfigs/r/rnaQUAST/rnaQUAST-2.2.2-foss-2021a-Python-3.9.6.eb
easybuild/easyconfigs/r/rnaQUAST/rnaQUAST-2.2.2-foss-2021b.eb

added rnaQUAST-2.2.2-foss-2021a-Python-3.9.6.eb
requires:

{bio}[foss/2021a] rnaQUAST v2.2.2 w/ Python 3.9.6

---

easybuild/easyconfigs/l/libdrm/libdrm-2.4.110-GCCcore-11.3.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.4.0-GCCcore-11.3.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.6.2-GCCcore-11.3.0.eb
easybuild/easyconfigs/m/Mako/Mako-1.2.0-GCCcore-11.3.0.eb

{lib}[GCCcore/11.3.0] libdrm v2.4.110, libglvnd v1.4.0, libunwind v1.6.2, ... w/ Python 3.10.4

---

easybuild/easyconfigs/l/LLVM/LLVM-14.0.3-GCCcore-11.3.0.eb

{compiler}[GCCcore/11.3.0] LLVM v14.0.3

---

easybuild/easyconfigs/f/freeglut/freeglut-3.2.2-GCCcore-11.3.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.3.0.eb

{lib,vis}[GCCcore/11.3.0] freeglut v3.2.2, libGLU v9.0.2

---

easybuild/easyconfigs/i/iimpi/iimpi-2022.05.eb
easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2022.1.0-iimpi-2022.05.eb
easybuild/easyconfigs/i/intel/intel-2022.05.eb

{numlib,toolchain}[iimpi/2022.05,system/system] iimpi v2022.05, imkl-FFTW v2022.1.0, intel v2022.05

---

easybuild/easyconfigs/g/GSL/GSL-2.7-GCC-11.3.0.eb
easybuild/easyconfigs/g/GST-plugins-bad/GST-plugins-bad-1.19.2-GCC-11.3.0.eb
easybuild/easyconfigs/g/GST-plugins-bad/GST-plugins-bad-1.20.2-GCC-11.3.0.eb
easybuild/easyconfigs/g/GST-plugins-base/GST-plugins-base-1.20.2-GCC-11.3.0.eb
easybuild/easyconfigs/g/GStreamer/GStreamer-1.20.2-GCC-11.3.0.eb
easybuild/easyconfigs/g/Graphene/Graphene-1.10.8-GCCcore-11.3.0.eb
easybuild/easyconfigs/p/PyCairo/PyCairo-1.21.0-GCCcore-11.3.0.eb
easybuild/easyconfigs/p/PyGObject/PyGObject-3.42.1-GCCcore-11.3.0.eb
easybuild/easyconfigs/w/Wayland/Wayland-1.20.0-GCCcore-11.3.0.eb

{vis}[GCC/11.3.0,GCCcore/11.3.0] GSL v2.7, Wayland v1.20.0, PyCairo v1.21.0, ... w/ Python 3.10.4

---

easybuild/easyconfigs/s/Salmon/Salmon-1.4.0-GCC-11.2.0.eb

added Salmon-1.4.0-GCC-11.2.0.eb

{bio}[GCC/11.2.0] Salmon-1.4.0

---

easybuild/easyconfigs/a/Anaconda3/Anaconda3-2022.05.eb

Easyconfig for the latest Anaconda3 distribution

{lang}[system/system] Anaconda3 v2022.05

---

easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-intel-2022.05.eb
easybuild/easyconfigs/s/SciPy-bundle/deap-1.3.1_no_2to3.patch
easybuild/easyconfigs/s/SciPy-bundle/numpy-1.22.3_disable-broken-override-test.patch

{lang}[intel/2022.05] SciPy-bundle v2022.05 w/ Python 3.10.4

---

easybuild/easyconfigs/b/Bazel/Bazel-5.1.1-GCCcore-11.3.0.eb
easybuild/easyconfigs/z/Zip/Zip-3.0-GCCcore-11.3.0.eb

Tried using `Java 17` (latest LTS), but `Bazel` crashes during the build. Settled for `Java 13`, but happy to drop to `11` if preferred

{devel,tools}[GCCcore/11.3.0] Bazel v5.1.1, Zip v3.0

---

easybuild/easyconfigs/j/Julia/Julia-1.7.3-linux-x86_64.eb

{lang}[system/system] Julia v1.7.3

---

easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.1.0.eb
easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.2.0.eb
easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-10.3.0.eb
easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-11.2.0.eb
easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-11.3.0.eb
easybuild/easyconfigs/x/XZ/XZ-5.2.5-GCCcore-9.3.0.eb
easybuild/easyconfigs/x/XZ/XZ-5.2.5_compat-libs.patch
easybuild/easyconfigs/x/XZ/xz-5.2.5-cve-2022-1271.patch

add CVE patch for XZ 5.2.5 + attempt to fix symbol patch for all OSs

---

easybuild/easyconfigs/i/intervaltree-python/intervaltree-python-3.1.0-GCCcore-11.2.0.eb
easybuild/easyconfigs/m/medaka/medaka-1.6.0-foss-2021b.eb
test/easyconfigs/easyconfigs.py

{bio}[GCCcore/11.2.0,foss/2021b] medaka v1.6.0, intervaltree-python v3.1.0 w/ Python 3.9.6

---

easybuild/easyconfigs/d/dbus-glib/dbus-glib-0.112-GCCcore-10.3.0.eb
easybuild/easyconfigs/g/GConf/GConf-3.2.6-GCCcore-10.3.0.eb
easybuild/easyconfigs/l/LibSoup/LibSoup-2.74.0-GCCcore-10.3.0.eb
easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.27.4-GCC-10.3.0.eb
easybuild/easyconfigs/w/WebKitGTK+/WebKitGTK+-2.27.4_icuBOOL.patch
easybuild/easyconfigs/w/wxPython/wxPython-4.1.1-foss-2021a.eb
easybuild/easyconfigs/w/wxPython/wxPython-4.1.1_fix_install_path.patch
easybuild/easyconfigs/w/wxPython/wxPython-4.1.1_use_bang_env_python.patch

{devel,lib}[GCCcore/10.3.0] wxPython v4.1.1, WebKitGTK+ v2.27.4, GConf v3.2.6, ... w/ Python 3.9.5

---

easybuild/easyconfigs/d/DB/DB-18.1.40-GCCcore-12.1.0.eb
easybuild/easyconfigs/e/expat/expat-2.4.8-GCCcore-12.1.0.eb
easybuild/easyconfigs/g/groff/groff-1.22.4-GCCcore-12.1.0.eb
easybuild/easyconfigs/l/libreadline/libreadline-8.1.2-GCCcore-12.1.0.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.3-GCCcore-12.1.0.eb
easybuild/easyconfigs/p/Perl/Perl-5.36.0-GCCcore-12.1.0.eb

New Version of Perl is implemented with a GCC version of 12.1.0

{lang}[GCCcore/12.1.0] Perl v5.36.0

---

easybuild/easyconfigs/d/Dakota/Dakota-6.16.0-foss-2021b.eb

adding sanity check command to easyconfig

add sanity check commands for Dakota v6.16.0

---

easybuild/easyconfigs/p/python-irodsclient/python-irodsclient-1.1.4-GCCcore-10.3.0.eb

add new python-irodsclient easyconfig

---

easybuild/easyconfigs/j/Julia/Julia-1.8.2-linux-x86_64.eb

{lang}[system/system] Julia v1.8.2

---

easybuild/easyconfigs/j/Julia/Julia-1.6.7-linux-x86_64.eb

Update Julia LTS to latest release

{lang}[system/system] Julia v1.6.7

---

easybuild/easyconfigs/l/libconfig/libconfig-1.7.3-GCCcore-11.2.0.eb

new easyconfig for old library..

{lib}[GCCcore/11.2.0] libconfig v1.7.3

---

easybuild/easyconfigs/s/SimPEG/SimPEG-0.14.1-intel-2020a-Python-3.8.2.eb

Noticed this while looking at #16837 and #16836

geo moduleclass for SimPEG

---

easybuild/easyconfigs/n/ngtcp2/ngtcp2-0.7.0-GCC-11.3.0.eb

{lib}[GCC/11.3.0] nghttp2 v0.7.0

---

RELEASE_NOTES
setup.py

prepare release notes for EasyBuild v4.7.0 + bump version to 4.7.0

---

easybuild/easyconfigs/j/Julia/Julia-1.8.5-linux-x86_64.eb

{lang}[system/system] Julia v1.8.5

---

easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-12.2.0.eb
easybuild/easyconfigs/l/libtirpc/libtirpc-1.3.3-GCCcore-12.2.0.eb

{data,lib}[GCCcore/12.2.0] HDF v4.2.15, libtirpc v1.3.3

---

easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0.1-GCCcore-11.3.0.eb

with `SDL2`, FFmpeg will also install `ffplay`, which allows the playing of videos.

add SDL2 dependency for FFmpeg 5.0.1 to build ffplay

---

easybuild/easyconfigs/d/DIRAC/DIRAC-22.0-intel-2021a-int64.eb

DIRAC code using a 64-bit integer compilation.

{chem}[intel/2021a] DIRAC 22.0 64bits

---

easybuild/easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-11.2.0.eb

added Jellyfish-2.3.0-GCC-11.2.0.eb

{bio}[GCC/11.2.0] Jellyfish-2.3.0

---

easybuild/easyconfigs/c/Check/Check-0.12.0-GCCcore-6.4.0.eb
easybuild/easyconfigs/l/libmo_unpack/libmo_unpack-3.1.2-GCCcore-6.4.0.eb

for https://github.com/easybuilders/easybuild-easyconfigs/issues/11824

consistently use Check capitailisation

---

easybuild/easyconfigs/g/GARLI/GARLI-2.01-gompi-2019a.eb
easybuild/easyconfigs/n/NEXUS-CL/NEXUS-CL-2.1.18-GCC-8.2.0-2.31.1.eb

for https://github.com/easybuilders/easybuild-easyconfigs/issues/11824

rename ncl to NEXUS-CL to avoid case-insensitive name clash

---

easybuild/easyconfigs/e/ESL-Bundle/ESL-Bundle-0.6.1-foss-2020b.eb
easybuild/easyconfigs/e/ESL-Bundle/ESL-Bundle-0.6.1-intel-2020b.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.10-GCC-10.2.0.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.10-GCC-10.3.0.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.10-GCC-11.2.0.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.10-iccifort-2020.4.304.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.10-intel-compilers-2021.2.0.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.10-intel-compilers-2021.4.0.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.7-foss-2016b.eb
easybuild/easyconfigs/l/libPSML/libPSML-1.1.7-foss-2017a.eb

for https://github.com/easybuilders/easybuild-easyconfigs/issues/11824

rename libpsml for consistency with libPSML

---

easybuild/easyconfigs/a/Armadillo/Armadillo-11.4.3-foss-2022b.eb
easybuild/easyconfigs/a/arpack-ng/arpack-ng-3.8.0-foss-2022b.eb

{numlib}[foss/2022b] Armadillo v11.4.3, arpack-ng v3.8.0

---

easybuild/easyconfigs/i/irodsfs/irodsfs-0.8.11-linux-amd64.eb
easybuild/easyconfigs/i/irodsfs/irodsfs-0.8.12-linux-amd64.eb
easybuild/easyconfigs/i/irodsfs/irodsfs-0.8.9-linux-amd64.eb

I am just adding easyconfig files for irodsfs (https://github.com/cyverse/irodsfs/)

{tools}[system] irodsfs v0.8.9, v0.8.11, v0.8.12

---

easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-iomkl-2021a.eb
easybuild/easyconfigs/h/HDF5/HDF5-1.10.7-iompi-2021a.eb
easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-21.06-iomkl-2021a.eb

It seems that some functions in `CASPT2` module is not compatible with Intel MPI. It pops up in case of `SO-CASSI` simulations.

{chem}[iomkl/2021a] OpenMolcas v21.06

---

easybuild/easyconfigs/b/barrnap/barrnap-0.9-gompi-2022a.eb

New toolchain, new dependencies

{bio}[gompi/2022a] barrnap v0.9

---

easybuild/easyconfigs/d/deepTools/deepTools-3.5.2-foss-2022a.eb

New version, new toolchain, new dependencies

{bio}[foss/2022a] deepTools v3.5.2

---

easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-intel-2022b.eb

{math}[intel/2022b] ELPA v2021.11.001

---

easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.0-GCCcore-6.4.0.eb
easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.1-GCCcore-7.3.0.eb
easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.2-GCCcore-8.2.0.eb
easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.2-GCCcore-8.3.0.eb
easybuild/easyconfigs/l/libsigc++/libsigc++-2.10.8-GCCcore-10.3.0.eb

disable building documentation for libsigc++ 2.10.x

---

easybuild/easyconfigs/b/Bazel/Bazel-6.3.1-GCCcore-12.3.0.eb
easybuild/easyconfigs/j/Java/Java-11.0.20.eb
easybuild/easyconfigs/j/Java/Java-11.eb

{devel}[GCCcore/12.3.0, system] Bazel v6.3.1, Java v11.0.20, Java v11

---

easybuild/easyconfigs/r/rclone/rclone-1.63.1-amd64.eb

Latest version of rclone (v1.63.1)

{tools}[SYSTEM] rclone-1.63.1-amd64.eb

---

easybuild/easyconfigs/c/Clang/Clang-16.0.4-GCCcore-12.2.0.eb
easybuild/easyconfigs/z/Z3/Z3-4.12.2-GCCcore-12.2.0.eb

requires:
* https://github.com/easybuilders/easybuild-easyblocks/pull/2929
otherwise the sanity check will fail

{compiler}[GCCcore/12.2.0] Clang v16.0.4, Z3 v4.12.2

---

easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2022a-CUDA-11.8.0.eb
easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2022a.eb
easybuild/easyconfigs/p/Pint/Pint-0.22-GCCcore-11.3.0.eb

Two separate easyconfigs for ESPResSo build with GPU and no-GPU support

{chem}[foss/2022a, GCCcore/11.3.0] ESPResSo v4.2.1, Pint v0.22

---

easybuild/easyconfigs/g/GHC/GHC-9.2.2-x86_64.eb

Hi there, this is an update to the GHC easy config.

adding easyconfigs: GHC-9.2.2-x86_64.eb

---

test/easyconfigs/easyconfigs.py

filter out template + archived easyconfigs when determining changed easyconfigs in PRs

---

RELEASE_NOTES

oops, missed a spot in #18754 ...

include additional PRs that got merged last-minute in v4.8.1 release notes

---

easybuild/easyconfigs/a/Amber/Amber-22.4-foss-2022a-AmberTools-22.5-CUDA-11.7.0.eb

- Successfully build at our site
- replaces https://github.com/easybuilders/easybuild-easyconfigs/pull/17824

{chem}[foss/2022a] Amber v22.4 with AmberTools v22.5 + CUDA 11.7.0

---

easybuild/easyconfigs/a/anadama2/anadama2-0.10.0-foss-2022a.eb
easybuild/easyconfigs/b/biobakery-workflows/biobakery-workflows-3.1-foss-2022a.eb
easybuild/easyconfigs/k/kneaddata/kneaddata-0.12.0-foss-2022a.eb
easybuild/easyconfigs/l/LevelDB/LevelDB-1.22-GCCcore-11.3.0.eb

adding easyconfigs: anadama2-0.10.0-foss-2022a.eb, biobakery-workflows-3.1-foss-2022a.eb, kneaddata-0.12.0-foss-2022a.eb, LevelDB-1.22-GCCcore-11.3.0.eb
based on https://github.com/vscentrum/vsc-software-stack/issues/138

{bio}[foss/2022a] biobakery-workflows v3.1

---

easybuild/easyconfigs/o/OpenImageIO/OpenImageIO-2.4.14.0-GCC-12.3.0.eb

Add alternate checksum for OpenImageIO v2.4.14.0

---

easybuild/easyconfigs/m/Miniconda3/Miniconda3-23.9.0-0.eb

Add Miniconda3-23.9.0-0

---

easybuild/easyconfigs/e/EUKulele/EUKulele-2.0.6-foss-2022a.eb

adding easyconfigs: EUKulele-2.0.6-foss-2022a.eb
related to: https://github.com/vscentrum/vsc-software-stack/issues/206

{bio}[foss/2022a] EUKulele v2.0.6

---

easybuild/easyconfigs/s/solo/solo-1.3-foss-2022a.eb

adding easyconfigs: solo-1.3-foss-2022a.eb
relates to: https://github.com/vscentrum/vsc-software-stack/issues/60

{bio}[foss/2022a] solo v1.3

---

easybuild/easyconfigs/t/tensorflow-probability/tensorflow-probability-0.19.0-foss-2022a.eb
easybuild/easyconfigs/v/vaeda/vaeda-0.0.30-foss-2022a.eb

adding easyconfigs: tensorflow-probability-0.19.0-foss-2022a.eb, vaeda-0.0.30-foss-2022a.eb
relates to: https://github.com/vscentrum/vsc-software-stack/issues/57

{bio}[foss/2022a] vaeda v0.0.30

---

easybuild/easyconfigs/c/CP2K/CP2K-2023.1-foss-2023a.eb
easybuild/easyconfigs/l/Libint/Libint-2.7.2-GCC-12.3.0-lmax-6-cp2k.eb
easybuild/easyconfigs/l/libvori/libvori-220621-GCCcore-12.3.0.eb
easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-GCC-12.3.0.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2023a.eb
easybuild/easyconfigs/x/xxd/xxd-9.0.2112-GCCcore-12.3.0.eb

{chem}[foss-2023a] CP2K 2023.1

---

easybuild/easyconfigs/b/Blosc/Blosc-1.21.5-GCCcore-12.3.0.eb
easybuild/easyconfigs/b/Blosc2/Blosc2-2.8.0-GCCcore-12.3.0.eb

Extracted from https://github.com/easybuilders/easybuild-easyconfigs/pull/19398

{lib}[GCCcore/12.3.0] Blosc 1.12.5, Blosc2 2.8.0

---

easybuild/easyconfigs/p/pymatgen/emmet-core-0.75.0-fix-readme.patch
easybuild/easyconfigs/p/pymatgen/pymatgen-2023.12.18-foss-2023a.eb
easybuild/easyconfigs/u/uncertainties/uncertainties-3.1.7-foss-2023a.eb

Extracted from https://github.com/easybuilders/easybuild-easyconfigs/pull/19398
Requires

{chem}[foss/2023a] pymatgen v2023.12.18, uncertainties 3.1.7

---

easybuild/easyconfigs/p/protobuf-python/protobuf-python-4.24.0-GCCcore-12.3.0.eb
easybuild/easyconfigs/p/protobuf-python/protobuf-python-4.24.0_fix-upb-copyfrom.patch

fixes the issue seen in https://github.com/protocolbuffers/protobuf/issues/13485

patch upb CopyFrom error in protobuf-python 4.24.0

---

easybuild/easyconfigs/g/Gblocks/Gblocks-0.91b.eb

Update source url
Old one does not work anymore

fix homepage + source URL for Gblocks 0.91b

---

easybuild/easyconfigs/m/Mathematica/Mathematica-12.0.0.eb
easybuild/easyconfigs/m/Mathematica/Mathematica-12.1.1.eb
easybuild/easyconfigs/m/Mathematica/Mathematica-13.0.0.eb
easybuild/easyconfigs/m/Mathematica/Mathematica-13.1.0.eb

add `download_instructions` to Mathematica easyconfigs

---

easybuild/easyconfigs/a/ADF/ADF-2019.303-intelmpi.eb

add `download_instructions` to ADF easyconfigs

---

easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-1.0.1.eb
easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.0.eb
easybuild/easyconfigs/c/CellRanger-ARC/CellRanger-ARC-2.0.1.eb
easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-1.2.0.eb
easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-2.0.0.eb
easybuild/easyconfigs/c/CellRanger-ATAC/CellRanger-ATAC-2.1.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-3.0.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-3.0.2.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-3.1.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-4.0.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-5.0.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-5.0.1.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.1.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-6.0.2.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-6.1.2.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-7.0.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-7.1.0.eb
easybuild/easyconfigs/c/CellRanger/CellRanger-7.2.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.1.0-GCC-9.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.2.2-GCC-9.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.0-GCC-10.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.1-GCC-11.2.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.0.0-GCC-11.2.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.0.1-GCC-11.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.1.0-GCC-11.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.1.0-GCC-12.2.0.eb

add download_instructions to `CellRanger`, `CellRanger-ARC`, `CellRanger-ATAC` and `SpaceRanger` easyconfigs

---

easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-13.04.011.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.02.008-r8.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.02.008.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.04.008-r8.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.04.008.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.06.007-r8.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-17.06.007.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-18.02.008-r8.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-18.02.008.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-18.06.006-r8.eb
easybuild/easyconfigs/s/STAR-CCM+/STAR-CCM+-18.06.006.eb

add `download_instructions` to STAR-CCM+ easyconfigs

---

easybuild/easyconfigs/s/Schrodinger/Schrodinger-2020-4.eb
easybuild/easyconfigs/s/Schrodinger/Schrodinger-2021-4.eb
easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-1.eb
easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-2.eb
easybuild/easyconfigs/s/Schrodinger/Schrodinger-2022-3.eb

add `download_instructions` to Schrodinger easyconfigs

---

easybuild/easyconfigs/a/ABAQUS/ABAQUS-2020.eb
easybuild/easyconfigs/a/ABAQUS/ABAQUS-2021-hotfix-2132.eb
easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022-hotfix-2214.eb
easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022-hotfix-2223.eb
easybuild/easyconfigs/a/ABAQUS/ABAQUS-2022.eb

add `download_instructions` to ABAQUS easyconfigs

---

easybuild/easyconfigs/a/AGeNT/AGeNT-3.0.6.eb

add `download_instructions` to AGeNT easyconfigs

---

easybuild/easyconfigs/o/ORCA/ORCA-5.0.0-gompi-2021a-static.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.0-gompi-2021a.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.1-gompi-2021a-static.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.1-gompi-2021a.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.2-gompi-2021a-static.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.2-gompi-2021a.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.2-gompi-2021b-static.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.2-gompi-2021b.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.3-gompi-2021b.eb
easybuild/easyconfigs/o/ORCA/ORCA-5.0.4-gompi-2022a.eb

add `download_instructions` to ORCA easyconfigs 

---

easybuild/easyconfigs/c/cuDNN/cuDNN-7.4.2.24-CUDA-10.0.130.eb

add `source_urls` to cuDNN easyconfig

---

easybuild/easyconfigs/o/OptiX/OptiX-6.5.0.eb
easybuild/easyconfigs/o/OptiX/OptiX-7.2.0.eb

add `download_instructions` to OptiX easyconfigs

---

easybuild/easyconfigs/s/SignalP/SignalP-5.0b-Linux.eb
easybuild/easyconfigs/s/SignalP/SignalP-6.0g-foss-2021b-fast.eb
easybuild/easyconfigs/s/SignalP/SignalP-6.0g-foss-2022a-fast-CUDA-11.7.0.eb
easybuild/easyconfigs/s/SignalP/SignalP-6.0g-foss-2022a-fast.eb
easybuild/easyconfigs/s/SignalP/SignalP-6.0h-foss-2022b-fast.eb

improve and add `download_instructions` to SignalP easyconfigs

---

easybuild/easyconfigs/t/TetGen/TetGen-1.6.0-GCCcore-10.2.0.eb

add `download_instructions` to TetGen easyconfig

---

easybuild/easyconfigs/x/XBeach/XBeach-20230831-gompi-2022a.eb

add `download_instructions` to XBeach easyconfigs

---

easybuild/easyconfigs/s/Stata/Stata-16-legacy.eb
easybuild/easyconfigs/s/Stata/Stata-17.eb

add `download_instructions` and `build_info_msg` to Stata easyconfig

---

easybuild/easyconfigs/a/annovar/annovar-20200607-GCCcore-11.2.0-Perl-5.34.0.eb

add `download_instructions` to annovar easyconfigs

---

easybuild/easyconfigs/d/dialog/dialog-1.3-20231002-GCCcore-10.3.0.eb

fix source definition for dialog

---

easybuild/easyconfigs/s/SMRT-Link/SMRT-Link-6.0.0.47841-cli-tools-only.eb

add `download_instructions` to SMRT-Link easyconfig

---

easybuild/easyconfigs/a/AMS/AMS-2020.102-iimpi-2020b-intelmpi.eb
easybuild/easyconfigs/a/AMS/AMS-2022.102-iimpi-2021b-intelmpi.eb
easybuild/easyconfigs/a/AMS/AMS-2023.101-iimpi-2022a-intelmpi.eb
easybuild/easyconfigs/a/AMS/AMS-2023.104-iimpi-2022b-intelmpi.eb

add `download_instructions` to AMS easyconfigs

---

easybuild/easyconfigs/f/FDTD_Solutions/FDTD_Solutions-8.20.1731.eb

add `download_instructions` to FDTD_Solutions easyconfigs

---

easybuild/easyconfigs/f/FLUENT/FLUENT-2019R3.eb
easybuild/easyconfigs/f/FLUENT/FLUENT-2021R1.eb
easybuild/easyconfigs/f/FLUENT/FLUENT-2021R2.eb

add `download_instructions` to FLUENT easyconfigs

---

easybuild/easyconfigs/g/GeneMark-ET/GeneMark-ET-4.65-GCCcore-10.2.0.eb

add `download_instructions` to GeneMark-ET easyconfigs

---

easybuild/easyconfigs/c/Chimera/Chimera-1.16-linux_x86_64.eb

add `download_instructions` to Chimera easyconfigs

---

easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-CrayCCE-19.06.eb
easybuild/easyconfigs/c/CASTEP/CASTEP-21.1.1-CrayGNU-19.06.eb

add `download_instructions` to CASTEP easyconfigs

---

easybuild/easyconfigs/m/Maple/Maple-2022.1.eb

add `download_instructions` to Maple easyconfigs

---

easybuild/easyconfigs/n/netMHC/netMHC-4.0a.eb
easybuild/easyconfigs/n/netMHCII/netMHCII-2.3.eb

add `download_instructions` to netMHC and netMHCII easyconfigs

---

easybuild/easyconfigs/d/datalad/datalad-0.19.5-GCCcore-12.3.0.eb
easybuild/easyconfigs/g/GHC/GHC-9.4.6-x86_64.eb
easybuild/easyconfigs/g/git-annex/git-annex-10.20230802-GCCcore-12.3.0.eb
easybuild/easyconfigs/p/PLY/PLY-3.11-GCCcore-12.3.0.eb
easybuild/easyconfigs/p/phono3py/phono3py-2.7.0-foss-2023a.eb
easybuild/easyconfigs/s/Stack/Stack-2.13.1-x86_64.eb

Hi, with this, I'm updating datalad for the GCCcore 12.3.0 toolchain, as per request in #19879

{tool}[GCCcore-12.3.0] datalad-0.19.5

---

easybuild/easyconfigs/j/Java/Java-21.0.2.eb

{lang}[system/system] Java v21.0.2

---

easybuild/easyconfigs/a/Anaconda3/Anaconda3-2024.02-1.eb

New easyconfig for Anaconda3 v 2024.02.   It seems support for Power has been dropped by the Anaconda folk.

{lang}[system/system] Anaconda3 version 2024.02-1

---

.github/workflows/linting.yml
easybuild/easyconfigs/__archive__/l/libunwind/libunwind-1.1-foss-2015a.eb
easybuild/easyconfigs/__archive__/l/libunwind/libunwind-1.1-goolf-1.4.10.eb
easybuild/easyconfigs/__archive__/l/libunwind/libunwind-1.1-ictce-5.3.0.eb
easybuild/easyconfigs/i/IntelDAAL/IntelDAAL-2019.4.007.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.1-GCC-4.9.2.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.1-foss-2016a.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.1-intel-2016b.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-GCCcore-6.3.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-GCCcore-6.4.0.eb
easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-foss-2016b.eb
easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb

This enables fatal error checking for ECs via `flake8` which includes unknown/undefined variables used and other serious issues.
Those found in current ECs are fixed here. Mostly duplicate dict keys which are obviously a mistake.
I kept the last entry each which is what python would use

Fix duplicate dict entries

---

easybuild/easyconfigs/m/Miniforge3/Miniforge3-24.1.2-0.eb

Add recipe for building Miniforge3.
Closes #20226

Add easyconfig for Miniforge3

---

easybuild/easyconfigs/a/assimp/assimp-5.3.1-GCCcore-13.2.0.eb
easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-foss-2023b.eb
easybuild/easyconfigs/q/Qt6/Qt6-6.6.3-GCCcore-13.2.0.eb
easybuild/easyconfigs/q/Qt6/Qt6-6.6.3_fix_OF-Gentoo.patch

adding easyconfigs: 
- ParaView-5.12.0-foss-2023b.eb (without building docs that aren't supported with Qt6)
- Qt6-6.6.3-GCCcore-13.2.0.eb
- assimp-5.3.1-GCCcore-13.2.0.eb
and patches: 
- Qt6-6.6.3_fix_OF-Gentoo.patch (updated file path)

adding easyconfigs: ParaView-5.12.0-foss-2023b.eb and Qt6-6.6.3-GCCcore

---

easybuild/easyconfigs/n/nanoget/nanoget-1.18.1-foss-2022b.eb

{bio}[foss/2022b] nanoget 1.18.1

---

easybuild/easyconfigs/p/pauvre/pauvre-0.2.3-foss-2022b.eb

{math}[foss/2022b] pauvre v0.2.3

---

easybuild/easyconfigs/g/gcloud/gcloud-472.0.0.eb

{tools}[system/system] gcloud v472.0.0

---

easybuild/easyconfigs/g/GTDB-Tk/GTDB-Tk-2.4.0-foss-2023a.eb
test/easyconfigs/easyconfigs.py

Added a new GTDB-tk for v 2.4.0 for foss 2023a

{bio}[foss/2023a] GTDB-Tk v2.4.0

---

setup.py

add 'archive' extra to optionally install easybuild-easyconfigs-archive

---

easybuild/easyconfigs/e/EGA-QuickView/EGA-QuickView-20240620-GCC-12.3.0.eb

rename ega-quickview to EGA-QuickView

---

easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-37-GCCcore-11.3.0.eb
easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-4-GCCcore-11.2.0.eb
easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.0-53-GCCcore-12.2.0.eb
easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.1.1-15-GCCcore-12.3.0.eb

Backporting some enhancements from https://github.com/easybuilders/easybuild-easyconfigs/pull/20892 to older versions.

make sure that recent ImageMagick versions pick up the right pkgconf and improve the sanity checks

---

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb

resolves https://github.com/vscentrum/vsc-software-stack/issues/374

add missMDA extension to R-bundle-CRAN 2023.12

---

easybuild/easyconfigs/b/BayesTraits/BayesTraits-4.1.2-Linux.eb

Added a newer BayesTraits they moved off of github

{bio}[SYSTEM] BayesTraits v4.1.2

---

easybuild/easyconfigs/h/HDF5/HDF5-1.14.3-gompi-2023b.eb
easybuild/easyconfigs/h/HDF5/HDF5-1.14.3-iimpi-2023b.eb
easybuild/easyconfigs/h/HDF5/HDF5-1.14.3_suppress_fp_exceptions.patch

HDF5 v1.14.3 was broken, this patch is the hotfix that was published soon after the release.
See: https://github.com/HDFGroup/hdf5/issues/3831

adding patch: HDF5-1.14.3_suppress_fp_exceptions.patch

---

easybuild/easyconfigs/g/GLM/GLM-1.0.1-GCCcore-13.3.0.eb
easybuild/easyconfigs/g/GTS/GTS-0.7.6-GCCcore-13.3.0.eb
easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-13.3.0.eb
easybuild/easyconfigs/g/gmpy2/gmpy2-2.2.0-GCCcore-13.3.0.eb
easybuild/easyconfigs/g/graphite2/graphite2-1.3.14-GCCcore-13.3.0.eb
easybuild/easyconfigs/i/Imath/Imath-3.1.11-GCCcore-13.3.0.eb
easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.5-GCCcore-13.3.0.eb
easybuild/easyconfigs/j/jemalloc/jemalloc-5.3.0-GCCcore-13.3.0.eb
easybuild/easyconfigs/j/json-c/json-c-0.17-GCCcore-13.3.0.eb

Added some packages from our new SW stage at JSC. They were mostly versions bumps and checksum adaptions.

Added GLM, GTS, gflags, gmpy2, graphite2, Imath, json-c, JsonCpp and jemalloc for GCCcore-13.3.0

---

easybuild/easyconfigs/p/psutil/psutil-6.0.0-GCCcore-13.3.0.eb

Added EC file for psutil 6.0.0

{lib}[GCCcore/13.3.0] psutil v6.0.0

---

easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-11.2.0-tools.eb
easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-11.3.0-tools.eb
easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-12.2.0-tools.eb
easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-12.3.0-tools.eb
easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-13.2.0-tools.eb
easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.7-GCCcore-13.3.0-tools.eb

Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/21747.

use new checksum for source tarball of SIONlib 1.7.7

---

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.27-GCC-13.3.0-seq-iface64.eb

{numlib}[GCC-13.2.0] OpenBLAS 0.3.27 sequential with 64 bit interface

{numlib}[GCC-13.3.0] OpenBLAS 0.3.27 sequential with 64 bit interface

---

easybuild/easyconfigs/l/libffi/libffi-3.4.5.eb

Added EC for libffi-3.4.5 with SYSTEM toolchain

{lib} [SYSTEM] libffi 3.4.5

---

easybuild/easyconfigs/m/MaxBin/MaxBin-2.2.7-gompi-2023a-Python-2.7.18.eb

Needs:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/22393

{bio}[gompi/2023a] MaxBin v2.2.7 w/ Python 2.7.18

---

easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.2-GCCcore-10.2.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.3-GCCcore-10.3.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.3.3-GCCcore-11.2.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.4.0-GCCcore-11.3.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.6.0-GCCcore-12.2.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.6.0-GCCcore-12.3.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-13.2.0.eb
easybuild/easyconfigs/l/libglvnd/libglvnd-1.7.0-GCCcore-13.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.0-GCC-10.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-1.3.1-GCC-11.2.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.0.0-GCC-11.2.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.0.1-GCC-11.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.1.0-GCC-11.3.0.eb
easybuild/easyconfigs/s/SpaceRanger/SpaceRanger-2.1.0-GCC-12.2.0.eb

Depends on:
* https://github.com/easybuilders/easybuild-framework/pull/4774

remove deprecated `allow_prepend_abs_path` from libglvnd and SpaceRanger

---

.github/workflows/linting.yml
.github/workflows/unit_tests.yml
RELEASE_NOTES

Don't use Ubuntu 20.04 anymore and update actions

Update GitHub actions runners

---

easybuild/easyconfigs/q/Qt6/Qt6-6.5.2-GCCcore-12.3.0.eb
easybuild/easyconfigs/q/Qt6/Qt6-6.5.2_fix_too_long_filenames.patch
easybuild/easyconfigs/q/Qt6/Qt6-6.6.3-GCCcore-13.2.0.eb
easybuild/easyconfigs/q/Qt6/Qt6-6.7.2-GCCcore-13.3.0.eb

Patch for issue https://bugreports.qt.io/browse/QTBUG-59769

add patch to fix build failure due to too long filenames in Qt6

---

easybuild/easyconfigs/m/Mesa/Mesa-20.2.1-GCCcore-10.2.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-21.1.1-GCCcore-10.3.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-21.1.7-GCCcore-11.2.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-22.0.3-GCCcore-11.3.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-22.2.4-GCCcore-12.2.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-23.1.4-GCCcore-12.3.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-23.1.9-GCCcore-13.2.0.eb
easybuild/easyconfigs/m/Mesa/Mesa-24.1.3-GCCcore-13.3.0.eb

Fixes failed test in https://gist.github.com/boegelbot/2645bd9f0653b47649fa39adae45a862

replace source URLs of Mesa to new location in archive.mesa3d.org

---

easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-foss-2020b-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.3.5-intel-2020b-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-foss-2021a-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.0-intel-2021a-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.1-foss-2021b-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.4.1-intel-2021b-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.0-foss-2021a-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.5.1-foss-2022a-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2022b-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2023a-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-foss-2023b-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.6.1-gomkl-2023a-metis-seq.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-foss-2023b-parmetis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-foss-2024a-metis.eb
easybuild/easyconfigs/m/MUMPS/MUMPS-5.7.2-intel-2023b-parmetis.eb

Current source URLs are 404ing.

update homepage and sources of MUMPS with new home at mumps-solver.org

---

easybuild/easyconfigs/v/VMD/VMD-1.9.4a51-foss-2020b.eb
easybuild/easyconfigs/v/VMD/VMD-1.9.4a51-fosscuda-2020b.eb
easybuild/easyconfigs/v/VMD/VMD-1.9.4a57-foss-2022a.eb
easybuild/easyconfigs/v/VMD/VMD-1.9.4a57-foss-2023a.eb

Current source URLs on http://webclu.bio.wzw.tum.de/stride/ are 404ing

switch webclu.bio.wzw.tum.de to HTTPS in VMD easyconfigs

---

easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-10.2.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-10.3.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.2.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.3.0-int64.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-11.3.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-12.2.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-12.3.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-13.2.0.eb
easybuild/easyconfigs/m/METIS/METIS-5.1.0-GCCcore-13.3.0.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2020b.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2021a.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2021b.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2022a.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2022b.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2023a.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-gompi-2023b.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2020b.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2021a.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2021b.eb
easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-iimpi-2023b.eb

The current source URLs are 404ing.

update homepage and sources of METIS and ParMETIS with new home at kaypis.github.io

---

RELEASE_NOTES
setup.py

draft because release notes need to be updated as well...

bump version to 5.0.0 + update release notes

---

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.11-foss-2024a.eb

resolves https://github.com/vscentrum/vsc-software-stack/issues/531

Update R-bundle-CRAN-{2024a, 2023b, 2023a} - add modsem and its dependencies

---

easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-10.2.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.1-GCCcore-10.3.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.2.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-11.3.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.2-GCCcore-12.2.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-12.3.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-13.2.0.eb
easybuild/easyconfigs/l/libGLU/libGLU-9.0.3-GCCcore-13.3.0.eb

This PR corrects URLs for libGLU that currently return a 404.
See #22624

Update URLs for libGLU

---

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb
easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.11-foss-2024a.eb

resolves https://github.com/vscentrum/vsc-software-stack/issues/543

Add sgdGMF to R-bundle-CRANs

---

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb

For iGUIDE https://github.com/vscentrum/vsc-software-stack/issues/555

Update R-bundle-CRAN-2023.12-foss-2023a.eb - add kableExtra

---

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb

For iGUIDE https://github.com/vscentrum/vsc-software-stack/issues/555

Update R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb - add hiAnnotator

---

easybuild/easyconfigs/l/LLVM/LLVM-18.1.8_envintest.patch
easybuild/easyconfigs/l/LLVM/LLVM-19.1.7-GCCcore-13.3.0.eb
easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_clang_rpathwrap_test.patch
easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_libomptarget_tests.patch

Added patches and EC file for LLVM 19.1.7-GCCcore13.3.0

{compiler}[GCCcore/13.3.0] LLVM 19.1.7

---

easybuild/easyconfigs/q/qrupdate/qrupdate-1.1.2-GCCcore-12.3.0.eb

Added EC file for qrupdate-1.1.2 and GCCcore-12.3.0

{numlib}[GCCcore/12.3.0] qrupdate-1.1.2

---

easybuild/easyconfigs/i/IsoSeq/IsoSeq-3.8.2-linux-x86_64.eb
easybuild/easyconfigs/i/IsoSeq/IsoSeq-4.0.0-linux-x86_64.eb

The URL was wrong. Just update to the correct link.

Update homepage URL for IsoSeq to correct repository link

---

.github/workflows/unit_tests.yml

reverts changed made in #23099, should only be merged after merge sprint of Mon 16 June 2025

restore test configurations

---

test/easyconfigs/easyconfigs.py

see https://github.com/easybuilders/easybuild-easyconfigs/pull/23235/#discussion_r2176184340

set a `User-Agent` for the https/http check

---

test/easyconfigs/easyconfigs.py

also check on post-install patches in easyconfigs test suite

---

easybuild/easyconfigs/o/Octave/Octave-10.1.0-foss-2023a.eb
easybuild/easyconfigs/o/Octave/optim-1.6.2-octave-10.patch

Added EC file for `Octave-10.1.0` on `foss/2023a`
Requires EC file from 
- #22930
- #22934

{math}[foss/2023a] Octave-10.1.0

---

easybuild/easyconfigs/o/occt/occt-7.5.0p1-foss-2021a.eb
easybuild/easyconfigs/o/occt/occt-7.5.0p1-foss-2022a.eb

Fixes outdated sources for `occt` 

---

easybuild/easyconfigs/c/cURL/cURL-7.76.0-GCCcore-10.3.0.eb
easybuild/easyconfigs/c/cURL/cURL-7.78.0-GCCcore-11.2.0.eb
easybuild/easyconfigs/c/cURL/cURL-7.83.0-GCCcore-11.3.0.eb
easybuild/easyconfigs/c/cURL/cURL-7.84.0-GCCcore-12.1.0.eb
easybuild/easyconfigs/c/cURL/cURL-7.86.0-GCCcore-12.2.0.eb
easybuild/easyconfigs/c/cURL/cURL-8.0.1-GCCcore-12.3.0.eb
easybuild/easyconfigs/c/cURL/cURL-8.0.1-GCCcore-13.1.0.eb
easybuild/easyconfigs/c/cURL/cURL-8.11.1-GCCcore-14.2.0.eb
easybuild/easyconfigs/c/cURL/cURL-8.14.1-GCCcore-14.3.0.eb
easybuild/easyconfigs/c/cURL/cURL-8.3.0-GCCcore-13.2.0.eb
easybuild/easyconfigs/c/cURL/cURL-8.7.1-GCCcore-13.3.0.eb

This may pick up a system library which can be or become incompatible.
Fixes #23514

Disable libgsasl in cURL

---

easybuild/easyconfigs/c/CMake/CMake-3.31.8-GCCcore-12.3.0.eb

Added newer CMake version for `foss/2023a`

{devel}[GCCcore/12.3.0] CMake 3.31.8

---

easybuild/easyconfigs/s/spdlog/spdlog-1.15.3-GCCcore-14.3.0.eb

spdlog 1.15.3 with GCCcore 14.3.0.

{lib}[GCCcore/14.3.0] spdlog v1.15.3
