easybuilders/easybuild-easyconfigs

easybuild/easyconfigs/m/Mathematica/Mathematica-12.0.0.eb
new Mathematica is out since m04 so it's time to give it to $users.
based entirely on previous easyconfig, just url and sha256sum updated.
[some wording from vendor](https://blog.stephenwolfram.com/2019/04/version-12-launches-today-big-jump-for-wolfram-language-and-mathematica/)
=> {math}[dummy/dummy] Mathematica v12.0.0

easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-intel-2018b-Python-2.7.15.eb, easybuild/easyconfigs/a/Arrow/Arrow-0.12.0-intel-2018b-Python-3.6.6.eb
That way, `pip install` does not abuse `$HOME/.cache/pip`...
=> set $XDG_CACHE_HOME to $TMPDIR before 'pip install' in Arrow 0.12.0 easyconfigs

easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4-iccifort-2019.1.144-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4_lm-fix.patch, easybuild/easyconfigs/l/libxc/libxc-4.3.4_rename-F03.patch
Using CMake is important to also get the CMake-related scripts in `share/cmake/libxc` installed, which are required to use `libxc` as a dependency for PSI4 (rather than letting it build its own (old & unpatched) version of `libxc`).
=> use CMake rather than configure script for libxc 4.3.4

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.7-foss-2018b-R-3.5.1.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.7-iomkl-2018a-R-3.5.0.eb
The `'checksum'` entry serves no purpose and is just being ignored, the actual correct checksum is specified via `'checksums'`...
=> remove unused checksum for ballgown extension in Bioconductor 3.7 easyconfigs

easybuild/easyconfigs/p/Perl/Perl-5.28.1-GCCcore-8.2.0.eb
extra Perl modules required for `BRAKER`, cfr. https://github.com/Gaius-Augustus/BRAKER#perl-pipeline-dependencies
=> add Logger::Simple, Scalar::Util::Numeric, YAML, Object::InsideOut extensions to Perl 5.28.1 easyconfig

easybuild/easyconfigs/b/BLAST+/BLAST+-2.9.0-gompi-2019a.eb
=> move BLAST+ 2.9.0 from foss/2019a to gompi/2019a subtoolchain

easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4_fix-CMakeLists.patch
installation of `CP2K-6.1-foss-2019a.eb` got broken due to changes in #8361
=> fix undefined reference error in CP2K due to libxc 4.3.4 built with CMake

easybuild/easyconfigs/c/CFITSIO/CFITSIO-3.47-GCCcore-8.2.0.eb, easybuild/easyconfigs/c/CFITSIO/CFITSIO_install_test_data.patch
let's make easyconfig for recent CFITSIO with current GCCcore toolchain.
new sanity check implemented using `testprog` from source tarball and backported into older `CFITSIO-3.45` which is still used by my $users.
=> new easyconfig for CFITSIO-3.47, updating CFITSIO-3.45 with https and sanity check

easybuild/easyconfigs/l/LibUUID/LibUUID-1.0.3-GCCcore-8.2.0.eb
just shifting GCCcore toolchain version to 8.2.0
=> {lib}[GCCcore/8.2.0] LibUUID v1.0.3

.travis.yml
This change is necessary because Travis CI is changing the default from Ubuntu Trusty (14.04) to Ubuntu Xenial (16.04), see also https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment .
Should fix following issue that occurs when running the easyconfig test suite with Python 2.6:
```
2.6 is not installed; attempting download
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-2.6.tar.bz2
0.11s$ curl -sSf -o python-2.6.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 2.6 archive. The archive may not exist. Please consider a different version.
```
=> stick to Ubuntu Trusty when testing with Python 2.6 in Travis

easybuild/easyconfigs/g/GDB/GDB-8.0.1-foss-2017b-Python-2.7.14.eb, easybuild/easyconfigs/g/GDB/GDB-8.0.1-foss-2017b-Python-3.6.3.eb, easybuild/easyconfigs/g/GDB/GDB-8.1-foss-2018a-Python-2.7.14.eb, easybuild/easyconfigs/g/GDB/GDB-8.1.1-intel-2018a-Python-2.7.14.eb, easybuild/easyconfigs/g/GDB/GDB-8.3-GCCcore-8.2.0-Python-3.7.2.eb
These libraries (and corresponding headers) shadow the libraries installed by `binutils`, which may cause subtle issues when building codes that use `libbfd` and/or `libopcode` (the GDB versions are static only and not compiled with `-fPIC`).  Older versions of GDB are also most likely affected, but I'm not sure it's worth the effort to fix them as well.
=> GDB: Suppress installation of libbfd and libopcode

easybuild/easyconfigs/o/OR-Tools/OR-Tools-7.1-foss-2019a-Python-3.7.2.eb
Easyconfig tests are broken after the merge of #8364 (because Travis approved the PR before other easyconfigs that use `Java/11` as a dep got merged).
@wpoely86 How do we test whether `Java/11` works as expected here?
=> use Java/11 rather than Java/1.8 as dependency for OR-Tools

easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
It looks like the `boot_1.3-22.tar.gz` source tarball at https://cran.r-project.org/src/contrib/Archive/boot/, was replaced with an older version (again, cfr. #8054).
Functionally, nothing has changed though, it's only the publication date in the description that was reverted:
```
$ diff -ru boot.old boot
diff -ru boot.old/DESCRIPTION boot/DESCRIPTION
--- boot.old/DESCRIPTION        2019-04-26 15:19:17.000000000 +0200
+++ boot/DESCRIPTION    2019-04-02 22:04:12.000000000 +0200
@@ -24,4 +24,4 @@
Author: Angelo Canty [aut],
Brian Ripley [aut, trl, cre] (author of parallel support)
Repository: CRAN
-Date/Publication: 2019-04-26 13:19:17 UTC
+Date/Publication: 2019-04-02 20:04:12 UTC
diff -ru boot.old/MD5 boot/MD5
--- boot.old/MD5        2019-04-26 15:19:17.000000000 +0200
+++ boot/MD5 …
```
=> fix checksum for boot 1.3-22 extension in R 3.6.0 easyconfig

easybuild/easyconfigs/n/Net-core/Net-core-2.2.5.eb
I realized that the tarball to download is named `dotnet-runtime` and not `aspnetcore-runtime` 
I have also added another easyconfig with the latest version
=> download correct Net-core tarball and add new easyconfig for Net-core 2.2.5

easybuild/easyconfigs/n/numexpr/numexpr-2.6.5-intel-2018b-Python-2.7.15.eb
just a port of foss2018b version into intel2018b..
=> {math}[intel/2018b] numexpr v2.6.5 w/ Python 2.7.15

easybuild/easyconfigs/p/PETSc/PETSc-3.11.1-foss-2019a.eb, easybuild/easyconfigs/p/PETSc/PETSc-3.11.1-intel-2019a.eb, easybuild/easyconfigs/p/PETSc/PETSc-3.9.3-foss-2018a.eb, easybuild/easyconfigs/p/PETSc/PETSc-3.9.3-intel-2018a.eb
After removing comments to enable SLURM batch support the build stops working due to malformed configure options.
=> Make additional configopts work after uncommenting

easybuild/easyconfigs/a/ANTs/ANTs-2.3.1-foss-2018b-Python-3.6.6.eb
The `Permission denied` errors that also popped in #6998 have surfaced again, so I've figured out a way to fix them properly: removing the (useless) `.git` subdirectories that trigger them (exact reason is still unclear though).
=> fix 'Permission denied' error when running 'cp -a' for ANTs 2.3.1 insallation by first removing the .git subdirectories causing them

easybuild/easyconfigs/n/ncdf4/ncdf4-1.16.1-foss-2018b-R-3.5.1.eb, easybuild/easyconfigs/n/ncdf4/ncdf4-1.16.1-intel-2018b-R-3.5.1.eb
Minor update of the R package `ncdf4` to version 1.16.1. One easyconfig for `foss/2018b` and another for `intel/2018b`.
=> {math}[foss/2018b,intel/2018b] ncdf4 v1.16.1

easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
This reverts the checksum 'fix' done in #8537, since the upstream source tarball was changed again to what it was before...
```
$ diff -ru boot.20190704 boot.20190607
diff -ru boot.20190704/DESCRIPTION boot.20190607/DESCRIPTION
--- boot.20190704/DESCRIPTION   2019-04-02 22:04:12.000000000 +0200
+++ boot.20190607/DESCRIPTION   2019-04-26 15:19:17.000000000 +0200
@@ -24,4 +24,4 @@
Author: Angelo Canty [aut],
Brian Ripley [aut, trl, cre] (author of parallel support)
Repository: CRAN
-Date/Publication: 2019-04-02 20:04:12 UTC
+Date/Publication: 2019-04-26 13:19:17 UTC
diff -ru boot.20190704/MD5 boot.20190607/MD5
--- boot.20190704/MD5   2019-04-02 22:04:12.000000000 +0200
+++ boot.20190607/MD5   2019-04-26 15:19:17.000000000 +0200
@@ -1,5 +1,5 @@
1b5ac46717dca02c841ea6e1325238a6 *ChangeLog …
```
=> revert checksum 'fix' for boot extension in R 3.6.0 

easybuild/easyconfigs/o/OpenMPI/OpenMPI-3.1.4-GCC-8.3.0-2.32.eb
The added patch is still necessary. Apparently its content will be available only from `4.x`.
`OpenMPI-3.1_fix-ib-query.patch` is no longer needed since it is already added to the sources.
=> Add required patch to OpenMPI-3.1.4

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.12-GCC-4.9.2-LAPACK-3.5.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.13-GCC-4.8.4-LAPACK-3.5.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.13-GCC-4.9.2-LAPACK-3.5.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.14-GNU-4.9.2-2.25-LAPACK-3.5.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.14-GNU-4.9.3-2.25-LAPACK-3.5.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-4.9.4-2.25-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.3.0-2.26-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.18-gompi-2016.07-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-GCC-5.4.0-2.26-LAPACK-3.7.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-GCC-6.3.0-2.27-LAPACK-3.7.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.19-gompi-2016.09-LAPACK-3.6.1.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.9-GCC-4.8.3-LAPACK-3.5.0.eb
=> fix names of local variables in OpenBLAS easyconfigs

easybuild/easyconfigs/f/FFTW/FFTW-2.1.5-intel-2016b.eb, easybuild/easyconfigs/f/FFTW/FFTW-2.1.5-intel-2017a.eb, easybuild/easyconfigs/f/FFTW/FFTW-2.1.5-intel-2018b.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gmpich-2016a.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gmvapich2-1.7.20.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gmvapich2-2016a.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016.04.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016.06.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016.07.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016a.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-gompi-2016b.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.4-intel-2016a.eb
done with --fix-deprecated-easyconfigs, no manual changes
required to avoid warnings when these easyconfigs are parsed because of changed made in easybuilders/easybuild-framework#2938
=> fix names of local variables in FFTW easyconfigs

easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gimpi-2017b-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gimpi-2018a-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gimpic-2017b-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmpich-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmpich-2017.08-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmvapich2-1.7.20-OpenBLAS-0.2.13-LAPACK-3.5.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmvapich2-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.04-OpenBLAS-0.2.18-LAPACK-3.6.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.06-OpenBLAS-0.2.18-LAPACK-3.6.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.07-OpenBLAS-0.2.18-LAPACK-3.6.1.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016.09-OpenBLAS-0.2.19-LAPACK-3.6.1.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2017a-OpenBLAS-0.2.19-LAPACK-3.7.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2017b-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018.08-OpenBLAS-0.3.3.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018a-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018b-OpenBLAS-0.3.1.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2019a-OpenBLAS-0.3.5.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2017b-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2018a-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2018b-OpenBLAS-0.3.1.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2019a-OpenBLAS-0.3.5.eb
done with --fix-deprecated-easyconfigs, no manual changes
required to avoid warnings when these easyconfigs are parsed because of changed made in easybuilders/easybuild-framework#2938
=> fix names of local variables in ScaLAPACK easyconfigs

easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.8-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-1.8.8-iccifort-2015.3.187-GNU-4.9.3-2.25.eb
I'm not sure how this happened, but a faulty checksum for OpenMPI 1.8.8 was added in #8016 somehow.
When you now download `openmpi-1.8.8.tar.gz`, you get the exact same tarball as the one we have which was downloaded on Sept 4th 2015.
Since both @migueldiascosta and myself verified the checksums using `eb --fetch` in a test report for #8016, I'm not quite sure what happened, maybe the source tarball that was served was temporarily corrupted somehow? 🤷‍♂
=> fix checksum in OpenMPI 1.8.8 easyconfigs

easybuild/easyconfigs/i/icc/icc-2016.0.109-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/icc/icc-2016.1.150-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/icc/icc-2016.2.181-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/icc/icc-2016.2.181-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/icc/icc-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/icc/icc-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/icc/icc-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/icc/icc-2017.0.098-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/icc/icc-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/icc/icc-2017.1.132-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/i/icc/icc-2017.2.174-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/i/icc/icc-2017.4.196-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2017.5.239-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2017.6.256-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2017.7.259-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2018.0.128-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2018.2.199-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/icc/icc-2018.3.222-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/i/icc/icc-2018.5.274-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/i/icc/icc-2019.0.117-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/i/icc/icc-2019.1.144-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/i/icc/icc-2019.2.187-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/i/icc/icc-2019.3.199-GCC-8.3.0-2.32.eb, easybuild/easyconfigs/i/icc/icc-system-GCC-system-2.29.eb
=> fix names of local variables in icc easyconfigs

easybuild/easyconfigs/i/ifort/ifort-2016.0.109-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.1.150-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.2.181-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.2.181-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2016.3.210-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.0.098-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.1.132-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/ifort/ifort-2017.1.132-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/i/ifort/ifort-2017.2.174-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/i/ifort/ifort-2017.4.196-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2017.5.239-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2017.6.256-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2017.7.259-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2018.0.128-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2018.1.163-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2018.2.199-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/i/ifort/ifort-2018.3.222-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/i/ifort/ifort-2018.5.274-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/i/ifort/ifort-2019.0.117-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/i/ifort/ifort-2019.1.144-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/i/ifort/ifort-2019.2.187-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/i/ifort/ifort-2019.3.199-GCC-8.3.0-2.32.eb, easybuild/easyconfigs/i/ifort/ifort-system-GCC-system-2.29.eb
=> fix names of local variables in ifort easyconfigs

easybuild/easyconfigs/p/PGI/PGI-15.10-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/p/PGI/PGI-15.7-GNU-4.9.2-2.25.eb, easybuild/easyconfigs/p/PGI/PGI-15.7-GNU-4.9.3-2.25.eb, easybuild/easyconfigs/p/PGI/PGI-16.1-CDK-GCC-4.9.2-2.25.eb, easybuild/easyconfigs/p/PGI/PGI-16.10-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/p/PGI/PGI-16.3-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/p/PGI/PGI-16.4-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/p/PGI/PGI-16.7-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/p/PGI/PGI-17.1-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/p/PGI/PGI-17.10-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/p/PGI/PGI-17.3-GCC-6.3.0-2.28.eb, easybuild/easyconfigs/p/PGI/PGI-17.4-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/p/PGI/PGI-18.1-GCC-7.2.0-2.29.eb, easybuild/easyconfigs/p/PGI/PGI-18.10-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/p/PGI/PGI-18.4-GCC-6.4.0-2.28.eb, easybuild/easyconfigs/p/PGI/PGI-18.7-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/p/PGI/PGI-19.1-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/p/PGI/PGI-19.4-GCC-8.2.0-2.31.1.eb
=> fix names of local variables in PGI easyconfigs

easybuild/easyconfigs/i/iimpi/iimpi-2016.00-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.01-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.02-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.02-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.03-GCC-4.9.3-2.25.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.03-GCC-5.3.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016.03-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2016b.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017.00-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017.01-GCC-5.4.0-2.26.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017.02-GCC-6.3.0-2.27.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017.09.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017a.eb, easybuild/easyconfigs/i/iimpi/iimpi-2017b.eb, easybuild/easyconfigs/i/iimpi/iimpi-2018.00.eb, easybuild/easyconfigs/i/iimpi/iimpi-2018.01.eb, easybuild/easyconfigs/i/iimpi/iimpi-2018.02.eb, easybuild/easyconfigs/i/iimpi/iimpi-2018.04.eb, easybuild/easyconfigs/i/iimpi/iimpi-2018a.eb, easybuild/easyconfigs/i/iimpi/iimpi-2018b.eb, easybuild/easyconfigs/i/iimpi/iimpi-2019.00.eb, easybuild/easyconfigs/i/iimpi/iimpi-2019.01.eb, easybuild/easyconfigs/i/iimpi/iimpi-2019.02.eb, easybuild/easyconfigs/i/iimpi/iimpi-2019.03.eb, easybuild/easyconfigs/i/iimpi/iimpi-2019a.eb, easybuild/easyconfigs/i/iimpi/iimpi-8.1.5-GCC-4.9.3-2.25.eb
=> fix names of local variables in iimpi easyconfigs

easybuild/easyconfigs/i/intel/intel-2016.00.eb, easybuild/easyconfigs/i/intel/intel-2016.01.eb, easybuild/easyconfigs/i/intel/intel-2016.02-GCC-4.9.eb, easybuild/easyconfigs/i/intel/intel-2016.02-GCC-5.3.eb, easybuild/easyconfigs/i/intel/intel-2016.03-GCC-4.9.eb, easybuild/easyconfigs/i/intel/intel-2016.03-GCC-5.3.eb, easybuild/easyconfigs/i/intel/intel-2016.03-GCC-5.4.eb, easybuild/easyconfigs/i/intel/intel-2016a.eb, easybuild/easyconfigs/i/intel/intel-2016b.eb, easybuild/easyconfigs/i/intel/intel-2017.00.eb, easybuild/easyconfigs/i/intel/intel-2017.01.eb, easybuild/easyconfigs/i/intel/intel-2017.02.eb, easybuild/easyconfigs/i/intel/intel-2017.09.eb, easybuild/easyconfigs/i/intel/intel-2017a.eb, easybuild/easyconfigs/i/intel/intel-2017b.eb, easybuild/easyconfigs/i/intel/intel-2018.00.eb, easybuild/easyconfigs/i/intel/intel-2018.01.eb, easybuild/easyconfigs/i/intel/intel-2018.02.eb, easybuild/easyconfigs/i/intel/intel-2018.04.eb, easybuild/easyconfigs/i/intel/intel-2018a.eb, easybuild/easyconfigs/i/intel/intel-2018b.eb, easybuild/easyconfigs/i/intel/intel-2019.00.eb, easybuild/easyconfigs/i/intel/intel-2019.01.eb, easybuild/easyconfigs/i/intel/intel-2019.02.eb, easybuild/easyconfigs/i/intel/intel-2019.03.eb, easybuild/easyconfigs/i/intel/intel-2019a.eb
=> fix names of local variables in intel easyconfigs

easybuild/easyconfigs/f/foss/foss-2016.04.eb, easybuild/easyconfigs/f/foss/foss-2016.06.eb, easybuild/easyconfigs/f/foss/foss-2016.07.eb, easybuild/easyconfigs/f/foss/foss-2016.09.eb, easybuild/easyconfigs/f/foss/foss-2016a.eb, easybuild/easyconfigs/f/foss/foss-2016b.eb, easybuild/easyconfigs/f/foss/foss-2017a.eb, easybuild/easyconfigs/f/foss/foss-2017b.eb, easybuild/easyconfigs/f/foss/foss-2018.08.eb, easybuild/easyconfigs/f/foss/foss-2018a.eb, easybuild/easyconfigs/f/foss/foss-2018b.eb, easybuild/easyconfigs/f/foss/foss-2019a.eb, easybuild/easyconfigs/g/gompi/gompi-2016.04.eb, easybuild/easyconfigs/g/gompi/gompi-2016.06.eb, easybuild/easyconfigs/g/gompi/gompi-2016.07.eb, easybuild/easyconfigs/g/gompi/gompi-2016.09.eb, easybuild/easyconfigs/g/gompi/gompi-2016a.eb, easybuild/easyconfigs/g/gompi/gompi-2016b.eb, easybuild/easyconfigs/g/gompi/gompi-2017a.eb, easybuild/easyconfigs/g/gompi/gompi-2017b.eb, easybuild/easyconfigs/g/gompi/gompi-2018.08.eb, easybuild/easyconfigs/g/gompi/gompi-2018a.eb, easybuild/easyconfigs/g/gompi/gompi-2018b.eb, easybuild/easyconfigs/g/gompi/gompi-2019a.eb, easybuild/easyconfigs/g/gompi/gompi-system-2.29.eb
=> fix names of local variables in gompi/foss easyconfigs

easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb, easybuild/easyconfigs/r/R/R-3.5.1-intel-2018b.eb, easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
Note: requires https://github.com/easybuilders/easybuild-framework/pull/2958 (without that, `eb` will complain with `Unknown checksum type` because it'll interpret the first checksum alternative as the checksum type)
=> add alternative checksums for nlme/mgcv/foreign/boot extensions in R 3.5.1 and 3.6.0 easyconfigs

easybuild/easyconfigs/n/NBO/NBO-7.0-intel-2017b.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.1.4-CUDA-9.0.176.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.2.13-CUDA-9.2.148.1.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.3.7-fosscuda-2018b.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.4.2-gcccuda-2019a.eb, easybuild/easyconfigs/n/NCL/NCL-6.4.0-intel-2017a.eb, easybuild/easyconfigs/n/NCL/NCL-6.4.0-intel-2017b.eb, easybuild/easyconfigs/n/NCL/NCL-6.4.0-intel-2018a.eb, easybuild/easyconfigs/n/NEdit/NEdit-5.5-Linux-x86.eb, easybuild/easyconfigs/n/NWChem/NWChem-6.6.revision27746-intel-2017a-2015-10-20-patches-20170814-Python-2.7.13.eb, easybuild/easyconfigs/n/NWChem/NWChem-6.6.revision27746-iomkl-2017a-2015-10-20-Python-2.7.12.eb, easybuild/easyconfigs/n/NWChem/NWChem-6.8.revision47-intel-2017b-2017-12-14-Python-2.7.14.eb, easybuild/easyconfigs/n/NWChem/NWChem-6.8.revision47-intel-2018a-2017-12-14-Python-2.7.14.eb, easybuild/easyconfigs/n/NetPIPE/NetPIPE-5.1-intel-2018a.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017a-HDF5-1.10.1.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017a-HDF5-1.8.19.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-foss-2017b-HDF5-1.8.19.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017a-HDF5-1.10.1.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017a-HDF5-1.8.18.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-intel-2017b-HDF5-1.8.19.eb, easybuild/easyconfigs/n/nodejs/nodejs-10.15.1-foss-2018b.eb, easybuild/easyconfigs/n/nodejs/nodejs-10.15.3-GCCcore-8.2.0.eb, easybuild/easyconfigs/n/novoalign/novoalign-3.09.00.eb, easybuild/easyconfigs/n/numpy/numpy-1.9.2-CrayGNU-2015.06-Python-2.7.9.eb, easybuild/easyconfigs/n/numpy/numpy-1.9.2-CrayGNU-2015.11-Python-2.7.9.eb
=> fix names of local variables in n/*/*.eb easyconfigs

easybuild/easyconfigs/r/R/Cairo-1.5-10.patch, easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb, easybuild/easyconfigs/r/R/Rtsne-0.15_icpc-wd308.patch, easybuild/easyconfigs/r/R/imager-0.41.2_icpc-wd308.patch, easybuild/easyconfigs/r/R/kohonen-3.0.8_intel-wd308.patch, easybuild/easyconfigs/r/R/locfit-1.5-9.1_Fix_logical_operators_icc.patch, easybuild/easyconfigs/r/R/tseries-0.10-47_ifort_explicit_free_form.patch, easybuild/easyconfigs/r/R/uroot-2.0-9.1_CUDA.patch
Still a WIP since the build of the `locfit` library causes an internal error for `icc`:
```
icc -I"/opt/easybuild/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/R/3.6.0/lib/R/include" -DNDEBUG   -I/opt/easybuild/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/imkl/2019.1.144/mkl/include -I/opt/easybuild/software/Compiler/GCCcore/8.2.0/X11/20190311/include -I/opt/easybuild/software/Compiler/GCCcore/8.2.0/Mesa/19.0.1/include -I/opt/easybuild/software/Compiler/GCCcore/8.2.0/libGLU/9.0.0/include -I/opt/easybuild/software/Compiler/GCCcore/8.2.0/cairo/1.16.0/include -I/opt/easybuild/software/Compiler/GCCcore/8.2.0/libreadline/8.0/include -I/opt/easybuild/software/Compiler/GCCcore/8.2.0/ncurses/6.1/include …
```
=> {lang}[intel/2019a] R v3.6.0

easybuild/easyconfigs/p/Perl/Perl-5.28.0-GCCcore-7.3.0.eb
see discussion in EasyBuild mailing list: https://lists.ugent.be/wws/arc/easybuild/2019-08/msg00029.html
=> add missing YAML extension to Perl 5.28.0 easyconfig (required by BioPerl scripts)

easybuild/easyconfigs/i/ieeg-cli/ieeg-cli-1.14.56.eb
=> use Java/11 wrapper as dependency for ieeg-cli rather than depending on a specific Java version

easybuild/easyconfigs/p/Python/Python-3.7-faulthandler.patch, easybuild/easyconfigs/p/Python/Python-3.7.2-GCCcore-8.2.0.eb, easybuild/easyconfigs/p/Python/Python-3.7.2-fix_faulthandler.patch
This pull request addresses the Issue: Python 3.7.4 segfault during `make test` #8771
Adding patch file and patch line for Python-3.7.2 for GCCcore-8.2.0
See https://bugs.python.org/issue21131#msg349768 for discussion.
Upstream commit at Python source is at
https://github.com/python/cpython/commit/1581d9c405f140491791a07dca3f6166bc499ec1
=> add patch to Python 3.7.2 easyconfig to fix faulthandler segfault

easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-foss-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-foss-2017b-Python-3.6.2.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-foss-2017b-Python-3.6.3.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-fosscuda-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-fosscuda-2017b-Python-3.6.3.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-3.6.3.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intelcuda-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intelcuda-2017b-Python-3.6.3.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-foss-2017b-Python-3.6.3.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-3.6.3.eb
matplotlib uses CPLUS_INCLUDE_PATH to search for include files, make sure it can find freetype.
=> matplotlib: Set CPLUS_INCLUDE_PATH for older matplotlib versions, newer already have it

easybuild/easyconfigs/e/EasyBuild/EasyBuild-3.9.4.eb, test/easyconfigs/easyconfigs.py
Required to fix `eb --install-latest-eb-release` which got broken by the change to `SYSTEM` in #8822, since `--install-latest-eb-release` pulls in the most recent `EasyBuild` easyconfig from `develop` branch...
(reported by @crphilipp on EasyBuild Slack channel)
=> stick to 'dummy' toolchain for now in easyconfig for latest EasyBuild 3.x

test/easyconfigs/easyconfigs.py
This reverts commit acd4f38a4c3f406a724d23e5388db7507f5d46fe (was added in #8369).
We'll leave the checksum requirement off for now, while we fix the local variable naming issues (see #8702, #8709, #8710, etc.)
This should be merged when that effort has been completed, certainly before `4.x` is collapsed into `develop`...
=> re-enable checksum requirement for easyconfig files touched in PRs

easybuild/easyconfigs/f/fastq-tools/fastq-tools-0.8-foss-2016b.eb, easybuild/easyconfigs/f/fastq-tools/fastq-tools-0.8-foss-2018b.eb
`autogen.sh` is run via `preconfigopts`, so `Autotools` is needed
currently fails if `autoreconf` is not available in OS
=> add missing Autotools build dep for fastq-tools

easybuild/easyconfigs/v/VMD/VMD-1.9.3-foss-2017b-Python-2.7.14.eb, easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018a-Python-2.7.14.eb, easybuild/easyconfigs/v/VMD/VMD-1.9.3-intel-2018b-Python-2.7.15.eb, easybuild/easyconfigs/v/VMD/VMD-1.9.3_plugins.patch
Also use the correct compiler and flags.
Depends on ~~https://github.com/easybuilders/easybuild-easyblocks/pull/1786~~
=> VMD: Add patch to plugins/Make-arch to use the correct tcl library version.

setup.cfg
Even though we're not using `setuptools` anymore in `setup.py`, people could still use `easy_install` (provided by `setuptools`).
We need to make sure that the easyconfigs is not installed as a zipped egg, since we need the easyconfig files + patches to be accessible separately...
=> avoid that easy_install installs easyconfigs package as a zipped egg

easybuild/easyconfigs/r/R-tesseract/R-tesseract-4.0-foss-2018b-R-3.5.1.eb
downloading of `sys` extension fails without this change...
=> consider archive source URL for all extensions in R-tesseract easyconfig

easybuild/easyconfigs/q/QIIME/QIIME-1.9.1.eb
It's unclear to me why we need to add `site-packages` to `$PYTHONPATH` now, and not before (see test reports in #3868)
=> fix issue where 'print_qiime_config.py -t' sanity check command fails for QIIME 1.9.1 because of subdir missing in $PYTHONPATH

easybuild/easyconfigs/g/GDAL/GDAL-3.0.0-foss-2019a-Python-2.7.15.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.7.2-foss-2019a-Python-2.7.15.eb, easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-GCCcore-8.2.0-Python-2.7.15.eb
This add GDAL 3.0.0 for Python 2.7.15 and fixes the Python 3.7.2 version. Without numpy the `_gdal_array` bindings are not generated (they live in `lib/python3.7/site-packages/osgeo`) - see https://gis.stackexchange.com/questions/153199/import-error-no-module-named-gdal-array
=> Add GDAL 3.0.0 for Python 2.7.15 and fix the Python 3.7.2 version

easybuild/easyconfigs/s/SALMON-TDDFT/SALMON-TDDFT-1.2.1-foss-2018b.eb, easybuild/easyconfigs/s/SALMON-TDDFT/SALMON-TDDFT-1.2.1-intel-2018b.eb
`SALMON` must be renamed in order to avoid conflicts with the already existing `Salmon` easyconfigs.
=> Rename SALMON to SALMON-TDDFT

easybuild/easyconfigs/p/Python/Python-3.7.0-foss-2018b.eb, easybuild/easyconfigs/p/Python/Python-3.7.0-intel-2018b.eb, easybuild/easyconfigs/p/Python/Python-3.7.0-iomkl-2018b.eb
This request simply adds the patch file that was approved for
add patch to Python 3.7.2 easyconfig to fix faulthandler segfault #8781
to the three Python 3.7.0 easyconfigs.
=> Adding faulthandler patches to Python 3.7.0 easyconfigs

easybuild/easyconfigs/g/gettext/gettext-0.19.8-GCCcore-4.9.3.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8-GCCcore-5.4.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016.04.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8-foss-2016b.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8-intel-2016b.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0-libxml2-2.9.7.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-6.4.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-7.3.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1-GCCcore-8.2.0.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.1.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8_fix-git-config.patch
cfr. problem reported by @sgowtham on Slack and via https://twitter.com/sgowtham/status/1175219728329166854
=> add patch for gettext 0.19.8* to avoid picking up global git config that could break the installation

test/easyconfigs/easyconfigs.py
works as expected, see #8999 where I squeezed in this change too by matter of proof of concept...
=> add check for http:// URLs in easyconfig files added/changed in PRs

easybuild/easyconfigs/l/lftp/lftp-4.8.4-GCCcore-6.4.0.eb
The builddependency libreadline pulls in ncurses/6.0, but that is also needed at runtime.
=> {tools}[GCCcore/6.4.0] bug fix, lftp requires ncurses as dependency

easybuild/easyconfigs/i/ICU/ICU-64.2-GCCcore-8.2.0.eb
It fails to build with system python 2.6 on CentOS 6.
=> ICU needs python 2.7+ to build, so add that as builddependency

easybuild/easyconfigs/a/AdapterRemoval/AdapterRemoval-2.3.1-foss-2018b.eb
I changed the `easyblock` to `ConfigureMake` because the `Makefile` does actually have a `install` target.
=> {bio}[foss/2018b] AdapterRemoval v2.3.1

easybuild/easyconfigs/a/Anaconda2/Anaconda2-2018.12.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-2019.03.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-2019.07.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-4.0.0.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-4.2.0.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-4.4.0.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.0.1.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.1.0.eb, easybuild/easyconfigs/a/Anaconda2/Anaconda2-5.3.0.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-2018.12.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.03.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-2019.07.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-4.0.0.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-4.2.0.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-4.4.0.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-5.0.1.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-5.1.0.eb, easybuild/easyconfigs/a/Anaconda3/Anaconda3-5.3.0.eb, easybuild/easyconfigs/m/Miniconda2/Miniconda2-4.3.21.eb, easybuild/easyconfigs/m/Miniconda2/Miniconda2-4.6.14.eb, easybuild/easyconfigs/m/Miniconda2/Miniconda2-4.7.10.eb, easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.4.10.eb, easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.5.12.eb, easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.6.14.eb, easybuild/easyconfigs/m/Miniconda3/Miniconda3-4.7.10.eb
`Anaconda` URLs changed from `continuum.io` to `anaconda.com`.
I also changed the homepage of `Miniconda` to a documentation site specific to `Miniconda`, maybe we can also use the description from this site instead of the same description as the one for `Anaconda`.
=> fix urls for Anaconda and Miniconda

easybuild/easyconfigs/s/savvy/savvy-1.3.0-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/s/shrinkwrap/shrinkwrap-1.0.0-beta-GCCcore-8.2.0.eb
The toolchain for `savvy` is `toolchain = {'name': 'GCC', 'version': '8.2.0-2.31.1'}` as it depends on `HTSlib` which has that toolchain - otherwise I'd have put them both at `GCCcore`.
=> {data}[GCC/8.2.0-2.31.1] savvy v1.3.0 + shrinkwrap v1.0.0-beta

.github/workflows/unit_tests.yml
Adding a configuration file to run the easyconfigs unit tests natively in GitHub, just like for framework (https://github.com/easybuilders/easybuild-framework/pull/3039) and easyblocks (https://github.com/easybuilders/easybuild-easyblocks/pull/1844), with the prospect of switching away from Travis CI...
Works as expected, see https://github.com/boegel/easybuild-easyconfigs/commit/61bca035d914e4adce48e4c7172358714b4144c7/checks?check_suite_id=299862067
=> add GitHub Actions workflow to run easybuild-easyconfigs test suite

test/easyconfigs/easyconfigs.py
It turns out that the guards that are supposed to avoid that the easyconfig files are parsed & ordered (via `resolve_dependencies`) multiple times don't work, because `self.parsed_easyconfigs` and `self.ordered_specs` refer to *instance* variables.
It seems that `unittest` creates a new instance of `EasyConfigTest` for every test being run, so checking `self.parsed_easyconfigs` and `self.ordered_specs` to cache things between tests is totally useless.
By switching to using the `EasyConfigTest.parsed_easyconfigs` and `EasyConfigTest.ordered_specs` *class* variables, which survive across instances, we're effectively caching parsed easyconfigs as intended...
This significantly speeds up the test suite (in GitHub CI):
* with Python 2.7: ~25% speedup (~9m to ~7m)
* with Python 3.5: ~60% (~17m …
=> speed up easyconfigs test suite by avoiding re-parsing and re-ordering of easyconfigs

easybuild/easyconfigs/i/ImageJ/ImageJ-1.51k.eb
This is mostly about fixing the typo (`$EBROOTIMAGE` -> `$EBROOTIMAGEJ`) highlighted by @JackPerdue in #9197, but I also fixed the `Java` dep and the name of the `morphology.zip` source file to avoid name clashes with updated versions (see also #9197)
=> apply fixes to ImageJ 1.51k easyconfig

.travis.yml
More test configurations are run in GitHub CI, where test budget is significantly higher.
=> only run easyconfigs test suite with Python 2.7 & 3.6 + Lmod 7 in Travis CI

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-fosscuda-2019b-Python-3.7.4.eb
cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/9254#discussion_r346702032
cc @Flamefire
requires ~~#9280~~ (protobuf) + ~~#9294~~ (git nodocs)
=> use protobuf 3.10.0 as build dep for TensorFlow 2.0.0 w/ fosscuda/2019b + use nodocs variant of git as build dep

easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-GCCcore-8.3.0.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb
- Qt5 depends on JasPer, which is missing from the spec.
- Add JasPer for GCCcore-8.3.0.
- Resolves #9274
=> Fix #9274, Qt5/5.13.1-GCCcore-8.3.0 depends on JasPer.

easybuild/easyconfigs/p/prokka/prokka-1.13.7-gompi-2019a.eb
Without `prokka --setupdb`, trying to use `prokka` fails with:
```
The sequence databases have not been indexed. Please run 'prokka --setupdb' first.
```
Changed toolchain to `gompi/2019a` since that's the toolchain used for `BLAST+`.
This is changing an existing easyconfig, which is only included in `develop` currently (was contributed in #9175).
also added custom sanity check commands...
=> fix prokka 1.13.7 easyconfig: run 'prokka --setupdb' after installation & add missing BLAST+ dep

easybuild/easyconfigs/h/h5py/h5py-2.10.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/h/h5py/h5py-2.10.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/h/h5py/h5py-2.10.0-intel-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-fosscuda-2019b-Python-3.7.4.eb
fixes #9395 (see also motivation there)
We usually don't make changes like this, but this one is still acceptable since there are no `h5py` easyconfigs using a `2019b` toolchain included in an EasyBuild release yet (only in `develop`), and all related PRs were merged fairly recently (see #9248, #9307 for `h5py`, #9382 + #9384 for TensorFlow 1.15.0 + #9254 for TensorFlow 2.0.0)
cc @Flamefire, @branfosj
=> bump h5py to 2.10.0 in 2019b easyconfigs

easybuild/easyconfigs/p/Python/Python-2.7.13-GCCcore-6.3.0-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.14-GCCcore-6.4.0-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-7.2.0-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-7.3.0-bare.eb, easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb, easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0.eb, easybuild/easyconfigs/p/Python/Python-3.7.2-GCCcore-8.2.0.eb, easybuild/easyconfigs/p/Python/Python-3.7.4-GCCcore-8.3.0.eb
It's required for pip install that involves compilation.
edit: fixes #9227
=> Python: Promote binutils to a runtime dependency for GCCcore based builds.

easybuild/easyconfigs/s/Spark/Spark-2.4.0-Hadoop-2.7-Java-1.8.eb, easybuild/easyconfigs/s/Spark/Spark-2.4.0-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/s/Spark/Spark-2.4.0-intel-2018b-Hadoop-2.7-Java-1.8-Python-3.6.6.eb, easybuild/easyconfigs/s/Spark/Spark-2.4.0-intel-2018b-Python-2.7.15.eb, easybuild/easyconfigs/s/Spark/Spark-2.4.0-intel-2018b-Python-3.6.6.eb
`$SPARK_HOME` is commonly relied on by that stuff that depends on `Spark`, so let's define it too next to `$EBROOTSPARK`...
=> define $SPARK_HOME in generated module file for Spark 2.4.0

easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-foss-2019a-Python-2.7.15.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-fosscuda-2019a-Python-2.7.15.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-intel-2019a-Python-2.7.15.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.4-intelcuda-2019a-Python-2.7.15.eb
For matplotlib 2.2.4 versions.
=> matplotlib 2.2.4: fix problems with mpl_toolkits namespace and Python 2

easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-foss-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-fosscuda-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intel-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.0-intelcuda-2017b-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.1-intel-2017b-Python-2.7.14.eb
For matplotlib 2.1.0 and 2.1.1 versions.
=> matplotlib 2.1.[01]: fix problems with mpl_toolkits namespace and Python 2

easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-foss-2018a-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.1.2-intel-2018a-Python-2.7.14.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.3-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.3-fosscuda-2018b-Python-2.7.15.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-2.2.3-intel-2018b-Python-2.7.15.eb
For matplotlib 2.1.2 and 2.2.3 versions.
=> matplotlib [2.1.2, 2.2.3]: Fix problems with mpl_toolkits namespace and Python 2

easybuild/easyconfigs/s/Spark/Spark-2.4.0-intel-2018b-Hadoop-2.7-Java-1.8-Python-3.6.6.eb
Installation fails now due to auto-downloaded dependency being detected (because `download_dep_fail` is set via `exts_default_options`).
When this easyconfig was added it went undetected because of a bug (which was fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1530)...
=> add missing 'wheel' extensions to Spark 2.4.0 easyconfig using intel/2018b toolchain

easybuild/easyconfigs/p/Python/Python-2.7.15-GCCcore-8.2.0.eb, easybuild/easyconfigs/p/Python/Python-2.7.16-GCCcore-8.3.0.eb
This was already fixed in the Python 3.7.2 & 3.7.4 easyconfigs in #9329, but was overlooked for Python 2.7.{15,16}...
=> add missing wcwidth extension to Python 2.7.15 + 2.7.16 easyconfigs & enable 'pip check' in sanity check

.github/workflows/unit_tests.yml
Since this morning, "sudo apt-get update" is failing in GitHub Actions:
```
Reading package lists...
W: Conflicting distribution: https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic InRelease (expected bionic but got stable)
E: Repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic InRelease' changed its 'Origin' value from 'microsoft-ubuntu-bionic-prod bionic' to 'vscode stable'
E: Repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic InRelease' changed its 'Label' value from 'microsoft-ubuntu-bionic-prod bionic' to 'vscode stable'
...
##[error]Process completed with exit code 100.
```
We don't actually really need it, so let's comment it out (at least for now).
I've contacted GitHub Support on this...
=> disable running of 'sudo apt-get update' in GitHub CI config, since it's failing (and we don't really need it)

test/easyconfigs/easyconfigs.py
Support for running `pip check` during the sanity check to ensure that all required Python packages are installed was added in EasyBuild v4.1.0 (see #1853).
We should start requiring it in contributed easyconfigs, since it can prevent shipping broken easyconfigs (see https://github.com/easybuilders/easybuild-easyconfigs/issues/9306 for example).
You can enable the running of `pip check` either via:
```python
sanity_pip_check = True
```
or
```python
exts_default_options = {'sanity_pip_check': True}
```
(it can also be enabled for individual extensions, but there's little point in doing that imho, so no need to cover that in the check here)
=> require that sanity_pip_check is enabled in new/changed easyconfigs

easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.2.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.29.1_fix-zip-d-on-power.patch, easybuild/easyconfigs/b/Bazel/Bazel-1.1.0-GCCcore-8.3.0.eb
- Stay with JDK8 (Java 1.8) as stated by Bazel docus
- Include patch from https://github.com/bazelbuild/bazel/issues/9263
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/9450
=> fix build of recent Bazel versions on Power9 + stick to Java/1.8 as dependency

easybuild/easyconfigs/i/IPython/IPython-7.7.0-foss-2019a-Python-3.7.2.eb, easybuild/easyconfigs/i/IPython/IPython-7.7.0-fosscuda-2019a-Python-3.7.2.eb, easybuild/easyconfigs/i/IPython/IPython-7.7.0-intel-2019a-Python-3.7.2.eb, easybuild/easyconfigs/i/IPython/IPython-7.9.0-foss-2019b-Python-3.7.4.eb
`pip check` fails because `jupyter_contrib_core` was not added when `jupyter_nbextensions_configurator` was added in #9133
=> add missing jupyter_contrib_core extension for IPython 7.7.0+ + consistently include jupyter_nbextensions_configurator extension

easybuild/easyconfigs/m/Meld/Meld-3.20.1-GCCcore-8.2.0-Python-3.7.2.eb, test/easyconfigs/easyconfigs.py
Meld is really good when resolving merge conflicts with git. This EC (finally) allows to build it with EB.
Usage suggestion: Add the following in your gitconfig:
```
[merge]
tool = meld
[mergetool "meld"]
cmd = meld --auto-merge \"$LOCAL\" \"$BASE\" \"$REMOTE\" --output \"$MERGED\"
trustExitCode = false
[mergetool]
keepBackup = false
```
Requires
Notes:
- meld does not support `pip install` but will support meson
- a good sanity check is `meld --help` which checks dependent packages but if X-fowarding is not set up then it fails with:
```
2019-12-20 12:12:59,639 CRITICAL Gtk: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
File "..../meld", line 287, in <module>
setup_resources()
File "..../meld", line 193, in setup_resources …
```
=> {devel}[GCCcore/8.2.0] Meld v3.20.1 w/ Python 3.7.2

easybuild/easyconfigs/p/plotly.py/plotly.py-4.4.1-intel-2019b.eb
In #9480 the `'plotly'` was replaced with `name` last-minute on @verdurin's request, but this broke the easyconfig since `name = 'plotly.py`, which makes EasyBuild look for a non-existing source tarball named `plotly.py-4.4.1.tar.gz`...
=> fix name for plotly extension in plotly.py v4.4.1 easyconfig

easybuild/easyconfigs/c/cyvcf2/cyvcf2-0.11.5-foss-2019a.eb, easybuild/easyconfigs/c/cyvcf2/cyvcf2-0.11.5-intel-2019a.eb
These easyconfigs fail to install because auto-downloaded dependencies are detected (enabled by default in `PythonBundle`):
```
== FAILED: Installation ended unsuccessfully (build directory: /tmp/vsc40023/easybuild_build/cyvcf2/0.11.5/foss-2019a): build failed (first 300 chars): Sanity check failed: extensions sanity check failed for 1 extensions: cyvcf2
failing sanity check for 'cyvcf2' extension: found one or more downloaded dependencies: Downloading https://files.pythonhosted.org/packages/08/0f/7877fc42fff0b9d70b6442df62d53b3868d3a6ad1b876bdb54335b30ff23/coloredlogs-10.0 (took 2 min 33 sec)
```
This went undetected until now because `monotonic` (which is only strictly needed with Python < 3.3) was available system-wide for Python 2.7, but those Python packages are now ignored thanks to …
=> fix broken easyconfigs for cyvcf2 v0.11.5 by adding missing 'monotonic' extension

easybuild/easyconfigs/g/gradunwarp/gradunwarp-1.1.0-foss-2019a-HCP-Python-2.7.15.eb
As suggested in https://github.com/easybuilders/easybuild-easyconfigs/pull/9614#discussion_r364658088, we're now using PIP
=> {bio}[foss/2019a] gradunwarp 1.1.0 (HCP fork): Use PIP to install

easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb, easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb, easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
Similar to MASS (https://github.com/easybuilders/easybuild-easyconfigs/pull/9621), the maintainers of RDA changed a tiny bit in their R package, without changing the version:
```
diff -ur rda2/rda/DESCRIPTION rda/rda/DESCRIPTION
--- rda2/rda/DESCRIPTION	2018-07-21 17:12:01.000000000 +0000
+++ rda/rda/DESCRIPTION	2020-01-01 15:58:30.000000000 +0000
@@ -17,3 +17,5 @@
X-CRAN-Original-Maintainer: Rob Tibshirani <tibs@stanford.edu>
X-CRAN-Comment: Orphaned and corrected on 2018-07-21 as check problems
were not corrected despite reminders.
+ .
+ BioC:MLInterfaces depends on this
diff -ur rda2/rda/MD5 rda/rda/MD5
--- rda2/rda/MD5	2018-07-21 17:12:01.000000000 +0000
+++ rda/rda/MD5	2020-01-01 15:58:30.000000000 +0000
@@ -1,4 +1,4 @@
-25d1293d678d5fbdf2bb20bf6fc64280 *DESCRIPTION …
```
=> {lang}[foss/2019a] R 3.6.0: Add second checksum for rda_1.0.2-2.1.tar.gz

easybuild/easyconfigs/m/MRtrix/MRtrix-3.0-rc-20191217-foss-2019b-Python-2.7.16.eb, easybuild/easyconfigs/m/MRtrix/MRtrix-3.0-rc-20191217-foss-2019b-Python-3.7.4.eb
see discussion in https://github.com/MRtrix3/mrtrix3/issues/1834
MRtrix 3.0_RC4 is only in `develop` (see #9535), so OK to change imho...
=> use latest master as release candidate of MRtrix 3.0 (since 3.0_RC4 is not an official release)

easybuild/easyconfigs/a/ant/ant-1.10.2-fix-doclint-error.patch, easybuild/easyconfigs/a/ant/ant-1.10.5-Java-1.8.eb, easybuild/easyconfigs/a/ant/ant-1.10.6-Java-1.8.eb, easybuild/easyconfigs/a/ant/ant-1.10.7-Java-11.eb
10.5 binary distribution is no longer available, 10.6/7 have https errors with wrong hostname as the url redirects to the new one
=> fix source URLs for ant v1.10.5 - v1.10.7

easybuild/easyconfigs/p/pyfits/pyfits-3.5-intel-2018b-Python-2.7.15.eb
fix for `pyfits` that was added in #7273...
It fails now due to a detected auto-downloaded extension `d2to1`, which was probably masked before because `d2to1` was available elsewhere (see also https://github.com/easybuilders/easybuild-easyblocks/pull/1891)
=> fix pyfits easyconfig by adding missing d2to1 extension

easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.4-intel-2017b.eb, easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-intel-2018a.eb, easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.5-iomkl-2018a.eb, easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.7-GCCcore-8.2.0.eb, easybuild/easyconfigs/m/MariaDB-connector-c/MariaDB-connector-c-2.3.7-foss-2018b.eb
The Download links are no longer working, they use a mirror now. The Github links are more reliable hence I replaced them. I verified that there is no diff in the extracted sources, only the folder name has changed hence the new checksum. No conflict with old files though as the filename changed too
=> use Github to download releases for MariaDB-connector-c

easybuild/easyconfigs/a/autopep8/autopep8-1.4.4-intel-2018a-Python-3.6.4.eb, easybuild/easyconfigs/p/pycodestyle/pycodestyle-2.5.0-intel-2018a-Python-3.6.4.eb
As requested by developers but maybe it's felt these should be installed in the underlying OS's Python installation rather than using EasyBuild.
=> New EB files for autopep8 and pycodestyle for Python/3.6.4-intel-2018a

easybuild/easyconfigs/s/spatialreg/spatialreg-1.1-5-foss-2019b-R-3.6.2.eb
=> {math}[foss/2019b] spatialreg v1.1-5

easybuild/easyconfigs/s/statsmodels/statsmodels-0.11.0-foss-2019b-Python-3.7.4.eb
Required for #9805
Providing _foss_ version of existing application
=> {math}[foss/2019b] statsmodels v0.11.0 w/ Python 3.7.4

easybuild/easyconfigs/b/Blosc/Blosc-1.17.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/l/LZO/LZO-2.10-GCCcore-8.3.0.eb, easybuild/easyconfigs/n/numexpr/numexpr-2.7.1-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-fix-libs.patch, easybuild/easyconfigs/p/PyTables/PyTables-3.6.1-foss-2019b-Python-3.7.4.eb
=> {data,devel,lib,math}[GCCcore/8.3.0,foss/2019b] Blosc v1.17.1, LZO v2.10, numexpr v2.7.1, ... w/ Python 3.7.4

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8-GCC-9.2.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.8_fix-dscal-inline-asm.patch
The leaq instructions in dscal_kernel_inc_8 modify x and x1 so they
must be declared as input/output constraints, otherwise the compiler
may assume the corresponding registers are not modified.
Fixes #9861
=> OpenBLAS 0.3.8: Fix inline asm in dscal: mark x, x1 as clobbered.

easybuild/easyconfigs/r/R/R-3.6.2-foss-2019b.eb, easybuild/easyconfigs/r/R/R-3.6.2-fosscuda-2019b.eb
Checksum for LaplacesDemon CRAN package has changed. Probably some changes considered minor by the authors, and "not enough" for a version bump.
=> add alternate checksum for LaplacesDemon in R 3.6.2 easyconfigs

easybuild/easyconfigs/l/LLVM/LLVM-8.0.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/n/numba/llvmlite-0.31.0_fix-ffi-Makefile.patch, easybuild/easyconfigs/n/numba/numba-0.47.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/s/scVelo/scVelo-0.1.24-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/s/scVelo/scanpy-1.4.5.post2_fix_h5py_version.patch, easybuild/easyconfigs/s/scVelo/scanpy-1.4.5.post2_fix_matplotlib_version.patch, test/easyconfigs/easyconfigs.py
Requires:
~~#9802~~
~~#9803~~
~~#9804~~
ScanPy (required by scVelo) requires Numba, which will only compile with LLVM versions 7 & 8 (not the version 9 that's already in _GCCcore-8.3.0_).
=> {bio,compiler,lang}[foss/2019b] scVelo v0.1.24, numba v0.47.0, LLVM v8.0.1 w/ Python 3.7.4

easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-foss-2019b.eb, easybuild/easyconfigs/p/PETSc/PETSc-3.12.4-intel-2019b.eb
was removed in #9880 since METIS is a dep of MUMPS, but `SLEPc` build is broken if `PETSc` doesn't list `METIS` as direct dep...
=> add back direct dependency on METIS in PETSc 3.12.4 easyconfigs

easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-8.3.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-9.1.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-9.2.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.32-readd-avx512-vmovd.patch, easybuild/easyconfigs/b/binutils/binutils-2.32.eb
This reverts parts of
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;h=704a705d7aaab8041df76e2981e2a1efc014aad0
from H.J. Lu <hjl.tools@gmail.com> for compatibility with the Intel compiler
Fixes #8003
=> binutils: Revert removal of AVX512 vmovd with 64-bit operands

.github/workflows/unit_tests.yml, .travis.yml
Downloading the sources for `bzip2-1.0.6.eb` is currently troublesome, so switching to M4 (under the assumption that the GNU software mirrors are less likely to be flaky).
=> use M4-1.4.18.eb for test installation in easyconfigs test suite

easybuild/easyconfigs/r/RDFlib/RDFlib-4.2.2-GCCcore-8.3.0.eb
=> stick to GCCcore toolchain for RDFlib, no need for a full toolchain

easybuild/easyconfigs/b/Bazel/Bazel-0.20.0-GCCcore-8.2.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.25.2-GCCcore-8.2.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.2.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.26.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.2.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.29.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/b/Bazel/Bazel-1.1.0-GCCcore-8.3.0.eb
fixes #9962
requires ~~#9958~~ + ~~#9971~~ for `Zip`
=> add Zip as build dependency for recent Bazel versions

easybuild/easyconfigs/f/FFTW/FFTW-3.3.8-gompi-2020a-rc3.eb, easybuild/easyconfigs/f/foss/foss-2020a-rc3.eb, easybuild/easyconfigs/g/gompi/gompi-2020a-rc3.eb, easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2020a-rc3.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-GCC-9.2.0.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.1.0-gompi-2020a-rc3.eb
sticking to `foss/2020a-rc3` for now since release of GCC 9.3.0 seems imminent (see https://gcc.gnu.org/ml/gcc/2020-02/msg00240.html)
=> switch to final release of OpenMPI 4.0.3 for foss/2020a-rc3

easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb
This is a silly PR, but it'll serve as a test case for the fix for https://github.com/easybuilders/easybuild-framework/issues/3233 (via https://github.com/boegelbot/easybuild-easyconfigs/pull/1)...
edit: well, probably not, since getting the fix in https://github.com/easybuilders/easybuild-framework/pull/3234 covered by the tests is not so straightforward... Still, it's a valid change/fix, so good to go...
=> use https in homepage/source_urls of zlib-1.2.11.eb

.github/workflows/unit_tests.yml, .travis.yml
I'll open a follow-up PR so we don't forget to roll this back...
=> temporarily limit test configurations during 2020a sprint

easybuild/easyconfigs/i/iccifort/iccifort-2020.0.166-GCC-9.2.0.eb, easybuild/easyconfigs/i/iimpi/iimpi-2020.00.eb, easybuild/easyconfigs/i/impi/impi-2019.6.166-iccifort-2020.0.166-GCC-9.2.0.eb, easybuild/easyconfigs/i/intel/intel-2020.00.eb
using the versionsuffixed iccifort should help to merge
in a new iccifort-2020.0.166.eb that uses GCC 9.3.0
(#10079).
=> intel-2020.00: use iccifort-2020.0.166-GCC-9.2.0.eb

easybuild/easyconfigs/d/double-conversion/double-conversion-3.0.3-foss-2018a.eb, easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.4-GCCcore-8.2.0.eb, easybuild/easyconfigs/d/double-conversion/double-conversion-3.1.4-GCCcore-8.3.0.eb
Reasoning:   
Using Scons (like currently done) will be using the system compiler instead of the toolchain set in the EasyConfig. This will completely fail during compilation when there is no system compiler (namely g++) installed. It may also fail, when this is linked into another application using a different compiler or compiler version due to different flags, ABI etc.
Furthermore Scons doesn't install the headers so that was done manually but to a wrong subdirectory. The correct path is `include/double-conversion/double-conversion.h` not  `include/double-conversion.h`. As the result dependents likely won't find it resulting in either build errors (e.g. when using plain `#include <double-conversion/double-conversion.h>`) or silently using an alternative version. E.g. Qt has a version …
=> [double-conversion] Use CMake for building

easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-foss-2020a.eb, easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-intel-2020a.eb
Based on information from https://elpa.rzg.mpg.de the version 2019.11.001 is the latest. Thus, only toolchain is changed.
=> ELPA for 2020a

easybuild/easyconfigs/l/libwebp/libwebp-1.0.2-GCCcore-8.2.0.eb
`libwebpmux` is required for `GraphicsMagick` (it required `webp/mux.h`)
=> configure libwebp to also install libwebpmux

easybuild/easyconfigs/m/MathGL/MathGL-2.4.1-foss-2018a.eb
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/9640
=> [MathGL] Don't use MPI cxx during build

.github/workflows/unit_tests.yml
seems like re-enabling `apt-get update` in #10336 is causing trouble, so disabling it again....
=> disable apt-get update (again) in GA workflow

.github/workflows/unit_tests.yml
This should help in dealing with the "`Could not connect to azure.archive.ubuntu.com`" issues that have been popping up...
=> use apt-spy2 before using apt in GitHub Actions

easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb, easybuild/easyconfigs/r/R/R-3.6.0-fosscuda-2019a.eb, easybuild/easyconfigs/r/R/R-3.6.0-intel-2019a.eb
=> also add alternative checksum for LaplacesDemon extension in R 3.6.0 easyconfigs

easybuild/easyconfigs/r/RepeatMasker/RepeatMasker-4.0.9-p2-gompi-2019b-HMMER.eb
Without this, sanity check fails with `bad interpreter: No such file or directory` if the installation prefix is too long, because the script has the full path to `perl` in the shebang...
=> fix Perl shebang for RepeatMasker

easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.13.1_fix-mantissatable.patch
Add patch for Qt5-5.13.1-GCCcore-8.3.0.eb fixing #10332, i.e. undefined reference to 'qfloat16::mantissatable' in Qt5.13.
=> Fix undefined reference to 'qfloat16::mantissatable' in Qt5-5.13.1-GCCcore-8.3.0

easybuild/easyconfigs/f/flex/flex-2.6.4.eb
make flex/2.6.4 depend on Bison 3.3.2 to streamline the bootstrap process of a toolchain
Currently flex depends on an older Bison which results in Bison and older M4 being built twice as first steps in the toolchain creation process
https://i.imgur.com/r9yVGpM.png
=> use Bison 3.3.2 as build dep for flex 2.6.4

easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.3-foss-2019b.eb, easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.3-intel-2019b.eb, easybuild/easyconfigs/a/AUGUSTUS/AUGUSTUS-3.3.3_fix-hardcoding.patch, easybuild/easyconfigs/b/BCFtools/BCFtools-1.10.2-iccifort-2019.5.281.eb, easybuild/easyconfigs/l/lpsolve/lpsolve-5.5.2.5-iccifort-2019.5.281.eb
fixed patch is required to make installation with `intel/2019b` work, since otherwise `g++` is used with compiler options for `icpc`...
=> {bio}[intel/2019b] AUGUSTUS v3.3.3 & lpsolve/BCFtools deps (+ fixed patch)

easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-gompi-2020a.eb, easybuild/easyconfigs/b/Boost.Python/Boost.Python-1.72.0-iimpi-2020a.eb, easybuild/easyconfigs/g/GATK/GATK-4.1.5.0-GCCcore-9.3.0-Java-11.eb, easybuild/easyconfigs/m/Mako/Mako-1.1.2-GCCcore-9.3.0.eb, easybuild/easyconfigs/p/PyYAML/PyYAML-5.3-GCCcore-9.3.0.eb, easybuild/easyconfigs/p/Python/Python-2.7.18-GCCcore-9.3.0.eb, easybuild/easyconfigs/s/SCons/SCons-3.1.2-GCCcore-9.3.0.eb
It's time to step into the future with Python 2.7.18...
(updated extensions also done for Python 3.8.2 in #10456)
=> update to Python 2.7.18 + minor updates for extensions

easybuild/easyconfigs/i/impi/impi-2019.7.217-iccifort-2020.1.217.eb
@lexming should have been part of #10280 ;)
=> add URL in comment to explain why UCX is included as a dep for impi 2019.7.217

easybuild/easyconfigs/o/OTF2/OTF2-2.2-GCCcore-8.2.0.eb, easybuild/easyconfigs/o/OTF2/OTF2-2.2-GCCcore-8.3.0.eb, easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompi-2019a.eb
As discussed in https://github.com/easybuilders/easybuild-easyconfigs/pull/10397#issuecomment-619363052 those should be runtime dependencies as they are used at runtime
CCing @lexming as he merged #10397
=> [OTF2 & Score-P] Move builddependencies to dependencies

easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-foss-2019b-Python-3.7.4-kokkos.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-3Mar2020-intel-2019b-Python-3.7.4-kokkos.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-foss-2019b-Python-3.7.4-kokkos.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos.eb
since https://github.com/easybuilders/easybuild-easyblocks/pull/1997, and since these are part of the toolchain they should not be included as dep.
=> remove FFTW dependencies from LAMMPS easyconfigs, no longer needed (MKL can be used too now)

easybuild/easyconfigs/h/h5py/h5py-2.10.0-foss-2020a-Python-3.8.2.eb, easybuild/easyconfigs/h/h5py/h5py-2.10.0-intel-2020a-Python-3.8.2.eb, easybuild/easyconfigs/h/h5py/h5py-2.10.0_fix-import-mpi.patch, easybuild/easyconfigs/y/yaff/yaff-1.6.0-foss-2020a-Python-3.8.2.eb, easybuild/easyconfigs/y/yaff/yaff-1.6.0-intel-2020a-Python-3.8.2.eb
This fix was also proposed upstream, see https://github.com/h5py/h5py/pull/1544 .
It may get merged in slightly different form since the `h5py` developers don't seem to favor the top-level `try` + `import mpi4py`, but it's good enough to fix the h5py 2.10.0 release we're using.
I've verified that the Parallel HDF5 capabilities of `h5py` are preserved with this patch (using the example from https://docs.h5py.org/en/stable/mpi.html.
This should unblock #10191...
=> add patch for h5py 2.10.0 with 2020a toolchains to avoid MPI_Init at import

easybuild/easyconfigs/c/Cbc/Cbc-2.10.3-foss-2018b.eb, easybuild/easyconfigs/c/Cgl/Cgl-0.60.2-foss-2018b.eb, easybuild/easyconfigs/c/Clp/Clp-1.17.3-foss-2018b.eb, easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.3-GCCcore-7.3.0.eb, easybuild/easyconfigs/c/CoinUtils/CoinUtils-2.11.3-foss-2018b.eb, easybuild/easyconfigs/o/Osi/Osi-0.108.5-GCCcore-7.3.0.eb, easybuild/easyconfigs/o/Osi/Osi-0.108.5-foss-2018b.eb
This PR fixes several issues with CoinUtils and packages depending on it
* None of these packages is actually using the dependencies established in the easyconfig. All libraries are being rebuild again within each package, which translates to having, for instance, the `libCoinUtils.so` file replicated in the install path of CoinUtils, Osi, Clp, Cgl, and Cbg.
* Most of these packages support BLAS/LAPACK but were not linking to it. Easyconfigs in `foss/2018b` are fixed and new ones are added into `foss` for those that were not in it.
* These packages also support MPI, so I added the corresponding `toolchainopts`
* Easyconfigs with GLPK as a dependency were not using it. Moreover, the packages that do support GLPK cannot use the GLPK installation from Easybuild because it is either to high a …
=> {math}[foss/2018b] fix dependencies and configuration of CoinUtils ecosystem

easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.5.2-gompi-2020a.eb
Build fails in systems where m4 is not there by default
=> Fix missing m4

easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.24-intel-2017a.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.25-foss-2017b.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.25-intel-2017b.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.2.0.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-8.3.0.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-GCCcore-9.3.0.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2018a.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-foss-2018b.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2017b.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018a.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-intel-2018b.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26-iomkl-2018b.eb
UDUNITS provides ftp and https sources. Converting the source URLs to use https
remotes where possible.
**NOTE:** I was not able to find the `udunits-2.2.20.tar.gz` sources (FTP or HTTPS)
Should `UDUNITS-2.2.20-foss-2016a.eb` and `UDUNITS-2.2.20-intel-2016b.eb` be removed?
Currently used sources and their HTTP response code:
- ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz **550**
- https://www.unidata.ucar.edu/downloads/udunits/udunits-2.2.24.tar.gz 200
- https://www.unidata.ucar.edu/downloads/udunits/udunits-2.2.25.tar.gz 200
- https://www.unidata.ucar.edu/downloads/udunits/udunits-2.2.26.tar.gz 200
=> update UDUNITS source_urls to https sources

easybuild/easyconfigs/r/R/R-3.6.0-foss-2019a.eb
I used #9789 as a reference...
=> add alternative checksum for pkgmaker, doRNG, cobs extension in R 3.6.0

easybuild/easyconfigs/r/ReFrame/ReFrame-3.0.eb
The recipe needs this fix: ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2075~~ for the `PythonBundle` easyblock to work correctly.
=> {devel}[system] ReFrame v3.0

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.9-GCC-9.3.0.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.9_fix-lapack_h.patch
OpenBLAS 0.3.9 has a bug which does not allow to use LAPACK functionality from C++:
https://github.com/xianyi/OpenBLAS/issues/2510
https://github.com/xianyi/OpenBLAS/issues/2600
The fix is a relatively straightforward change of the lapack.h header file:
https://github.com/xianyi/OpenBLAS/pull/2512/files
Include that patch here so that the foss/2020a toolchain allows use of LAPACK from C++.
=> OpenBLAS-0.3.9: Fix lapack.h for use with C++

.travis.yml
I consider this a last resort for keeping Travis...
If it still causes trouble with this included, we should stop using it for this repo at least.
I'm already working on getting @boegelbot to submit comments based on the test suite results from GitHub Actions rather than Travis (for easyconfigs)...
=> use travis_wait to extend 10m timeout when no output is produced

test/easyconfigs/easyconfigs.py
This avoids the deprecation warnings on CI.
Seems like my autopep8 also found 2 overlong lines in that file. I'm inclined to keep that change.
=> Use is_generic_easyblock from filetools

easybuild/easyconfigs/g/gomkl/gomkl-2020a.eb, easybuild/easyconfigs/i/imkl/imkl-2020.1.217-gompi-2020a.eb, easybuild/easyconfigs/i/imkl/imkl-2020.1.217-iompi-2020a.eb, easybuild/easyconfigs/i/iomkl/iomkl-2020a.eb, easybuild/easyconfigs/i/iompi/iompi-2020a.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.3-iccifort-2020.1.217.eb
This PR splits the `gmkl` and `iimkl` out of the PR https://github.com/easybuilders/easybuild-easyconfigs/pull/11035  and assumes that `imkl` is installed at the MPI level.
=> added only gomkl, iomkl, iompi, and imkl compiled at the MPI level

test/easyconfigs/easyconfigs.py
Some changes were made in Git 2.28.0 that break how we determine the list of changed files in PRs.
For example (from tests for https://github.com/easybuilders/easybuild-easyconfigs/pull/11068):
```
ERROR: test_changed_files_pull_request (test.easyconfigs.easyconfigs.EasyConfigTest)
Specific checks only done for the (easyconfig) files that were changed in a pull request.
File "test/easyconfigs/easyconfigs.py", line 739, in test_changed_files_pull_request
changed_ecs_filenames = get_eb_files_from_diff(diff_filter='M')
File "test/easyconfigs/easyconfigs.py", line 708, in get_eb_files_from_diff
out, ec = run_cmd(cmd, simple=False)
File …
```
=> fall back to using PR target branch when determining "merge base" between PR branch & target branch fails in test suite

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-foss-2019a-Python-3.7.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1-fosscuda-2019a-Python-3.7.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0-foss-2019a-Python-3.7.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.14.0-fosscuda-2019a-Python-3.7.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.2-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.15.2-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-foss-2019a-Python-3.7.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.1-foss-2019a-Python-3.7.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.0.1-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb
Handled by the EasyBlock now in a more general way
Follow-up to ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2110~~
Note: For 1.12.0 the patch is still there but I considered them too old (2018b toolchain)
=> stop using 'remove_usr_bin'-patch in TensorFlow easyconfig, no longer required with updated TensorFlow easyblock

README.rst
mainly done to make it uniform with framework (https://github.com/easybuilders/easybuild-framework/pull/3415) and easyblocks (https://github.com/easybuilders/easybuild-easyblocks/pull/2126)
see https://github.com/boegel/easybuild-easyconfigs/blob/README_status_badge/README.rst for result
=> move GitHub Actions status badge to top of README

easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompi-2020a.eb, easybuild/easyconfigs/s/Score-P/Score-P-6.0_binutils_2.34_api_change.patch
Fixes #11105 
@jhein32 Please test - works for me.
=> [gompi/2020a] Score-P 6.0: Add patch to support libbfd 2.34 API change

easybuild/easyconfigs/q/Qt5/Qt5-5.14.1-GCCcore-9.3.0.eb
Building the qtwayland component gives grief on (some?) Centos 7 systems.  Changed config to disable qtwayland being build
=> {lib}[GCCcore/9.3.0] Qt5 v5.14.1: disable qtwayland

easybuild/easyconfigs/c/Clang/Clang-8.0.0-GCC-8.2.0-2.31.1-CUDA-10.1.105.eb, easybuild/easyconfigs/c/Clang/Clang-8.0.1-GCC-8.2.0-2.31.1-CUDA-10.1.105.eb
As suggested by @lexming at https://github.com/easybuilders/easybuild-easyconfigs/pull/11157#pullrequestreview-474470339 this adds a Clang with dependency on GCC instead of GCCCore to avoid 2 different CUDA versions in dependency chains
=> Add Clang-8.0.1-GCC-8.2.0-CUDA-10.1.105

easybuild/easyconfigs/f/flatbuffers/flatbuffers-1.12.0-GCCcore-8.3.0.eb, easybuild/easyconfigs/j/JsonCpp/JsonCpp-1.9.3-GCCcore-8.3.0.eb, easybuild/easyconfigs/n/nsync/nsync-1.24.0-GCCcore-8.3.0.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-collective-all-reduce-strategy.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-flatbuffers.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-jsoncpp.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-nasm.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.1.0_fix-system-protobuf.patch
This is basically a test run. It makes the installation faster and smaller and avoids some downloads at build time.
This approach will be required for TF 2.3.0 and I'll add PRs for the other 2.x ECs once this is merged
Reason why it is required is the TF 2.3 bundles cURL but builds it with Bazel side-stepping the (correct) configuration from cURL and introducing a bug on some systems making parts of TF unusable: https://github.com/tensorflow/tensorflow/issues/40065#issuecomment-667129086
=> update TensorFlow 2.1.0 easyconfigs to provide more dependencies via EasyBuild

easybuild/easyconfigs/p/PyTorch/PyTorch-1.4.0_fix-system-pybind11.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-missing-source-dir.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-rpc-test-world-size.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-system-pybind11.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-test-cuda.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-test-dataloader-fixed-affinity.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-test-missing-rpc-shutdown.patch, easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0_fix-test-tensorexpr.patch
=> {devel}[fosscuda/2019b] PyTorch v1.6.0 w/ Python 3.7.4

easybuild/easyconfigs/e/edlib/edlib-1.3.8.post1-iccifort-2019.5.281-Python-3.7.4.eb, easybuild/easyconfigs/m/minibar/minibar-20200326-iccifort-2019.5.281-Python-3.7.4.eb
follow-up for @smoors's request in #10470
=> move edlib and minibar down to iccifort toolchain

easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.10.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.10.0-fosscuda-2019b-Python-3.7.4.eb
Seems like the protobuf C++ extensions are not good: https://github.com/protocolbuffers/protobuf/blob/c6493970296fa5c5b4a81a37248a328579fe9662/python/google/protobuf/internal/api_implementation.py#L69-L71
I've seen reports about crashes related to this and TensorFlow and while TF 2.2 seems to work fine TF 2.3 fails to run with the following stacktrace:
```
File "/home/s3248973/git/easybuild-easyconfigs/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.x_mnist-test.py", line 15, in <module>
tf.keras.layers.Dense(10, activation='softmax'),
File "/tmp/ebinstall/software/TensorFlow/2.3.0-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
result = method(self, *args, **kwargs)
File …
```
=> disable building the C++ extension in the protobuf-python v3.10.0 easyconfigs

easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.27-GCCcore-8.2.0.eb
Ghostscript was not compiling due to failing on:
`libpng/1.6.36-GCCcore-8.2.0/lib/libpng16.so.16: undefined reference to inflateValidate@ZLIB_1.2.9`
needed to add `-L$EBROOTZLIB/lib` to the
`preconfigopts += 'export LIBS="$LIBS -lz" && '`
line
=> {tools} [GCCcore/8.2.0] Ghostscript 9.27: LIBS change to fix ZLIB error

easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-foss-2019a-Python-3.7.2.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.2.0-fosscuda-2019a-Python-3.7.2.eb
As discussed in Slack and confirmed in https://github.com/pytorch/pytorch/issues/44948 using those 2 is not officially tested and known to cause problems at least on POWER architectures
Hence the removal
=> Remove GLog and GFlags from PyTorch 1.2.0

test/easyconfigs/easyconfigs.py
As per Slack discussion, this PR aims to make GitHub Action unit test failures
easier to read, eg. `AssertionError: 'download_dep_fail' is set in [...]` implies that
is shouldn't be set despite demanding the opposite, whereas `AssertionError:
'download_dep_fail' should be set in [...]` makes that clear.
=> Make CI sanity check messages less confusing ("is" -> "should be")

easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-foss-2019b-Python-3.7.4-kokkos.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-intel-2019b-Python-3.7.4-kokkos.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019_EPYC.patch
see https://github.com/easybuilders/easybuild-easyblocks/pull/1975#issuecomment-591218724
=> add patch to fix installation of LAMMPS 7Aug2019 on AMD Epyc systems

easybuild/easyconfigs/h/Hadoop/HADOOP-14597.04.patch, easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0-GCCcore-8.3.0-native.eb, easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0_tirpc.patch
Addresses 2 issues: 
1) OpenSSL changes: `HADOOP-14597.04.patch` (this should be in version `2.10.1`)
2) `RPC` is not anymore in `glibc` (see for example: https://github.com/easybuilders/easybuild-easyconfigs/pull/11279)
**MUST** recompile `libtirpc` for install this! (see: https://github.com/easybuilders/easybuild-easyconfigs/pull/11355)
=> fix installation of Hadoop v2.10.0 on RHEL8

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.2.0-fosscuda-2019b-Python-3.7.4.eb
Similar to #11109 this updates the TensorFlow 2.2.0 ECs to use more dependencies provided by EB
=> use more EasyBuild installed dependencies for TensorFlow 2.2.0

easybuild/easyconfigs/f/FuSeq/FuSeq-1.1.2-gompi-2019b.eb, easybuild/easyconfigs/f/FuSeq/FuSeq-1.1.2_RHEL8.patch
fixes the follwing problem:
```
/tmp/vsc40003/easybuild/FuSeq/1.1.2/gompi-2019b/sailfish-0.10.0/include/spdlog/details/format.h: In member function void fmt::internal::ArgFormatterBase<Impl, Char>::visit_char(int):
/tmp/vsc40003/easybuild/FuSeq/1.1.2/gompi-2019b/sailfish-0.10.0/include/spdlog/details/format.h:2056:24: error: expected unqualified-id before numeric constant
const unsigned CHAR_WIDTH = 1;
^~~~~~~~~~
```
=> add patch to fix installation of FuSeq v1.1.2 on RHEL8

easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1-gompi-2019b.eb, easybuild/easyconfigs/s/Sailfish/Sailfish-0.10.1_RHEL8.patch
fixes the problem:
```
/tmp/vsc40003/easybuild/FuSeq/1.1.2/gompi-2019b/sailfish-0.10.0/include/spdlog/details/format.h: In member function void fmt::internal::ArgFormatterBase<Impl, Char>::visit_char(int):
/tmp/vsc40003/easybuild/FuSeq/1.1.2/gompi-2019b/sailfish-0.10.0/include/spdlog/details/format.h:2056:24: error: expected unqualified-id before numeric constant
const unsigned CHAR_WIDTH = 1;
^~~~~~~~~~
```
=> add patch to fix installation of Sailfish v0.10.1 on RHEL8

easybuild/easyconfigs/p/PyTorch/PyTorch-1.6.0-fosscuda-2019b-Python-3.7.4.eb
It seems that the `caffe2.python` module contained in pytorch requires protobuf-python
=> Add protobuf-python as a dependency and corresponding sanity check to PyTorch 1.6

easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.6-intel-2019a.eb, easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.6-intel-2019b.eb, easybuild/easyconfigs/m/Multiwfn/Multiwfn-3.6_RHEL8.patch
see https://github.com/easybuilders/easybuild-easyconfigs/issues/11394
There is no https version of the homepage (it is in China)
=> fix Multiwfn 3.6 installation on RHEL8

easybuild/easyconfigs/w/worker/worker-1.6.11-intel-2019b.eb, easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2016b.eb, easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2017a.eb, easybuild/easyconfigs/w/worker/worker-1.6.7-intel-2017b.eb, easybuild/easyconfigs/w/worker/worker-1.6.8-intel-2018a.eb, easybuild/easyconfigs/w/worker/worker-1.6.8-intel-2018b.eb
Worker with system toolchain have to be fixed due to https://github.com/easybuilders/easybuild-framework/pull/3399
It seems that worker with system toolchain breaks in some RHEL8 system (annobin in Perl, see https://bugzilla.redhat.com/show_bug.cgi?id=1792997 )
The annobin flag `-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1` inherited from Perl, when something builds against Perl
`Linux node3502.doduo.os 4.18.0-193.14.3.el8_2.x86_64 #1 SMP Mon Jul 20 15:02:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` and `perl-5.26.3-416.el8.x86_64`, 
Note that annobin plugin is not a dependency for Perl.
For the annobin problems, a follow-up PR will come (if this PR passes), if  not RHEL8 problems will be fixed here, but it will takes some time.
=> fix broken worker easyconfigs

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1-intel-2019b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-2.3.1_RHEL8.patch
fixes:
```
ensight/part/ensightPartIO.C(66): error: identifier "isnan" is undefined
if (idList[i] >= field.size() || isnan(field[idList[i]]))
^
ensight/part/ensightPartIO.C(83): error: identifier "isnan" is undefined
if (isnan(field[i]))
^
```
and 
```
ensight/part/ensightPart.C(54): error: identifier "isnan" is undefined
if (id >= field.size() || isnan(field[id]))
^
```
=> fix OpenFOAM 2.3.1-intel-2019b installation on RHEL8

easybuild/easyconfigs/h/Horovod/Horovod-0.20.0-fosscuda-2019b-TensorFlow-2.3.1-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2019b-Python-3.7.4.eb
Contains security fixes
Removes the superflous keras-applications package and scipy package
edit (@boegel): OK because TensorFlow 2.3.0 easyconfigs have only been merged very recently into `develop` via #11040...
=> in-place update of TensorFlow 2.3.0 easyconfigs to version 2.3.1

easybuild/easyconfigs/b/BAMSurgeon/BAMSurgeon-1.2-GCC-8.3.0-Python-2.7.16.eb, easybuild/easyconfigs/p/PyVCF/PyVCF-0.6.8-GCC-8.3.0-Python-2.7.16.eb
I noticed that the PyVCF scripts had a hardcoded `/software/Python/2.7.16-GCCcore-8.3.0/bin/python`, so I enabled the use of `fix_python_shebang_for` to fix the scripts.
That led to a failing sanity check, with "`vcf_sample_filter.py --help`" failing with:
```
File "/software/PyVCF/0.6.8-GCC-8.3.0/bin/vcf_sample_filter.py", line 37
print "Samples:"
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Samples:")?
```
This shows that PyVCF is really only compatible with Python 2 (makes sense, sort of, last release was in March 2016...)
=> fix PyVCF easyconfig, only supports Python 2

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.11-foss-2020a-R-4.0.0.eb
All of these are in https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb so we can remove them from here.
* fs: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L1485
* sys: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L786
* askpass: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L789
* clue: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb#L2224
* ggplot2: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/r/R/R-4.0.0-foss-2 …
=> remove extentions from R-bundle-Bioconductor 3.11 easyconfigs that are also included in R 4.0.0

.github/workflows/unit_tests.yml
This should help with avoiding tests failing with errors like:
```
ERROR: Build of /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs/easybuild/easyconfigs/m/M4/M4-1.4.18.eb failed (err: "build failed (first 300 chars): Unexpected error occurred when trying to download https://ftpmirror.gnu.org/gnu/m4/m4-1.4.18.tar.gz to /tmp/runner/f34bb1a5734d6a0525710aa9ddc9f6be927f2737/sources/m/M4/m4-1.4.18.tar.gz: hostname 'gnu.mirror.constant.com' doesn't match 'arch.mirror.constant.com'")
```
=> cache M4 source tarball to avoid test failures because of download problems

easybuild/easyconfigs/d/DIRAC/DIRAC-19.0-intel-2020a-Python-2.7.18-int64.eb, easybuild/easyconfigs/d/DIRAC/DIRAC-19.0-intel-2020a-Python-2.7.18-mpi-int64.eb, easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_fix-bss_energy_test.patch, easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_fix_mpi_tests.patch, easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_fix_test_path.patch, easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_remove-broken-tests-intel.patch, easybuild/easyconfigs/d/DIRAC/DIRAC-19.0_use_easybuild_opts_intel.patch
Change the sequential version to work with native CMakeMake easyblock, and add mpi version.
Also, the unnecessary dependencies were removed (they only needed if PCMSOLVER is built)
PS: Dirac does not have `https` homepage
=> tweak non-MPI DIRAC 19.0 easyconfig to use CMakeMake easyblock + add MPI version of DIRAC 19.0

easybuild/easyconfigs/q/Qt5/Qt5-5.12.3-GCCcore-8.2.0.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.12.3_fix-socketcan.patch, easybuild/easyconfigs/q/Qt5/Qt5-5.12.3_fix-webrtc.patch, easybuild/easyconfigs/q/Qt5/Qt5-5.13.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/q/Qt5/Qt5-5.13.1_fix-webrtc.patch
Compiling Qt5 on Ubuntu 20.04, or other OS with a similarly up to date kernel yields:
```
socketcanbackend.cpp: In member function ‘void SocketCanBackend::readSocket()’:
socketcanbackend.cpp:697:41: error: ‘SIOCGSTAMP’ was not declared in this scope
if (Q_UNLIKELY(ioctl(canSocket, SIOCGSTAMP, &timeStamp) < 0)) {
^~~~~~~~~~
```
EL8.2 doesn't have this problem, but perhaps 8.3 will...?
=> fix compilation of Qt5 v5.12.3 and v5.13.1 on Ubuntu 20.04

easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-Add-Easybuild-configuration-files.patch, easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-foss-2019b-Python-3.7.4.eb, easybuild/easyconfigs/g/GPAW/GPAW-20.1.0-intel-2019b-Python-3.7.4.eb
GPAW patch doesn't check if BLAS and LAPACK actually exist, so it might trigger a `AttributeError: 'NoneType' object has no attribute 'split'`
=> add BLAS/LAPACK check to GPAW patch adding EasyBuild configuration files

easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompi-2020a.eb, easybuild/easyconfigs/s/Score-P/Score-P-6.0-gompic-2019b.eb, easybuild/easyconfigs/s/Score-P/Score-P-6.0_binutils_2.34_api_change.patch, easybuild/easyconfigs/s/Score-P/Score-P-6.0_no_PDT_for_CUDA.patch
Amend #11123 to support the binutils 2.34 API in another source-code location (discovered recently; used when built for PGI/NVHPC compilers, for example) and add a patch to prevent PDT instrumentation of `.cu` files.  The latter fixes a `make installcheck` failure when both PDT and CUDA are configured, but can also show up in real life.
=> {perf}[gompi/2020a] Backported fixes for Score-P v6.0

easybuild/easyconfigs/x/XCFun/XCFun-2.1.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/x/XCFun/XCFun-2.1.0-foss-2020a.eb
There exists an old version under the name `XCfun`, but the name really should be [XCFun](https://xcfun.readthedocs.io/en/latest/index.html), so where do you want me to put this, @boegel?
=> {chem}[GCCcore/9.3.0] XCFun 2.1.0

easybuild/easyconfigs/c/Clang/Clang-11.0.0-GCCcore-9.3.0.eb
Updated Clang to version 11. Updated Python dependency to `3.8`. Removed `ppc64le` patch that isn't needed.
Tested on both `x86_64` and `ppc64le`.
=> {compiler}[GCCcore/9.3.0] Clang v11.0.0

easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb
Requires ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2235~~
=> enable NVPTX offload support in GCCcore 10.2.0 easyconfig

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-foss-2019b-20200508.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7-foss-2019b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8-foss-2020a.eb
gnuplot is necessary to observe residuals during simulation so I suggest to include it as a dependecy.
=> add missing gnuplot dependency in easyconfig for OpenFOAM 7 and 8

easybuild/easyconfigs/n/nodejs/nodejs-10.15.1-foss-2018b.eb, easybuild/easyconfigs/n/nodejs/nodejs-10.15.3-GCCcore-8.2.0.eb, easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-GCCcore-7.3.0.eb, easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/n/nodejs/nodejs-12.16.1-GCCcore-9.3.0.eb, easybuild/easyconfigs/n/nodejs/nodejs-12.19.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/v/V8/V8-2.2-foss-2018b-R-3.5.1.eb, easybuild/easyconfigs/v/V8/V8-2.3-foss-2019a-R-3.6.0.eb, easybuild/easyconfigs/v/V8/V8-2.3-intel-2019a-R-3.6.0.eb, easybuild/easyconfigs/v/V8/V8-3.2.0-foss-2019b-R-3.6.2.eb
Because nodejs installations include OpenSSL header files, which causes trouble (see #11663 + https://github.com/jeroen/openssl/issues/84).
Other easyconfigs that depend on `nodejs` don't need to be fixed because of these changes (I'll confirm that in the test report).
=> don't add include/node to $CPATH in nodejs easyconfigs + tweak V8 easyconfigs accordingly

test/easyconfigs/easyconfigs.py
Needed by https://github.com/easybuilders/easybuild-easyconfigs/pull/11902
=> add CESM-deps to whitelist in check for custom sanity_check_paths

easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb
Some extensions were missing from #11663:
* nlsem (#11733)
* mitools, survey, tableone, jstable (see #11841)
* RCAL, sensemakr (see #11921)
=> add additional extensions to R v4.0.3 easyconfig

easybuild/easyconfigs/n/NVHPC/NVHPC-20.9.eb
Added new multi-arch version of NVHPC, this requires `easyblock` PR
easybuilders/easybuild-easyblocks#2233.
=> {compiler} [NVHPC/20.9] Added new multi arch version

easybuild/easyconfigs/r/ReFrame/ReFrame-3.3.eb
Fixes https://github.com/eth-cscs/reframe/issues/1615
=> {devel}[system] ReFrame v3.3

easybuild/easyconfigs/l/libfabric/libfabric-1.10.1-GCCcore-9.3.0.eb, easybuild/easyconfigs/l/libfabric/libfabric-1.11.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/l/libfabric/libfabric-1.11.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/l/libfabric/libfabric-1.9.1-GCCcore-9.3.0.eb
Fix bogus OS dependency on OpenSSL for `libfabric-1.11.0-GCCcore-10.2.0.eb` and consistently use `OS_PKG_IBVERBS_DEV` constant.
=> Libfabric: fix OS deps

easybuild/easyconfigs/r/R/R-3.5.0-iomkl-2018a-X11-20180131.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/r/R/R-3.5.1-foss-2018b.eb, easybuild/easyconfigs/r/R/R-3.5.1-intel-2018b.eb, test/easyconfigs/easyconfigs.py
A user reported a failure when building with: `eb --package R-3.5.1-foss-2018b.eb --skip --force --ignore-checksum --debug --info`
```
== 2021-01-28 18:36:09,232 run.py:222 INFO running cmd:  R CMD INSTALL /tmp/centos/R/3.5.1/foss-2018b/later/later   --library=/mnt/eb/apps/R/3.5.1-foss-2018b/lib64/R/library --no-clean-on-error
== 2021-01-28 18:36:10,920 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): cmd " R CMD INSTALL /tmp/centos/R/3.5.1/foss-2018b/later/later   --library=/mnt/eb/apps/R/3.5.1-foss-2018b/lib64/R/library --no-clean-on-error " exited with exit code 1 and output:
* installing *source* package later ...
[...]
C11-style threads.h support not detected. Using tinycthread library.
[...] …
```
=> Remove duplicate extensions in R 3.5.x easyconfigs, and add test to detect such issues

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2012-cleanup.patch, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2012-foss-2020a.eb
Hi @boegel - a heads-up for the upcoming OpenFOAM-v2012
To help accommodate easybuild and other systems, we have an additional `FOAM_CONFIG_ETC` variable that we can hook into to quickly switch between different types of configurations (eg, intelmpi/openmpi, 64/32-bit, spdp/dp etc). It also can be used by easybuild to define its configuration, largely without patching the original sources.
The OpenFOAM internal mpi selector now recognizes "EASYBUILDMPI"  (no patching needed), and the readline discovery can be customized with the usual config.sh mechanism, which means that easybuild can generate its settings without patching into the wmake/scripts directory.  Using this approach, we are getting one step closer to being able to generate settings on-the-fly instead of patching. 
In this …
=> {cae}[foss/2020a] OpenFOAM v2012

easybuild/easyconfigs/b/BLIS/BLIS-0.8.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/b/BLIS/BLIS-0.8.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/b/BLIS/BLIS-2.2-GCCcore-9.3.0-amd.eb, easybuild/easyconfigs/g/gobff/gobff-2020.06-amd.eb, easybuild/easyconfigs/g/gobff/gobff-2020.11.eb, easybuild/easyconfigs/g/gobff/gobff-2020b.eb, easybuild/easyconfigs/l/libFLAME/libFLAME-2.2-GCCcore-9.3.0-amd.eb, easybuild/easyconfigs/l/libFLAME/libFLAME-5.2.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/l/libFLAME/libFLAME-5.2.0-GCCcore-9.3.0.eb
Building BLIS with Intel compilers is problematic (see https://github.com/flame/blis/issues/371), and doesn't make much sense either (no performance benefit in case of BLIS), so let's move these to `GCCcore`...
For the easyconfigs using `GCC/10.2.0` that's not a problem, since they're only in `develop` currently.
requires ~~#12166~~
=> move most recent BLIS and libFLAME easyconfigs from GCC to GCCcore

easybuild/easyconfigs/m/MrBayes/MrBayes-3.2.6-foss-2017a.eb
1.  Now using 2017a FOSS toolchain, to avoid libibverbs failures with 2016a.  
2.  Download location updated from SourceForge to GitHub.
=> {bio}[foss/2017a] MrBayes v3.2.6

easybuild/easyconfigs/c/Clang/Clang-10.0.0-GCCcore-8.3.0.eb, easybuild/easyconfigs/c/Clang/Clang-10.0.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/c/Clang/Clang-10.0.1-GCCcore-9.3.0.eb, easybuild/easyconfigs/c/Clang/Clang-11.0.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/z/Z3/Z3-4.8.9-GCCcore-8.3.0.eb, easybuild/easyconfigs/z/Z3/Z3-4.8.9-GCCcore-9.3.0.eb
`libxml2` is a runtime dependency rather than a build dependency. Also enable use of `hwloc` for affinity in the OpenMP runtime and `Z3` in the Clang static analyzer, and build extra Clang tools.
Depends on ~~https://github.com/easybuilders/easybuild-easyblocks/pull/2310~~
=> {compiler}[GCCcore/8.3.0, GCCcore/9.3.0] Update Clang 10+ deps & build extra tools

.github/workflows/unit_tests.yml
We're making the necessary changes to rename the `master` branch to `main`.
Currently both are available (and they're identical), but we'll remove `master` as soon as we're done with making the necessary changes.
See also https://github.com/easybuilders/easybuild-framework/pull/3589
=> use 'main' rather than 'master' branch in test suite configuration

easybuild/easyconfigs/i/IPython/IPython-7.18.1-GCCcore-10.2.0.eb
skipping test_system_interrupt, generally failing (https://github.com/ipython/ipython/issues/12164)
=> Skip sanity check test in IPython-7.18.1-GCCcore-10.2.0.eb

easybuild/easyconfigs/n/netCDF/netCDF-4.6.2-gompi-2019a.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.7.1-gompi-2019b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.7.1-gompic-2019b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-fix-mpi-info-f2c.patch, easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-gompi-2020a.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-gompi-2020b.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.7.4-gompic-2020a.eb
This affects versions 4.6.2 to 4.7.4, see
https://github.com/Unidata/netcdf-c/pull/1957
=> netCDF:add patch fixing MPI_Info_f2c OpenMPI issue

easybuild/easyconfigs/m/manta/manta-1.6.0-GCC-10.2.0-Python-2.7.18.eb
I renamed `manta` to `Manta` in #12359 before merging it, but I overlooked the existing `manta` easyconfigs, so it's better to stick to `manta` (since it's not very clear that `Manta` should be preferred)...
=> stick to 'manta' software name, to be consistent with existing easyconfigs

test/easyconfigs/easyconfigs.py
When the tests are run they changes the EasyBuild easyconfigs, to replace
```
toolchain = {'name': 'dummy', 'version': 'dummy'}
```
with
```
toolchain = SYSTEM
```
This changes the tests to just not do the check for the `dummy` toolchain on the EasyBuild easyconfigs.
=> Stop tests changing the EasyBuild easyconfigs

test/easyconfigs/easyconfigs.py
This is for #12451, #12452, #12453 to avoid reintroducing that
The 2nd commit fixes the failure seen in #12453: https://github.com/easybuilders/easybuild-easyconfigs/runs/2174370525
=> Add CI test checking if the Python default source_urls are used and Fix CI check where use_pip=False was ignored

test/easyconfigs/easyconfigs.py
Fix for check that was added in #12456 by @Flamefire
Via the `EasyConfig` instance, you always get the default value for easyconfig parameters that are not defined in the easyconfig file.
If you only grab the *defined* easyconfig parameters via the parser instance though, you can check whether an easyconfig parameter was defined exactly like the default value:
```python
>>> from easybuild.tools.options import set_up_configuration
>>> set_up_configuration()
>>> from easybuild.framework.easyconfig.tools import process_easyconfig
>>> ec = process_easyconfig('easybuild/easyconfigs/p/pybedtools/pybedtools-0.8.2-iccifort-2020.4.304.eb')[0]['ec']
>>> ec.get('source_urls', resolve=False)
['https://pypi.python.org/packages/source/%(nameletter)s/%(name)s']
>>> pure_ec = ec.parser.get_config_dict() …
```
=> fix check for default source_urls value for easyconfigs using PythonPackage or PythonBundle

test/easyconfigs/easyconfigs.py
From https://github.com/easybuilders/easybuild-easyconfigs/pull/12456#issuecomment-805852017
IMO it should always be required as this could/does(?) catch the recent issue where installation via setup.py resulted in a version of 0.0.0
@boegel 
> I'm not sure it makes sense to run pip check when pip was not used to install the package...
>
> How would running pip check catch the problem with 0.0.0 versions? That would require enhancements in the generic PythonPackage PR first?
`pip` also sees packages installed by `setup.py` and that might introduce conflicts as well which would make later installations that use this software fail.
It may catch the 0.0.0 versions indirectly: When another package requires a specific version of this software but that is 0.0.0 `pip check` will fail
A proper …
=> Require sanity_pip_check for all Python package/bundles

easybuild/easyconfigs/h/Hadoop/Hadoop-2.10.0-GCCcore-10.2.0-native-Java-1.8.eb
required to make enhanced easyconfig test suite pass, see #3655
=> add -Java versionsuffix for Hadoop easyconfig using GCCcore/10.2.0 toolchain, since it depends on Java 1.8

easybuild/easyconfigs/p/Perl/Perl-5.32.0-GCCcore-10.2.0.eb
Reverts easybuilders/easybuild-easyconfigs#12627
This extension is already included in `perl-5.32.0.tar.gz`, the base distribution of Perl. Adding it as an extension is incompatible with `--skip` as the module in the base distribution will have precedence over the extension and it will not be installed, regardless of its version.
=> Revert "add Compress::Raw::Zlib to Perl v5.32.0"

easybuild/easyconfigs/b/BirdNET/BirdNET-20201214-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/b/BirdNET/BirdNET-20201214_add-model-path-envvar.patch
The patch included with PR #12685 didn't seem to work correctly, as the main script (`analyze.py`) has some relative paths to files in a subdir of the installation. By calling the script for any location other than the installation dir, this leads to errors. This new patch fixes it by prepending the location by the path to the script that is being called.
=> fix BirdNET patch: don't use relative paths to files in installation directory

easybuild/easyconfigs/b/BirdNET/BirdNET-20201214-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/b/BirdNET/BirdNET-20201214_add-model-path-envvar.patch
Found one more issue after #12685 and #12712 were merged: the name of one of the environment variables that is being checked is wrong (too much copy-pasting...). This should fix that, and also adds a comment about the purpose of the 2nd part of the patch.
=> Fix wrong variable name in BirdNET patch

easybuild/easyconfigs/f/fastqz/fastqz-1.5-GCC-4.8.2.eb, easybuild/easyconfigs/g/Genome_Profiler/Genome_Profiler-2.1-foss-2016b-Perl-5.24.0.eb, easybuild/easyconfigs/s/STREAM/STREAM-5.10-GCC-7.3.0-2.30.eb, easybuild/easyconfigs/s/STREAM/STREAM-5.10-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/s/STREAM/STREAM-5.10-GCC-9.3.0.eb, easybuild/easyconfigs/s/STREAM/STREAM-5.10-iccifort-2020.1.217.eb, easybuild/easyconfigs/s/STREAM/STREAM-5.10-intel-2016b.eb, easybuild/easyconfigs/s/STREAM/STREAM-5.10-intel-2018b.eb, test/easyconfigs/easyconfigs.py
Skipping the `source` step implies not verifying checksums, so we shouldn't do that...
requires ~~#12794~~ (fixes for FastTree)
=> add check to make sure that source step is not being skipped

easybuild/easyconfigs/r/R/DMCfun-1.3.0_fix-parallel-detect.patch, easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb
fixes #12569
This only solves PBS cases so other queue systems might need different solution(s)
=> add patch to fix hardcoded num_cores in DMCfun extension included with R 4.0.x

easybuild/easyconfigs/a/astropy/astropy-4.2.1-intelcuda-2020b.eb
Adding astropy-4.2.1 into intel-cuda-2020b. Astropy documentation adds dependency on ERFA so adding it and replacing deprecated astropy-helpers with extension-helpers.
=> {astro}[intelcuda/2020b] astropy v4.2.1 w/ Python 3.8.6

test/easyconfigs/easyconfigs.py
This change is required because of the fix to `get_config_dict` in https://github.com/easybuilders/easybuild-framework/pull/3692 .
The result of the fix is that `ec.parser.get_config_dict()` now accurately reflects the original easyconfig file, whereas before the fix the value of mutable easyconfig parameters could have been tweaked by the easyblock constructor (like `PythonBundle` does for `exts_default_options`).
The easyconfig file that is dumped via `ec.dump()` will still include the modified easyconfig parameter though, and hence the comparison between the original easyconfig file and the dumped easyconfig file failed for easyconfigs that use an easyblock like `PythonBundle` that fiddles with easyconfig parameters at initialization.
Note that the behavior of `dump()` wasn't affected …
=> dump easyconfig before initializing easyblock in order to compare it with original easyconfig

easybuild/easyconfigs/r/R-INLA/R-INLA-21.05.02-foss-2020b-R-4.0.4.eb, easybuild/easyconfigs/r/R-INLA/R-INLA-21.05.02-foss-2020b-remove-hardcoding.patch
Changelog:
* add link to `bin/fmesher` into `INLA/bin/linux/64bit/`, in the same way that we already do for `bin/inla`
* patch out hardcoded paths from `fmesher.run`, in the same way that we already do for `inla.run`
* improve sanity checks
=> fix installation of fmesher within R-INLA

test/easyconfigs/easyconfigs.py
I think this is what was intended?
This showed up when testing https://github.com/easybuilders/easybuild-easyconfigs/pull/12863, which has an external module dependency with no version information, but I suppose `test_changed_files_pull_request` should also filter out external modules, like `process_all_easyconfigs` does?
=> in easyconfig tests, check version of dependencies named Python, not if dependencies with certain versions are named Python

easybuild/easyconfigs/c/Clang/Clang-11.0.1-gcccuda-2020b.eb
If `elfutils` is missing during build, CUDA offloading support is not enabled as one would expect with the `gcccuda` toolchain.
This fixes #13006
=> add elfutils as build dependency for Clang 11.0.1 built with gcccuda toolchain

easybuild/easyconfigs/f/futile/futile-1.8.3-foss-2020b.eb, easybuild/easyconfigs/f/futile/futile-1.8.3-intel-2020b.eb, easybuild/easyconfigs/f/futile/futile_intel_bug.patch, easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-foss-2020b.eb, easybuild/easyconfigs/p/PSolver/PSolver-1.8.3-intel-2020b.eb
This version has a new dependency on the futile library, so we also include futile-1.8.3-foss-2020b and futile-1.8.3-foss-2020b.
=> {phys}[foss/2020b,intel/2020b] PSolver v1.8.3

test/easyconfigs/easyconfigs.py
This PR adds `GCCcore-1[0-9]` to `test_dep_versions_per_toolchain_generation`. Before only `GCCcore-[7-9]` was included, that is why the check was not executed in https://github.com/easybuilders/easybuild-easyconfigs/pull/13164 and https://github.com/easybuilders/easybuild-easyconfigs/pull/13165
=> add GCCcore-1[0-9].x to test_dep_versions_per_toolchain_generation

test/easyconfigs/easyconfigs.py
Improves https://github.com/easybuilders/easybuild-easyconfigs/pull/13243
This PR adds `GCCcore-[1-9][0-9]` to `test_dep_versions_per_toolchain_generation`.
=> add GCCcore-[1-9][0-9].x to test_dep_versions_per_toolchain_generation

.github/workflows/unit_tests.yml, test/easyconfigs/easyconfigs.py, test/easyconfigs/styletests.py, test/easyconfigs/suite.py
Major improvements to the test suite
- Remove a forgotten debug print
- Checkout full history on CI to avoid failure to get merge base
- Remove workaround to cleanup test TMPDIR in favor of class teardown method
- Process ECs on demand (preparation for next change, but also means for non-prs the ecs-in-pr-changed test is a no-op instead of parsing all ECs and never using them)
- Refactor the ECs-changed-in-PR test to run the subtests as separate test cases so failures in one of them don't abort the others
- Ignore cmdline args passed to the test suite, those are handled by unittest and should not be handled by easybuild. This allows to run subsets of tests like: `python test/easyconfigs/easyconfigs.py -v -k test_pr` to run all PR tests only
- Remove unused setting of …
=> code cleanup + improvements for easyconfigs test suite

test/easyconfigs/easyconfigs.py
These hacks were included in #13253 to make the PR mergeable, but should be re-activated now ASAP...
=> re-enable checksum and Python checks in easyconfigs test suite

easybuild/easyconfigs/g/GCCcore/GCCcore-10.2.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-10.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-9.3.0_nvptx_sm_35_default.patch
This adds a patch included in GCC 11.1.0 setting -misa=sm_35 by default
for compatibility with CUDA 11 which no longer supports the previous
default sm_30.
Fixes #12518
=> add patch for recent GCCcore versions to fix compability with CUDA 11

easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-GCC-10.2.0.eb, easybuild/easyconfigs/t/taxator-tk/taxator-tk-1.3.3-gompi-2019a.eb
This is required because of the changes made in 
Without it, these two `taxator-tk` easyconfigs fail at configure time with:
```
CMake Warning (dev) at /software/Boost/1.74.0-GCC-10.2.0/lib64/cmake/Boost-1.74.0/BoostConfig.cmake:240 (if):
Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
--help-policy CMP0057" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
IN_LIST will be interpreted as an operator when the policy is set to NEW.
Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
cmake-modules/FindBoost.cmake:206 (find_package)
CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Error at …
```
=> fix recent taxator-tk easyconfigs by adding (back) -DBoost_NO_BOOST_CMAKE=ON configure option

easybuild/easyconfigs/h/h5py/h5py-3.1.0-foss-2020b.eb, easybuild/easyconfigs/h/h5py/h5py-3.1.0-fosscuda-2020b.eb, easybuild/easyconfigs/h/h5py/h5py-3.1.0-intel-2020b.eb, easybuild/easyconfigs/h/h5py/h5py-3.1.0-intelcuda-2020b.eb, easybuild/easyconfigs/h/h5py/h5py-3.2.1-foss-2021a.eb
By default h5py's setup.py has a setup_requires for exactly the minimum supported version of numpy (older then the one in SciPy-bundle, in some cases) based on the python interpretor version, resulting in pip attempting to fetch it during the EasyBuild install phase.
As the dependency is already managed through easy_build, and h5py's install_requires is for any version newer than the minimum version, this change suppresses the setup_requires (using the mechanism provided by h2py for "downstream packagers - e.g. Linux distros").
Resolves #13424
=> avoid downloading old numpy version during install for h5py

easybuild/easyconfigs/g/GOATOOLS/GOATOOLS-1.1.6-foss-2020b.eb
follow-up for #13364
The original easyconfig is already broken because `go-basic.odo` was updated in place, and there's no versioned download available.
These files don't need to be part of the installation itself, they just need to be available in the current working directory, so and end user can download these easily themselves...
=> don't include unversioned go-basic.odo and goslin_generic.odo files in GOATOOLS installation (renamed from goatools)

.github/workflows/unit_tests.yml
see https://github.com/easybuilders/easybuild-easyconfigs/pull/13767#discussion_r691452271
If the tests fail then the `|| echo "ERROR: Not all tests were successful"` means that the non-zero exit code is taken since the `echo` succeeds.
=> make the testsuite print error and still return a non-zero exitcode

easybuild/easyconfigs/c/Co-phylog/Co-phylog-20201012-GCC-7.3.0-2.30.eb
I had to disable RPATH to build this easyconfig. Can anyone try to build this easyconfig using `eb --rpath` to check if this only happens to me?
=> {bio}[GCC/7.3.0] Co-phylog-20201012-GCC-7.3.0-2.30.eb

easybuild/easyconfigs/o/OpenCV/OpenCV-4.5.1-foss-2020b-contrib.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-4.5.1-fosscuda-2020b-contrib.eb
fixes #12491 
Freetype and Harfbuzz are required to build freetype: https://github.com/opencv/opencv_contrib/tree/master/modules/freetype
=> Added those modules as dependencies
OpenCV contrib bug in ocv_check_modules prevents detection of Freetype and HarfBuzz, required to build freetype module, ref:
- https://github.com/opencv/opencv_contrib/issues/1497
- https://github.com/opencv/opencv_contrib/issues/2239
=> Applied configopts to "force detection" of the module as per described workaround in issue 2239.
Module requires Python 3:
=> Added configopt to disable Python2 compilation (removes error messages)
=> fix sanity check error for OpenCV v4.5.1

easybuild/easyconfigs/c/CUDA/CUDA-11.3.1.eb, easybuild/easyconfigs/c/CUDA/CUDA-11.4.1.eb, easybuild/easyconfigs/c/ctffind/ctffind-4.1.14-foss-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/c/cuDNN/cuDNN-8.2.1.32-CUDA-11.3.1.eb, easybuild/easyconfigs/c/cuDNN/cuDNN-8.2.2.26-CUDA-11.4.1.eb, easybuild/easyconfigs/m/magma/magma-2.6.1-foss-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-10.3.0-CUDA-11.3.1.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.10.3-GCCcore-11.2.0-CUDA-11.4.1.eb, easybuild/easyconfigs/n/NCCL/NCCL-2.9.9-CUDA-11.3.1.eb, easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-gompi-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.10.0-GCCcore-10.3.0-CUDA-11.3.1.eb, easybuild/easyconfigs/u/UCX-CUDA/UCX-CUDA-1.11.0-GCCcore-11.2.0-CUDA-11.4.1.eb
So, unfortunately, we have released some of these easyconfigs, but it is an important change we might still consider, as it would otherwise require some either ugly workarounds, or fixing a bunch of easyblocks.
Some of these only need to rebuild the module.
Possible alternative: Have CUDAcore also defined EBROOTCUDA 
Affected easyconfigs that have already been released:
cuDNN-8.2.1.32-CUDA-11.3.1.eb
NCCL-2.10.3-GCCcore-10.3.0-CUDA-11.3.1.eb
magma-2.6.1-foss-2021a-CUDA-11.3.1.eb
OSU-Micro-Benchmarks-5.7.1-gompi-2021a-CUDA-11.3.1.eb
edit this was wrong, it was actually just cuDNN was affected, yay
I.M.O., having to rebuild these is not a huge issue as we don't provide anything that depends on top of them. Might also get away with just a module-rebuild if it's not RPATH'ed
=> rename CUDAcore to CUDA for v11.3.1 and v11.4.1 after merging foss/fosscuda, to ensure that get_software_root('CUDA') used in easyblocks works

easybuild/easyconfigs/s/snippy/snippy-4.6.0-GCC-9.3.0-Java-13-Python-3.8.2.eb
The `Snippy` easyconfig was added in #12893, but we already had `snippy` (cfr. #13475 and #8635)
=> fix software name for Snippy to snippy

easybuild/easyconfigs/x/xtb/xtb-6.4.1-intel-2021a.eb
Easyconfig for `xTB` was added in #13649, but we already have easyconfigs under the `xtb` name, cfr. #9878 and #9993
=> fix software name for xTB to xtb

easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb
When trying to build R 4.1.0 I found that the checksum for the lhs v1.1.1 extension was wrong.
I corrected with the right checksum (build tested and working) for all its occurences.
Don't know what happened, maybe they repackaged/replaced the source at some point...
=> add additional valid checksum for lhs 1.1.1 extension in recent R 4.0.x and 4.1.0 easyconfigs

test/easyconfigs/easyconfigs.py
Added artic-ncov2019-2021.06.24 for TF version 2.2.3 as artic-ncov2019-2021.06.24 required medaka which itself required TF-2.2.3.
=> Update to include artic-ncov2019-2021.06.24

easybuild/easyconfigs/b/BerkeleyGW/BerkeleyGW-3.0.1-foss-2020b.eb
There is no existing 2020b EasyConfig for BerkeleyGW.
=> {phys}[foss/2020b] BerkeleyGW v3.0.1

easybuild/easyconfigs/a/ANIcalculator/ANIcalculator-1.0-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/libnsl/libnsl-1.3.0-GCCcore-10.3.0.eb, test/easyconfigs/easyconfigs.py
This adds an easyconfig for `{devel}[GCCcore/10.3.0] libnsl`, and adds a dependency on that easyconfig to `ANIcalculator`. This should solve the issue that it doesn't work on newer Linux distros (e.g. EL8) due to a missing `libnsl.so.1` (which used to be part of older `glibc` versions). Note that `libnsl` creates a symlink `libnsl.so.1 -> libnsl.so.2`; it should be backwards compatible.
I've also removed the "fake" build dependency on `binutils`, which only was there to pass the CI tests. Instead, I've now added an exception in the test suite that allows `ANIcalculator` to not have a requirement on `binutils`, as it only installs some binaries.
=> add dependency on libnsl for ANIcalculator

easybuild/easyconfigs/a/ANIcalculator/ANIcalculator-1.0-GCCcore-10.3.0.eb
I just found that the permissions were not set correctly for the installed binaries (other users were not able to run them):
```
-rwxr-xr--. 1 boegelbot boegelbot  12M  7 aug  2014 ANIcalculator
-rwxr-xr--. 1 boegelbot boegelbot 451K  7 aug  2014 nsimscan
```
This PR fixes it by doing a `chmod a+x` on `bin/*`.
=> Correctly set execute permissions for ANIcalculator binaries

easybuild/easyconfigs/m/Mash/Mash-2.0-foss-2018a.eb, easybuild/easyconfigs/m/Mash/Mash-2.1-foss-2018b.eb, easybuild/easyconfigs/m/Mash/Mash-2.2-GCC-9.3.0.eb, easybuild/easyconfigs/m/Mash/Mash-2.2_fix-hardcoding.patch, easybuild/easyconfigs/m/Mash/Mash-2.3-GCC-10.3.0.eb
Fixes #14509 by reintroducing (an updated version of) the patches that were already used for version 2.1. I've also added sanity check commands for all Mash easyconfigs, as this would have spotted the issue.
=> add patch to fix broken (hanging) Mash binaries

easybuild/easyconfigs/c/cxxopts/cxxopts-3.0.0.eb, easybuild/easyconfigs/e/ELFIO/ELFIO-3.9.eb, easybuild/easyconfigs/t/termcolor/termcolor-2.0.0.eb
follow up from #14487, #14488, #14489, cc @robert-mijakovic
=> move cxxopts, termcolor and ELFIO header only libraries to SYSTEM toolchain

easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2016a.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2017b-5build1.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2018a-5build1.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2019a-5build1.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2019b-5build1.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2021a.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2016a.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2017b-5build1.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-intel-2019a-5build1.eb
cleaning up after merging https://github.com/easybuilders/easybuild-easyconfigs/pull/14445 before noticing the different grace/Grace easyconfigs
WIP because we may want to additionally change the contents to make easyconfigs more uniform across toolchains
also related to https://github.com/easybuilders/easybuild-easyconfigs/pull/14468 and https://github.com/easybuilders/easybuild-easyconfigs/pull/12717
=> consistently use 'Grace' software name + sync homepage/source_urls + fix easyconfig for Grace v5.1.25 with foss/2021a

test/easyconfigs/styletests.py
Example output of failing style checks without this change:
```
FAIL: test_style_conformance (test.easyconfigs.styletests.StyleTest)
Check the easyconfigs for style
File "test/easyconfigs/styletests.py", line 57, in test_style_conformance
self.assertEqual(result, 0, "Found code style errors (and/or warnings): %s" % result)
AssertionError: Found code style errors (and/or warnings): 1
```
with this change you at least get a clue of what's wrong (so you don't need to run `eb --check-style --from-pr` anymore...):
```
FAIL: test_style_conformance (test.easyconfigs.styletests.StyleTest)
Check the easyconfigs for style …
```
=> include output of failing code style check in message produced by failing easyconfigs style test

easybuild/easyconfigs/i/IPython/IPython-7.25.0-GCCcore-10.3.0.eb, easybuild/easyconfigs/i/IPython/IPython-7.26.0-GCCcore-11.2.0.eb
Bump of nbconvert to version 6.4.0. The previous version of nbconvert that was in `IPython-7.25.0-GCCcore-10.3.0.eb` (nbconvert 6.1.0), could cause permission denied errors when run in a shared environment. See https://github.com/jupyter/nbconvert/issues/1430 . This was fixed in PR https://github.com/jupyter/nbconvert/pull/1646 . Since many EasyBuild users work in shared environments, I think this is a relevant fix to have included.
=> bump nbconvert extension in recent IPython easyconfigs to version 6.4.0

test/easyconfigs/easyconfigs.py
fix for failing easyconfig tests, introduced in #14591:
```
ERROR: test_pr_sanity_check_paths (test.easyconfigs.easyconfigs.EasyConfigTest)
Make sure a custom sanity_check_paths value is specified for easyconfigs that use a generic easyblock.
File "test/easyconfigs/easyconfigs.py", line 1030, in test_pr_sanity_check_paths
bundle_sanity_check_components = ec['sanity_check_components'] or ec['sanity_check_all_components']
File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 125, in new_ec_method
return ec_method(self, key, *args, **kwargs)
File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/easyb …
```
=> only check sanity_check_components and sanity_check_all_components when Bundle easyblock is used in test_pr_sanity_check_paths

.github/workflows/linting.yml, .github/workflows/unit_tests.yml
Running tests with Python 3.5 is broken using `setup-python@v1`, has been end-of-life for quite a long time now
```
Run actions/setup-python@v1
Error: Version 3.5 with arch x64 not found
Available versions:
2.7.18 (x64)
3.10.2 (x64)
3.6.15 (x64)
3.7.12 (x64)
3.8.12 (x64)
3.9.10 (x64)
```
=> use actions/setup-python@v2 in CI workflows, also test with Python 3.8-3.10

.github/workflows/unit_tests.yml
The changes in #14857 were a bit ambitious, testing with a wide range of Python 3.x versions quickly leads to a large backlog for easyconfig PRs...
Only testing with Python 2.7 + 3.6 (most popular Python 3.x version), and no longer testing with Lmod 6.x (deprecated for a while, see https://github.com/easybuilders/easybuild-framework/pull/3077) should be enough...
=> trim test configurations for easyconfigs test suite: only test with Python 2.7 + 3.6 and Lmod 7.x + 8.x

easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-gompi-2021a.eb, easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-gompi-2021b.eb, easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-iimpi-2021a.eb, easybuild/easyconfigs/l/libGridXC/libGridXC-0.9.6-iimpi-2021b.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4-GCC-11.2.0.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4-intel-compilers-2021.4.0.eb, test/easyconfigs/easyconfigs.py
This PR also adds Libxc v4.3.4 for `GCC/11.2.0` and `intel-compilers/2021.4.0`, as libGridXC is currently not compatible with Libxc v5.x.
=> {phys}[foss/2021a,foss/2021b,intel/2021a,intel/2021b] libGridXC v0.9.6 

easybuild/easyconfigs/g/gmpy2/gmpy2-2.1.2-GCC-11.2.0.eb, easybuild/easyconfigs/p/PPanGGOLiN/PPanGGOLiN-1.1.136-foss-2021b.eb
Using a release candidate rather than a proper release is something we should avoid, since it's a recipe for trouble (cfr. problems with `sympy` tests on top of `gmpy2` v2.1.0rc1 in #14376).
=> don't use v2.1.0rc1 release candidate of gmpy2, stick to proper release v2.1.2

easybuild/easyconfigs/l/libffi/libffi-3.4.2-GCCcore-11.2.0.eb
Some projects like gobject-introspection use ffi_closure_alloc() as a way to allocate executable memory.
The new exec static tramp in libffi 3.4 interferes with it and therefor must be disabled - or it can result in segfaults.
https://github.com/libffi/libffi/pull/647
This is currently the only solution like it is also done in conda:
https://github.com/conda-forge/libffi-feedstock/pull/39
"Interesting" is this comment: https://github.com/libffi/libffi/pull/647#issuecomment-869184620
`we can do the 3.4 release and distros can initially build with --disable-exec-static-tramp`
=> libffi 3.4.2 - disable-exec-static-tramp

easybuild/easyconfigs/m/matplotlib-inline/matplotlib-inline-0.1.3-GCCcore-10.2.0.eb
Adding an easyconfig recipe for a new sw called matplotlib-inline providing a Matplotlib Inline Back-end for IPython and Jupyter.
=> {vis}[GCCcore/10.2.0] matplotlib-inline v0.1.3

easybuild/easyconfigs/g/Grace/Grace-5.1.25-foss-2021a.eb, easybuild/easyconfigs/g/Grace/Grace-5.1.25-tirpc-dependency.patch
The `grconvert` tool has a hard dependency on a RPC library providing XDR functionality.
This is typically not present under the expected library names on RedHat-like distros so we add a dependency on `libtirpc` to satisfy the requirement.
We expect the `grconvert` to be present during sanity check so this is otherwise a hard build breakage.
=> fix grconvert build for Grace/5.1.25 with foss/2021a by adding libtirpc dependency + related patch

easybuild/easyconfigs/s/snpEff/snpEff-5.0e-GCCcore-11.2.0-Java-11.eb
Despite claims on the website that snpEff needs Java 12+, Java 11 is perfectly sufficient (and used in e.g. the debian package):
```
$ java -xf snpEff.jar
$ find . -type f -name "*.class" -exec file {} \; | grep -Eo "(version .*)" | sort | uniq
version 45.3
version 46.0 (Java 1.2)
version 48.0 (Java 1.4)
version 49.0 (Java 1.5)
version 50.0 (Java 1.6)
version 51.0 (Java 1.7)
version 52.0 (Java 1.8)
version 53.0
```
=> {bio}[GCCcore/11.2.0] snpEff v5.0e w/ Python 3.9.6

easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-10.2.0.eb, easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-11.2.0.eb, easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-9.3.0.eb, easybuild/easyconfigs/s/SeqLib/SeqLib-1.2.0_use-external-deps.patch
There was a syntax error in the autoconf macro, which causes an
error if pkg-config is available, and if not available simply
causes configure to issue a warning and ignore it.
Since the result is not used anyway, we can remove it.
=> Remove pkg-config use from SeqLib configure patch

easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.2.eb
=> pkg-config-0.29.2 easyconfig: "find /usr" should not descend into other filesystems

easybuild/easyconfigs/x/X11/X11-20220504-GCCcore-11.3.0.eb
=> {vis}[GCCcore/11.3.0] X11 v20220504

easybuild/easyconfigs/c/cairo/cairo-1.17.4-GCCcore-11.3.0.eb, easybuild/easyconfigs/g/GLib/GLib-2.72.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.72.0-GCCcore-11.3.0.eb, easybuild/easyconfigs/p/pixman/pixman-0.40.0-GCCcore-11.3.0.eb
=> {vis}[GCCcore/11.3.0] cairo v1.17.4, GObject-Introspection v1.72.0, GLib v2.72.1, ... w/ Python 3.10.4

setup.py
fixes [#790](https://github.com/easybuilders/easybuild/issues/790)
Tested with:
```
$ python3 -m venv
$ source venv/bin/activate
$ cd easybuild-framework/
$ pip install .
$ cd ../easybuild-easyblocks/
$ pip install .
$ cd ../easybuild-easyconfigs/
$ pip install .
```
And `$ eb --search pytorch` shows expected output.
Two tests with:
* updating setuptools to latest (61.2.0)
* using EB installed Python 3.9.5, which has 56.0.0
* using OS Python 3.6.8 which has 39.2.0
=> fix installation with setuptools>=61 by explicitly declaring there are no Python packages

easybuild/easyconfigs/f/FFTW.serial/FFTW.serial-3.3.10-GCC-11.3.0.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.10-GCC-11.3.0.eb
using --new-pr but manually adjusted
Note that since FFTW puts MPI functionality in separate libraries (such as `libfftw3f_mpi.so.3.5.8`) the concerns raised by @Micket in https://github.com/easybuilders/easybuild/issues/649#issuecomment-692744500 that apply to HDF5 and netCDF don't apply for FFTW (or Boost).
=> {numlib}[GCC/11.3.0] FFTW v3.3.10

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-GCC-10.3.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1-GCC-11.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.1_build-with-internal-cuda-header.patch, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.4-GCC-11.3.0.eb
If libcuda.so is not found then Open MPI will warn, but this is a
common situation if the base Open MPI tries to find libcuda.so even
on nodes without GPUs. Therefore disable this warning by default
if we use --with-cuda=internal in configure.
edit (by @boegel): just for reference, here's the warning that is produced without this enhanced patch:
```
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you …
```
=> eliminate benign libcuda warning when OpenMPI is configured with --with-cuda=internal

easybuild/easyconfigs/c/Clang/Clang-12.0.1-GCCcore-10.3.0-CUDA-11.3.1.eb, easybuild/easyconfigs/c/Clang/Clang-13.0.1-GCCcore-11.2.0-CUDA-11.4.1.eb
requires #https://github.com/easybuilders/easybuild-easyblocks/pull/2729 to pass the sanity checks
=> {compiler}[GCCcore/10.3.0,GCCcore/11.2.0] Clang v12.0.1, Clang v13.0.1

easybuild/easyconfigs/r/Rust/Rust-1.60.0-GCCcore-11.3.0.eb
=> add sysroot patch to Rust 1.60.0 (GCCcore/11.3.0)

easybuild/easyconfigs/c/cryoDRGN/cryoDRGN-0.3.5-foss-2021a-CUDA-11.3.1.eb
cfr. https://github.com/zhonge/cryodrgn/issues/81, which is fixed with https://github.com/zhonge/cryodrgn/commit/80aa37612a5eda018f0553a23a26c8ad38fd2459, which is included in cryoDRGN v0.3.5
=> in-place update for cryoDRGN to v0.3.5 with foss/2021a to fix compatibility issue with PyTorch v1.10

easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
As usual, only actual change in the "new" source tarballs is the publication date in the `DESCRIPTION` file:
```diff
$ diff -ru class.old class
diff -ru class.old/DESCRIPTION class/DESCRIPTION
--- class.old/DESCRIPTION       2022-01-13 09:05:10.000000000 +0100
+++ class/DESCRIPTION   2022-01-16 11:24:56.000000000 +0100
@@ -19,4 +19,4 @@
William Venables [cph]
Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
Repository: CRAN
-Date/Publication: 2022-01-13 08:05:10 UTC
+Date/Publication: 2022-01-16 10:24:56 UTC
diff -ru class.old/MD5 class/MD5
--- class.old/MD5       2022-01-13 09:05:10.000000000 +0100
+++ class/MD5   2022-01-16 11:24:56.000000000 +0100
@@ -1,4 +1,4 @@
-c85caea72c963aee6dfa23c3c0309fc0 *DESCRIPTION
+e965faf1b6a7e86497d8047c9c255042 *DESCRIPTION …
```
=> add alternative checksums for class, nnet, spatial extensions in R v4.2.0 easyconfig

easybuild/easyconfigs/g/GCTA/GCTA-1.94.0beta-gfbf-2022.05.eb, easybuild/easyconfigs/s/SpectrA/SpectrA-1.0.1-GCCcore-11.3.0.eb
=> {bio,math}[GCCcore/11.3.0,gfbf/2022.05] GCTA v1.94.0beta, SpectrA v1.0.1

easybuild/easyconfigs/m/Mmg/Mmg-5.6.0-gompi-2021b.eb, easybuild/easyconfigs/m/Mmg/mmg-5.6.0_remove_ci_tests.patch
Fixes #15691 
I also run the test sequentially now since these are so quick anyway and it's more readable like this.
=> Rework Mmg-5.6.0 tests, fixes #15662

easybuild/easyconfigs/n/netCDF/netCDF-4.9.0-gompi-2022.05.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.9.0_fix-lib-name.patch, easybuild/easyconfigs/n/netCDF/netCDF-4.9.0_fix-linking-errors.patch
I intended to actually open #15676 with netCDF v4.9.0, but apparently I managed to screw that up 😅 
(opened as draft PR, because compilation fails even though it worked fine with v4.8.1...)
=> [gompi/2022.05] in-place update to netCDF v4.9.0

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b.eb
non-CUDA version of TensorFlow 2.7.1. Requires the patches from:
=> {lib}[foss/2021b] TensorFlow v2.7.1 w/ Python 3.9.6

easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb
fixes the same issue I also saw in 4.2.1: https://github.com/easybuilders/easybuild-easyconfigs/pull/15767#issuecomment-1175049808
=> add Autotools build dependency to R 4.2.0 w/ foss 2021b

test/easyconfigs/easyconfigs.py
Fixes failed tests in https://github.com/easybuilders/easybuild-easyconfigs/pull/15910
=> exclude Binary, PackedBinary and JAR easyblocks from binutils build requirements

easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021a-kokkos.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-foss-2021b-kokkos.eb
We haven't made a release yet and the first update for the latest stable version of LAMMPS has landed, so makes sense to update the sources
=> Update LAMMPS 23Jun2022 for latest bugfix sources

easybuild/easyconfigs/p/PyOpenCL/PyOpenCL-2021.2.13-foss-2021b.eb
All easyconfigs are `vis` so I am keeping it.
=> {vis}[foss/2021b] PyOpenCL v2021.2.13 w/ Python 3.9.6

easybuild/easyconfigs/n/netCDF/netCDF-4.9.0-gompi-2022a.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.9.0_skip-nasa-test.patch
=> Skip NASA performance test in netCDF

easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCC-11.3.0.eb, easybuild/easyconfigs/s/SoX/SoX-14.4.2-GCCcore-11.3.0.eb
Hi.
Since the existing SoX is built on GCC/8.3.0, I decided to upgrade it and add support for other sound file types after receiving a request for SoX some time ago.
Edit:
To be absolutely clear, here are the changes in supported file formats
```
OPTIONAL FILE FORMATS
amrnb......................no
amrwb......................no
-flac.......................no
+flac.......................yes
gsm........................yes (in-tree)
lpc10......................yes (in-tree)
-mp2/mp3....................no
+mp2/mp3....................yes
id3tag....................no
- lame......................no
+ lame......................yes
+ lame id3tag...............yes
+ dlopen lame...............no
mad.......................no
twolame...................no
-oggvorbis..................no …
```
=> {data}[GCCcore/11.3.0] SoX w/ GCCcore/11.3.0 + additional format support

.github/workflows/linting.yml, .github/workflows/unit_tests.yml
see also https://github.com/actions/runner-images/issues/6002
=> update CI workflows to use Ubuntu 20.04 (since Ubuntu 18.04 is deprecated)

test/easyconfigs/easyconfigs.py
Extension patches may use templates so use `collect_exts_file_info` to gather the information about extensions and their sources and patches.
See https://github.com/easybuilders/easybuild-easyconfigs/pull/15968
=> refactor checksum test for extensions to use collect_exts_file_info

easybuild/easyconfigs/g/GTK2/GTK2-2.24.33-GCCcore-11.3.0.eb, easybuild/easyconfigs/g/Ghostscript/Ghostscript-9.56.1-GCCcore-11.3.0.eb
Currently, Ghostscript refers to GTK2 installed on OS level, I think it's better to include GTK2 as a dependency.
=> {tools/vis}[GCCcore/11.3.0] Ghostscript v9.56.1, GTK2 v2.24.33

easybuild/easyconfigs/r/RheoTool/RheoTool-5.0-foss-2019b.eb
https://github.com/hpcugent/eb_inuits/issues/263
=> {cae}[foss/2019b] RheoTool v5.0

test/easyconfigs/easyconfigs.py
requires:
* https://github.com/easybuilders/easybuild-framework/pull/4069
=> make check for toolchain value in dependency spec in easyconfigs test suite aware that dumped easyconfig uses SYSTEM constant

easybuild/easyconfigs/m/MaxQuant/MaxQuant-2.0.3.0-GCCcore-11.2.0.eb
Amends ``$EBROOTMAXQUANT`` to ``%(installdir)s`` as this variable would be undefined (as a TCL variable).
=> fix set-alias statements for MaxQuant v2.0.3.0

test/easyconfigs/easyconfigs.py
add ncbi-vdb 3.0.0 to test/easyconfigs/easyconfigs.py multidep execption for HDF5 1.10.x
=> ncbi-vdb-3.0.0 requires multidep exception for HDF5

easybuild/easyconfigs/l/libpsl/libpsl-0.21.1-GCCcore-11.2.0.eb
The existing download link in this doesn't work anymore. This file was added by #16087.
=> Fix GitHub download link in libpsl-0.21.1-GCCcore-11.2.0.eb

easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-10.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-11.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-9.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-GCCcore-9.3.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-GCCcore-7.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-GCCcore-7.3.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-GCCcore-8.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.9-GCCcore-8.3.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.32-GCCcore-7.3.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.33-GCCcore-8.2.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-10.2.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-11.2.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-8.3.0.eb, easybuild/easyconfigs/l/libxslt/libxslt-1.1.34-GCCcore-9.3.0.eb
closes https://github.com/easybuilders/easybuild-easyconfigs/issues/16419
updates sources for all relatively recent easyconfigs (`GCCcore/7.3.0` and onwards)
=> update libxml2, libxslt sources to use gnome.org

.github/workflows/linting.yml, .github/workflows/unit_tests.yml
Save (free) CPU hours by canceling running actions on the same branch, e.g. after a re-push on a PR
=> Cancel old GithubAction runs

easybuild/easyconfigs/g/git/git-2.38.1-GCCcore-12.2.0-nodocs.eb
Git subtree is part of git since 1.7, and is default on OS git - we shouldn't have less functionality
=> install subtree support for git 2.38.1

easybuild/easyconfigs/g/git/git-2.36.0-GCCcore-11.3.0-nodocs.eb
Git subtree is part of git since 1.7, and it gets installed by default on the OS package of git.
=> install subtree support for git 2.36.0

easybuild/easyconfigs/m/MRCPP/MRCPP-1.4.1-foss-2022a.eb, easybuild/easyconfigs/m/MRChem/MRChem-1.1.1-foss-2022a.eb, easybuild/easyconfigs/x/XCFun/XCFun-2.1.1-GCCcore-11.3.0.eb
Trivial version upgrade of MRChem with dependencies:
- `XCfun-2.1.1-GCCcore-11.3.0`
- `MRCPP-1.4.1-foss-2022a`
- `MRChem-1.1.1-foss-2022a`
=> {chem}[foss/2022a] MRChem v1.1.1 w/ Python-3.10.4

easybuild/easyconfigs/c/cell2location/cell2location-0.05-alpha-fosscuda-2020b.eb, easybuild/easyconfigs/h/Hyperopt/Hyperopt-0.2.4-intel-2019b-Python-3.7.4-Java-1.8.eb, easybuild/easyconfigs/h/Hyperopt/Hyperopt-0.2.5-fosscuda-2020b.eb
We have easyconfigs for Hyperopt with both names `Hyperopt` and `hyperopt`. Consolidate names on Hyperopt.
=> rename hyperopt to Hyperopt, to be consistent with existing Hyperopt easyconfigs

easybuild/easyconfigs/d/dlb/dlb-3.2-gompi-2022a.eb, easybuild/easyconfigs/d/dlb/dlb-3.2-iimpi-2022a.eb
Add dlb easyconfigs.
DLB is a dynamic library designed to speed up HPC hybrid applications
(i.e., two levels of parallelism) by improving the load balance of the
outer level of parallelism (e.g., MPI) by dynamically redistributing the
computational resources at the inner level of parallelism (e.g., OpenMP).
at run time.
More info at https://pm.bsc.es/dlb.
=> Add easyconfigs: dlb

easybuild/easyconfigs/p/Python/Python-3.10.8-GCCcore-12.2.0.eb
setuptools >= 64.0 has some breaking changes (see [setuptools history](https://setuptools.pypa.io/en/latest/history.html#v64-0-0)) that are likely to cause trouble with various Python packages which are not aware of that yet, or which need time to resolve the problems that pop up because of that.
When installing `numpy` on top of setuptools 65.5.1, we hit this for example:
```
File "/software/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
raise AttributeError(attr)
AttributeError: fcompiler. Did you mean: 'compiler'?
error: subprocess-exited-with-error
```
(see also https://github.com/numpy/numpy/issues/22157)
=> downgrade to setuptools 63.4.3 in Python 3.10.8 easyconfig

easybuild/easyconfigs/l/libwpe/libwpe-1.13.3-GCCcore-11.2.0.eb, easybuild/easyconfigs/l/libwpe/libwpe-1.13.3_include-string-before-poison.patch
also removed the `parallel = 2` restriction, since it builds fine with more cores.
=> libwpe 1.13.3: add patch to avoid build issues on CentOS 7

test/easyconfigs/easyconfigs.py
`ncbi-vdb` 3.0.0 is needed for `SRA-Toolkit 3.0.0` (which is needed for Finder).
See more:
https://github.com/easybuilders/easybuild-easyconfigs/pull/16908
=> Add ncbi-vdb to test exceptions

easybuild/easyconfigs/n/ncbi-vdb/ncbi-vdb-3.0.0-gompi-2022a.eb, test/easyconfigs/easyconfigs.py
follow-up for #16376, with improvements that were implemented as a part of #16908
=> add patch to make ncbi-vdb 3.0.0 compatible with HDF5 1.12.2

easybuild/easyconfigs/b/Blosc2/Blosc2-2.6.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/p/PyTables/PyTables-3.8.0-fix-libs.patch, easybuild/easyconfigs/p/PyTables/PyTables-3.8.0-foss-2022a.eb, easybuild/easyconfigs/p/PyTables/PyTables-3.8.0_fix-find-blosc2-library-path.patch, easybuild/easyconfigs/p/PyTables/PyTables-3.8.0_fix-libs.patch, easybuild/easyconfigs/p/PyTables/blosc2-2.0.0_use-Blosc2-dep.patch, easybuild/easyconfigs/p/py-cpuinfo/py-cpuinfo-9.0.0-GCCcore-11.3.0.eb
adding easyconfigs:
`PyTables-3.8.0-foss-2022a.eb`
and patches:
`PyTables-3.8.0-fix-libs.patch`
dependency for:
https://github.com/easybuilders/easybuild-easyconfigs/pull/17142
=> {data}[foss/2022a] PyTables v3.8.0

easybuild/easyconfigs/w/wxWidgets/wxWidgets-3.2.1-GCC-11.3.0.eb
Replace git checkout with a tarball download (see PR #16292)
=> use proper source tarball instead of cloning GitHub repository for wxWidgets v3.2.1

easybuild/easyconfigs/p/Python/Python-3.10.8-GCCcore-12.2.0.eb
adds the following extensions (used to run `scipy` test suite):
- pooch
- doit
- cloudpickle
- pydevtool
- rich
- rich-click
- commonmark
- execnet
- pytest-xdist
=> add additional extensions to Python 3.10.8 (required for scipy test suite)

easybuild/easyconfigs/h/HDF5/HDF5-1.10.5-GCC-8.3.0-serial.eb, easybuild/easyconfigs/h/HDF5/HDF5-1.12.2-GCC-11.3.0-serial.eb, easybuild/easyconfigs/h/HDF5/HDF5-1.13.1-GCC-11.3.0-serial.eb
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/17219
I've left the merged `v1.13.1` there as I can't be sure of the impact of removing it. The only easyconfig that depends on one of  these (in our releases) is `h5py-2.10.0-foss-2019b-serial-Python-3.7.4.eb` and since that uses the same compiler there is no material change.
=> HDF5 has a FORTRAN api so must be at compiler level

easybuild/easyconfigs/q/Qt5/Qt5-5.15.2_fix-qtwebengine-abseil-cpp-glibc-2.34.patch, easybuild/easyconfigs/q/Qt5/Qt5-5.15.2_fix-qtwebengine-breakpad-glibc-2.34.patch, easybuild/easyconfigs/q/Qt5/Qt5-5.15.5-GCCcore-11.3.0.eb
=> add patches for Qt5 5.15.5 to fix compilation failures in abseil and breakpad with glibc 2.34

easybuild/easyconfigs/i/IMB/IMB-2021.3-gompi-2022a.eb, easybuild/easyconfigs/i/IMB/IMB-2021.3-gompi-2022b.eb, easybuild/easyconfigs/i/IMB/IMB-2021.3-iimpi-2022a.eb, easybuild/easyconfigs/i/IMB/IMB-2021.3-iimpi-2022b.eb
Easy configurations for Intel MPI Benchmarks on 2022a and 2022b toolchains
Replacing #17276, which is a mess.
=> {perf}[gompi/2022a, gompi/2022b, iimpi/2022a, iimpi/2022b] IMB v2021.3

test/easyconfigs/easyconfigs.py
Add `CUDA` to `versionsuffix_deps` next to `CUDAcore` as newer toolchains don't use `CUDAcore`.
Tested locally on top of #17272 : Before `test_dep_versions_per_toolchain_generation` fails, after this PR it succeeds.
=> Allow multiple ECs with same name if they differ by CUDA version

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-foss-2020b.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-fosscuda-2019b-Python-3.7.4.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0-fosscuda-2020b.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.0_fix-arm-vector-intrinsics.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.3-foss-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.3-foss-2021a.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.5.3_fix-aarch64-build.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.6.0-foss-2021a.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b-CUDA-11.4.1.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.7.1-foss-2021b.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4-foss-2021b.eb
The patch is actually wrong and may yield wrong results. Use the upstream patch from TF 2.10
I misunderstood the comment when creating the original patch which I noticed when checking the patches for TF 2.11 where the issue was fixed in the TensorFlow repo.
@boegel Can you test this on your ARM machine and include this for the next release please?
=> fix build of TensorFlow 2.5+ on aarch64

easybuild/easyconfigs/s/shovill/shovill-0.9.0-foss-2018a-Python-2.7.14.eb, easybuild/easyconfigs/s/shovill/shovill-1.0.4-foss-2018b-Python-2.7.15.eb, easybuild/easyconfigs/s/shovill/shovill-1.1.0-gompi-2021b.eb
- Create the script containing the (unexpanded) $EBROOT* variables.
- Quote string to be echoed to make it easier to read and avoid the escaping
Extracted from #11149
```
$ cat software/shovill/1.1.0-gompi-2021b/bin/{pilon,trimmomatic}
exec java -jar "$EBROOTPILON"/pilon-*.jar "$@"
exec java -jar "$EBROOTTRIMMOMATIC"/trimmomatic-*.jar "$@"
```
@jfgrimm @boegel
=> fix postinstallcmds in shovill easyconfigs

easybuild/easyconfigs/g/graphviz-python/graphviz-python-0.5.1-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/g/graphviz-python/graphviz-python-0.5.1-intel-2016b-Python-2.7.12.eb, easybuild/easyconfigs/g/graphviz-python/graphviz-python-0.5.1-intel-2016b-Python-3.5.2.eb, easybuild/easyconfigs/g/graphviz-python/graphviz-python-0.8.2-intel-2018a-Python-3.6.4.eb, easybuild/easyconfigs/m/MXNet/MXNet-0.9.3-foss-2016b-Python-2.7.12-R-3.3.3.eb
for https://github.com/easybuilders/easybuild-easyconfigs/issues/11824
I'm unable to build easyconfigs from these toolchains.
=> rename python graphviz to graphviz-python to avoid case-insensitiive name clash

test/easyconfigs/easyconfigs.py
Avoids repeated test runs by showing all errors at once.
Example from new output:
```
AssertionError: Verification of patches for TensorFlow-2.11.0-foss-2022a.eb failed:
Patch file TensorFlow-2.8.4_exclude-xnnpack-on-ppc.patch for extension TensorFlow is missing.
Patch file TensorFlow-2.8.4_resolve-gcc-symlinks.patch for extension TensorFlow is missing.
Patch file TensorFlow-2.9.1_remove-duplicate-gpu-tests.patch for extension TensorFlow is missing.
```
=> Combine errors of extension patch check into a single failure

easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-foss-2022b.eb, easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-intel-2022b-int64.eb, easybuild/easyconfigs/d/DIRAC/DIRAC-23.0-intel-2022b.eb
DIRAC code, release 23.0
Both, intel and foss compilations are given. In addition, a 64bits intel compilation is also provided.
=> {chem}[foss/2022b,intel/2022b,intel/2022b 64bits] DIRAC v23.0

easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-GCC-8.3.0.eb, easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-iccifort-2020.4.304.eb, easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-intel-2019a.eb, easybuild/easyconfigs/d/DFT-D3/DFT-D3-3.2.0-intel-compilers-2021.2.0.eb
Both the homepage and source urls of the `DFT-D3` easyconfigs didn't work for me, and it looks like they have been moved. This PR changes them for all existing easyconfigs.
=> update homepage and source urls of DFT-D3

easybuild/easyconfigs/c/cppzmq/cppzmq-4.9.0-GCC-11.2.0.eb, easybuild/easyconfigs/c/cppzmq/cppzmq-4.9.0.eb
easyconfig for cppzmq, a C++ binding for libzmq.
=> Added easyconfig for cppzmq

easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021a.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b-CUDA-11.5.2.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2021b.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2022a-CUDA-11.7.0.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-1.12.1-foss-2022a.eb
Based on the failures in  #17732 and #17733 I think we should revert this. It looks to be a case of fixing one flaky test and making other tests less reliable. :(
We'll also add `test_optim` to excluded tests, which it has been for 1.9.0 to 1.12.0.
I've also made sure all 1.12.1 easyconfigs skip the tests metnioned in #17615.
=> make excluded tests for PyTorch 1.12.1 consistent + also exclude flaky test_optim rather than adding patch to try and fix it

easybuild/easyconfigs/a/AOCC/AOCC-4.0.0-GCCcore-12.2.0.eb
It seems the current link does not work and has been replaced.
`== 2023-04-25 09:38:03,924 filetools.py:842 WARNING IOError occurred while trying to download http://developer.amd.com/wordpress/media/files/aocc-compiler-4.0.0.tar to /gxfs/apps/easybuild/sources/a/AOCC/aocc-compiler-4.0.0.tar: The read operation timed out`
'https://download.amd.com/developer/eula/aocc-compiler/' works well. The file and checksum are the same.
=> Replacing AOCC broken link

easybuild/easyconfigs/x/X11/X11-20190717-GCCcore-8.3.0.eb, easybuild/easyconfigs/x/X11/X11-20200222-GCCcore-9.3.0.eb, easybuild/easyconfigs/x/X11/X11-20201008-GCCcore-10.2.0.eb, easybuild/easyconfigs/x/X11/X11-20210518-GCCcore-10.3.0.eb, easybuild/easyconfigs/x/X11/X11-20210802-GCCcore-11.2.0.eb, easybuild/easyconfigs/x/X11/X11-20220504-GCCcore-11.3.0.eb, easybuild/easyconfigs/x/X11/X11-20221110-GCCcore-12.2.0.eb
adding `Doxygen` since finding it in the OS is causing build failures in `X11-20210802-GCCcore-11.2.0.eb` on our 22.04 Ubuntu systems
=> add Doxygen build dependency to X11

easybuild/easyconfigs/d/dlb/dlb-3.3.1-gompi-2022a.eb, easybuild/easyconfigs/d/dlb/dlb-3.3.1-iimpi-2022a.eb
Add version 3.3 for gompi and iimpi toolchains
=> {lib}[gompi/2022a,iimpi/2022a] dlb v3.3.1

easybuild/easyconfigs/t/texlive/texlive-20200406-GCCcore-8.3.0.eb, easybuild/easyconfigs/t/texlive/texlive-20210324-GCC-10.3.0.eb, easybuild/easyconfigs/t/texlive/texlive-20210324-GCC-11.2.0.eb, easybuild/easyconfigs/t/texlive/texlive-20220321-GCC-11.2.0.eb
* see discussion in https://github.com/easybuilders/easybuild-easyconfigs/issues/17871
tl;dr: the default `-repository` location for the install script points to the default mirror, which raises an error for version_year != 2023
=> add historical repo paths to install cmd for old versions of texlive

.github/workflows/unit_tests.yml
Fix for problem with `actions/setup-python`:
```
Error: Version 2.7 with arch x64 not found
```
Python 2.7 is no longer available in GitHub Actions, see https://github.com/actions/runner-images/issues/7401 and https://github.com/actions/setup-python/issues/672
edit: I was enabling running the tests with Python 3.11 as a replacement, but that re-introduces the problem that was fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/10326, because the `prune = 0` in `setup.cfg` doesn't seem to work anymore (see also https://github.com/pypa/setuptools/issues/1807)
=> stop running easyconfig unit tests with Python 2.7

easybuild/easyconfigs/c/Cantera/Cantera-2.6.0-foss-2022a.eb
CVodes from SUNDIALS 6.3.0 was bugged, with 6.5.1 seems working fine
```
CanteraError thrown by CVodesIntegrator::integrate:
CVodes error encountered. Error code: -4
```
In https://github.com/LLNL/sundials/releases/tag/v6.5.0
was solved: Fixed an underflow bug during root finding in ARKODE, CVODE, CVODES, IDA and IDAS.
=> {chem}[foss/2022a] Cantera v2.6.0 w/ Python 3.10.4

test/easyconfigs/easyconfigs.py
Test fix to allow several (sync) ncbi-vdb/SRA-Toolkit in the same toolchain
=> allow multiply dependency variants of ncbi-vdb for SRA-Toolkit per easyconfigs generation, as long as versions match

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4-foss-2021b-CUDA-11.4.1.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4_exclude-xnnpack-on-ppc.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4_fix-PPC-JIT.patch, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4_resolve-gcc-symlinks.patch
This adds the new TF 2.8.4 EC with CUDA support and some changes for the non-CUDA version:
- Add missing `astor` package (SYSTEM_LIB, i.e. will be downloaded when missing which we want to avoid)
- Add the profile plugin for tensorboard as we did in previous ECs
- Reorder sources, patches, checksums so they are next to each other for easier manual verification
- Replace `TensorFlow-2.1.0_fix-cuda-build.patch` by the upstream patch from https://github.com/tensorflow/tensorflow/pull/56360 so we can drop it in the future
- Fix build on PPC (that was some major work)
Once this is merged we can finish TF 2.9 in #16620 and #16008 as they suffer from the same issues as the ones fixed here.
=> Add TensorFlow-2.8.4-foss-2021b-CUDA-11.4.1.eb and fix TensorFlow-2.8.4-foss-2021b.eb

easybuild/easyconfigs/g/GMAP-GSNAP/GMAP-GSNAP-2021-12-17-GCC-11.2.0.eb, easybuild/easyconfigs/r/rnaQUAST/rnaQUAST-2.2.2-foss-2021b.eb
The original tarfile was named gmap-gsnap-2021-21-17.tar.gz but has later been corrected for the typo. Also adjust the  version in rnaQUAST-2.2.2-foss-2021b.eb which is the only place it is used.
=> fix incorrect version for GMAP-GSNAP 2021-12-17 (was 2021-21-17)

easybuild/easyconfigs/q/Qt5/Qt5-5.15.7-GCCcore-12.2.0.eb
requires PR 18007, already merged into develop.
=> patch files for QT5-5.17.7-GCCcore-12.20.0.eb for SIGSTKSZ in glibc 2.34

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.11.0-foss-2022a-CUDA-11.7.0.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.8.4-foss-2021b-CUDA-11.4.1.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.9.1-foss-2022a-CUDA-11.7.0.eb
Add the TensorFlow-2.1.0_fix-cuda-build.patch to the TensorFlow-CUDA ECs to fix failure when compilers are on symlinked paths and e.g. ccache or rpath wrappers are used.
Fixes #17892
Followup to #17058
I don't think a full test build is required as we already have experience with that patch and it used to be in 2.8.4. I verified that it applies to a git checkout of 2.9.1 and 2.11.0 as `--stop=patch` doesn't work for extensions.
=> Fix CUDA build of TensorFlow when using compiler symlinks

easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2023a.eb, easybuild/easyconfigs/f/foss/foss-2023a.eb, easybuild/easyconfigs/g/gfbf/gfbf-2023a.eb, easybuild/easyconfigs/g/gompi/gompi-2023a.eb, easybuild/easyconfigs/h/HPL/HPL-2.3-foss-2023a.eb, easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-7.1-1-gompi-2023a.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.0-gompi-2023a-fb.eb
Since `foss/2023.05` is only in `develop` (and not included in an EasyBuild release yet), we can rename it to `foss/2023a` rather than copying and retaining `foss/2023.05` as well.
=> {toolchain} foss/2023a

easybuild/easyconfigs/i/impi/impi-2021.9.0-intel-compilers-2023.1.0.eb, easybuild/easyconfigs/i/intel-compilers/intel-compilers-2023.1.0.eb, easybuild/easyconfigs/i/intel/intel-2023.03.eb
Since there's no newer Intel compilers release than 2023 update 1, which is used in `intel/2023.03`, we need to change the base compiler to `GCCcore/12.3.0`, since that's the one used for `foss/2023.05` (which will become `foss/2023a`).
=> change base for intel/2023.03 to GCCcore/12.3.0

easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2021a.eb
This update includes `-DWITH_CUDA=OFF` and `-DWITH_CUDA=ON` flags to distinguish between CPU and GPU builds.
=> {chem}[foss/2021a] ESPResSo v4.2.1

easybuild/easyconfigs/m/MXNet/MXNet-1.9.1-foss-2022a.eb, easybuild/easyconfigs/m/MXNet/mxnet-1.9.1-add_flexiblas.patch, easybuild/easyconfigs/m/MXNet/mxnet-fix_blas.patch
adding easyconfigs: MXNet-1.9.1-foss-2022a.eb and patches: mxnet-fix_blas.patch
this is a dependency for https://github.com/vscentrum/vsc-software-stack/issues/89
=> {math}[foss/2022a] MXNet 1.9.1 w/ Python 3.10.4 

easybuild/easyconfigs/b/BUFRLIB/BUFRLIB-11.3.0.2-iccifort-2020.1.217.eb, easybuild/easyconfigs/c/crossguid/crossguid-20190529-GCCcore-11.3.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.1.2-foss-2016a.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.1-GCCcore-6.4.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.1-intel-2017a.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.1-intel-2017b.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.2.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-10.3.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-11.2.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-8.2.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-8.3.0.eb, easybuild/easyconfigs/g/gflags/gflags-2.2.2-GCCcore-9.3.0.eb, easybuild/easyconfigs/l/LEMON/LEMON-1.3.1-GCC-8.2.0-2.31.1.eb, easybuild/easyconfigs/m/mctc-lib/mctc-lib-0.3.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/m/mstore/mstore-0.2.0-GCCcore-11.3.0.eb, easybuild/easyconfigs/n/NTPoly/NTPoly-2.5.1-foss-2020b.eb, easybuild/easyconfigs/n/NTPoly/NTPoly-2.5.1-intel-2020b.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.3.0-GCCcore-8.2.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-8.3.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.5.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.6.1-GCCcore-10.3.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.6.1-GCCcore-11.2.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.7.0-GCCcore-11.3.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.8.0-GCCcore-12.2.0.eb, easybuild/easyconfigs/u/utf8proc/utf8proc-2.8.0-GCCcore-12.3.0.eb
CMake defines options as uppercase:
> True if the constant is 1, ON, YES, TRUE, Y, or a non-zero number
> False if the constant is 0, OFF, NO, FALSE, N, IGNORE, NOTFOUND, the empty string, or ends in the suffix -NOTFOUND
Although it (now?) says "Named boolean constants are case-insensitive." this may not have always been the case.
So make all values for `-DBUILD_SHARED_LIBS`  ON/OFF to be consistent.
=> consistently use ON/OFF for -DBUILD_SHARED_LIBS

test/easyconfigs/easyconfigs.py
Extracted the test only from #18646 to check the file permissions of EC files on PR.
Test: ECs are readable, owner-writable and non-executable, i.e. at least 0644 without any executable flag.
An example failure I forced to test the test:
`AssertionError: CFITSIO-3.34-ictce-5.5.0.eb must be readable (owner, group, other), not executable, at least owner writable, is: 0o100511`
=> add test for easyconfig file permissions

easybuild/easyconfigs/a/at-spi2-atk/at-spi2-atk-2.38.0-GCCcore-12.3.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.36.0-GCCcore-9.3.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.38.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.40.2-GCCcore-10.3.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.40.3-GCCcore-11.2.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.44.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.46.0-GCCcore-12.2.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.49.90-GCCcore-12.3.0.eb, easybuild/easyconfigs/a/at-spi2-core/at-spi2-core-2.49.91-GCCcore-12.3.0.eb
Systems that have Dbus broker installed have this detected by `at-spi2-core` (which is an `R` dependency) and this has been seen to cause issues with builds.
=> disable detection of Dbus broker for `at-spi2-core` (+ bump at-spi2-core v2.49.90 to v2.49.91)

easybuild/easyconfigs/j/JupyterNotebook/JupyterNotebook-7.0.2-GCCcore-12.3.0.eb
Renames `notebook` easyconfig that was added by @casparvl in #18617
`JupyterNotebook` makes a lot more sense since it matches better with the `JupyterHub` and `JupyterLab` we already have.
=> rename `notebook` to `JupyterNotebook`

easybuild/easyconfigs/g/git-annex/git-annex-10.20230802-GCCcore-12.2.0.eb
Hi there, this is a module providing git-annex. This will be useful together with my other PRs 
- #18672 
- #18645
to build Datalad.
=> {base}[GCCcore/12.2.0] git-annex v10.20230802

easybuild/easyconfigs/c/Clair3/Clair3-1.0.4-foss-2022a.eb, easybuild/easyconfigs/c/Clair3/Clair3-remove_htslib.patch, easybuild/easyconfigs/c/cffi/cffi-1.15.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/m/mpath/mpath-1.1.3-GCCcore-11.3.0.eb
adding easyconfigs: cffi-1.15.1-GCCcore-11.3.0.eb, Clair3-1.0.4-foss-2022a.eb, mpath-1.1.3-GCCcore-11.3.0.eb and patches: Clair3-remove_htslib.patch
comes from https://github.com/vscentrum/vsc-software-stack/issues/146
=> {bio}[foss/2022a] Clair3 v1.0.4

.gitignore
EasyBuild creates the file `.eb-path-index` in `easybuild/easyconfigs` to cache searches which shows up in git checkouts when used directly.
As we never want to add this file to git ignore it explicitly
=> Ignore EasyConfig cache file

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-12.3.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-GCC-13.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5-intel-compilers-2023.1.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5_fix-pmix3x.patch
I needed this to use any MPI application with srun with pmix or with plain mpirun, or else I would run into OOB/TCP communication errors for even "mpirun hostname" across two nodes (see https://github.com/open-mpi/ompi/issues/11729
for another user with the same problem). This patch is taken from https://github.com/open-mpi/ompi/pull/11472 and with it, both srun and mpirun run flawlessly without further ado.
=> add patch to fix Open MPI 4.1.5 with PMIx >= 4.2.3

easybuild/easyconfigs/c/Cufflinks/Cufflinks-20190706-GCC-11.2.0.eb
This version of Cufflinks easyconfig statically links Boost libraries, so it can be used with packages that require more recent Boost versions.
(for example see  https://github.com/easybuilders/easybuild-easyconfigs/pull/16356)
=> statically link Boost 1.75 in Cufflinks v20190706 installed with GCC/11.2.0, so Boost can be changed to build dependency

easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2021a-CUDA-11.3.1.eb, easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2021a.eb, easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2022a-CUDA-11.8.0.eb, easybuild/easyconfigs/e/ESPResSo/ESPResSo-4.2.1-foss-2022a.eb
Specify python in ESPResSo. See comment [here](https://github.com/EESSI/software-layer/pull/331#issuecomment-1743480608).
=> make sure Python dependency included for ESPResSo is actually used by specifying `-DPYTHON_EXECUTABLE`

scripts/archive_old, scripts/archive_toolchain
edit: wopps wrong base branch, forgot to swap to 5.0.x
=> scripts to archive easyconfigs

easybuild/easyconfigs/a/ASE/ASE-3.22.1-gfbf-2023a.eb
Since 2022b, the ASE package has been on the gfbf toolchain level, not foss.
Unfortunately, somebody beat me to adding ASE to the 2023a toolchain, and it is back at the foss level, forcing packages that depend on ASE to be at that level too. It has not yet been released, so it is not too late to move it to gfbf/2023a.
Fixes issue #19039 .
=> Move ASE from foss/2023a tol gfbf/2023a

easybuild/easyconfigs/c/casacore/casacore-3.4.0-foss-2021b.eb
Running tests for casacore 3.5.0, we discovered that GSL was missing as a dependency for casacore 3.4.0
The test report:
https://gist.github.com/boegelbot/3e68e69278124da4ab5ab1b64d497db4
=> Adding missing GSL dependency to casacore-3.4.0-foss-2021b

easybuild/easyconfigs/a/AutoDock-GPU/AutoDock-GPU-1.5.3-GCC-10.3.0-CUDA-11.3.1.eb, easybuild/easyconfigs/a/AutoDock-GPU/AutoDock-GPU-1.5.3-GCC-11.3.0-CUDA-11.7.0.eb, easybuild/easyconfigs/b/BayesTraits/BayesTraits-3.0.2-Linux.eb, easybuild/easyconfigs/e/EZC3D/EZC3D-1.5.2-foss-2022a.eb, easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.8-foss-2021a.eb, easybuild/easyconfigs/g/garnett/garnett-0.1.20-foss-2020b-R-4.0.3.eb, easybuild/easyconfigs/g/gmsh/gmsh-4.11.1-foss-2022a.eb, easybuild/easyconfigs/g/gmsh/gmsh-4.7.1-foss-2020a-Python-3.8.2.eb, easybuild/easyconfigs/g/gmsh/gmsh-4.7.1-intel-2020a-Python-3.8.2.eb, easybuild/easyconfigs/g/gmsh/gmsh-4.9.0-foss-2021a.eb, easybuild/easyconfigs/k/KMC/KMC-3.2.1-GCC-11.2.0-Python-2.7.18.eb, easybuild/easyconfigs/k/KMC/KMC-3.2.1-GCC-11.2.0.eb, easybuild/easyconfigs/k/KMC/KMC-3.2.2-GCC-12.2.0.eb, easybuild/easyconfigs/m/meshtool/meshtool-16-GCC-10.2.0.eb, easybuild/easyconfigs/m/meshtool/meshtool-16-GCC-9.3.0.eb, easybuild/easyconfigs/m/molmod/molmod-1.4.5-foss-2020a-Python-3.8.2.eb, easybuild/easyconfigs/m/molmod/molmod-1.4.5-intel-2020a-Python-3.8.2.eb, easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2020b.eb, easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2021a.eb, easybuild/easyconfigs/m/molmod/molmod-1.4.8-foss-2021b.eb, easybuild/easyconfigs/p/Paraver/Paraver-4.11.1-foss-2022a.eb, easybuild/easyconfigs/p/Paraver/Paraver-4.9.2-foss-2021a.eb, easybuild/easyconfigs/p/popscle/popscle-0.1-beta-20210505-GCC-11.3.0.eb, easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2020b-R-4.0.3.eb, easybuild/easyconfigs/q/Qualimap/Qualimap-2.2.1-foss-2021b-R-4.1.2.eb, easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.4-GCCcore-10.2.0.eb, easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.4-GCCcore-9.3.0.eb, easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.5-GCCcore-10.3.0.eb, easybuild/easyconfigs/t/TCLAP/TCLAP-1.2.5-GCCcore-11.2.0.eb
There are some typos in the docs/version-specific/supported-software.md document reported by codespell tool [1]. Most often these issues comes from the upstream description of the software, which has usually been corrected since the creation of the easyconfig file.
This commit fixes the typo issues in software description for non-archived easyconfig files.
[1] https://github.com/codespell-project/codespell
=> Fix some typos found in software descriptions

easybuild/easyconfigs/f/flook/flook-0.8.1-GCC-11.3.0.eb, easybuild/easyconfigs/f/flook/flook-0.8.1_flook.pc.in.patch
=> {data}[GCC/11.3.0] flook v0.8.1

easybuild/easyconfigs/o/Optuna/Optuna-3.1.0-foss-2022a.eb
```
ERROR: Traceback (most recent call last):
File "/scratch/brussel/vo/000/bvo00005/vsc10001/easybuild-framework/easybuild/main.py", line 135, in build_and_install_software
(ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
File "/scratch/brussel/vo/000/bvo00005/vsc10001/easybuild-framework/easybuild/framework/easyblock.py", line 4256, in build_and_install_one
result = app.run_all_steps(run_test_cases=run_test_cases)
File "/scratch/brussel/vo/000/bvo00005/vsc10001/easybuild-framework/easybuild/framework/easyblock.py", line 4135, in run_all_steps
self.run_step(step_name, step_methods)
File "/scratch/brussel/vo/000/bvo00005/vsc10001/easybuild-framework/easybuild/framework/easyblock.py", line 3970, in run_step
step_method(self)()
File …
```
=> replace format tag with explicit extension name in Optuna v3.0.3

easybuild/easyconfigs/l/LERC/LERC-3.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/l/LERC/LERC-3.0-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-12.2.0.eb, easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-12.3.0.eb
The LERC test binary was compiled in the sanity check step, but that doesn't pick up the RPATH wrappers when RPATH linking is enabled. This, in turn, leads to errors when `$LD_LIBRARY_PATH` is filtered as well:
```
./lerctest: error while loading shared libraries: libLerc.so.4: cannot open shared object file: No such file or directory
```
This PR fixes that by doing the compilation of the test binary as part of `postinstallcmds`, and also stores both the source and binary in a subdir of the installation directory. The latter should make sure that it still works if `--sanity-check-only` is used.
=> compile LERC test binary in `postinstallcmds` to fix sanity check error when RPATH linking is enabled

easybuild/easyconfigs/k/kim-api/kim-api-2.3.0-GCC-11.3.0.eb
There are Fortran .mod files in kim-api, so we should move it (see https://github.com/easybuilders/easybuild-framework/pull/4389)
=> move kim-api/2.3.0-GCCcore-11.3.0 to GCC

easybuild/easyconfigs/k/kim-api/kim-api-2.3.0-GCC-12.3.0.eb, easybuild/easyconfigs/o/openkim-models/openkim-models-20210811-GCC-12.3.0.eb
There are Fortran .mod files in kim-api, so we should move it (see https://github.com/easybuilders/easybuild-framework/pull/4389)
=> move kim-api/2.3.0-GCCcore-12.3.0 to GCC

test/easyconfigs/easyconfigs.py
`test_dep_versions_per_toolchain_generation` fails because the versions with and without Python-bindings can be used as dependencies.
I extracted the refactoring to #19355 in case that needs discussion. Otherwise we can just merge this Pr which closes #19355
cc @lexming @branfosj as this change is required after adding the ECs in https://github.com/easybuilders/easybuild-easyconfigs/pull/18284
=> allow Python version of Z3 to be used as a dependency

easybuild/easyconfigs/b/bcbio-gff/bcbio-gff-0.7.0-foss-2022b.eb, easybuild/easyconfigs/h/hifiasm/hifiasm-0.19.7-GCCcore-12.2.0.eb, easybuild/easyconfigs/m/MitoHiFi/MitoHiFi-3.2-foss-2022b.eb
TODO:
- fix non-functional patch (now there's a workaround in `postinstallcmds`)
adding easyconfigs: bcbio-gff-0.7.0-foss-2022b.eb, hifiasm-0.19.7-GCCcore-12.2.0.eb, MitoHiFi-3.2-foss-2022b.eb
=> {bio}[foss/2022b] MitoHiFi v3.2

test/easyconfigs/easyconfigs.py
Don't use the deprecated distutils variant causing warnings.
=> Use `LooseVersion` from easybuilt.tools

easybuild/easyconfigs/m/MPFR/MPFR-4.2.0-GCCcore-12.2.0.eb, easybuild/easyconfigs/m/MPFR/MPFR-4.2.0-GCCcore-12.3.0.eb
This patch was originally added to MPFR 4.1.0 easyconfigs (in https://github.com/easybuilders/easybuild-easyconfigs/pull/18746), but was removed in version 4.2.0. However, we are still seeing failures for the `tsprintf` test in the EESSI environment (glibc 2.37) for version 4.2.0. 
I was just reading the MPFR changelog and this page is really confusing; the page for 4.2.1 (https://www.mpfr.org/mpfr-4.2.1/#changes) refers to the changelog page of 4.2.0 (https://www.mpfr.org/mpfr-4.2.0/#fixed), and the latter does seem to suggest that the bug has been solved (first item in the list). However, the code does not confirm this:
4.1.0 -> https://gitlab.inria.fr/mpfr/mpfr/-/blob/4.1.0/tests/tsprintf.c?ref_type=tags#L1653
4.2.0 -> https://gitlab.inria.fr/mpfr/mpfr/-/blob/4.2.0/tests/tsprintf.c?ref_ …
=> include MPFR 4.1.0 patch in MPFR 4.2.0 easyconfigs to fix failing tsprintf test with glibc >= 2.37

easybuild/easyconfigs/f/flook/flook-0.8.1-GCC-11.3.0.eb, easybuild/easyconfigs/f/flook/flook-0.8.1_flook.pc.in.patch
Description and author for patch file was missing for flook. This has now been added.
=> Add missing description to patch file for flook

easybuild/easyconfigs/f/fastjet-contrib/fastjet-contrib-1.053-gompi-2023a.eb, easybuild/easyconfigs/f/fastjet/fastjet-3.4.2-gompi-2023a.eb, easybuild/easyconfigs/h/HepMC3/HepMC3-3.2.6-GCC-12.3.0.eb, easybuild/easyconfigs/r/Rivet/Rivet-3.1.9-gompi-2023a-HepMC3-3.2.6.eb, easybuild/easyconfigs/s/siscone/siscone-3.0.6-GCCcore-12.3.0.eb
This PR is for https://github.com/EESSI/software-layer/pull/418
=> {phys}[gompi/2023a] Rivet v3.1.9, HepMC3 v3.2.6, fastjet v3.4.2, fastjet-contrib v1.053, siscone v3.0.6

easybuild/easyconfigs/r/Rivet/Rivet-3.1.7-gompi-2022a-HepMC3-3.2.5.eb, easybuild/easyconfigs/r/Rivet/Rivet-3.1.9-gompi-2023a-HepMC3-3.2.6.eb, easybuild/easyconfigs/y/YODA/YODA-1.9.7-GCC-11.3.0.eb, easybuild/easyconfigs/y/YODA/YODA-1.9.9-GCC-12.3.0.eb
Problem in EESSI https://github.com/EESSI/software-layer/pull/418
=> Add zlib dependency to YODA and Rivet

easybuild/easyconfigs/c/CDO/CDO-2.0.5-gompi-2021b.eb, easybuild/easyconfigs/c/CDO/CDO-2.0.6-gompi-2022a.eb, easybuild/easyconfigs/c/CDO/CDO-2.1.1-gompi-2021a.eb, easybuild/easyconfigs/c/CDO/CDO-2.2.2-gompi-2023a.eb
For EESSI we ran into an issue when building `CDO` on Arm CPUs (also see https://github.com/EESSI/software-layer/pull/427#issuecomment-1910422096):
```
cfortran.h:193:2: warning: #warning "Please specify the fortran compiler using -D flags. Try to guess the compiler used" [-Wcpp]
193 | #warning "Please specify the fortran compiler using -D flags. Try to guess the compiler used"
|  ^~~~~~~
cfortran.h:265:2: error: #error "cfortran.h:  Can't find your environment among:    - GNU gcc (gfortran) on Linux.                                           - MIPS cc and f7
7 2.0. (e.g. Silicon Graphics, DECstations, ...)         - IBM AIX XL C and FORTRAN Compiler/6000 Version 01.01.0000.0000         - VAX   VMS CC 3.1 and FORTRAN 5.4.        
- Alpha VMS DEC C 1.3 and DEC FORTRAN 6.0. …
```
=> explicitly specify Fortran compiler for recent CDO versions to fix issues on non-x86_64 architectures

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb, easybuild/easyconfigs/r/R/R-3.6.3-foss-2020a.eb, easybuild/easyconfigs/r/R/R-4.0.0-foss-2020a.eb, easybuild/easyconfigs/r/R/R-4.0.0-fosscuda-2020a.eb, easybuild/easyconfigs/r/R/R-4.0.3-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.3-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.4-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.4-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.5-foss-2020b.eb, easybuild/easyconfigs/r/R/R-4.0.5-fosscuda-2020b.eb, easybuild/easyconfigs/r/R/R-4.1.0-foss-2021a.eb, easybuild/easyconfigs/r/R/R-4.1.2-foss-2021b.eb, easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb, easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb, easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb, easybuild/easyconfigs/r/R/R-4.3.2-gfbf-2023a.eb
This removes
```
easybuild_version = '3.5.0'
```
from all not-archived R easyconfigs in the `5.0.x` branch. I cannot see that having this set serves any useful purpose in EasyBuild 5.
=> remove `easybuild_version = '3.5.0'` from R easyconfigs

easybuild/easyconfigs/m/matplotlib/matplotlib-3.7.2-gfbf-2023a.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-3.8.2-gfbf-2023b.eb
`meson(-python)` is not a runtime requirement for `maplotlib`
=> demote meson-python to a build dep in matplotlib

easybuild/easyconfigs/l/libarchive/libarchive-3.6.2-GCCcore-12.3.0.eb
we're not building `libarchive` with `libiconv` as a dependency, and it's not hard required. However, the `libarchive.pc` file has an `iconv` entry, causing software picking up `libarchive` via `pkg{conf,-config}`  to error. Building with `libiconv` doesn't even fix this, since `libiconv` installs no `libiconv.pc` file 
=> strip iconv from pkgconfig file for libarchive v3.6.2

test/easyconfigs/easyconfigs.py
Currently we see the information for the [command we run](https://github.com/easybuilders/easybuild-easyconfigs/actions/runs/7947681784/job/21696808255?pr=19887#step:8:137) repeated several times.
```
>> running command:
[started at: 2024-02-18 08:25:30]
[working dir: /home/runner/work/easybuild-easyconfigs/easybuild-easyconfigs]
[output saved to /tmp/eb-ezpo529j/eb-6nea9o24/run-shell-cmd-output/git-wp5r1raf/out.txt]
git merge-base 5.0.x HEAD
>> command completed: exit 0, ran in < 1s
Merge base for 5.0.x and HEAD: f92b7bda2b783094292b158b2ac99ff248ac39c1
```
This change removes this, so the [output is much cleaner](https://github.com/easybuilders/easybuild-easyconfigs/actions/runs/7942197227/job/21685268172?pr=19886#step:8:137).
This is also closer to the existing output, see …
=> add `hidden=True` to `run_shell_cmd` use in testsuite

easybuild/easyconfigs/w/WIEN2k/WIEN2k-19.2-intel-2020b.eb, easybuild/easyconfigs/w/WIEN2k/WIEN2k-21.1-intel-2021a.eb
#19881
This copies over the instructions from the newer `WIEN2k` easyconfigs.
=> add `download_instructions` to WIEN2k easyconfigs

easybuild/easyconfigs/p/PEAR/PEAR-0.9.11-GCC-10.3.0.eb, easybuild/easyconfigs/p/PEAR/PEAR-0.9.11-GCC-11.2.0.eb, easybuild/easyconfigs/p/PEAR/PEAR-0.9.11-GCCcore-9.3.0.eb
This copies in the instructions from the latest easyconfig (`PEAR-0.9.11-GCC-11.3.0.eb`) which uses a more direct link to the download page.
=> add `download_instructions` to PEAR easyconfigs

easybuild/easyconfigs/d/dlb/dlb-3.4-gompi-2023b.eb, easybuild/easyconfigs/d/dlb/dlb-3.4-iimpi-2023b.eb
Add dlb version 3.4 for gompi and iimpi toolchains.
I have been suggested before to remove the toolchain from the Python dependency, but I have not been able to build it this time for some reason. Feel free to correct if there's a better way.
=> {lib}[gompi/2023b,iimpi/2023b] dlb v3.4

easybuild/easyconfigs/g/GHC/GHC-9.2.2-x86_64.eb, easybuild/easyconfigs/g/git-annex/git-annex-10.20230802-GCCcore-12.2.0.eb
despite using the `GCCcore 12.2.0` toolchain, `git-annex-10.20230802-GCCcore-12.2.0.eb` currently has a runtime dependency on `('GCC', '12.2.0', '', SYSTEM)`
also adds `-std=c++14` to `CXXFLAGS` for the `ncurses` component, to let it build with newer system compilers
=> replace SYSTEM-level GCC dependency in git-annex with binutils

easybuild/easyconfigs/p/Perl-bundle-CPAN/Net-SSLeay-1.92_fix.patch, easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb
This patch is required when installing on a RHEL 9.x system where `OpenSSL/1.1` is being replaced with `OpenSSL/3` with a hook (to avoid using an OpenSSL 1.1.x that is built from source as opposed to using the system OpenSSL).
=> add patch to fix failing tests with OpenSSL 3.x for Net-SSLeay v1.92 extension in Perl-bundle-CPAN v5.36.1

easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-12.x_riscv_multiarch_support.patch, easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
This fixes an issue where building GCC on RISC-V will fail due to:
```
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
27 | #include <bits/libc-header-start.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106271 and https://bugs.gentoo.org/890636.
Also depends on https://github.com/easybuilders/easybuild-easyblocks/pull/3256.
=> add multiarch support for RISC-V to all GCCcore 12.x and 13.x easyconfigs

easybuild/easyconfigs/f/Flye/Flye-2.9.3-GCC-10.3.0.eb, easybuild/easyconfigs/f/Flye/Flye-2.9.3-GCCcore-10.3.0.eb
I am installing a deck of bioinformatics tools for a number of trainings, all under the 2021a toolchain. That's why this latest version of Flye is compiled with an older toolchain.
=> {bio}[GCC/10.3.0] Flye v2.9.3

easybuild/easyconfigs/d/Delft3D/Delft3D-4.04.01-foss-2022a-FLOW.eb, easybuild/easyconfigs/o/OmegaFold/OmegaFold-1.1.0-foss-2022a-CUDA-11.7.0.eb, easybuild/easyconfigs/r/ReaxFF/ReaxFF-2.0-GCC-11.3.0-sim.eb
Those will become a SyntaxError in some Python version, so that suppression to make CI pass isn't a good idea, because that sequence **IS invalid**, no matter what flake8 says.
Solution is either to use raw strings or remove the escapes.
For OmegaFold it isn't required as an escaped space is used just to make for nice indentation which isn't required at this place.
FYI: `ReaxFF-2.0-GCC-11.3.0-sim.eb` requires a registration to download the source. However in that file only the comment was removed, so a rebuild isn't exactly required to check
=> Remove flake8 suppressions for invalid escape sequences

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3-foss-2023a.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3-intel-2023a.eb
Added easyconfig files for QE 7.3 working with new easyblock from [PR-3241](https://github.com/easybuilders/easybuild-easyblocks/pull/3241)
Also ran some performance testing on a workstations with an intel i9-13900k.
After taking into account the presence of both performance and efficiency cores, and running all tests with the same pinning for reproducibility, both the `-O3` and `-ffast-math` do not give any visible improvement at the scale this tests are being ran.
In order to properly compare the efficiency with respect to the EESSI version (compiled with older easyblock), a multi-node heavy run would be needed as what has been fixed is mostly related to Scalapack and ELPA libraries usage.
The run reported are generated using the ReFrame test from …
=> Added QuantumESPRESSO easyconfigs for 7.3 (both intel and foss)

easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-intel-2021a.eb, easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.1-intel-2022a.eb, easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-intel-2022a.eb, easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8.2-intel-2023a.eb
=> Fix several typos in GlobalArrays 5.8 configure step

easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-11.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-11.3.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-12.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-12.3.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-13.2.0.eb
Recent intel MPI might need ucx >=1.16.0 if MLNX/NVIDIA OFED >= 23.10 is installed. 
(We experienced infinite hangs with FDS/6.8.0-intel-2022b, and swapping to UCX-1.16.0-rc4 solved the problem. UCX < 1.16 did not solve the problem) Note that only AMD CPUs are affected, we did not get the same problem with Intel CPUs.
With our previous OFED 23.04 version, we did not have the problem.
=> {lib}[GCC 11.2.0-13.2.0] UCX 1.16.0-rc4

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2023.12-foss-2023a.eb, easybuild/easyconfigs/r/R/R-4.2.0-foss-2021b.eb, easybuild/easyconfigs/r/R/R-4.2.1-foss-2022a.eb, easybuild/easyconfigs/r/R/R-4.2.2-foss-2022b.eb
See https://github.com/vdorie/dbarts/issues/66. We've run into this with EESSI for versions R-bundle-CRAN-2023.12-foss-2023a.eb and R-4.2.2-foss-2022b.eb, but I've also applied the fix to the other R 4.2.x versions.
=> fix `incompatible types` errors when building the R extension `dbarts` on Arm

easybuild/easyconfigs/l/libarchive/libarchive-3.6.0_fix-tar-error-reporting.patch, easybuild/easyconfigs/l/libarchive/libarchive-3.6.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.1-GCCcore-12.2.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.2-GCCcore-12.3.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.2-GCCcore-13.1.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.7.2-GCCcore-13.2.0.eb
This is more out of abundance of caution than anything else, there's a link here to the [XZ backdoor situation](https://boehs.org/node/everything-i-know-about-the-xz-backdoor)
=> add patch to fix for libarchive to fix error reporting in tar

test/easyconfigs/easyconfigs.py
Aggregate failures and report all together.
This is especially useful when the same error is found multiple times, e.g. multiple patch files are missing.
This avoids multiple back-and-forth between CI and user updating the PR.
=> Improve test for validity of easyconfig files

easybuild/easyconfigs/o/OpenMolcas/OpenMolcas-23.06-intel-2023a.eb
no substantive changes:
```
[jfg508@login2[viking2] openmolcas]$ diff -Nru OpenMolcas-v23.06.{old,new}
diff -Nru OpenMolcas-v23.06.old/.tags OpenMolcas-v23.06.new/.tags
--- OpenMolcas-v23.06.old/.tags	2023-06-12 12:58:03.000000000 +0100
+++ OpenMolcas-v23.06.new/.tags	2023-06-12 12:58:03.000000000 +0100
@@ -1,2 +1,2 @@
1cda3772686cbf99a4af695929a12d563c795ca2
- (tag: v23.06, refs/merge-requests/635/head, refs/keep-around/1cda3772686cbf99a4af695929a12d563c795ca2)
+ (tag: v23.06, refs/keep-around/1cda3772686cbf99a4af695929a12d563c795ca2)
```
I checked other versions, and the only other one affected was 18.09 (which was already fixed)
=> add alternate checksum to OpenMolcas v23.06

easybuild/easyconfigs/b/biom-format/biom-format-2.1.15-foss-2023a.eb, easybuild/easyconfigs/s/scCODA/scCODA-0.1.9-foss-2023a.eb, easybuild/easyconfigs/s/scikit-bio/scikit-bio-0.6.0-foss-2023a.eb
The easyconfig for `scikit-bio` 0.5.9 that got merged via #20067 was using a commit ID that doesn't correspond to the 0.5.9 release at all (commit `7565847` is from 2024-03-05, while `0.5.9` release is from 2023-08-03).
This was done because `scikit-bio` 0.5.9 required a `scipy` version <= 1.10.1, which is older than what we have in SciPy-bundle 2023.07 (scipy 1.11.1).
`scikit-bio` 0.6.0 was not released yet at the time of PR #20067, but it is now (2024-03-28), so we should rectify this...
Going with 0.6.0 makes most sense, since the commit that was used is quite close to that version already (was closer than it was to 0.5.9).
The easyconfig for `biom-format` is there because `scikit-bio` 0.6.0 now requires it (it didn't yet in v0.5.9)
=> replace incorrect scikit-bio 0.5.9 with scikit-bio 0.6.0 as dependency for scCODA

easybuild/easyconfigs/a/assembly-stats/assembly-stats-1.0.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/a/assembly-stats/assembly-stats-1.0.1_fix_str_cast.patch
I was asked to install `assembly-stats` for a specific bioinformatics training, and I realized that this is the first easyconfig file for this tool. A patch file is needed to improve two lines of code in the source file and make the compiler happy.
The provided easyconfig+patch file build successfully on our Intel Skylake, Cascadelake and Icelake nodes under Rocky 8.9 OS, and using `GCCcore/11.3.0` from `2022a` toolchain.
=> assembly-stats/1.0.1-GCCcore-11.3.0

easybuild/easyconfigs/n/nanomath/nanomath-1.3.0-foss-2022b.eb
=> {bio}[foss/2022b] nanomath 1.3.0

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/Rhdf5lib-1.20.0_fix_hardcoded_path_to_mv.patch
This is now using a patch instead of the nested `sed` commands used in #20316.
=> add patch to fix hardcoded `/bin/mv` path in Rhdf5lib extension included in R-bundle-Bioconductor v3.16 + v3.18

easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.13-foss-2021a-R-4.1.0.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.14-foss-2021b-R-4.1.2.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2021b-R-4.2.0.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2022a-R-4.2.1.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2022b-R-4.2.2.eb, easybuild/easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.18-foss-2023a-R-4.3.2.eb
While debugging an Rhdf5lib build issue, I started wondering if the dependency on HDF5 in Bioconductor easyconfigs makes any sense. Rhdf5lib provides the C/C++ headers and libraries of HDF5, which is the reason why its source tarball includes a tarball of an (ancient and customized 😞 ) HDF5 version.
The Rhdf5 extension, also part of Bioconductor, depends on Rhdf5lib and provides the interface between R and HDF5. The easyconfigs had a comment `('HDF5', '1.14.0'),  # for rhdf5`, but that doesn't seem to be correct, as Rhdf5 will be using whatever Rhdf5lib provides.
Having the EB-provided HDF5 in there as well seems like a potential cause for issues, which is why I've removed it from (recent) Bioconductor easyconfigs.
Also see:
https://www.bioconductor.org/packages/release/bioc/html/Rhdf5lib. …
=> remove dependency on HDF5 in recent Bioconductor easyconfigs

easybuild/easyconfigs/u/UCX/UCX-1.15.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.15.0-add_riscv_support.patch
Support for RISC-V has been added in 1.16.0, but I backported this to 1.15.0 using https://github.com/openucx/ucx/pull/9168.
~Requires #20428 as well.~
@SebastianAchilles let me know me that this worked without #20428 for him. I originally ran into the issue solved in #20428, so I assumed this was still necessary. However, it seems that it's indeed not really necessary, as the `autoreconf` command from this PR will apparently update the `config.guess` script to a newer version that does recognize RISC-V:
```
$ grep timestamp config.guess
timestamp='2013-06-10'
$ grep riscv config.guess
$
$ grep timestamp config.guess
timestamp='2021-06-03'
$ grep riscv config.guess 
riscv32:Linux:*:* | riscv32be:Linux:*:* | riscv64:Linux:*:* | riscv64be:Linux:*:*)
```
=> add RISC-V support to UCX 1.15.0

easybuild/easyconfigs/u/UCC/UCC-1.2.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/u/UCC/UCC-1.2.0_add-riscv-support.patch
RISC-V support was added after the 1.2.0 release, but the patch file of the PR seems to work fine for 1.2.0 as well. As it's not officially supported, I'm only applying the patch on RISC-V build hosts.
=> add RISC-V support to UCC 1.2.0

easybuild/easyconfigs/n/NanoPlot/NanoPlot-1.42.0-foss-2022a.eb, easybuild/easyconfigs/n/NanoStat/NanoStat-1.6.0-foss-2022a.eb, easybuild/easyconfigs/n/nanoget/nanoget-1.19.1-foss-2022a.eb, easybuild/easyconfigs/p/pauvre/pauvre-0.2.3-foss-2022a.eb
This PR adds three easyconfigs for building `pauvre/0.2.3-foss-2022a`, `nanoget/1.19.1-foss-2022a` and eventually `NanoPlot/1.42.0-foss-2022a`.
=> {bio}[foss/2022a] NanoPlot v1.42.0, nanoget v1.19.1, pauve v0.2.3, and use nanoget 1.19.1 for Nanostat 1.6.0

easybuild/easyconfigs/b/BLIS/BLIS-0.9.0-GCC-13.2.0.eb, easybuild/easyconfigs/b/BLIS/BLIS-0.9.0_add-riscv-support.patch
RISC-V support has been added on the `master` branch of BLIS, this PR backports it to version 0.9.0. As it's not part of the official release, I've added an if statement that only applies the patch on RISC-V hosts.
=> add RISC-V support to BLIS 0.9.0

easybuild/easyconfigs/u/UCX/UCX-1.13.1-GCCcore-12.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.14.0-GCCcore-12.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.14.1-GCCcore-12.3.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.15.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-11.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-11.3.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-12.2.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-12.3.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.16.0-rc4-GCCcore-13.2.0.eb
The UCX easyconfigs for version 1.9.0 and newer are currently using `configure_cmd = contrib/configure-release`; this is a wrapper script around `./configure` which passed some predefined flags (these haven't changed for many years), see:
https://github.com/openucx/ucx/blob/master/contrib/configure-release
While trying to install UCX on RISC-V, I ran into issues with the outdated `config.guess` included with UCX. The ConfigureMake easyblock should download a newer version and use that one, but it turns out that it only does that when the `configure_cmd` script includes a certain string (`Generated by GNU Autoconf`). Though the `configure` script does include it, this is not the case for the `contrib/configure-release` wrapper script, hence that step is skipped. By appending the options …
=> use regular `configure` instead of wrapper script for recent UCX easyconfigs

easybuild/easyconfigs/j/Java/Java-21.0.2.eb
This version supports RISC-V, see https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.2%2B13.
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/3323.
=> add checksum for RISC-V version to Java 21.0.2 easyconfig

easybuild/easyconfigs/w/wfdb/wfdb-4.1.2-foss-2022a.eb
=> {lib}[foss/2022a] wfdb v4.1.2

easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.13-foss-2023a.eb, easybuild/easyconfigs/f/f90wrap/f90wrap-0.2.13_fix_old_typing.patch, easybuild/easyconfigs/m/MetalWalls/MetalWalls-21.06.1-foss-2023a.eb
Depends on easyblock from https://github.com/easybuilders/easybuild-easyblocks/pull/3311
Adds the following EC files:
- MetalWalls (https://gitlab.com/ampere2/metalwalls)
- f90wrap (with a patch not yet included in the main distribution) as a dependency to build the python interface of MetalWalls
=> {chem,devel}[foss/2023a] f90wrap v0.2.13, MetalWalls v21.06.1

easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.1.2-GCCcore-12.2.0.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-6.0-GCCcore-12.3.0.eb, easybuild/easyconfigs/f/FFmpeg/FFmpeg-6.0-GCCcore-13.2.0.eb
Building those pages apparently requires `texinfo`, as I ran into the following issue:
```
GENTEXI doc/avoptions_format.texi
GENTEXI doc/avoptions_codec.texi
HTML    doc/ffmpeg.html
makeinfo: error parsing ./doc/t2h.pm: Undefined subroutine &Texinfo::Config::set_from_init_file called at ./doc/t2h.pm line 24.
make: *** [doc/Makefile:70: doc/ffmpeg.html] Error 1
```
A `texinfo` package (version 7.1) is actually available on my system, but it looks like that specific version is causing issues: 
https://groups.google.com/g/linux.debian.bugs.dist/c/1f_eeuQd_2U
Instead of adding `texinfo` as a (heavy) build/OS dependency, this PR adds a `--disable-htmlpages` flag to recent versions, which will not build these pages.
=> add `--disable-htmlpages` to recent FFmpeg easyconfigs

easybuild/easyconfigs/g/gnupg-bundle/gnupg-bundle-20240306-GCCcore-13.2.0.eb, easybuild/easyconfigs/p/poppler/poppler-24.04.0-GCC-13.2.0.eb, easybuild/easyconfigs/t/texlive/texlive-20230313-GCC-13.2.0.eb
(almost created using eb --new-pr)
=> {devel,lib}[GCC/13.2.0] poppler v24.04.0, texlive v20230313

easybuild/easyconfigs/b/BLAST+/BLAST+-2.13.0-gompi-2022a.eb, easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.0-gompi-2022b.eb, easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.1-gompi-2023a.eb
@TopRichard found that when RPATH support is enabled BLAST+ fails on some systems (mostly on distros with more recent GCC versions, it seems) due to:
```
WARNING No '(RPATH)' found in 'readelf -d' output for /path/to/BLAST+/2.14.1-gompi-2023a/bin/run_with_lock
```
Only this executable was using RUNPATH instead of RPATH, all the other ones in the installation did have RPATH. This executable actually gets compiled at the end of the `configure` script, and it turned out that it's using the system GCC compiler (and using `--enable-new-dtags`). By debugging it a bit more and replacing my system compiler by a bash script that spits out some more information, I found that `$PATH` was actually changed, and this lead me to the following line `src/build-system/configure`:
``` …
```
=> prevent configure script of recent BLAST+ versions from prepending system paths to $PATH

easybuild/easyconfigs/b/BLAST+/BLAST+-2.13.0-gompi-2022a.eb, easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.0-gompi-2022b.eb, easybuild/easyconfigs/b/BLAST+/BLAST+-2.14.1-gompi-2023a.eb
Compiling BLAST+ on Arm fails in the configure step:
```
checking whether this system supports --with(out)-64... no
configure: error: cannot continue; please try different options
```
The `--with-64` adds `-m64` to the compiler flags, and this is not supported on Arm (and neither on for instance RISC-V). Without the flag, it just doesn't add `-m64` (which should be fine too) and I preferred that over having to add if statements for distinguishing between the different architectures.
=> remove `--with-64` from `configopts` for recent BLAST+ versions

easybuild/easyconfigs/e/EasyBuild/EasyBuild-4.9.2.eb
When this is merged, "`eb --install-latest-eb-release`" (which pulls the easyconfig for the latest EasyBuild release) will work again, without having to use `--include-easyblocks-from-pr 3358`, see also https://github.com/easybuilders/easybuild-easyblocks/pull/3358
=> rename unpacked sources for components of EasyBuild v4.9.2, to ensure that '`--install-latest-eb-release`' works with older EasyBuild versions

easybuild/easyconfigs/t/tensorboard/tensorboard-2.10.0-foss-2022a.eb, easybuild/easyconfigs/t/tensorboard/tensorboard-2.10_jupyterhub-support.patch, easybuild/easyconfigs/t/tensorboard/tensorboard-2.15.1-gfbf-2023a.eb
Changelog:
* fix issue https://github.com/tensorflow/tensorboard/pull/3142 in `tensorboard-2.10.0-foss-2022a.eb` and `tensorboard-2.15.1-gfbf-2023a.eb`
* `tensorboard-2.15.1-gfbf-2023a.eb`: replace extension on `grpcio` with regular dependency
* `tensorboard-2.15.1-gfbf-2023a.eb`: remove deprecated `tensorboard_plugin_wit` and add `tensorboard-plugin-profile` to be on par with TensorFlow v2.15.1
=> add support for JupyterHub to TensorBoard

easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-foss-2021a.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-gomkl-2021a.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.05-intel-2021a.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-foss-2021b-Python-2.7.18.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-foss-2021b.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2021.10-intel-2021b.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-foss-2022.05.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-foss-2022a.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-intel-2022.05.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2022.05-intel-2022a.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.02-gfbf-2022b.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.07-gfbf-2023a.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2023.07-iimkl-2023a.eb, easybuild/easyconfigs/s/SciPy-bundle/numpy-1.20.3_fix-fortran-compiler-error.patch
NumPy doesn't need Fortran for building but still initializes the Fortran compiler which fails when the compiler requires a different commandline argument than GCC, e.g. the Fujitsu compiler. Failure message starts with
> A valid Fortran version was not found in this string:
See https://github.com/easybuilders/easybuild-easyblocks/issues/2518 Patch is from https://github.com/numpy/numpy/pull/26502 which won't get merged but isn't necessary in numpy 1.26+
CC @migueldiascosta
=> Fix build error with numpy with some compilers

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2306-foss-2022b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2312-foss-2023a.eb
See https://github.com/easybuilders/easybuild-easyblocks/pull/3366.
=> add GMP and MPFR as dependencies to OpenFOAM v2306 and v2312

easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2022a.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2022b.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023a.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2-foss-2023b.eb, easybuild/easyconfigs/p/PyTorch/PyTorch-2.1.2_skip-memory-leak-test.patch
Result of a Slack discussion where the test fails. That it works correctly can be checked with this script (to be run after installing PyTorch):
```
import torch; import tempfile; import os;import pickle;import tracemalloc; import random
filename = tempfile.mktemp()
writer = torch._C.PyTorchFileWriter(filename)
buffers = [os.urandom(size) for size in [random.randint(1, 100) for i in range(20)]]
offsets = []
for i, buf in enumerate(buffers):
writer.write_record(str(i), buf, len(buf))
offsets.append(i)
serialized_offsets = pickle.dumps(offsets)
writer.write_record("meta", serialized_offsets, len(serialized_offsets))
writer.write_end_of_file()
num_iters = 10000
tracemalloc.start()
for i in range(num_iters):
torch._C.PyTorchFileReader(filename)
_, peak_from_string = …
```
=> Skip unreliable memory leak test in PyTorch 2.1.2

easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024.05.eb, easybuild/easyconfigs/s/SciPy-bundle/numpy-1.26.4_fix-riscv64-test-failures.patch
See https://github.com/numpy/numpy/pull/26743.
Before:
```
=========================== short test summary info ============================
FAILED core/tests/test_numeric.py::TestBoolCmp::test_float - AssertionError:
FAILED core/tests/test_umath.py::TestFPClass::test_fpclass[-4] - AssertionErr...
FAILED core/tests/test_umath.py::TestFPClass::test_fpclass[-2] - AssertionErr...
FAILED core/tests/test_umath.py::TestFPClass::test_fpclass[-1] - AssertionErr...
FAILED core/tests/test_umath.py::TestFPClass::test_fpclass[1] - AssertionError:
FAILED core/tests/test_umath.py::TestFPClass::test_fp_noncontiguous[f] - Asse...
= 6 failed, 32076 passed, 1746 skipped, 1305 deselected, 31 xfailed, 3 xpassed, 18 warnings in 1008.04s (0:16:48) =
```
After:
```
= 32082 passed, 1746 skipped, 1305 deselected, …
```
=> add patch to SciPy-bundle 2024.05 that fixes numpy test failures on RISC-V

easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.2.eb, easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.3.eb
I ran into this when installing ReFrame on a system with Cython 3:
```
==> [+pygelf] python3 -m pip install --no-cache-dir -q -r /tmp/eb-myh20jsw/tmp.V9e2PYU6tR --target=external/ --upgrade
DEPRECATION: Loading egg at /cvmfs/riscv.eessi.io/versions/20240402/software/linux/riscv64/generic/software/ReFrame/4.3.3/lib/python3.11/site-packages/pip-21.3.1-py3.11.egg is deprecated. pi
p 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
error: subprocess-exited-with-error
Getting requirements to build wheel did not run successfully.
exit code: 1
> [54 lines of output]
running egg_info
writing lib/PyYAML.egg-info/PKG-INFO
writing dependency_links to …
```
=> use PyYAML 6.0.1 instead of 6.0 for recent ReFrame versions

easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.2.0.eb, easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-11.3.0.eb, easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-12.2.0.eb, easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-12.3.0.eb, easybuild/easyconfigs/x/x265/x265-3.5-GCCcore-13.2.0.eb
This solves the following issue on RISC-V:
```
/cvmfs/riscv.eessi.io/versions/20240402/compat/linux/riscv64/usr/bin/ld: encoder/CMakeFiles/encoder.dir/analysis.cpp.o: relocation R_RISCV_HI20 against `_ZN4x26510g_log2SizeE' can not be used when making a shared object; recompile with -fPIC
/cvmfs/riscv.eessi.io/versions/20240402/compat/linux/riscv64/usr/bin/ld: encoder/CMakeFiles/encoder.dir/search.cpp.o: relocation R_RISCV_HI20 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/cvmfs/riscv.eessi.io/versions/20240402/compat/linux/riscv64/usr/bin/ld: encoder/CMakeFiles/encoder.dir/bitcost.cpp.o: relocation R_RISCV_HI20 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
<more of those....> …
```
=> enable PIC in recent x265 easyconfigs to solve compilation errors on RISC-V

test/easyconfigs/easyconfigs.py
Also extend the `sanity_pip_check` whitelist for all 2016 ECs although this won't really matter going forward. Just kept that commit as long as that check is there
=> whitelist ConfigureMakePythonPackage for sanity_check_paths CI check

easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-11.2.0.eb, easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-12.2.0.eb, easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-12.3.0.eb, easybuild/easyconfigs/l/LAME/LAME-3.100-GCCcore-13.2.0.eb
This workaround would set an environment variable with `configure_cmd_prefix`, and this is somewhat ugly. It also breaks the config.guess update functionality in the configuremake easyblock, as this will check if `configure_command` exists, and it will think it doesn't exist if the command includes this environment variable (as it's basically doing `os.path.exists("FRONTEND_LDADD='-L${EBROOTNCURSES}/lib' ./configure"`). See https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/generic/configuremake.py#L303. As LAME includes a very old config.guess, it doesn't build on RISC-V this way.
I couldn't reproduce any issues with the workaround removed, and without it LAME would indeed build fine on RISC-V, as the easyblock then does update the config.guess. So I'm …
=> add RISC-v support to recent LAME easyconfigs by removing workaround for finding libncurses

easybuild/easyconfigs/e/Extrae/Extrae-4.2.0-gompi-2023b.eb
Extrae produces segmentation faults when using libunwind in ARM architectures
=> Extrae: Make libunwind dependency architecture specific

easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-10.2.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-10.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-11.2.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-12.2.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-12.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-13.2.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-6.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-6.4.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-7.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-8.2.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-8.3.0.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-GCCcore-9.3.0.eb
Szip seems to have moved, update both the download links and the homepage.
=> Szip: Update source and homepage URLs

easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-12.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-13.2.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.16-GCCcore-12.3.0.eb
* based on issue #21105
* source_url location www.hdf5group.org no longer working. support.hdf5group.org works.
=> HDF v4.2.16-2: Rename source URL

easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-12.2.0.eb, easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-12.3.0.eb, easybuild/easyconfigs/b/BioPerl/BioPerl-1.7.8-GCCcore-13.3.0.eb
This was causing problems in https://github.com/EESSI/software-layer/pull/658 as `eb` was attempting to copy the same easyblock twice and that was failing if `EasyBuild` had a read-only installation.
=> Ensure that recent BioPerl easyconfigs use `Bundle` easyblock

easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.09.1+494-foss-2023a-Java-11-R-4.3.2.eb, easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.09.1+494-gfbf-2023a-Java-11-R-4.3.2.eb
This looks to fix https://github.com/easybuilders/easybuild-easyconfigs/pull/21167#issuecomment-2286625820
We only look to have been having this problem with https://github.com/branfosj/easybuild-easyconfigs/blob/rstudio/easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.12.1%2B402-gfbf-2023b-Java-11-R-4.3.3.eb and https://github.com/branfosj/easybuild-easyconfigs/blob/rstudio/easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2023.09.1%2B494-foss-2023a-Java-11-R-4.3.2.eb, but not with the older versions of RStudio-Server. This PR fixes `RStudio-Server-2023.09.1+494-foss-2023a-Java-11-R-4.3.2.eb`. However, there is no (merged) R-bundle-CRAN (to provide `renv`) that we can use for `RStudio-Server-2023.12.1+402-gfbf-2023b-Java-11-R-4.3.3.eb`, so I've not fixed that one.
=> stop RStudio-Server 2023.09 from installing R packages (+ move to `foss/2023a` toolchain)

easybuild/easyconfigs/p/python-igraph/python-igraph-0.10.6-foss-2022b.eb
Seems on some systems (generoso) it picked system cairo - so it did not fail 
Link with a problem: https://github.com/easybuilders/easybuild-easyconfigs/pull/21141#issuecomment-2298833068
resolves https://github.com/vscentrum/vsc-software-stack/issues/357
fix for failing sanity check:
```
AttributeError: Plotting not available; please install pycairo or cairocffi
```
=> Add missing cairo dependency for python-igraph v0.10.6

easybuild/easyconfigs/r/R-bundle-CRAN/R-bundle-CRAN-2024.06-foss-2023b.eb
#21260 added `insight`. #21272 added `performance`, `datwizard`, and `bayestestR`, but before `insight`.
Failure in https://github.com/easybuilders/easybuild-easyconfigs/pull/20913#issuecomment-2319486003
```
ERROR: dependency insight is not available for package datawizard
```
=> correct extension order in R-bundle-CRAN 2024.06

easybuild/easyconfigs/l/libdap/libdap-3.20.11-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/libdap/libdap-3.20.11-GCCcore-12.3.0.eb, easybuild/easyconfigs/l/libdap/libdap-3.20.7-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/libdap/libdap-3.20.8-GCCcore-11.2.0.eb
It looks like the source tarballs have been removed from the original source URL (https://www.opendap.org/pub/source/).
=> use source tarballs from GitHub for recent libdap easyconfigs

easybuild/easyconfigs/o/OTF2/OTF2-3.0-GCCcore-11.3.0.eb, easybuild/easyconfigs/o/OTF2/OTF2-3.0.2-GCCcore-11.2.0.eb, easybuild/easyconfigs/o/OTF2/OTF2-3.0.2-GCCcore-11.3.0.eb, easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-GCCcore-12.2.0.eb, easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-GCCcore-12.3.0.eb, easybuild/easyconfigs/o/OTF2/OTF2-3.0.3-GCCcore-13.2.0.eb
Add Python as a dependency to OTF2 versions to ensure that the toolchain Python is used. To verify, a sanity check is added which ensures that the OTF2 Python module can be loaded. As `six` is required, newer toolchains also need Python-bundle-PyPI.
Resolves #21266
=> {perf} OTF2: Use toolchain Python instead of system one

easybuild/easyconfigs/h/HDF/HDF-4.2.11-intel-2016a.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.12-intel-2017a.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.13-GCCcore-6.4.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.13-intel-2017a-no-netcdf.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-6.4.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-7.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-8.2.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.14-GCCcore-8.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-10.2.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-10.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-11.2.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-11.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-12.2.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-GCCcore-9.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-12.3.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.16-2-GCCcore-13.2.0.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.16-GCCcore-12.3.0.eb, easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.3-foss-2018b.eb, easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.3-gompi-2019b.eb, easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.3-gompi-2020b.eb, easybuild/easyconfigs/h/h4toh5/h4toh5-2.2.5-gompi-2022a.eb
Implemented from #21131.
Not sure what the policy is regarding `__archive__`.
Not sure if the exact versions of h4toh5 are still there, but the site seems in principle there.
=> consistently fix homepage + source URL for `HDF` + `h4toh5`

easybuild/easyconfigs/d/dtcmp/dtcmp-1.1.5-gompi-2024a.eb, easybuild/easyconfigs/l/libcircle/libcircle-0.3-gompi-2024a.eb, easybuild/easyconfigs/l/lwgrp/lwgrp-1.0.6-gompi-2024a.eb, easybuild/easyconfigs/m/maeparser/maeparser-1.3.1-gompi-2024a.eb, easybuild/easyconfigs/m/mpifileutils/mpifileutils-0.11.1-gompi-2024a.eb
This PR adds some files to the gompi-2024a toolchain from the new SW stage at JSC.
=> {lib, tools}[gompi/2024a] dtcmp-1.1.5, libcircle-0.3, lwgrp-1.0.6, maeparser-1.3.1, mpifileutils-0.11.1

easybuild/easyconfigs/c/cell2location/cell2location-0.05-alpha-fosscuda-2020b.eb, easybuild/easyconfigs/f/flit/flit-3.9.0-GCCcore-12.3.0.eb, easybuild/easyconfigs/f/flit/flit-3.9.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/f/flit/flit-3.9.0-GCCcore-13.3.0.eb, easybuild/easyconfigs/g/GI-DocGen/GI-DocGen-2023.3-GCCcore-12.3.0.eb, easybuild/easyconfigs/o/OpenStackClient/OpenStackClient-5.5.0-GCCcore-10.2.0.eb, easybuild/easyconfigs/o/OpenStackClient/OpenStackClient-5.8.0-GCCcore-11.2.0.eb, easybuild/easyconfigs/o/OpenStackClient/OpenStackClient-6.0.0-GCCcore-12.2.0.eb, easybuild/easyconfigs/p/PyClone/PyClone-2020.9b2-GCCcore-10.2.0.eb, easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2023.06-GCCcore-12.3.0.eb, easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2023.10-GCCcore-13.2.0.eb, easybuild/easyconfigs/p/Python-bundle-PyPI/Python-bundle-PyPI-2024.06-GCCcore-13.3.0.eb, easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.6.0-GCCcore-12.3.0.eb, easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.8.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/s/setuptools-rust/setuptools-rust-1.9.0-GCCcore-13.3.0.eb, easybuild/easyconfigs/v/virtualenv/virtualenv-20.23.1-GCCcore-12.3.0.eb, easybuild/easyconfigs/v/virtualenv/virtualenv-20.24.6-GCCcore-13.2.0.eb, easybuild/easyconfigs/v/virtualenv/virtualenv-20.26.2-GCCcore-13.3.0.eb
It is easier in the top-level and might cause confusion with https://github.com/easybuilders/easybuild-easyblocks/pull/3428
=> use top-level parameters for `use_pip` & co instead of `exts_default_options` for `PythonBundle` easyconfigs

test/easyconfigs/easyconfigs.py
Some bundle easyconfigs have a checksums parameter. The current test code clears that unconditionally which makes the test fail when it should not.
As we know the easyconfig dict will be modified we can just make a copy here.
=> Fix checksum checks for easyconfigs using a `Bundle`-like easyblock in easyconfigs test suite

test/easyconfigs/easyconfigs.py
The test fails if the easyconfig cache file .eb-path-index is present. This is caused by checking all files instead of only easyconfigs. Fix that, directly ignore the TEMPLATE.eb and replace `assertTrue(False`
=> Fix test_easyconfig_locations when cache is present

easybuild/easyconfigs/a/ATK/ATK-2.38.0-GCCcore-13.3.0.eb, easybuild/easyconfigs/g/Gdk-Pixbuf/Gdk-Pixbuf-2.42.11-GCCcore-13.3.0.eb
Added ATK and Gdk-Pixbuf after the GObject-Introspection fix (part of the SW stage at JSC)
=> {vis}[GCCcore/13.3.0] ATK-2.38.0, Gdk-Pixbuf-2.42.11

test/easyconfigs/easyconfigs.py
Fix for failing CI
> easybuild.tools.build_log.EasyBuildError: "Missing checksum for DeltaLake-0.15.1_remove-obsolete-pyarrow-hotfix.patch in {'addr2line-0.21.0.tar.gz': '8a30b2e23b9e17a9f90641c7ab1549cd9b44f296d3ccbf309d2863cfe398a0cb'}"
This problem arose due to the change in https://github.com/easybuilders/easybuild-easyblocks/pull/3448, where `self.cfg = self.cfg.copy()` was added to the Cargo constructor before `self.cfg['sources']` (was equal to the input `ec` instance) is being changed.
Closes #21416 which addresses the issue in a more specific way. This PR is more generic.
=> account for crates for easyconfigs using Cargo-based easyblock when determining checksums for patches

easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-foss-2020a-Python-3.8.2.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.1-fosscuda-2020a-Python-3.8.2.eb
=> remove `exts_default_options` from TensorFlow 2.3.1

.gitignore
Such paths should never be committed:
- `.eb_bak` files are remnants after `eb --inject-checksums`
- `.out` files are log remnants after `eb --job`
- `.venv/` are probably created for ad-hoc testing
=> add `*.eb_bak_*`, `*.out`, `.venv/` to `.gitignore`

easybuild/easyconfigs/g/git-annex/git-annex-10.20230802-GCCcore-12.2.0.eb, easybuild/easyconfigs/g/git-annex/git-annex-10.20230802-GCCcore-12.3.0.eb, easybuild/easyconfigs/g/git-annex/git-annex-10.20240731-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libnsl/libnsl-2.0.1-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libtirpc/libtirpc-1.3.5-GCCcore-13.3.0.eb
Hey,
when we updated some of our nodes to Rocky9, I noticed, that in the installation of git-annex, libnsl is a system-requirement, although it doesn't have to be. It is already in the GCCcore toolchain. In order to be more system-independent, I suggest using the EB-version of libnsl to build git-annex.
=> use proper dependency for libnsl in git-annex

easybuild/easyconfigs/c/Check/Check-0.15.2-GCCcore-13.3.0.eb, easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.7-GCCcore-13.3.0.eb
Add GOTCHA, a library which helps to wrap function calls. This will get relevant for tools like Score-P.
The build itself is straight-forward, but parallel builds need to be disabled due to issues when enabling tests. 
This is not a huge problem though, as the library builds quickly (~20 seconds on my machine).
=> {devel,lib}{GCCcore/13.3.0} Add GOTCHA v1.0.7, Check v0.15.2

easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-foss-2021a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.2-intel-2021a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-foss-2021b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.0-foss-2021b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.8.1-foss-2022a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2022b.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.0-foss-2023a.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.2-foss-2023b.eb
This was introduced in an old version as a workaround for an issue with the intel toolchain, see: https://github.com/easybuilders/easybuild-easyconfigs/issues/7822.
I think we should remove this for several reasons:
- it was only required for intel toolchains, but there are no recent easyconfigs of PLUMED with the intel toolchain (most recent one is with intel 2021a)
- `ld.gold` is disabled by default for GCC >= 11.3.0, see https://github.com/easybuilders/easybuild-easyblocks/pull/2711
- explicitly using `ld.gold` may cause issues on systems without `ld.gold`
- most importantly, I don't think it's still required anyway, as the test build of `PLUMED-2.7.2-intel-2021a.eb` should demonstrate
=> remove explicit use of `ld.gold` in recent PLUMED easyconfigs

easybuild/easyconfigs/a/AOCC/AOCC-5.0.0-GCCcore-14.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.13.4-GCCcore-14.2.0.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.5-GCCcore-14.2.0.eb, easybuild/easyconfigs/p/pkgconf/pkgconf-2.3.0-GCCcore-14.2.0.eb, easybuild/easyconfigs/p/pkgconf/pkgconf-2.3.0.eb, easybuild/easyconfigs/x/XZ/XZ-5.6.3-GCCcore-14.2.0.eb
Add AOCC 5.0.0 and required dependencies to GCCcore 14.2.0. I chose the newest toolchain, as there's #21343 for GCCcore/13.3.0 already.
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/3480 for compilers to work correctly.
=> {devel,tools,lib,compiler}[system/system,GCCcore/14.2.0] Add pkgconf 2.3.0, XZ 5.6.3, ncurses 6.5, libxml 2.13.4, AOCC 5.0.0

easybuild/easyconfigs/l/LIME/LIME-1.3.2-GCCcore-13.2.0.eb, easybuild/easyconfigs/l/LIME/LIME-1.3.2-GCCcore-13.3.0.eb
This is just to add LIME, as in #21630, but for newer GCCcore versions. @jfgrimm, could you have a look at this, as it is the same, except for the toolchain version?
=> {phys}[GCCcore/13.2.0,GCCcore/13.3.0] LIME v1.3.2

test/easyconfigs/easyconfigs.py
While `alt_location` can be used for patches in the main EasyConfig part and in extensions the verification code handled them differently and missed to take the `alt_location` into account for extension patches.
Factor our the checking code to a function that can be used for both cases.
This also removes a redundant condition in one of the code instances before verifying the checksums.
More general solution of #21656
=> fix CI check for extension patches using `alt_location`

easybuild/easyconfigs/f/FLINT/FLINT-3.1.2-gfbf-2024a.eb, easybuild/easyconfigs/f/fmt/fmt-11.0.2-GCCcore-13.3.0.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.12.2-GCC-13.3.0.eb, easybuild/easyconfigs/l/LERC/LERC-4.0.0-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libaio/libaio-0.3.113-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libcerf/libcerf-2.4-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libcroco/libcroco-0.6.13-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libdap/libdap-3.21.0-27-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libtirpc/libtirpc-1.3.5-GCCcore-13.3.0.eb, easybuild/easyconfigs/n/NTL/NTL-11.5.1-GCC-13.3.0.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.45-GCCcore-13.3.0.eb
These packages are used in the new SW stage at JSC and were more or less version bumps from earlier toolchains.
=> Adding FLINT (+NTL), fmt, GEOS, LERC, libaio, libcerf, libcroco, libtirpc, libdap (+PCRE) for GCC(core) 13.3.0

easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.3.27-GCC-13.2.0-seq-iface64.eb
needed to a fortran software that uses -i8 and forking, so a single threaded version with interface64 is needed.
=> {numlib}[GCC-13.2.0] OpenBLAS 0.3.27 sequential with 64 bit interface

.github/workflows/tagbot.py, .github/workflows/tagbot.yml
See https://github.com/actions/labeler?tab=readme-ov-file#permissions
=> Change tagbot workflow to run on pull_request_target and comment on security

easybuild/easyconfigs/i/intel-compilers/intel-compilers-2025.0.0.eb
Add the newly released Intel oneAPI compilers for GCCcore 14.2.0. Basically just a version bump. 
The most notable change from the patch notes:
> Intel® Fortran Compiler Classic (ifort) is now discontinued in oneAPI 2025 release.
Requires https://github.com/easybuilders/easybuild-easyblocks/pull/3495
=> [system/system] Add Intel 2025.0.0 compilers

test/easyconfigs/suite.py
Re-enable the option to error on any deprecated behavior.
This is more general than the test case added in https://github.com/easybuilders/easybuild-easyconfigs/pull/19375/commits/93ed7fe27632968a85826fcd83bd51671f35feed checking (only) for use of deprecated EC parameters.
I'm not fully sure which one we want:
1. `test_pr_deprecated_ec_params` catches only deprecated EC params in changed easyconfigs
2. `$EASYBUILD_DEPRECATED` catches any use of deprecated behavior
The advantage of the test method is that it reports failures for all (changed) ECs in a single error while $EASYBUILD_DEPRECATED would error and stop on the first failure. We can also be more specific in what kind of deprecated behavior we want to check for if we don't use the variable, e.g. just the EC params in changed ECs, …
=> detect use of deprecated behavior in test runs

easybuild/easyconfigs/n/NVHPC/NVHPC-24.11-CUDA-12.6.0.eb
Basic version bump from 24.9.
Fixes I've noticed:
- OpenMPI 5 can once again build without the configure flag workaround
- Fixes in the OpenACC profiling interface
- Fixes in the OpenMP Tools Interface (and OpenMP runtime)
----
The release notes also include a mention which might affect EasyBuild in a future version:
> In a future release, the HPC SDK tar package file name will be extended to include the release number, in addition to the version. Automations that download and install the HPC SDK from the tar file package may need to be updated.
=> {compiler}[system/system] NVHPC-24.11-CUDA-12.6.0

easybuild/easyconfigs/n/NCCL/NCCL-2.22.3-GCCcore-13.3.0-CUDA-12.6.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3-NVHPC-24.9-CUDA-12.6.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3_disable_opal_path_nfs_test.patch, easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.3_fix_hle_make_errors.patch, easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.3.0-GCCcore-13.3.0-CUDA-12.6.0.eb, easybuild/easyconfigs/u/UCC-CUDA/UCC-CUDA-1.3.0_link_against_existing_UCC_libs.patch
Add NCCL 2.22.3 & UCC-CUDA 1.3.0 for GCCcore 13.3.0.
Add OpenMPI 5.0.3 for NVHPC 24.9. 
NVHPC 24.9 requires some patches to work correctly with OpenMPI 5.0.3.
=> {lib,mpi}[GCCcore/13.3.0,NVHPC/24.9] Add NCCL 2.22.3, UCC-CUDA 1.3.0, OpenMPI 5.0.3 w/CUDA 12.6.0

easybuild/easyconfigs/p/Pylint/Pylint-3.2.5-GCCcore-13.2.0.eb
The PyLint EasyConfig installs a different version of the `platformdirs` package than available in e.g. Python-bundle-PyPI which leads to conflicts later on.
Depend on that to pull in the right version
=> Fix confliction platformdirs dependency in Pylint-3.2.5-GCCcore-13.2.0

easybuild/easyconfigs/d/datalad/datalad-1.1.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/g/git-annex/git-annex-10.20240531-GCCcore-13.2.0.eb, easybuild/easyconfigs/l/libnsl/libnsl-2.0.1-GCCcore-13.2.0.eb
Hey,
for completeness, I also built datalad-1.1.0 for the 2023b stack, as this was one version that was missing.
=> {tools}[GCCcore/13.2.0] datalad v1.1.0, git-annex v10.20240531, libnsl v2.0.1

easybuild/easyconfigs/s/SlurmViewer/SlurmViewer-1.0.2-GCCcore-13.3.0.eb
=> {tools}[GCCcore/13.3.0] SlurmViewer v1.0.2

easybuild/easyconfigs/j/Java/Java-11.0.16.eb, easybuild/easyconfigs/j/Java/Java-11.0.18.eb, easybuild/easyconfigs/j/Java/Java-11.0.20.eb, easybuild/easyconfigs/j/Java/Java-16.0.1.eb, easybuild/easyconfigs/j/Java/Java-17.0.1.eb, easybuild/easyconfigs/j/Java/Java-17.0.2.eb, easybuild/easyconfigs/j/Java/Java-17.0.4.eb, easybuild/easyconfigs/j/Java/Java-17.0.6.eb, easybuild/easyconfigs/j/Java/Java-19.0.2.eb, easybuild/easyconfigs/j/Java/Java-21.0.2.eb, easybuild/easyconfigs/j/Java/Java-21.0.5.eb, easybuild/easyconfigs/j/Java/Java-8.345.eb, easybuild/easyconfigs/j/Java/Java-8.362.eb, easybuild/easyconfigs/j/Java/Java-8.402.eb
Fixes #22090 for Java easyconfigs
=> replace easybuild templates with f-strings on Java easyconfigs

test/easyconfigs/easyconfigs.py
* checksums are now checked in the fetch step
* `SYSTEM` toolchain check had a conditional on archived in EB5 toolchains
=> test suite changes for EB5

easybuild/easyconfigs/s/Score-P/Score-P-8.4-iimpi-2024a-CUDA-12.6.0.eb, easybuild/easyconfigs/s/Score-P/Score-P-8.4-iimpi-2024a.eb
Add Intel variant of Score-P 8.4 built for oneAPI compilers with and without CUDA support.
Depends:
Due to dependency targeting `5.0.x`, this PR also targets `5.0.x`. See: https://github.com/easybuilders/easybuild-easyblocks/pull/3548#issuecomment-2582289086
=> {perf}[iimpi/2024a] Add Score-P 8.4 (w/ CUDA 12.6.0)

easybuild/easyconfigs/r/ReFrame/ReFrame-4.3.3.eb
I was trying to install ReFrame 4.3.3 in EESSI, in the same way (same easyconfig, same EB version) as we had done before, but it's now failing because of:
```
ImportError: cannot import name 'splat' from 'jaraco.functools' (/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/lib/python3.11/site-packages/jaraco/functools.py)
```
This is probably related to https://github.com/pypa/setuptools/issues/4665, and it's caused by the ReFrame bootstrap.sh doing two `pip install`s with https://github.com/reframe-hpc/reframe/blob/v4.3.3/requirements.txt and https://github.com/reframe-hpc/reframe/blob/v4.3.3/docs/requirements.txt. The first already installs `setuptools`, but the latter has jsonschema, which has a `setuptools>= 40.6.0` requirement …
=> fix setuptools issue by sticking to a single version in ReFrame 4.3.3 easyconfig

easybuild/easyconfigs/c/CubeGUI/CubeGUI-4.8.2-GCCcore-13.2.0.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.1-gompi-2023b.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.6.1_nowarn_omp_pragmas.patch
This PR adds Scalasca to 2023b, using the latest versions of Cube[x], OTF2 and Score-P. 
In addition, a patch was added, which is being used on the JSC systems for some time (see [here](https://github.com/easybuilders/JSC/blob/2024/Golden_Repo/s/Scalasca/Scalasca-2.6.1_nowarn_omp_pragmas.patch)). This patch fixes a typo, which causes all checks after the OpenMP check to fail when they produce any output on `stdout` or `stderr`. This can cause issues in detecting compiler flags or the environment correctly.
=> {perf}[gompi/2022a,gompi/2023b] CubeGUI 4.8.2 & Scalasca 2.6.1 for 2023b | Patch to fix configure after OpenMP

easybuild/easyconfigs/a/archspec/archspec-0.2.5-GCCcore-12.3.0.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update2-foss-2023a-kokkos-CUDA-12.1.1.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-2Aug2023_update2-foss-2023a-kokkos.eb
Version 0.2.1 does not support newer CPUs like Sapphire Rapids, so I'm bumping the version of archspec (which is only used as build dependency) to the latest one. LAMMPS 2Aug2023 and newer do support Sapphire Rapids, but with the current archspec version it detects Sapphire Lake as Icelake and hence uses `ICX` for the Kokkos architecture.
=> use latest version (0.2.5) of archspec for LAMMPS 2Aug2023 easyconfigs

test/easyconfigs/easyconfigs.py
Fixes e.g.
```
File "test/easyconfigs/easyconfigs.py", line 1047, in test_r_libs_site_env_var
if 'R_LIBS' in ec['ec'][key]:
...
easybuild.tools.build_log.EasyBuildError: 'Failed to resolve all templates in "/path/to/AlphaFold_DBs/%(versions)s" using template dictionary
```
Similar for other changes
Drive-by fix for `r_libs_ecs.append(ec['spec'])` that could append the same EC twice.
=> Fix test failure due to unresolved template

easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a-CUDA-12.1.1.eb, easybuild/easyconfigs/p/PyTorch-bundle/PyTorch-bundle-2.1.2-foss-2023a.eb
There is problem with version of torchaudio - it has `version` instead of `2.1.2` in easyconfig, but it not get right version.
See: https://github.com/easybuilders/easybuild-framework/issues/4706
=> unset `$BUILD_VERSION` set by `torchvision` easyblock in `preinstallopts` for `torchaudio` in easyconfigs for `PyTorch-bundle` 2.1.2

easybuild/easyconfigs/n/NEURON/NEURON-8.2.6-foss-2023a.eb
Depends on: https://github.com/easybuilders/easybuild-easyblocks/pull/3618
Tests in easyblock PR
=> migrate easyconfig for NEURON v8.2.6 to use custom easyblock for NEURON

easybuild/easyconfigs/m/MATLAB/MATLAB-2023a.eb, easybuild/easyconfigs/m/MATLAB/MATLAB-2023b.eb, easybuild/easyconfigs/m/MATLAB/MATLAB-2024b.eb
This wasn't updated from the 4.9.4 target when merged into 5.0.x, lets be consistent.
=> Use f-strings for MATLAB download instructions

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-foss-2024a.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.4-parallel-symmetrization.patch
This patch fixes glitches in the symmetrization procedure happening for given inputs and parallelizatoins (the same patch is probably also useful for people using qe-7.2 and qe-7.3), details in:
https://gitlab.com/QEF/q-e/-/merge_requests/2575
https://gitlab.com/QEF/q-e/-/issues/761
=> add patch for QuantumESPRESSO 7.4 to fix parallel symmetrization glitch

.github/workflows/linting.yml, .github/workflows/unit_tests.yml
Rebase of https://github.com/easybuilders/easybuild-easyconfigs/pull/22459 on 5.0x
Use newer Ubuntu for linting to avoid having to update it too soon
Also test with Python 3.7 instead of 3.9 as minimum version of 5.0x is 3.6
=> Update GitHub actions workflows to use ubuntu-22.04 or ubuntu-24.04

easybuild/easyconfigs/m/MPICH/MPICH-3.3.2-GCC-10.2.0.eb, easybuild/easyconfigs/m/MPICH/MPICH-3.4.2-GCC-10.3.0.eb, easybuild/easyconfigs/m/MPICH/MPICH-4.2.1-GCC-12.3.0.eb, easybuild/easyconfigs/m/MPICH/MPICH-4.2.2-GCC-13.3.0.eb
It's no `--with-devices` but `--with-device`.
Depends on:
=> fix MPICH with-device configuration option

easybuild/easyconfigs/l/libStatGen/libStatGen-1.0.15-GCCcore-10.2.0.eb, easybuild/easyconfigs/l/libStatGen/libStatGen-1.0.15-GCCcore-12.3.0.eb
> ERROR: Installation of libStatGen-1.0.15-GCCcore-12.3.0.eb failed: "Sanity check failed: no file found at 'include/VcfFile.h' in /user/brussel/101/vsc10122/easybuild/install/zen2/software/libStatGen/1.0.15-GCCcore-12.3.0\nno file found at 'include/SamFile.h' in /user/brussel/101/vsc10122/easybuild/install/zen2/software/libStatGen/1.0.15-GCCcore-12.3.0\nno file found at 'include/BamIndex.h' in /user/brussel/101/vsc10122/easybuild/install/zen2/software/libStatGen/1.0.15-GCCcore-12.3.0\nno file found at 'include/Cigar.h' in /user/brussel/101/vsc10122/easybuild/install/zen2/software/libStatGen/1.0.15-GCCcore-12.3.0"
=> disable keepsymlinks in libStatGen

easybuild/easyconfigs/s/Scalene/Scalene-1.5.13-GCCcore-11.2.0.eb, easybuild/easyconfigs/s/Scalene/Scalene-1.5.20-GCCcore-11.3.0.eb, easybuild/easyconfigs/s/Scalene/Scalene-1.5.26-GCCcore-12.2.0.eb, easybuild/easyconfigs/s/Scalene/Scalene-1.5.26-GCCcore-12.3.0.eb, easybuild/easyconfigs/s/Scalene/Scalene-1.5.35-GCCcore-13.2.0.eb, easybuild/easyconfigs/s/Scalene/Scalene-1.5.51-gfbf-2024a.eb
Scalene downloads some vendored packages with `git` at build time:
```
== 2025-03-13 14:03:00,251 run.py:598 INFO Output of '/user/brussel/101/vsc10122/easybuild/install/zen2/software/Python/3.11.3-GCCcore-12.3.0/bin/python ...' shell command (stdout + stderr):
Processing /rhea/scratch/brussel/vo/000/bvo00005/vsc10122/easybuild/install/zen2/build/Scalene/1.5.26/GCCcore-12.3.0/Scalene/scalene-1.5.26
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
/user/brussel/101/vsc10122/easybuild/install/zen2/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: …
```
=> add build dependency on git to Scalene

easybuild/easyconfigs/c/CharLS/CharLS-2.4.2-GCCcore-13.3.0.eb, easybuild/easyconfigs/d/dcm2niix/dcm2niix-1.0.20241211-GCCcore-13.3.0.eb
The version of `dcm2niix` is bumped up to the latest (as of this day) and we aim for the 2024a toolchain.
=> dcm2niix for 2024a

easybuild/easyconfigs/g/gemmi/gemmi-0.4.5-GCCcore-10.2.0.eb, easybuild/easyconfigs/g/gemmi/gemmi-0.6.5-GCCcore-12.3.0.eb
CMake is needed at runtime, importing `gemmi` fails without it:
```
== 2025-03-13 14:50:12,728 build_log.py:226 ERROR EasyBuild encountered an error (at easybuild/easybuild-framework/easybuild/base/exceptions.py:126 in __init__): Sanity check failed: command "/user/brussel/101/vsc10122/easybuild/install/zen2/software/Python/3.11.3-GCCcore-12.3.0/bin/python -c "import gemmi"" failed; output:
File "<string>", line 1, in <module>
File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 1080, in _find_spec
File "/user/brussel/101/vsc10122/easybuild/install/zen2/software/gemmi/0.6.5-GCCcore-12.3.0/lib/python3.11/site-packages/_gemmi_ …
```
=> make CMake a runtime dependency of gemmi

easybuild/easyconfigs/s/Stellarscope/Stellarscope-1.4.1-foss-2023a.eb
New tarball with same name and minor differences in the source code:
```
diff -r -u stellarscope-1.4.1.a/stellarscope/_version.py stellarscope-1.4.1.b/stellarscope/_version.py
--- stellarscope-1.4.1.a/stellarscope/_version.py       2024-09-25 17:08:59.000000000 +0200
+++ stellarscope-1.4.1.b/stellarscope/_version.py       2024-09-25 17:08:59.000000000 +0200
@@ -25,7 +25,7 @@
-    git_refnames = " (HEAD -> main, tag: 1.4.1)"
+    git_refnames = " (tag: 1.4.1)"
git_full = "af8902ac72e03f23603c55bdf2920c89228a6493"
git_date = "2024-09-25 11:08:59 -0400"
keywords = {"refnames": git_refnames, "full": git_full, "date": git_date}
```
=> add new checksum for sources of Stellarscope v1.4.1

easybuild/easyconfigs/t/tantan/tantan-50-GCC-12.3.0.eb
New tarball with same name and minor differences in the source code:
```
diff -r -u tantan-50.a/src/Makefile tantan-50.b/src/Makefile
--- tantan-50.a/src/Makefile    2024-07-29 08:49:17.000000000 +0200
+++ tantan-50.b/src/Makefile    2024-07-29 08:49:17.000000000 +0200
@@ -10,7 +10,7 @@
rm -f ../bin/tantan
VERSION1 = git describe --dirty
-VERSION2 = echo ' (HEAD -> main, tag: 50) ' | sed -e 's/.*tag: *//' -e 's/[,) ].*//'
+VERSION2 = echo ' (tag: 50) ' | sed -e 's/.*tag: *//' -e 's/[,) ].*//'
VERSION = \"`test -e ../.git && $(VERSION1) || $(VERSION2)`\"
```
=> add new checksum for tantan v50 tarball

easybuild/easyconfigs/h/HepMC3/HepMC3-3.2.5-GCC-11.3.0.eb, easybuild/easyconfigs/h/HepMC3/HepMC3-3.2.6-GCC-12.3.0.eb
Installation fails because cmake detects the Python interpreter from the host system instead of the one loaded as dependency of HepMC3:
```
-- HepMC3 python: Python verson 3.X found in /user/brussel/101/vsc10122/.local/venv/eb.py36/bin/python3. Python bindings generation is possible.
-- HepMC3 python: For this platforrm CMAKE_SHARED_LIBRARY_PREFIX=lib, CMAKE_SHARED_LIBRARY_SUFFIX=.so
-- HepMC3 python: For this platforrm CMAKE_IMPORT_LIBRARY_PREFIX=, CMAKE_IMPORT_LIBRARY_SUFFIX=
-- HepMC3 python: Tweak HEPMC3_Python_SITEARCH36 option to set the installation path for the python36 bindings.
-- HepMC3 python: HEPMC3_Python_SITEARCH36 defaults to /user/brussel/101/vsc10122/.local/venv/eb.py36/lib64/python3.6/site-packages
-- HepMC3 python: WARNING: The installation path of the python modules …
```
=> fix Python detection in HepMC3

easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2020b.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2021a.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2021b.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2022a.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1.4-gompi-2022b.eb, easybuild/easyconfigs/i/Infernal/Infernal-1.1.5-gompi-2023a.eb
to enable MPI support in `Infernal` we either need to add `usempi` to the `toolchainopts` (so that `$CC=$MPICC` etc.) , or explicitly configure with `--enable-mpi`.
It also doesn't depend on BLAS/LAPACK, so should be dropped to `gompi` instead of `foss`
=> ensure `Infernal` is built with MPI support, and drop toolchain to gompi

easybuild/easyconfigs/p/Proteinortho/Proteinortho-6.2.3-foss-2021b.eb, easybuild/easyconfigs/p/Proteinortho/Proteinortho-6.3.2-foss-2023a.eb
Current easyconfigs missed the BLAS/LAPACK dependency. This didn't result in build failures, because the sources bundle their own lapack and pre-compiled artefacts, which are used as a fallback.
To see the difference, run an `ldd` on e.g. `bin/proteinortho_clustering` before/after the PR
=> Ensure `Proteinortho` links against `FlexiBLAS`, and bump to `foss`

test/easyconfigs/easyconfigs.py
` [patch_descr + "is missing"]` has a missing space.
Convert to f-strings and move `patch_descr` closer to its usage
=> Fix missing space in missing-patch CI error

easybuild/easyconfigs/k/king/king-2.3.2.eb
=> {bio}[system] King v2.3.2

easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0.eb
- Switch Java version to Java 21 to be consistent with remaining toolchain
- Add groff as a build dependency to avoid system version being used, which can cause libstdc++ issues (see below).
```console
eb-shell> qmake -o cmd/gvedit/qMakefile cmd/gvedit/gvedit.pro &&  make  -j 8
make  all-recursive
make[1]: Entering directory '/data/EasyBuild-develop/build/Graphviz/12.2.0/GCCcore-13.3.0/graphviz-12.2.0'
Making all in libltdl
make[2]: Entering directory '/data/EasyBuild-develop/build/Graphviz/12.2.0/GCCcore-13.3.0/graphviz-12.2.0/libltdl'
make  all-am
make[3]: Entering directory '/data/EasyBuild-develop/build/Graphviz/12.2.0/GCCcore-13.3.0/graphviz-12.2.0/libltdl'
make[3]: Leaving directory '/data/EasyBuild-develop/build/Graphviz/12.2.0/GCCcore-13.3.0/graphviz-12.2.0/libltdl'
make[2]: …
```
=> {vis}[GCCcore/13.3.0] Update dependencies of Graphviz 12.2.0

contrib/easyconfig-templates/2022a/PythonBundle-minimal.eb.tmpl, contrib/easyconfig-templates/2022a/PythonBundle-scipy.eb.tmpl, contrib/easyconfig-templates/2023a/PythonBundle-minimal.eb.tmpl, contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl, contrib/easyconfig-templates/2024a/PythonBundle-minimal.eb.tmpl, contrib/easyconfig-templates/2024a/PythonBundle-scipy.eb.tmpl
The extensions examples for some of the `PythonBundle` templates are missing `})`.
=> Add missing extension curly brackets and parentheses

easybuild/easyconfigs/l/LLVM/LLVM-18.1.8_envintest.patch, easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_clang_rpathwrap_test.patch, easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_libomptarget_tests.patch, easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.3.0.eb
Added patches and EC file for LLVM 20.1.5-GCCcore13.3.0
=> {compiler}[GCCcore-13.3.0] LLVM 20.1.5

easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-18.1.8_envintest.patch, easybuild/easyconfigs/l/LLVM/LLVM-18.1.8_libomptarget_tests.patch, easybuild/easyconfigs/l/LLVM/LLVM-19.1.7_clang_rpathwrap_test.patch
EC files to compile LLVMcore (clang + flang-new + optional projects) for `18.1.8` with GCCcore 13.3.0 as a base
-  [x] Requires EB from PR (https://github.com/easybuilders/easybuild-easyblocks/pull/3373)
-  Splitted from https://github.com/easybuilders/easybuild-easyconfigs/pull/20902
=> {compiler}[GCCcore/13.3.0] LLVM 18.1.8 (new)

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.5_disable_opal_path_nfs_test.patch
Similarly to the patch for 5.0.3, I've added one for 4.1.5.
=> add optional patch file for OpenMPI 4.1.5 to disable OPAL path NFS test

easybuild/easyconfigs/o/OPERA-MS/OPERA-MS-0.9.0-20240703-foss-2023a.eb, easybuild/easyconfigs/o/OPERA-MS/OPERA-MS-0.9.0-20240703_fix-perl-dependency-check.patch
- The command `OPERA-MS check_dependency` is executed as a sanity check. It will however revert an earlier created symlink to the correct perl interpreter. A patch is added to make sure the existing correct symlink is not removed.
- Some paths are hardcoded in scripts such as `tools_opera_ms/MUMmer3.23/exact-tandems` during compilation. This is why the build is now done in the installation directory (`buildininstalldir = True`)
=> add patch to fix dependency check in OPERA-MS

easybuild/easyconfigs/g/Graphviz/Graphviz-12.2.0-GCCcore-13.3.0-minimal.eb
This adds a variant of the `Graphviz` package without the GUI and Java dependencies which pull many different dependencies.
This is helpful for tools such as [MUST](https://itc.rwth-aachen.de/must/) which require the `dot` command to draw graphs but nothing else of the Graphviz package. In particular, it might be of use in #22836.
The following dependencies are removed: `Java`, `FriBidi`, `Gdk-Pixbuf`, `Ghostscript`, `GTS`, `Pango`, `Perl`, `Qt6`, `Tcl`.
The version suffix is to be discussed, of course. :slightly_smiling_face:
=> {vis}[GCCcore/13.3.0] Graphviz v12.2.0-minimal 

easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb, easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.0-GCCcore-13.2.0.eb, easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.38.2-GCCcore-13.3.0.eb, easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-5.40.0-GCCcore-14.2.0.eb, easybuild/easyconfigs/p/Perl-bundle-CPAN/Perl-bundle-CPAN-IO-Socket-SSL-OCSP.patch
The OCSP stapling tests run by the `IO::Socket::SSL` extension of `Perl-bundle-CPAN` started failing due to a change of behavior of the server contacted by these tests (see https://github.com/noxxi/p5-io-socket-ssl/issues/169).
A patch derived from https://github.com/noxxi/p5-io-socket-ssl/commit/58ad1d1672516d246f7536961c6ab320ffde1b8a is applied to avoid this issue.
=> Fix Perl-bundle-CPAN `IO::Socket::SSL` failing tests

easybuild/easyconfigs/z/Zoltan/Zoltan-3.901-foss-2023a.eb
A Zoltan build for EESSI on a Neoverse v1 node resulted in:
```
configure: error: cannot guess build type; you must specify one
```
(see https://github.com/EESSI/software-layer/pull/1113#issuecomment-2957964386)
Zoltan includes a very old `config.guess` (https://github.com/sandialabs/Zoltan/blob/v3.901/config/config.guess). Although EasyBuild should obtain a new version of this file, that's not being done here due to building in a subdirectory and using `configure_cmd = ../configure`:
```
preconfigopts = 'mkdir build && cd build &&'
configure_cmd = '../configure'
```
The `../configure` leads to `os.path.exists(configure_command)`  being False for this check, as that's being run in the root of the source dir: https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easybl …
=> ensure that configure step of Zoltan uses an up-to-date `config.guess`

easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-11.3.0.eb, easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.2.0.eb, easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.3.0-Python-2.7.18.eb, easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-12.3.0.eb, easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9-GCCcore-13.3.0.eb, easybuild/easyconfigs/m/MEGAHIT/MEGAHIT-1.2.9_support-non-x86_64-architectures.patch
Building on for instance Arm fails, see https://github.com/EESSI/software-layer/pull/1117#issuecomment-2959836864. This patch is taken from https://github.com/voutcn/megahit/pull/368.
=> add patch to fix support for non-x86_64 architectures for MEGAHIT 1.2.9

easybuild/easyconfigs/m/matplotlib/matplotlib-3.7.2-iimkl-2023a.eb
For https://github.com/vscentrum/vsc-software-stack/issues/563
```
FAILED: src/_contourpy.cpython-311-x86_64-linux-gnu.so.p/line_type.cpp.o
icpx: error: -Wl,-rpath=~/matplotlib/3.7.2-iimkl-2023a/lib: 'linker' input unused [-Werror,-Wunused-command-line-argument]
icpx: error: -Wl,-rpath=~/matplotlib/3.7.2-iimkl-2023a/lib64: 'linker' input unused [-Werror,-Wunused-command-line-argument]
icpx: error: -Wl,-rpath=$ORIGIN: 'linker' input unused [-Werror,-Wunused-command-line-argument]
icpx: error: -Wl,-rpath=$ORIGIN/../lib: 'linker' input unused [-Werror,-Wunused-command-line-argument]
icpx: error: -Wl,-rpath=$ORIGIN/../lib64: 'linker' input unused [-Werror,-Wunused-command-line-argument]
icpx: error: -Wl,--disable-new-dtags: 'linker' input unused [-Werror,-Wunused-command-line-argument]
```
=> Fix failing contourpy installation in matplotlib-3.7.2-iimkl-2023a with rpath (EB5 default)

easybuild/easyconfigs/v/Virtuoso-opensource/Virtuoso-opensource-7.2.14-GCC-13.2.0.eb
This PR adds `Virtuoso-opensource/7.2.14-GCC-13.2.0`.
=> {data}[GCC/13.2.0] Virtuoso-opensource for 2023b

easybuild/easyconfigs/d/DaliLite/DaliLite-5.0-gompi-2024a.eb
An update of DaliLite. This EC file is to make DaliLite use DSSP as indicated in [the document](http://ekhidna2.biocenter.helsinki.fi/dali/README.v5.html).
NOTE: I created one previous PR of about the same thing for older toolchain weeks ago ( https://github.com/easybuilders/easybuild-easyconfigs/pull/22767 ). It is hard for me to rebase (or something like that) that branch to current develop so I created this one. Would close the old PR later.
=> {bio}[gompi/2024a] DaliLite 5 using DSSP

easybuild/easyconfigs/m/MinPath/MinPath-1.6-GCCcore-11.2.0.eb, easybuild/easyconfigs/m/MinPath/MinPath-1.6-GCCcore-12.3.0.eb
this sanity check assumes we're running in the install dir, but since EB 5.0 we run the sanity check in a temporary directory
=> fix sanity_check_commands for MinPath 1.6 and add GCCcore/12.3.0 version

easybuild/easyconfigs/g/GCCcore/GCCcore-12.1.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-12.2.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-12.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-13.1.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-13.2.0.eb
Fixes #23074
GCCcore 12.x, 13.1, 13.2 builds failed when using CUDA 12 due to the `sm_35` gpu-name flag not being recognized.
[CUDA 12](https://docs.nvidia.com/cuda/archive/12.0.0/cuda-toolkit-release-notes/#cuda-libraries) libraries removed support for compute capabilities `sm_35` and `sm_37`.
The `nvtx-tools` package used by `GCCcore` introduced a [fix](https://github.com/SourceryTools/nvptx-tools/commit/13216705844e5d7c9d20b4e34f89a39017e191d4#diff-5d92d01a011b195a642f1fc5b9704a1b2dea168a392c9ad3a4c1a56720ee52bc) bumping the baseline architecture from `sm_35` to `sm_50`.
Therefore, the version of `nvtx-tools` installed by `GCCcore` is updated to `20240419`, the same used by GCCcore 13.3.
=> GCCcore 12-13: update `nvptx-tools` version to fix compatibility with CUDA 12

easybuild/easyconfigs/a/Abseil/Abseil-20250512.1-GCCcore-14.2.0.eb
=> {lib}[GCCcore/14.2.0] Added EC for `Abseil 20250512.1`

test/easyconfigs/easyconfigs.py
#12687 switched to testing for multidep variants per toolchain generation, but this is only enabled for 2023b and newer.
We should still test for multidep variants per toolchain for the older generations.
The previous check (`r'GCCcore-([7-9]|[1-9][0-9])\.[0-9]'`) missed `GCC` toolchains and I've retained that due to there being multidep variant failures in `GCC` toolchains. The check on the newer generations will catch these problems, so the historical ones will get archived away over time.
=> restore toolchain multideps test

easybuild/easyconfigs/l/LLVM/LLVM-11.1.0-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-12.0.1-GCCcore-11.2.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-14.0.3-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-12.2.0-llvmlite.eb, easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-12.3.0-llvmlite.eb, easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-13.2.0-llvmlite.eb, easybuild/easyconfigs/l/LLVM/LLVM-14.0.6-GCCcore-13.3.0-llvmlite.eb, easybuild/easyconfigs/l/LLVM/LLVM-15.0.5-GCCcore-12.2.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-16.0.6-GCCcore-12.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-16.0.6-GCCcore-13.2.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0-minimal.eb, easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-19.1.7-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-20.1.4-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.2.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.3.0.eb
=> Replace deprecated `usepolly` with `use_polly` in LLVM easyconfigs

easybuild/easyconfigs/m/MetaGeneMark-2/MetaGeneMark-2-1.06-GCC-13.2.0.eb, easybuild/easyconfigs/m/MetaGeneMark-2/MetaGeneMark-2-fix_Makefile.patch
This PR adds a new module, MetaGeneMark-2. The installation on (Skylake, Cascadelake, Icelake and Sapphire Rapids) Intel architectures on Rocky 8.9 Linux works out fine.
=> {bio}[GCC/13.2.0] MetaGeneMark-2 for 2023b

easybuild/easyconfigs/r/rocm-smi/rocm-smi-4.5.0-GCCcore-11.2.0.eb, easybuild/easyconfigs/r/rocm-smi/rocm-smi-5.4.4-GCCcore-11.3.0.eb, easybuild/easyconfigs/r/rocm-smi/rocm-smi-5.6.0-GCCcore-11.3.0.eb
rocm_smi_lib is a C/C++ library, but the binary is a Python wrapper around it. To avoid issues with the incorrect Python being used, add an explicit Python dependency.
See https://github.com/easybuilders/easybuild-easyconfigs/pull/23280#discussion_r2182488862 for more information
=> Add missing Python dependency to rocm-smi

test/easyconfigs/easyconfigs.py
This adds the full toolchain generation test for `intel/2023b` and newer (`intel-compilters/2023.2.1`. For the older `intel-compilers` the checks are just inside the toolchain (and not toolchain generation).
The way this has been added it does check that we use the same version for both `intel` and `foss`.
=> include `intel-compilers` in the toolchain multi-variant checks

easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.45-GCCcore-12.3.0.eb, easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-1.3.45-GCCcore-13.3.0.eb, easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick-12.3.0_pkgconfig_libtiff-4.patch, easybuild/easyconfigs/g/GraphicsMagick/GraphicsMagick_pkgconfig_libtiff-4.patch
New EC files for `GraphicsMagick` and `foss/2023a` with potential fix for 
- #22927 
- #22929
If from the discussion on the PR/Issue it is decided this is the proper way to go we should apply the change to enable both static and shared builds (+ sanity checks)
```
configure_opts = '--enable-shared --enable-static'
```
also to
GraphicsMagick-1.3.45-GCCcore-13.3.0.eb
=> {vis}[GCCcore/12.3.0,GCCcore/13.3.0] Added `GraphicsMagick-1.3.45` EC for GCCcore-12.3.0 + fix for #22927

contrib/easyconfig-templates/2022a/PythonBundle-minimal.eb.tmpl, contrib/easyconfig-templates/2022a/PythonBundle-scipy.eb.tmpl, contrib/easyconfig-templates/2023a/PythonBundle-minimal.eb.tmpl, contrib/easyconfig-templates/2023a/PythonBundle-pytest.eb.tmpl, contrib/easyconfig-templates/2023a/PythonBundle-scipy.eb.tmpl, contrib/easyconfig-templates/2024a/PythonBundle-minimal.eb.tmpl, contrib/easyconfig-templates/2024a/PythonBundle-pytest.eb.tmpl, contrib/easyconfig-templates/2024a/PythonBundle-scipy.eb.tmpl
The `sanity_pip_check': True` option is enabled by default since EasyBuild 5 and checks in PRs fail if this option is set explicitly.
=> remove `'sanity_pip_check': True` from easyconfig templates

easybuild/easyconfigs/e/EasyBuild/EasyBuild-5.1.1.eb, easybuild/easyconfigs/e/EasyBuild/EasyBuild-5.1.1_fix-failing-copy-of-readonly-patches.patch
In PR https://github.com/easybuilders/easybuild-framework/pull/4939 I fixed an issue where patches of extensions would not be copied to the `easybuild` subdir, but it introduced a new bug that would basically add every patch to the list twice (only for easyconfigs with extensions that have patches). This causes every patch to be copied twice, where the second copy would just overwrite the first one. This in itself should not cause issues, except in the case where the patch file has read-only permissions. For anyone using `--read-only-installdir`, this may happen frequently though, as all the patches in the EasyBuild installation itself will have such permissions. The second copy will then result in a `Permission denied` error, as we're also observing in EESSI.
To solve the issue for …
=> add patch to EasyBuild 5.1.1 easyconfig for bug that causes failures when copying readonly patches 

easybuild/easyconfigs/l/LLVM/LLVM-18.1.8-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-19.1.7-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-20.1.4-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.2.0.eb, easybuild/easyconfigs/l/LLVM/LLVM-20.1.5-GCCcore-13.3.0.eb
Companion PR to 
- https://github.com/easybuilders/easybuild-easyblocks/pull/3849
- `libffi` was already an indirect dependency but this future proofs it and makes it clear it is also a dependency
- Removed the `skip_mod_files_sanity_check` option as it is now being set by the EasyBlock when needed
- Even if the linked issue is related to `offload` which has been introduced since `LLVM >= 19` the added configure options are also available for `18.1.8`
=> LLVM fix for libffi

easybuild/easyconfigs/n/ninja-python/ninja-python-1.11.1.4-GCCcore-14.3.0.eb, easybuild/easyconfigs/s/scikit-build-core/scikit-build-core-0.11.5-GCCcore-14.3.0.eb
Older versions blocks updating e.g. pybind11. Was accidentally missed when providing scikit-build-core for new toolchain.
=> {lib}[GCCcore/14.3.0] Bump scikit-build-core to 0.11.5

easybuild/easyconfigs/m/Mesa/Mesa-23.1.4-GCCcore-12.3.0.eb, easybuild/easyconfigs/m/Mesa/Mesa-23.1.9-GCCcore-13.2.0.eb
To reflect the current structure of the [archive.mesa3d.org](https://archive.mesa3d.org/) website.
The old path:
`https://archive.mesa3d.org/older-versions/%(version_major)s.x/`
no longer resolves for versions 23.x
Replaced with:
`https://archive.mesa3d.org/%(version_major)s.x/`
which matches the live layout for 23.x tarballs.
Tested against:
Mesa-23.1.4-GCCcore-13.2.0.eb
Successful download and checksum match.
=> Mesa: fix broken source_urls for versions 23.x 

easybuild/easyconfigs/g/gzip/gzip-1.13-GCCcore-13.1.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-10.3.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.5.1-GCCcore-11.2.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.1-GCCcore-11.3.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.1-GCCcore-12.2.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.2-GCCcore-12.3.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.6.2-GCCcore-13.1.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.7.2-GCCcore-13.2.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.7.4-GCCcore-13.3.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.7.7-GCCcore-14.2.0.eb, easybuild/easyconfigs/l/libarchive/libarchive-3.8.1-GCCcore-14.3.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.11.5-GCCcore-13.1.0.eb, easybuild/easyconfigs/l/lz4/lz4-1.9.4-GCCcore-13.1.0.eb, easybuild/easyconfigs/z/zstd/zstd-1.5.5-GCCcore-13.1.0.eb
Configure searches for those and might pick up system libraries without the modules.
Fixes https://github.com/easybuilders/easybuild-easyconfigs/issues/23513
=> Add missing dependencies libxml2 & zstd to libarchive

easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7-GCC-14.2.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7_build-with-internal-cuda-header.patch, easybuild/easyconfigs/o/OpenMPI/OpenMPI-5.0.7_fix_gpfs_compatibility.patch
- Fix OpenMPI incompatibility with GPFS >= 5.2.3
- Fix stubs for OpenMPI build with internal CUDA
=> Add additional patches for OpenMPI-5.0.7 from 2025a

easybuild/easyconfigs/a/ASE/ASE-3.25.0-gfbf-2025b.eb, easybuild/easyconfigs/b/bokeh/bokeh-3.7.3-gfbf-2025b.eb, easybuild/easyconfigs/f/FFTW.MPI/FFTW.MPI-3.3.10-gompi-2025b.eb, easybuild/easyconfigs/f/FLINT/FLINT-3.3.1-gfbf-2025b.eb, easybuild/easyconfigs/f/foss/foss-2025b.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2025.2-foss-2025b.eb, easybuild/easyconfigs/g/gfbf/gfbf-2025b.eb, easybuild/easyconfigs/g/gompi/gompi-2025b.eb, easybuild/easyconfigs/h/HPCG/HPCG-3.1-foss-2025b.eb, easybuild/easyconfigs/h/HPCG/HPCG-3.1-intel-2025b.eb, easybuild/easyconfigs/h/hmmlearn/hmmlearn-0.3.3-gfbf-2025b.eb, easybuild/easyconfigs/i/iimkl/iimkl-2025b.eb, easybuild/easyconfigs/i/iimpi/iimpi-2025b.eb, easybuild/easyconfigs/i/imageio/imageio-2.37.0-gfbf-2025b.eb, easybuild/easyconfigs/i/imkl-FFTW/imkl-FFTW-2025.2.0-iimpi-2025b.eb, easybuild/easyconfigs/i/intel/intel-2025b.eb, easybuild/easyconfigs/m/matplotlib/matplotlib-3.10.5-gfbf-2025b.eb, easybuild/easyconfigs/m/mpi4py/mpi4py-4.1.0-gompi-2025b.eb, easybuild/easyconfigs/n/networkx/networkx-3.5-gfbf-2025b.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.2.2-gompi-2025b-fb.eb, easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2025.07-gfbf-2025b.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-1.7.1-gfbf-2025b.eb, easybuild/easyconfigs/s/spglib-python/spglib-python-2.6.0-gfbf-2025b.eb
Renames all existing EasyConfigs for 2025.07 / 2025.08 to 2025b.
As discussed on Slack, we've successfully built GROMACS with `foss/2025.07`, which is a nice target to test.
For Intel, PRs are open for HPL and HPCG to test with. Based on their results, the toolchain looks similar to our prior ones.
**PRs using candidate toolchains:**
=> Establish `2025b` toolchain (and rename / remove candidate toolchains 2025.07 / 2025.08 )

easybuild/easyconfigs/o/OCaml/OCaml-4.14.0-GCC-11.3.0.eb, easybuild/easyconfigs/o/OCaml/OCaml-5.1.1-GCC-13.2.0.eb
Some versions of OCaml packages are no longer available in OPAM. Update dependencies to the nearest available version.
=> {lang}[foss/2023b] Fix package dependencies versions for OCaml

easybuild/easyconfigs/p/PARI-GP/PARI-GP-2.15.4-GCCcore-11.3.0.eb, easybuild/easyconfigs/p/PARI-GP/PARI-GP-2.15.5-GCCcore-13.2.0.eb
The authors of PARI/GP provide tarballs only for the stable and development versions of PARI/GP. Fetch source from the git repository.
=> {math}[foss/2023b] Fix source for PARI-GP

easybuild/easyconfigs/t/tcsh/tcsh-6.24.16-GCCcore-14.3.0.eb
add easyconfig for new version of tcsh, this will used in build foss-2025 e.g NAMD version 3.0.2  upstream packages that needs tcsh and tcl
=> {tools}[GCCcore/14.3.0] tcsh v6.24.16

easybuild/easyconfigs/p/Parallel-Hashmap/Parallel-Hashmap-2.0.0-GCCcore-13.3.0.eb
Explicitly include -lpthread in configopts due to multiple 'undefined reference' errors in build on Rocky 8
=> add `-lpthread` to configure options for `Parallel-Hashmap v2.0.0`

easybuild/easyconfigs/j/JupyterLab-git/JupyterLab-git-0.51.1-GCCcore-13.2.0.eb, easybuild/easyconfigs/j/JupyterLab-git/JupyterLab-git-0.51.2-GCCcore-13.3.0.eb
This PR adds two versions of `jupyterlab-git` plugin for JupyterLab for 2023b and 2024a toolchains. A similar installation based on the modules in 2023a fails with some `hatchling` issues.
=> {tools} [GCCcore/13.3.0, GCCcore/13.2.0] JupyterLab-git v.0.51.2, JupyterLab-git v.0.51.1
